// Generated by stratus_hls 23.02-s004  (100793.100415)
// Mon Jun  9 16:22:21 2025
// from dut.cc

`timescale 1ps / 1ps


module dut_Sub_15Ux8U_16S_4( in2, in1, out1 );

    input [14:0] in2;
    input [7:0] in1;
    output [15:0] out1;

    
    // rtl_process:dut_Sub_15Ux8U_16S_4/dut_Sub_15Ux8U_16S_4_thread_1
    assign out1 = {1'b0, in2} - {8'b00000000, in1};

endmodule


