`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:44:22 CST (Jun  9 2025 08:44:22 UTC)

module dut_LessThan_6Ux8U_1U_4(in2, in1, out1);
  input [5:0] in2;
  input [7:0] in1;
  output out1;
  wire [5:0] in2;
  wire [7:0] in1;
  wire out1;
  wire lt_16_32_n_0, lt_16_32_n_1, lt_16_32_n_2, lt_16_32_n_3,
       lt_16_32_n_4, lt_16_32_n_5, lt_16_32_n_6, lt_16_32_n_7;
  wire lt_16_32_n_8, lt_16_32_n_9, lt_16_32_n_10, lt_16_32_n_11,
       lt_16_32_n_12, lt_16_32_n_13, lt_16_32_n_14, lt_16_32_n_15;
  AOI32X1 lt_16_32_g162(.A0 (lt_16_32_n_15), .A1 (lt_16_32_n_7), .A2
       (lt_16_32_n_12), .B0 (lt_16_32_n_7), .B1 (lt_16_32_n_13), .Y
       (out1));
  OAI211X1 lt_16_32_g163(.A0 (lt_16_32_n_4), .A1 (in1[3]), .B0
       (lt_16_32_n_14), .C0 (lt_16_32_n_11), .Y (lt_16_32_n_15));
  OAI221X1 lt_16_32_g164(.A0 (lt_16_32_n_9), .A1 (lt_16_32_n_10), .B0
       (lt_16_32_n_3), .B1 (in2[2]), .C0 (lt_16_32_n_6), .Y
       (lt_16_32_n_14));
  OAI32X1 lt_16_32_g165(.A0 (lt_16_32_n_8), .A1 (lt_16_32_n_1), .A2
       (in1[4]), .B0 (lt_16_32_n_2), .B1 (in1[5]), .Y (lt_16_32_n_13));
  AOI21X1 lt_16_32_g166(.A0 (in1[4]), .A1 (lt_16_32_n_1), .B0
       (lt_16_32_n_8), .Y (lt_16_32_n_12));
  NAND3X1 lt_16_32_g167(.A (lt_16_32_n_6), .B (in2[2]), .C
       (lt_16_32_n_3), .Y (lt_16_32_n_11));
  AOI22X1 lt_16_32_g168(.A0 (in1[0]), .A1 (lt_16_32_n_5), .B0 (in1[1]),
       .B1 (lt_16_32_n_0), .Y (lt_16_32_n_10));
  NOR2X1 lt_16_32_g169(.A (lt_16_32_n_0), .B (in1[1]), .Y
       (lt_16_32_n_9));
  NOR2BX1 lt_16_32_g170(.AN (in1[5]), .B (in2[5]), .Y (lt_16_32_n_8));
  NOR2X1 lt_16_32_g171(.A (in1[7]), .B (in1[6]), .Y (lt_16_32_n_7));
  NAND2X1 lt_16_32_g172(.A (in1[3]), .B (lt_16_32_n_4), .Y
       (lt_16_32_n_6));
  INVX1 lt_16_32_g173(.A (in2[0]), .Y (lt_16_32_n_5));
  INVX1 lt_16_32_g174(.A (in2[3]), .Y (lt_16_32_n_4));
  INVX1 lt_16_32_g175(.A (in1[2]), .Y (lt_16_32_n_3));
  INVX1 lt_16_32_g176(.A (in2[5]), .Y (lt_16_32_n_2));
  INVX1 lt_16_32_g177(.A (in2[4]), .Y (lt_16_32_n_1));
  INVX1 lt_16_32_g178(.A (in2[1]), .Y (lt_16_32_n_0));
endmodule


