`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:46:06 CST (Jun  9 2025 08:46:06 UTC)

module dut_Add_13Ux12U_14U_1(in2, in1, out1);
  input [12:0] in2;
  input [11:0] in1;
  output [13:0] out1;
  wire [12:0] in2;
  wire [11:0] in1;
  wire [13:0] out1;
  wire add_16_31_n_1, add_16_31_n_2, add_16_31_n_3, add_16_31_n_8,
       add_16_31_n_11, add_16_31_n_13, add_16_31_n_14, add_16_31_n_15;
  wire add_16_31_n_16, add_16_31_n_17, add_16_31_n_18, add_16_31_n_19,
       add_16_31_n_20, add_16_31_n_21, add_16_31_n_22, add_16_31_n_23;
  wire add_16_31_n_24, add_16_31_n_25, add_16_31_n_26, add_16_31_n_27,
       add_16_31_n_28, add_16_31_n_29, add_16_31_n_30, add_16_31_n_31;
  wire add_16_31_n_32, add_16_31_n_33, add_16_31_n_34, add_16_31_n_35,
       add_16_31_n_36, add_16_31_n_37, add_16_31_n_38, add_16_31_n_39;
  wire add_16_31_n_40, add_16_31_n_41, add_16_31_n_42, add_16_31_n_43,
       add_16_31_n_44, add_16_31_n_45, add_16_31_n_46, add_16_31_n_47;
  wire add_16_31_n_48, add_16_31_n_49, add_16_31_n_50, add_16_31_n_51,
       add_16_31_n_52, add_16_31_n_53, add_16_31_n_54, add_16_31_n_55;
  wire add_16_31_n_56, add_16_31_n_57, add_16_31_n_58, add_16_31_n_59,
       add_16_31_n_60, add_16_31_n_61, add_16_31_n_62, add_16_31_n_63;
  wire add_16_31_n_64, add_16_31_n_65, add_16_31_n_66, add_16_31_n_67,
       add_16_31_n_68, add_16_31_n_69, add_16_31_n_70, add_16_31_n_71;
  wire add_16_31_n_72, add_16_31_n_73, add_16_31_n_74, add_16_31_n_75,
       add_16_31_n_76, add_16_31_n_77, add_16_31_n_78, add_16_31_n_79;
  wire add_16_31_n_80, add_16_31_n_81, add_16_31_n_82, add_16_31_n_83,
       add_16_31_n_84, add_16_31_n_85, add_16_31_n_86, add_16_31_n_87;
  wire add_16_31_n_88, add_16_31_n_89, add_16_31_n_90, add_16_31_n_93,
       add_16_31_n_95, add_16_31_n_96, add_16_31_n_97, n_126;
  wire n_127, n_128, n_130, n_131, n_132, n_134, n_135, n_136;
  wire n_138, n_140, n_141, n_142, n_143, n_145;
  MXI2XL add_16_31_g294(.A (in2[12]), .B (add_16_31_n_13), .S0
       (add_16_31_n_97), .Y (out1[12]));
  MXI2XL add_16_31_g295(.A (add_16_31_n_46), .B (add_16_31_n_47), .S0
       (add_16_31_n_93), .Y (out1[11]));
  MXI2XL add_16_31_g297(.A (add_16_31_n_41), .B (add_16_31_n_42), .S0
       (add_16_31_n_95), .Y (out1[9]));
  NOR2X1 add_16_31_g298(.A (add_16_31_n_75), .B (add_16_31_n_90), .Y
       (add_16_31_n_97));
  NOR2X1 add_16_31_g299(.A (add_16_31_n_66), .B (add_16_31_n_8), .Y
       (add_16_31_n_96));
  NOR2BX1 add_16_31_g300(.AN (add_16_31_n_27), .B (add_16_31_n_89), .Y
       (add_16_31_n_95));
  OAI21X1 add_16_31_g301(.A0 (add_16_31_n_71), .A1 (add_16_31_n_87),
       .B0 (add_16_31_n_78), .Y (out1[13]));
  NOR2X1 add_16_31_g302(.A (add_16_31_n_77), .B (add_16_31_n_88), .Y
       (add_16_31_n_93));
  MXI2XL add_16_31_g304(.A (add_16_31_n_60), .B (add_16_31_n_61), .S0
       (add_16_31_n_85), .Y (out1[7]));
  MXI2XL add_16_31_g306(.A (add_16_31_n_55), .B (add_16_31_n_56), .S0
       (add_16_31_n_86), .Y (out1[5]));
  NOR2X1 add_16_31_g307(.A (add_16_31_n_67), .B (add_16_31_n_87), .Y
       (add_16_31_n_90));
  NOR2X1 add_16_31_g309(.A (add_16_31_n_21), .B (add_16_31_n_87), .Y
       (add_16_31_n_89));
  NOR2X1 add_16_31_g310(.A (add_16_31_n_70), .B (add_16_31_n_87), .Y
       (add_16_31_n_88));
  NOR2X6 add_16_31_g311(.A (add_16_31_n_74), .B (add_16_31_n_83), .Y
       (add_16_31_n_87));
  NOR2BX1 add_16_31_g312(.AN (add_16_31_n_33), .B (add_16_31_n_84), .Y
       (add_16_31_n_86));
  NOR2X1 add_16_31_g316(.A (add_16_31_n_76), .B (add_16_31_n_82), .Y
       (add_16_31_n_85));
  NOR2X1 add_16_31_g317(.A (add_16_31_n_20), .B (n_145), .Y
       (add_16_31_n_84));
  NOR2X4 add_16_31_g319(.A (add_16_31_n_69), .B (add_16_31_n_80), .Y
       (add_16_31_n_83));
  NOR2X1 add_16_31_g320(.A (add_16_31_n_68), .B (n_145), .Y
       (add_16_31_n_82));
  NOR2BX1 add_16_31_g321(.AN (add_16_31_n_31), .B (add_16_31_n_2), .Y
       (add_16_31_n_81));
  NOR2X6 add_16_31_g323(.A (add_16_31_n_62), .B (add_16_31_n_79), .Y
       (add_16_31_n_80));
  NOR2X4 add_16_31_g325(.A (add_16_31_n_52), .B (add_16_31_n_73), .Y
       (add_16_31_n_79));
  NAND2XL add_16_31_g326(.A (in2[12]), .B (add_16_31_n_75), .Y
       (add_16_31_n_78));
  OAI2BB1X1 add_16_31_g327(.A0N (add_16_31_n_17), .A1N
       (add_16_31_n_66), .B0 (add_16_31_n_24), .Y (add_16_31_n_77));
  OAI21X1 add_16_31_g328(.A0 (n_140), .A1 (n_131), .B0
       (add_16_31_n_32), .Y (add_16_31_n_76));
  OAI2BB1X1 add_16_31_g329(.A0N (add_16_31_n_45), .A1N
       (add_16_31_n_66), .B0 (add_16_31_n_64), .Y (add_16_31_n_75));
  OAI21X4 add_16_31_g330(.A0 (add_16_31_n_59), .A1 (add_16_31_n_63),
       .B0 (add_16_31_n_65), .Y (add_16_31_n_74));
  NOR2X6 add_16_31_g331(.A (add_16_31_n_1), .B (add_16_31_n_72), .Y
       (add_16_31_n_73));
  NOR2X4 add_16_31_g333(.A (add_16_31_n_36), .B (add_16_31_n_23), .Y
       (add_16_31_n_72));
  OR2XL add_16_31_g334(.A (add_16_31_n_13), .B (add_16_31_n_67), .Y
       (add_16_31_n_71));
  NAND2X1 add_16_31_g336(.A (add_16_31_n_17), .B (add_16_31_n_53), .Y
       (add_16_31_n_70));
  NAND2X1 add_16_31_g337(.A (add_16_31_n_58), .B (add_16_31_n_40), .Y
       (add_16_31_n_69));
  NAND2BX1 add_16_31_g338(.AN (n_143), .B (add_16_31_n_40), .Y
       (add_16_31_n_68));
  NAND2X1 add_16_31_g339(.A (add_16_31_n_45), .B (add_16_31_n_53), .Y
       (add_16_31_n_67));
  OAI21X1 add_16_31_g340(.A0 (add_16_31_n_27), .A1 (add_16_31_n_26),
       .B0 (add_16_31_n_37), .Y (add_16_31_n_66));
  AOI2BB1X4 add_16_31_g341(.A0N (add_16_31_n_32), .A1N
       (add_16_31_n_34), .B0 (add_16_31_n_28), .Y (add_16_31_n_65));
  OA21X1 add_16_31_g342(.A0 (add_16_31_n_24), .A1 (add_16_31_n_35), .B0
       (add_16_31_n_29), .Y (add_16_31_n_64));
  NOR2X2 add_16_31_g344(.A (add_16_31_n_39), .B (add_16_31_n_51), .Y
       (add_16_31_n_63));
  OAI21X2 add_16_31_g345(.A0 (add_16_31_n_31), .A1 (add_16_31_n_18),
       .B0 (add_16_31_n_38), .Y (add_16_31_n_62));
  INVX1 add_16_31_g346(.A (add_16_31_n_60), .Y (add_16_31_n_61));
  INVX1 add_16_31_g347(.A (add_16_31_n_58), .Y (add_16_31_n_59));
  INVX1 add_16_31_g349(.A (add_16_31_n_55), .Y (add_16_31_n_56));
  NAND2X2 add_16_31_g352(.A (add_16_31_n_25), .B (add_16_31_n_19), .Y
       (add_16_31_n_52));
  NOR2X2 add_16_31_g353(.A (add_16_31_n_33), .B (add_16_31_n_22), .Y
       (add_16_31_n_51));
  NOR2X1 add_16_31_g354(.A (add_16_31_n_28), .B (n_138), .Y
       (add_16_31_n_60));
  NOR2X1 add_16_31_g355(.A (add_16_31_n_34), .B (add_16_31_n_30), .Y
       (add_16_31_n_58));
  NOR2X1 add_16_31_g356(.A (add_16_31_n_1), .B (add_16_31_n_36), .Y
       (add_16_31_n_50));
  NAND2X1 add_16_31_g357(.A (add_16_31_n_24), .B (add_16_31_n_17), .Y
       (add_16_31_n_57));
  NOR2X1 add_16_31_g358(.A (add_16_31_n_39), .B (add_16_31_n_22), .Y
       (add_16_31_n_55));
  NAND2X1 add_16_31_g359(.A (add_16_31_n_31), .B (n_134), .Y
       (add_16_31_n_54));
  NOR2X1 add_16_31_g360(.A (add_16_31_n_26), .B (add_16_31_n_21), .Y
       (add_16_31_n_53));
  INVX1 add_16_31_g363(.A (add_16_31_n_46), .Y (add_16_31_n_47));
  INVX1 add_16_31_g366(.A (add_16_31_n_41), .Y (add_16_31_n_42));
  NAND2BX1 add_16_31_g369(.AN (n_141), .B (add_16_31_n_32), .Y
       (add_16_31_n_49));
  NAND2BX1 add_16_31_g370(.AN (add_16_31_n_21), .B (add_16_31_n_27), .Y
       (add_16_31_n_48));
  NOR2BX1 add_16_31_g371(.AN (add_16_31_n_29), .B (add_16_31_n_35), .Y
       (add_16_31_n_46));
  NOR2X1 add_16_31_g372(.A (add_16_31_n_35), .B (add_16_31_n_16), .Y
       (add_16_31_n_45));
  NAND2BX1 add_16_31_g373(.AN (add_16_31_n_20), .B (add_16_31_n_33), .Y
       (add_16_31_n_44));
  NAND2X1 add_16_31_g374(.A (add_16_31_n_38), .B (add_16_31_n_19), .Y
       (add_16_31_n_43));
  NOR2BX1 add_16_31_g375(.AN (add_16_31_n_37), .B (add_16_31_n_26), .Y
       (add_16_31_n_41));
  NOR2X1 add_16_31_g376(.A (add_16_31_n_22), .B (add_16_31_n_20), .Y
       (add_16_31_n_40));
  AND2X1 add_16_31_g378(.A (in2[5]), .B (in1[5]), .Y (add_16_31_n_39));
  NAND2X1 add_16_31_g379(.A (in2[3]), .B (in1[3]), .Y (add_16_31_n_38));
  NAND2X1 add_16_31_g380(.A (in2[9]), .B (in1[9]), .Y (add_16_31_n_37));
  NOR2X6 add_16_31_g381(.A (in2[1]), .B (in1[1]), .Y (add_16_31_n_36));
  NOR2X1 add_16_31_g382(.A (in2[11]), .B (in1[11]), .Y
       (add_16_31_n_35));
  NOR2X6 add_16_31_g383(.A (in2[7]), .B (in1[7]), .Y (add_16_31_n_34));
  NAND2X2 add_16_31_g384(.A (in2[4]), .B (in1[4]), .Y (add_16_31_n_33));
  NAND2X2 add_16_31_g385(.A (in2[6]), .B (in1[6]), .Y (add_16_31_n_32));
  NAND2X2 add_16_31_g386(.A (in2[2]), .B (in1[2]), .Y (add_16_31_n_31));
  NOR2X2 add_16_31_g387(.A (in2[6]), .B (in1[6]), .Y (add_16_31_n_30));
  CLKINVX2 add_16_31_g389(.A (add_16_31_n_18), .Y (add_16_31_n_19));
  INVX1 add_16_31_g390(.A (add_16_31_n_16), .Y (add_16_31_n_17));
  NAND2X1 add_16_31_g391(.A (in2[11]), .B (in1[11]), .Y
       (add_16_31_n_29));
  AND2X6 add_16_31_g392(.A (in2[7]), .B (in1[7]), .Y (add_16_31_n_28));
  NAND2X1 add_16_31_g393(.A (in2[8]), .B (in1[8]), .Y (add_16_31_n_27));
  NOR2X1 add_16_31_g394(.A (in2[9]), .B (in1[9]), .Y (add_16_31_n_26));
  NAND2X2 add_16_31_g395(.A (add_16_31_n_14), .B (add_16_31_n_15), .Y
       (add_16_31_n_25));
  NAND2X1 add_16_31_g396(.A (in2[10]), .B (in1[10]), .Y
       (add_16_31_n_24));
  NAND2X4 add_16_31_g397(.A (in2[0]), .B (in1[0]), .Y (add_16_31_n_23));
  NOR2X4 add_16_31_g398(.A (in2[5]), .B (in1[5]), .Y (add_16_31_n_22));
  NOR2X1 add_16_31_g399(.A (in2[8]), .B (in1[8]), .Y (add_16_31_n_21));
  NOR2X2 add_16_31_g400(.A (in2[4]), .B (in1[4]), .Y (add_16_31_n_20));
  NOR2X6 add_16_31_g401(.A (in2[3]), .B (in1[3]), .Y (add_16_31_n_18));
  NOR2X1 add_16_31_g402(.A (in2[10]), .B (in1[10]), .Y
       (add_16_31_n_16));
  CLKINVX2 add_16_31_g405(.A (in1[2]), .Y (add_16_31_n_15));
  CLKINVX3 add_16_31_g407(.A (in2[2]), .Y (add_16_31_n_14));
  INVX1 add_16_31_g408(.A (in2[12]), .Y (add_16_31_n_13));
  XNOR2X1 add_16_31_g2(.A (add_16_31_n_23), .B (add_16_31_n_50), .Y
       (out1[1]));
  NOR2BX1 add_16_31_g409(.AN (n_130), .B (add_16_31_n_3), .Y
       (add_16_31_n_11));
  CLKXOR2X1 add_16_31_g410(.A (add_16_31_n_57), .B (add_16_31_n_96), .Y
       (out1[10]));
  CLKXOR2X1 add_16_31_g411(.A (add_16_31_n_54), .B (n_126), .Y
       (out1[2]));
  NOR2BX2 add_16_31_g412(.AN (add_16_31_n_53), .B (add_16_31_n_87), .Y
       (add_16_31_n_8));
  CLKXOR2X1 add_16_31_g413(.A (add_16_31_n_49), .B (add_16_31_n_11), .Y
       (out1[6]));
  CLKXOR2X1 add_16_31_g414(.A (add_16_31_n_48), .B (add_16_31_n_87), .Y
       (out1[8]));
  CLKXOR2X1 add_16_31_g415(.A (add_16_31_n_44), .B (n_145), .Y
       (out1[4]));
  CLKXOR2X1 add_16_31_g416(.A (add_16_31_n_43), .B (add_16_31_n_81), .Y
       (out1[3]));
  NOR2BX1 add_16_31_g417(.AN (add_16_31_n_40), .B (n_145), .Y
       (add_16_31_n_3));
  NOR2BX1 add_16_31_g418(.AN (n_135), .B (n_127), .Y (add_16_31_n_2));
  CLKAND2X6 add_16_31_g419(.A (in2[1]), .B (in1[1]), .Y
       (add_16_31_n_1));
  CLKXOR2X1 add_16_31_g420(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  INVXL fopt(.A (n_128), .Y (n_126));
  INVXL fopt1(.A (n_128), .Y (n_127));
  INVXL fopt2(.A (add_16_31_n_73), .Y (n_128));
  INVXL fopt421(.A (n_132), .Y (n_130));
  INVXL fopt422(.A (n_132), .Y (n_131));
  INVXL fopt423(.A (add_16_31_n_63), .Y (n_132));
  INVXL fopt424(.A (n_136), .Y (n_134));
  INVXL fopt425(.A (n_136), .Y (n_135));
  INVXL fopt426(.A (add_16_31_n_25), .Y (n_136));
  BUFX2 fopt427(.A (add_16_31_n_34), .Y (n_138));
  INVXL fopt428(.A (n_142), .Y (n_140));
  INVXL fopt429(.A (n_142), .Y (n_141));
  INVXL fopt430(.A (n_143), .Y (n_142));
  BUFX2 fopt3(.A (add_16_31_n_30), .Y (n_143));
  BUFX3 fopt431(.A (add_16_31_n_80), .Y (n_145));
endmodule


