`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:44:48 CST (Jun  9 2025 08:44:48 UTC)

module dut_GreaterThanEQ_1U_54_4(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  OAI32X1 gte_15_26_g99(.A0 (in1[7]), .A1 (in1[5]), .A2 (in1[4]), .B0
       (in1[7]), .B1 (in1[6]), .Y (out1));
endmodule


