`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:44:19 CST (Jun  9 2025 08:44:19 UTC)

module dut_Add_32Sx8U_32S_4(in2, in1, out1);
  input [31:0] in2;
  input [7:0] in1;
  output [31:0] out1;
  wire [31:0] in2;
  wire [7:0] in1;
  wire [31:0] out1;
  wire add_16_23_n_0, add_16_23_n_1, add_16_23_n_2, add_16_23_n_3,
       add_16_23_n_4, add_16_23_n_5, add_16_23_n_6, add_16_23_n_7;
  wire add_16_23_n_8, add_16_23_n_9, add_16_23_n_10, add_16_23_n_11,
       add_16_23_n_12, add_16_23_n_13, add_16_23_n_14, add_16_23_n_15;
  wire add_16_23_n_16, add_16_23_n_17, add_16_23_n_18, add_16_23_n_19,
       add_16_23_n_20, add_16_23_n_21, add_16_23_n_22, add_16_23_n_23;
  wire add_16_23_n_24, add_16_23_n_25, add_16_23_n_26, add_16_23_n_27,
       add_16_23_n_28, add_16_23_n_29, add_16_23_n_30, add_16_23_n_31;
  wire add_16_23_n_32, add_16_23_n_33, add_16_23_n_36, add_16_23_n_37,
       add_16_23_n_39, add_16_23_n_40, add_16_23_n_42, add_16_23_n_44;
  wire add_16_23_n_45, add_16_23_n_46, add_16_23_n_49, add_16_23_n_50,
       add_16_23_n_51, add_16_23_n_52, add_16_23_n_54, add_16_23_n_55;
  wire add_16_23_n_56, add_16_23_n_57, add_16_23_n_58, add_16_23_n_59,
       add_16_23_n_60, add_16_23_n_65, add_16_23_n_66, add_16_23_n_67;
  wire add_16_23_n_68, add_16_23_n_69, add_16_23_n_70, add_16_23_n_75,
       add_16_23_n_76, add_16_23_n_77, add_16_23_n_78, add_16_23_n_83;
  XNOR2X1 add_16_23_g634(.A (in2[31]), .B (add_16_23_n_83), .Y
       (out1[31]));
  XNOR2X1 add_16_23_g635(.A (in2[23]), .B (add_16_23_n_76), .Y
       (out1[23]));
  XNOR2X1 add_16_23_g636(.A (in2[27]), .B (add_16_23_n_77), .Y
       (out1[27]));
  XNOR2X1 add_16_23_g637(.A (in2[29]), .B (add_16_23_n_75), .Y
       (out1[29]));
  XNOR2X1 add_16_23_g638(.A (in2[15]), .B (add_16_23_n_68), .Y
       (out1[15]));
  XNOR2X1 add_16_23_g639(.A (in2[21]), .B (add_16_23_n_66), .Y
       (out1[21]));
  XNOR2X1 add_16_23_g640(.A (in2[19]), .B (add_16_23_n_67), .Y
       (out1[19]));
  XNOR2X1 add_16_23_g641(.A (in2[25]), .B (add_16_23_n_60), .Y
       (out1[25]));
  XNOR2X1 add_16_23_g642(.A (in2[30]), .B (add_16_23_n_78), .Y
       (out1[30]));
  XNOR2X1 add_16_23_g643(.A (in2[17]), .B (add_16_23_n_1), .Y
       (out1[17]));
  XNOR2X1 add_16_23_g644(.A (in2[13]), .B (add_16_23_n_56), .Y
       (out1[13]));
  XNOR2X1 add_16_23_g645(.A (in2[11]), .B (add_16_23_n_55), .Y
       (out1[11]));
  NAND2BX1 add_16_23_g646(.AN (add_16_23_n_78), .B (in2[30]), .Y
       (add_16_23_n_83));
  XNOR2X1 add_16_23_g647(.A (in2[28]), .B (add_16_23_n_65), .Y
       (out1[28]));
  XNOR2X1 add_16_23_g648(.A (in2[9]), .B (add_16_23_n_0), .Y (out1[9]));
  XNOR2X1 add_16_23_g649(.A (in2[22]), .B (add_16_23_n_70), .Y
       (out1[22]));
  XNOR2X1 add_16_23_g650(.A (in2[26]), .B (add_16_23_n_69), .Y
       (out1[26]));
  NAND2BX1 add_16_23_g651(.AN (add_16_23_n_69), .B (in2[26]), .Y
       (add_16_23_n_77));
  NAND2BX1 add_16_23_g652(.AN (add_16_23_n_70), .B (in2[22]), .Y
       (add_16_23_n_76));
  NAND2BX1 add_16_23_g653(.AN (add_16_23_n_65), .B (in2[28]), .Y
       (add_16_23_n_75));
  NAND3BXL add_16_23_g654(.AN (add_16_23_n_65), .B (in2[29]), .C
       (in2[28]), .Y (add_16_23_n_78));
  XNOR2X1 add_16_23_g655(.A (in2[20]), .B (add_16_23_n_59), .Y
       (out1[20]));
  XOR2XL add_16_23_g656(.A (in2[24]), .B (add_16_23_n_54), .Y
       (out1[24]));
  XNOR2X1 add_16_23_g657(.A (in2[14]), .B (add_16_23_n_57), .Y
       (out1[14]));
  XNOR2X1 add_16_23_g658(.A (in2[18]), .B (add_16_23_n_58), .Y
       (out1[18]));
  NAND2BX1 add_16_23_g659(.AN (add_16_23_n_57), .B (in2[14]), .Y
       (add_16_23_n_68));
  NAND2BX1 add_16_23_g660(.AN (add_16_23_n_58), .B (in2[18]), .Y
       (add_16_23_n_67));
  NAND2BX1 add_16_23_g661(.AN (add_16_23_n_59), .B (in2[20]), .Y
       (add_16_23_n_66));
  OR2XL add_16_23_g662(.A (add_16_23_n_19), .B (add_16_23_n_59), .Y
       (add_16_23_n_70));
  NAND2BX1 add_16_23_g663(.AN (add_16_23_n_10), .B (add_16_23_n_54), .Y
       (add_16_23_n_69));
  XNOR2X1 add_16_23_g664(.A (in2[16]), .B (add_16_23_n_49), .Y
       (out1[16]));
  XNOR2X1 add_16_23_g665(.A (add_16_23_n_28), .B (add_16_23_n_50), .Y
       (out1[7]));
  XOR2XL add_16_23_g666(.A (in2[10]), .B (add_16_23_n_51), .Y
       (out1[10]));
  XOR2XL add_16_23_g667(.A (in2[12]), .B (add_16_23_n_52), .Y
       (out1[12]));
  NAND2X1 add_16_23_g668(.A (in2[24]), .B (add_16_23_n_54), .Y
       (add_16_23_n_60));
  NAND4BX1 add_16_23_g669(.AN (add_16_23_n_10), .B (add_16_23_n_54), .C
       (in2[27]), .D (in2[26]), .Y (add_16_23_n_65));
  OR2XL add_16_23_g670(.A (add_16_23_n_23), .B (add_16_23_n_49), .Y
       (add_16_23_n_59));
  OR2XL add_16_23_g671(.A (add_16_23_n_11), .B (add_16_23_n_49), .Y
       (add_16_23_n_58));
  NAND2BX1 add_16_23_g672(.AN (add_16_23_n_9), .B (add_16_23_n_52), .Y
       (add_16_23_n_57));
  NAND2X1 add_16_23_g674(.A (in2[12]), .B (add_16_23_n_52), .Y
       (add_16_23_n_56));
  NAND2X1 add_16_23_g675(.A (in2[10]), .B (add_16_23_n_51), .Y
       (add_16_23_n_55));
  NOR4X1 add_16_23_g676(.A (add_16_23_n_49), .B (add_16_23_n_23), .C
       (add_16_23_n_2), .D (add_16_23_n_19), .Y (add_16_23_n_54));
  XNOR2X1 add_16_23_g677(.A (in2[8]), .B (add_16_23_n_46), .Y
       (out1[8]));
  NOR2X1 add_16_23_g678(.A (add_16_23_n_22), .B (add_16_23_n_46), .Y
       (add_16_23_n_52));
  NOR2X1 add_16_23_g679(.A (add_16_23_n_12), .B (add_16_23_n_46), .Y
       (add_16_23_n_51));
  OAI21X1 add_16_23_g681(.A0 (add_16_23_n_16), .A1 (add_16_23_n_45),
       .B0 (add_16_23_n_5), .Y (add_16_23_n_50));
  OR4X1 add_16_23_g683(.A (add_16_23_n_46), .B (add_16_23_n_22), .C
       (add_16_23_n_13), .D (add_16_23_n_9), .Y (add_16_23_n_49));
  XNOR2X1 add_16_23_g684(.A (add_16_23_n_27), .B (add_16_23_n_45), .Y
       (out1[6]));
  XNOR2X1 add_16_23_g685(.A (add_16_23_n_26), .B (add_16_23_n_44), .Y
       (out1[5]));
  AOI221X1 add_16_23_g687(.A0 (add_16_23_n_24), .A1 (add_16_23_n_32),
       .B0 (add_16_23_n_24), .B1 (add_16_23_n_42), .C0
       (add_16_23_n_31), .Y (add_16_23_n_46));
  NOR2X1 add_16_23_g688(.A (add_16_23_n_32), .B (add_16_23_n_42), .Y
       (add_16_23_n_45));
  OAI2BB1X1 add_16_23_g689(.A0N (add_16_23_n_4), .A1N (add_16_23_n_40),
       .B0 (add_16_23_n_14), .Y (add_16_23_n_44));
  XNOR2X1 add_16_23_g690(.A (add_16_23_n_29), .B (add_16_23_n_40), .Y
       (out1[4]));
  NOR3BX1 add_16_23_g691(.AN (add_16_23_n_40), .B (add_16_23_n_15), .C
       (add_16_23_n_3), .Y (add_16_23_n_42));
  XNOR2X1 add_16_23_g692(.A (add_16_23_n_30), .B (add_16_23_n_39), .Y
       (out1[3]));
  OAI221X1 add_16_23_g693(.A0 (add_16_23_n_17), .A1 (add_16_23_n_37),
       .B0 (add_16_23_n_7), .B1 (add_16_23_n_17), .C0 (add_16_23_n_20),
       .Y (add_16_23_n_40));
  NAND2X1 add_16_23_g694(.A (add_16_23_n_7), .B (add_16_23_n_37), .Y
       (add_16_23_n_39));
  XNOR2X1 add_16_23_g695(.A (add_16_23_n_25), .B (add_16_23_n_36), .Y
       (out1[2]));
  NAND2BX1 add_16_23_g696(.AN (add_16_23_n_8), .B (add_16_23_n_36), .Y
       (add_16_23_n_37));
  ADDFX1 add_16_23_g697(.A (add_16_23_n_33), .B (in1[1]), .CI (in2[1]),
       .CO (add_16_23_n_36), .S (out1[1]));
  ADDHX1 add_16_23_g698(.A (in2[0]), .B (in1[0]), .CO (add_16_23_n_33),
       .S (out1[0]));
  OAI21X1 add_16_23_g699(.A0 (add_16_23_n_14), .A1 (add_16_23_n_15),
       .B0 (add_16_23_n_21), .Y (add_16_23_n_32));
  OAI21X1 add_16_23_g700(.A0 (add_16_23_n_5), .A1 (add_16_23_n_6), .B0
       (add_16_23_n_18), .Y (add_16_23_n_31));
  NAND2BX1 add_16_23_g701(.AN (add_16_23_n_17), .B (add_16_23_n_20), .Y
       (add_16_23_n_30));
  NAND2X1 add_16_23_g702(.A (add_16_23_n_14), .B (add_16_23_n_4), .Y
       (add_16_23_n_29));
  NAND2BX1 add_16_23_g703(.AN (add_16_23_n_6), .B (add_16_23_n_18), .Y
       (add_16_23_n_28));
  NOR2BX1 add_16_23_g704(.AN (add_16_23_n_5), .B (add_16_23_n_16), .Y
       (add_16_23_n_27));
  NAND2BX1 add_16_23_g705(.AN (add_16_23_n_15), .B (add_16_23_n_21), .Y
       (add_16_23_n_26));
  NAND2BX1 add_16_23_g706(.AN (add_16_23_n_8), .B (add_16_23_n_7), .Y
       (add_16_23_n_25));
  NOR2X1 add_16_23_g707(.A (add_16_23_n_6), .B (add_16_23_n_16), .Y
       (add_16_23_n_24));
  NAND3BXL add_16_23_g708(.AN (add_16_23_n_11), .B (in2[19]), .C
       (in2[18]), .Y (add_16_23_n_23));
  NAND3BXL add_16_23_g709(.AN (add_16_23_n_12), .B (in2[11]), .C
       (in2[10]), .Y (add_16_23_n_22));
  NAND2X1 add_16_23_g710(.A (in2[15]), .B (in2[14]), .Y
       (add_16_23_n_13));
  NAND2X1 add_16_23_g711(.A (in2[5]), .B (in1[5]), .Y (add_16_23_n_21));
  NAND2X1 add_16_23_g712(.A (in2[3]), .B (in1[3]), .Y (add_16_23_n_20));
  NAND2X1 add_16_23_g713(.A (in2[21]), .B (in2[20]), .Y
       (add_16_23_n_19));
  NAND2X1 add_16_23_g714(.A (in2[7]), .B (in1[7]), .Y (add_16_23_n_18));
  NOR2X1 add_16_23_g715(.A (in2[3]), .B (in1[3]), .Y (add_16_23_n_17));
  NOR2X1 add_16_23_g716(.A (in2[6]), .B (in1[6]), .Y (add_16_23_n_16));
  NOR2X1 add_16_23_g717(.A (in2[5]), .B (in1[5]), .Y (add_16_23_n_15));
  NAND2X1 add_16_23_g718(.A (in2[4]), .B (in1[4]), .Y (add_16_23_n_14));
  INVX1 add_16_23_g719(.A (add_16_23_n_3), .Y (add_16_23_n_4));
  NAND2X1 add_16_23_g720(.A (in2[23]), .B (in2[22]), .Y
       (add_16_23_n_2));
  NAND2X1 add_16_23_g721(.A (in2[9]), .B (in2[8]), .Y (add_16_23_n_12));
  NAND2X1 add_16_23_g722(.A (in2[17]), .B (in2[16]), .Y
       (add_16_23_n_11));
  NAND2X1 add_16_23_g723(.A (in2[25]), .B (in2[24]), .Y
       (add_16_23_n_10));
  NAND2X1 add_16_23_g724(.A (in2[13]), .B (in2[12]), .Y
       (add_16_23_n_9));
  NOR2X1 add_16_23_g725(.A (in2[2]), .B (in1[2]), .Y (add_16_23_n_8));
  NAND2X1 add_16_23_g726(.A (in2[2]), .B (in1[2]), .Y (add_16_23_n_7));
  NOR2X1 add_16_23_g727(.A (in2[7]), .B (in1[7]), .Y (add_16_23_n_6));
  NAND2X1 add_16_23_g728(.A (in2[6]), .B (in1[6]), .Y (add_16_23_n_5));
  NOR2X1 add_16_23_g729(.A (in2[4]), .B (in1[4]), .Y (add_16_23_n_3));
  NAND2BX1 add_16_23_g2(.AN (add_16_23_n_49), .B (in2[16]), .Y
       (add_16_23_n_1));
  NAND2BX1 add_16_23_g730(.AN (add_16_23_n_46), .B (in2[8]), .Y
       (add_16_23_n_0));
endmodule


