`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:47:21 CST (Jun  9 2025 08:47:21 UTC)

module dut_LessThan_1U_187_1(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire lt_15_26_n_0, lt_15_26_n_1, lt_15_26_n_2, lt_15_26_n_3,
       lt_15_26_n_4, lt_15_26_n_5, lt_15_26_n_6;
  AOI21X1 lt_15_26_g125(.A0 (lt_15_26_n_0), .A1 (lt_15_26_n_3), .B0
       (lt_15_26_n_6), .Y (out1));
  NOR2X1 lt_15_26_g126(.A (lt_15_26_n_5), .B (lt_15_26_n_4), .Y
       (lt_15_26_n_6));
  NAND2BX2 lt_15_26_g127(.AN (in1[4]), .B (lt_15_26_n_3), .Y
       (lt_15_26_n_5));
  NAND2X1 lt_15_26_g128(.A (lt_15_26_n_2), .B (lt_15_26_n_1), .Y
       (lt_15_26_n_4));
  NOR2X6 lt_15_26_g129(.A (in1[7]), .B (in1[6]), .Y (lt_15_26_n_3));
  NOR2X4 lt_15_26_g130(.A (in1[3]), .B (in1[2]), .Y (lt_15_26_n_2));
  NOR2X2 lt_15_26_g131(.A (in1[1]), .B (in1[0]), .Y (lt_15_26_n_1));
  INVX1 lt_15_26_g132(.A (in1[5]), .Y (lt_15_26_n_0));
endmodule


