`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:44:17 CST (Jun  9 2025 08:44:17 UTC)

module dut_Add_10Ux10U_11U_4(in2, in1, out1);
  input [9:0] in2, in1;
  output [10:0] out1;
  wire [9:0] in2, in1;
  wire [10:0] out1;
  wire add_16_31_n_0, add_16_31_n_1, add_16_31_n_2, add_16_31_n_3,
       add_16_31_n_4, add_16_31_n_5, add_16_31_n_6, add_16_31_n_7;
  wire add_16_31_n_8, add_16_31_n_9, add_16_31_n_10, add_16_31_n_11,
       add_16_31_n_12, add_16_31_n_13, add_16_31_n_14, add_16_31_n_15;
  wire add_16_31_n_16, add_16_31_n_17, add_16_31_n_18, add_16_31_n_19,
       add_16_31_n_20, add_16_31_n_21, add_16_31_n_22, add_16_31_n_23;
  wire add_16_31_n_24, add_16_31_n_25, add_16_31_n_26, add_16_31_n_27,
       add_16_31_n_28, add_16_31_n_31, add_16_31_n_32, add_16_31_n_34;
  wire add_16_31_n_35, add_16_31_n_37, add_16_31_n_39, add_16_31_n_40,
       add_16_31_n_41, add_16_31_n_44, add_16_31_n_45, add_16_31_n_47;
  XNOR2X1 add_16_31_g210(.A (add_16_31_n_24), .B (add_16_31_n_47), .Y
       (out1[9]));
  XNOR2X1 add_16_31_g211(.A (add_16_31_n_21), .B (add_16_31_n_44), .Y
       (out1[7]));
  OAI221X1 add_16_31_g212(.A0 (add_16_31_n_8), .A1 (add_16_31_n_45),
       .B0 (add_16_31_n_1), .B1 (add_16_31_n_8), .C0 (add_16_31_n_7),
       .Y (out1[10]));
  NAND2XL add_16_31_g213(.A (add_16_31_n_1), .B (add_16_31_n_45), .Y
       (add_16_31_n_47));
  XNOR2X1 add_16_31_g214(.A (add_16_31_n_22), .B (add_16_31_n_41), .Y
       (out1[8]));
  OR2XL add_16_31_g215(.A (add_16_31_n_15), .B (add_16_31_n_41), .Y
       (add_16_31_n_45));
  OAI21X1 add_16_31_g216(.A0 (add_16_31_n_2), .A1 (add_16_31_n_40), .B0
       (add_16_31_n_0), .Y (add_16_31_n_44));
  XNOR2X1 add_16_31_g217(.A (add_16_31_n_19), .B (add_16_31_n_40), .Y
       (out1[6]));
  XNOR2X1 add_16_31_g218(.A (add_16_31_n_20), .B (add_16_31_n_39), .Y
       (out1[5]));
  AOI221X1 add_16_31_g219(.A0 (add_16_31_n_17), .A1 (add_16_31_n_26),
       .B0 (add_16_31_n_17), .B1 (add_16_31_n_37), .C0
       (add_16_31_n_27), .Y (add_16_31_n_41));
  NOR2X1 add_16_31_g220(.A (add_16_31_n_26), .B (add_16_31_n_37), .Y
       (add_16_31_n_40));
  OAI2BB1X1 add_16_31_g221(.A0N (add_16_31_n_10), .A1N
       (add_16_31_n_35), .B0 (add_16_31_n_5), .Y (add_16_31_n_39));
  XNOR2X1 add_16_31_g222(.A (add_16_31_n_18), .B (add_16_31_n_35), .Y
       (out1[4]));
  NOR3BX1 add_16_31_g223(.AN (add_16_31_n_35), .B (add_16_31_n_12), .C
       (add_16_31_n_9), .Y (add_16_31_n_37));
  XNOR2X1 add_16_31_g224(.A (add_16_31_n_23), .B (add_16_31_n_34), .Y
       (out1[3]));
  OAI221X1 add_16_31_g225(.A0 (add_16_31_n_4), .A1 (add_16_31_n_32),
       .B0 (add_16_31_n_3), .B1 (add_16_31_n_4), .C0 (add_16_31_n_13),
       .Y (add_16_31_n_35));
  NAND2X1 add_16_31_g226(.A (add_16_31_n_3), .B (add_16_31_n_32), .Y
       (add_16_31_n_34));
  XNOR2X1 add_16_31_g227(.A (add_16_31_n_25), .B (add_16_31_n_31), .Y
       (out1[2]));
  NAND2BX1 add_16_31_g228(.AN (add_16_31_n_6), .B (add_16_31_n_31), .Y
       (add_16_31_n_32));
  ADDFX1 add_16_31_g229(.A (add_16_31_n_28), .B (in1[1]), .CI (in2[1]),
       .CO (add_16_31_n_31), .S (out1[1]));
  ADDHX1 add_16_31_g230(.A (in2[0]), .B (in1[0]), .CO (add_16_31_n_28),
       .S (out1[0]));
  OAI21X1 add_16_31_g231(.A0 (add_16_31_n_0), .A1 (add_16_31_n_11), .B0
       (add_16_31_n_16), .Y (add_16_31_n_27));
  OAI21X1 add_16_31_g232(.A0 (add_16_31_n_5), .A1 (add_16_31_n_12), .B0
       (add_16_31_n_14), .Y (add_16_31_n_26));
  NAND2BX1 add_16_31_g233(.AN (add_16_31_n_6), .B (add_16_31_n_3), .Y
       (add_16_31_n_25));
  NAND2BX1 add_16_31_g234(.AN (add_16_31_n_8), .B (add_16_31_n_7), .Y
       (add_16_31_n_24));
  NAND2BX1 add_16_31_g235(.AN (add_16_31_n_4), .B (add_16_31_n_13), .Y
       (add_16_31_n_23));
  NOR2BX1 add_16_31_g236(.AN (add_16_31_n_1), .B (add_16_31_n_15), .Y
       (add_16_31_n_22));
  NAND2BX1 add_16_31_g237(.AN (add_16_31_n_11), .B (add_16_31_n_16), .Y
       (add_16_31_n_21));
  NAND2BX1 add_16_31_g238(.AN (add_16_31_n_12), .B (add_16_31_n_14), .Y
       (add_16_31_n_20));
  NOR2BX1 add_16_31_g239(.AN (add_16_31_n_0), .B (add_16_31_n_2), .Y
       (add_16_31_n_19));
  NAND2X1 add_16_31_g240(.A (add_16_31_n_5), .B (add_16_31_n_10), .Y
       (add_16_31_n_18));
  NOR2X1 add_16_31_g241(.A (add_16_31_n_11), .B (add_16_31_n_2), .Y
       (add_16_31_n_17));
  INVX1 add_16_31_g242(.A (add_16_31_n_9), .Y (add_16_31_n_10));
  NAND2X1 add_16_31_g243(.A (in2[7]), .B (in1[7]), .Y (add_16_31_n_16));
  NOR2X1 add_16_31_g244(.A (in2[8]), .B (in1[8]), .Y (add_16_31_n_15));
  NAND2X1 add_16_31_g245(.A (in2[5]), .B (in1[5]), .Y (add_16_31_n_14));
  NAND2X1 add_16_31_g246(.A (in2[3]), .B (in1[3]), .Y (add_16_31_n_13));
  NOR2X1 add_16_31_g247(.A (in2[5]), .B (in1[5]), .Y (add_16_31_n_12));
  NOR2X1 add_16_31_g248(.A (in2[7]), .B (in1[7]), .Y (add_16_31_n_11));
  NOR2X1 add_16_31_g249(.A (in2[4]), .B (in1[4]), .Y (add_16_31_n_9));
  NOR2X1 add_16_31_g250(.A (in2[9]), .B (in1[9]), .Y (add_16_31_n_8));
  NAND2X1 add_16_31_g251(.A (in2[9]), .B (in1[9]), .Y (add_16_31_n_7));
  NOR2X1 add_16_31_g252(.A (in2[2]), .B (in1[2]), .Y (add_16_31_n_6));
  NAND2X1 add_16_31_g253(.A (in2[4]), .B (in1[4]), .Y (add_16_31_n_5));
  NOR2X1 add_16_31_g254(.A (in2[3]), .B (in1[3]), .Y (add_16_31_n_4));
  NAND2X1 add_16_31_g255(.A (in2[2]), .B (in1[2]), .Y (add_16_31_n_3));
  NOR2X1 add_16_31_g256(.A (in2[6]), .B (in1[6]), .Y (add_16_31_n_2));
  NAND2X1 add_16_31_g257(.A (in2[8]), .B (in1[8]), .Y (add_16_31_n_1));
  NAND2X1 add_16_31_g258(.A (in2[6]), .B (in1[6]), .Y (add_16_31_n_0));
endmodule


