`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:47:33 CST (Jun  9 2025 08:47:33 UTC)

module dut_LessThan_1U_220_1(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire lt_15_26_n_0, lt_15_26_n_1, lt_15_26_n_2, lt_15_26_n_3,
       lt_15_26_n_4, lt_15_26_n_5, lt_15_26_n_6;
  NOR2X1 lt_15_26_g117(.A (lt_15_26_n_5), .B (lt_15_26_n_6), .Y (out1));
  NOR2X1 lt_15_26_g118(.A (lt_15_26_n_0), .B (lt_15_26_n_4), .Y
       (lt_15_26_n_6));
  NOR2X1 lt_15_26_g119(.A (lt_15_26_n_1), .B (lt_15_26_n_0), .Y
       (lt_15_26_n_5));
  NAND2X1 lt_15_26_g120(.A (lt_15_26_n_3), .B (lt_15_26_n_2), .Y
       (lt_15_26_n_4));
  NOR2X2 lt_15_26_g121(.A (in1[3]), .B (in1[2]), .Y (lt_15_26_n_3));
  NOR2X1 lt_15_26_g124(.A (in1[1]), .B (in1[0]), .Y (lt_15_26_n_2));
  AND2XL lt_15_26_g2(.A (in1[5]), .B (in1[4]), .Y (lt_15_26_n_1));
  OR2XL lt_15_26_g129(.A (in1[7]), .B (in1[6]), .Y (lt_15_26_n_0));
endmodule


