`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:45:14 CST (Jun  9 2025 08:45:14 UTC)

module dut_GreaterThanEQ_1U_135_4(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire gte_15_26_n_0, gte_15_26_n_1, gte_15_26_n_2;
  OAI22X1 gte_15_26_g107(.A0 (gte_15_26_n_1), .A1 (gte_15_26_n_2), .B0
       (in1[4]), .B1 (gte_15_26_n_1), .Y (out1));
  OA22X1 gte_15_26_g108(.A0 (in1[3]), .A1 (gte_15_26_n_0), .B0
       (in1[3]), .B1 (in1[2]), .Y (gte_15_26_n_2));
  OR3XL gte_15_26_g109(.A (in1[5]), .B (in1[7]), .C (in1[6]), .Y
       (gte_15_26_n_1));
  AND2XL gte_15_26_g110(.A (in1[1]), .B (in1[0]), .Y (gte_15_26_n_0));
endmodule


