`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  4 2025 00:51:01 CST (Jun  3 2025 16:51:01 UTC)

module dut_Equal_1U_104_4(in1, out1);
  input [6:0] in1;
  output out1;
  wire [6:0] in1;
  wire out1;
  wire n_0;
  AND4XL g23(.A (in1[4]), .B (in1[3]), .C (in1[5]), .D (n_0), .Y
       (out1));
  NOR4BBX1 g24(.AN (in1[2]), .BN (in1[0]), .C (in1[6]), .D (in1[1]), .Y
       (n_0));
endmodule


