`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:45:06 CST (Jun  9 2025 08:45:06 UTC)

module dut_GreaterThanEQ_1U_102_4(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire gte_15_26_n_0, gte_15_26_n_1;
  AND2XL gte_15_26_g107(.A (gte_15_26_n_1), .B (gte_15_26_n_0), .Y
       (out1));
  NAND4XL gte_15_26_g108(.A (in1[3]), .B (in1[2]), .C (in1[1]), .D
       (in1[0]), .Y (gte_15_26_n_1));
  NOR4X1 gte_15_26_g109(.A (in1[7]), .B (in1[6]), .C (in1[5]), .D
       (in1[4]), .Y (gte_15_26_n_0));
endmodule


