`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:47:22 CST (Jun  9 2025 08:47:22 UTC)

module dut_LessThan_1U_191_1(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire lt_15_26_n_0, lt_15_26_n_1, lt_15_26_n_2, lt_15_26_n_3,
       lt_15_26_n_4, lt_15_26_n_5;
  AOI21X2 lt_15_26_g123(.A0 (lt_15_26_n_3), .A1 (lt_15_26_n_4), .B0
       (lt_15_26_n_5), .Y (out1));
  NOR2X1 lt_15_26_g124(.A (in1[5]), .B (lt_15_26_n_2), .Y
       (lt_15_26_n_5));
  NOR2X4 lt_15_26_g125(.A (in1[4]), .B (lt_15_26_n_2), .Y
       (lt_15_26_n_4));
  AOI211X4 lt_15_26_g126(.A0 (in1[1]), .A1 (in1[0]), .B0 (in1[3]), .C0
       (in1[2]), .Y (lt_15_26_n_3));
  NAND2X8 lt_15_26_g127(.A (lt_15_26_n_1), .B (lt_15_26_n_0), .Y
       (lt_15_26_n_2));
  CLKINVX12 lt_15_26_g128(.A (in1[7]), .Y (lt_15_26_n_1));
  CLKINVX4 lt_15_26_g129(.A (in1[6]), .Y (lt_15_26_n_0));
endmodule


