`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:47:08 CST (Jun  9 2025 08:47:08 UTC)

module dut_LessThan_1U_138_1(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire lt_15_26_n_0, lt_15_26_n_1, lt_15_26_n_2, lt_15_26_n_3,
       lt_15_26_n_4, lt_15_26_n_5;
  NOR2X1 lt_15_26_g116(.A (lt_15_26_n_3), .B (lt_15_26_n_5), .Y (out1));
  AOI21X1 lt_15_26_g117(.A0 (in1[3]), .A1 (lt_15_26_n_2), .B0
       (lt_15_26_n_4), .Y (lt_15_26_n_5));
  NAND2BX1 lt_15_26_g118(.AN (in1[4]), .B (lt_15_26_n_1), .Y
       (lt_15_26_n_4));
  NOR2BX1 lt_15_26_g119(.AN (lt_15_26_n_1), .B (in1[5]), .Y
       (lt_15_26_n_3));
  NAND2BX1 lt_15_26_g120(.AN (in1[2]), .B (lt_15_26_n_0), .Y
       (lt_15_26_n_2));
  NOR2X4 lt_15_26_g121(.A (in1[7]), .B (in1[6]), .Y (lt_15_26_n_1));
  NOR2X6 lt_15_26_g122(.A (in1[1]), .B (in1[0]), .Y (lt_15_26_n_0));
endmodule


