`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:45:30 CST (Jun  9 2025 08:45:30 UTC)

module dut_LessThan_1U_193_4(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire lt_15_26_n_0, lt_15_26_n_1;
  AOI2BB1X1 lt_15_26_g105(.A0N (in1[5]), .A1N (lt_15_26_n_0), .B0
       (lt_15_26_n_1), .Y (out1));
  NOR4X1 lt_15_26_g106(.A (in1[3]), .B (in1[2]), .C (in1[4]), .D
       (lt_15_26_n_0), .Y (lt_15_26_n_1));
  OR2XL lt_15_26_g107(.A (in1[7]), .B (in1[6]), .Y (lt_15_26_n_0));
endmodule


