`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:44:24 CST (Jun  9 2025 08:44:24 UTC)

module dut_LessThan_4Ux8U_1U_4(in2, in1, out1);
  input [3:0] in2;
  input [7:0] in1;
  output out1;
  wire [3:0] in2;
  wire [7:0] in1;
  wire out1;
  wire lt_16_34_n_0, lt_16_34_n_1, lt_16_34_n_2, lt_16_34_n_3,
       lt_16_34_n_4, lt_16_34_n_5, lt_16_34_n_6, lt_16_34_n_7;
  wire lt_16_34_n_8, lt_16_34_n_9, lt_16_34_n_10;
  NAND2X1 lt_16_34_g127(.A (lt_16_34_n_6), .B (lt_16_34_n_10), .Y
       (out1));
  OAI211X1 lt_16_34_g128(.A0 (lt_16_34_n_3), .A1 (in1[3]), .B0
       (lt_16_34_n_9), .C0 (lt_16_34_n_8), .Y (lt_16_34_n_10));
  OAI221X1 lt_16_34_g129(.A0 (lt_16_34_n_5), .A1 (lt_16_34_n_7), .B0
       (lt_16_34_n_2), .B1 (in2[2]), .C0 (lt_16_34_n_4), .Y
       (lt_16_34_n_9));
  NAND3X1 lt_16_34_g130(.A (lt_16_34_n_4), .B (in2[2]), .C
       (lt_16_34_n_2), .Y (lt_16_34_n_8));
  AOI22X1 lt_16_34_g131(.A0 (in1[0]), .A1 (lt_16_34_n_0), .B0 (in1[1]),
       .B1 (lt_16_34_n_1), .Y (lt_16_34_n_7));
  NOR4X1 lt_16_34_g132(.A (in1[7]), .B (in1[6]), .C (in1[5]), .D
       (in1[4]), .Y (lt_16_34_n_6));
  NOR2X1 lt_16_34_g133(.A (lt_16_34_n_1), .B (in1[1]), .Y
       (lt_16_34_n_5));
  NAND2X1 lt_16_34_g134(.A (in1[3]), .B (lt_16_34_n_3), .Y
       (lt_16_34_n_4));
  INVX1 lt_16_34_g135(.A (in2[3]), .Y (lt_16_34_n_3));
  INVX1 lt_16_34_g136(.A (in1[2]), .Y (lt_16_34_n_2));
  INVX1 lt_16_34_g137(.A (in2[1]), .Y (lt_16_34_n_1));
  INVX1 lt_16_34_g138(.A (in2[0]), .Y (lt_16_34_n_0));
endmodule


