`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:47:08 CST (Jun  9 2025 08:47:08 UTC)

module dut_GreaterThanEQ_1U_139_1(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire gte_15_26_n_0, gte_15_26_n_1, gte_15_26_n_2;
  NAND2X2 gte_15_26_g102(.A (gte_15_26_n_0), .B (gte_15_26_n_1), .Y
       (gte_15_26_n_2));
  CLKINVX2 gte_15_26_g103(.A (in1[6]), .Y (gte_15_26_n_1));
  CLKINVX4 gte_15_26_g104(.A (in1[7]), .Y (gte_15_26_n_0));
  AOI21X2 g2(.A0 (in1[5]), .A1 (in1[4]), .B0 (gte_15_26_n_2), .Y
       (out1));
endmodule


