`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:44:20 CST (Jun  9 2025 08:44:20 UTC)

module dut_LessThan_7Ux8U_1U_4(in2, in1, out1);
  input [6:0] in2;
  input [7:0] in1;
  output out1;
  wire [6:0] in2;
  wire [7:0] in1;
  wire out1;
  wire lt_16_31_n_0, lt_16_31_n_1, lt_16_31_n_2, lt_16_31_n_3,
       lt_16_31_n_4, lt_16_31_n_5, lt_16_31_n_6, lt_16_31_n_7;
  wire lt_16_31_n_8, lt_16_31_n_9, lt_16_31_n_10, lt_16_31_n_11,
       lt_16_31_n_12, lt_16_31_n_13, lt_16_31_n_14, lt_16_31_n_15;
  wire lt_16_31_n_16, lt_16_31_n_17, lt_16_31_n_18;
  AOI221X1 lt_16_31_g174(.A0 (lt_16_31_n_13), .A1 (lt_16_31_n_16), .B0
       (lt_16_31_n_15), .B1 (lt_16_31_n_18), .C0 (lt_16_31_n_12), .Y
       (out1));
  OAI211X1 lt_16_31_g175(.A0 (lt_16_31_n_0), .A1 (in1[3]), .B0
       (lt_16_31_n_17), .C0 (lt_16_31_n_11), .Y (lt_16_31_n_18));
  OAI221X1 lt_16_31_g176(.A0 (lt_16_31_n_8), .A1 (lt_16_31_n_10), .B0
       (lt_16_31_n_1), .B1 (in2[2]), .C0 (lt_16_31_n_7), .Y
       (lt_16_31_n_17));
  OAI32X1 lt_16_31_g177(.A0 (lt_16_31_n_9), .A1 (lt_16_31_n_6), .A2
       (in1[4]), .B0 (lt_16_31_n_5), .B1 (in1[5]), .Y (lt_16_31_n_16));
  AOI211XL lt_16_31_g178(.A0 (in1[4]), .A1 (lt_16_31_n_6), .B0
       (lt_16_31_n_14), .C0 (lt_16_31_n_9), .Y (lt_16_31_n_15));
  INVX1 lt_16_31_g179(.A (lt_16_31_n_13), .Y (lt_16_31_n_14));
  AOI21X1 lt_16_31_g180(.A0 (in1[6]), .A1 (lt_16_31_n_3), .B0 (in1[7]),
       .Y (lt_16_31_n_13));
  NOR3X1 lt_16_31_g181(.A (in1[7]), .B (lt_16_31_n_3), .C (in1[6]), .Y
       (lt_16_31_n_12));
  NAND3BXL lt_16_31_g182(.AN (in1[2]), .B (lt_16_31_n_7), .C (in2[2]),
       .Y (lt_16_31_n_11));
  AOI22X1 lt_16_31_g183(.A0 (in1[0]), .A1 (lt_16_31_n_2), .B0 (in1[1]),
       .B1 (lt_16_31_n_4), .Y (lt_16_31_n_10));
  NOR2BX1 lt_16_31_g184(.AN (in1[5]), .B (in2[5]), .Y (lt_16_31_n_9));
  NOR2X1 lt_16_31_g185(.A (lt_16_31_n_4), .B (in1[1]), .Y
       (lt_16_31_n_8));
  NAND2X1 lt_16_31_g186(.A (in1[3]), .B (lt_16_31_n_0), .Y
       (lt_16_31_n_7));
  INVX1 lt_16_31_g187(.A (in2[4]), .Y (lt_16_31_n_6));
  INVX1 lt_16_31_g188(.A (in2[5]), .Y (lt_16_31_n_5));
  INVX1 lt_16_31_g189(.A (in2[1]), .Y (lt_16_31_n_4));
  INVX1 lt_16_31_g190(.A (in2[6]), .Y (lt_16_31_n_3));
  INVX1 lt_16_31_g191(.A (in2[0]), .Y (lt_16_31_n_2));
  INVX1 lt_16_31_g192(.A (in1[2]), .Y (lt_16_31_n_1));
  INVX1 lt_16_31_g193(.A (in2[3]), .Y (lt_16_31_n_0));
endmodule


