`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:47:26 CST (Jun  9 2025 08:47:26 UTC)

module dut_LessThan_1U_202_1(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire lt_15_26_n_0, lt_15_26_n_1, lt_15_26_n_2, lt_15_26_n_3,
       lt_15_26_n_4, lt_15_26_n_5, lt_15_26_n_6, lt_15_26_n_7;
  NOR2X1 lt_15_26_g115(.A (lt_15_26_n_0), .B (lt_15_26_n_7), .Y (out1));
  NOR2X1 lt_15_26_g116(.A (lt_15_26_n_5), .B (lt_15_26_n_6), .Y
       (lt_15_26_n_7));
  AOI21X1 lt_15_26_g117(.A0 (lt_15_26_n_1), .A1 (lt_15_26_n_2), .B0
       (lt_15_26_n_3), .Y (lt_15_26_n_6));
  NAND2BX1 lt_15_26_g118(.AN (in1[4]), .B (lt_15_26_n_4), .Y
       (lt_15_26_n_5));
  NOR2X4 lt_15_26_g121(.A (in1[7]), .B (in1[6]), .Y (lt_15_26_n_4));
  NOR2X1 lt_15_26_g122(.A (in1[3]), .B (in1[2]), .Y (lt_15_26_n_3));
  NAND2X6 lt_15_26_g123(.A (in1[1]), .B (in1[0]), .Y (lt_15_26_n_2));
  CLKINVX2 lt_15_26_g124(.A (in1[3]), .Y (lt_15_26_n_1));
  NOR2BX1 lt_15_26_g2(.AN (lt_15_26_n_4), .B (in1[5]), .Y
       (lt_15_26_n_0));
endmodule


