`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:46:24 CST (Jun  9 2025 08:46:24 UTC)

module dut_LessThan_2Ux8U_1U_1(in2, in1, out1);
  input [1:0] in2;
  input [7:0] in1;
  output out1;
  wire [1:0] in2;
  wire [7:0] in1;
  wire out1;
  wire lt_16_36_n_0, lt_16_36_n_1, lt_16_36_n_2, lt_16_36_n_3,
       lt_16_36_n_4, lt_16_36_n_5, lt_16_36_n_6, lt_16_36_n_7;
  wire lt_16_36_n_8, lt_16_36_n_9;
  NAND2X1 lt_16_36_g111(.A (lt_16_36_n_8), .B (lt_16_36_n_9), .Y
       (out1));
  NOR2X1 lt_16_36_g112(.A (lt_16_36_n_0), .B (lt_16_36_n_7), .Y
       (lt_16_36_n_9));
  OAI21X1 lt_16_36_g113(.A0 (lt_16_36_n_1), .A1 (lt_16_36_n_3), .B0
       (lt_16_36_n_4), .Y (lt_16_36_n_8));
  NAND2X1 lt_16_36_g114(.A (lt_16_36_n_6), .B (lt_16_36_n_5), .Y
       (lt_16_36_n_7));
  NOR2X4 lt_16_36_g116(.A (in1[5]), .B (in1[4]), .Y (lt_16_36_n_6));
  NOR2X2 lt_16_36_g117(.A (in1[3]), .B (in1[2]), .Y (lt_16_36_n_5));
  NAND2X1 lt_16_36_g118(.A (in2[1]), .B (lt_16_36_n_2), .Y
       (lt_16_36_n_4));
  NOR2X1 lt_16_36_g120(.A (lt_16_36_n_2), .B (in2[1]), .Y
       (lt_16_36_n_3));
  INVX1 lt_16_36_g122(.A (in1[1]), .Y (lt_16_36_n_2));
  NOR2BX1 lt_16_36_g2(.AN (in1[0]), .B (in2[0]), .Y (lt_16_36_n_1));
  OR2XL lt_16_36_g125(.A (in1[7]), .B (in1[6]), .Y (lt_16_36_n_0));
endmodule


