`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:44:34 CST (Jun  9 2025 08:44:34 UTC)

module dut_LessThan_1U_19_4(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire lt_15_26_n_0, lt_15_26_n_1, lt_15_26_n_2, lt_15_26_n_3,
       lt_15_26_n_4;
  AOI221X1 lt_15_26_g107(.A0 (lt_15_26_n_0), .A1 (lt_15_26_n_3), .B0
       (lt_15_26_n_3), .B1 (lt_15_26_n_4), .C0 (lt_15_26_n_2), .Y
       (out1));
  OAI21X1 lt_15_26_g108(.A0 (in1[2]), .A1 (lt_15_26_n_1), .B0 (in1[3]),
       .Y (lt_15_26_n_4));
  NOR2X1 lt_15_26_g109(.A (in1[7]), .B (in1[5]), .Y (lt_15_26_n_3));
  NOR2X1 lt_15_26_g110(.A (in1[7]), .B (in1[6]), .Y (lt_15_26_n_2));
  AND2XL lt_15_26_g111(.A (in1[1]), .B (in1[0]), .Y (lt_15_26_n_1));
  INVX1 lt_15_26_g112(.A (in1[4]), .Y (lt_15_26_n_0));
endmodule


