`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:44:57 CST (Jun  9 2025 08:44:57 UTC)

module dut_GreaterThanEQ_1U_77_4(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire gte_15_26_n_0;
  OAI32X1 gte_15_26_g110(.A0 (gte_15_26_n_0), .A1 (in1[3]), .A2
       (in1[2]), .B0 (in1[7]), .B1 (in1[6]), .Y (out1));
  OR3XL gte_15_26_g111(.A (in1[7]), .B (in1[5]), .C (in1[4]), .Y
       (gte_15_26_n_0));
endmodule


