`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:44:22 CST (Jun  9 2025 08:44:22 UTC)

module dut_OrReduction_2U_1U_4(in1, out1);
  input [1:0] in1;
  output out1;
  wire [1:0] in1;
  wire out1;
  OR2XL g4(.A (in1[1]), .B (in1[0]), .Y (out1));
endmodule


