`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:46:35 CST (Jun  9 2025 08:46:35 UTC)

module dut_LessThan_1U_29_1(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire lt_15_26_n_0, lt_15_26_n_1, lt_15_26_n_2, lt_15_26_n_3,
       lt_15_26_n_4, lt_15_26_n_5, lt_15_26_n_6, lt_15_26_n_7;
  wire lt_15_26_n_8, lt_15_26_n_9;
  NOR2X1 lt_15_26_g118(.A (lt_15_26_n_8), .B (lt_15_26_n_9), .Y (out1));
  NOR2X1 lt_15_26_g119(.A (lt_15_26_n_1), .B (lt_15_26_n_6), .Y
       (lt_15_26_n_9));
  NAND2X1 lt_15_26_g120(.A (lt_15_26_n_0), .B (lt_15_26_n_7), .Y
       (lt_15_26_n_8));
  NAND2BX1 lt_15_26_g121(.AN (in1[7]), .B (lt_15_26_n_3), .Y
       (lt_15_26_n_7));
  NOR2X1 lt_15_26_g122(.A (lt_15_26_n_4), .B (lt_15_26_n_5), .Y
       (lt_15_26_n_6));
  NOR2X1 lt_15_26_g123(.A (in1[3]), .B (in1[1]), .Y (lt_15_26_n_5));
  NOR2X1 lt_15_26_g126(.A (in1[3]), .B (in1[2]), .Y (lt_15_26_n_4));
  NOR2X2 lt_15_26_g127(.A (in1[5]), .B (in1[4]), .Y (lt_15_26_n_3));
  CLKINVX2 lt_15_26_g128(.A (in1[7]), .Y (lt_15_26_n_2));
  NAND2BX1 lt_15_26_g2(.AN (in1[5]), .B (lt_15_26_n_2), .Y
       (lt_15_26_n_1));
  NAND2BX1 lt_15_26_g131(.AN (in1[6]), .B (lt_15_26_n_2), .Y
       (lt_15_26_n_0));
endmodule


