`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:44:26 CST (Jun  9 2025 08:44:26 UTC)

module dut_GreaterThanEQ_3Ux8U_1U_4(in2, in1, out1);
  input [2:0] in2;
  input [7:0] in1;
  output out1;
  wire [2:0] in2;
  wire [7:0] in1;
  wire out1;
  wire gte_16_35_n_0, gte_16_35_n_1, gte_16_35_n_2, gte_16_35_n_3,
       gte_16_35_n_4, gte_16_35_n_5, gte_16_35_n_6, gte_16_35_n_7;
  OA21X1 gte_16_35_g125(.A0 (gte_16_35_n_6), .A1 (gte_16_35_n_7), .B0
       (gte_16_35_n_4), .Y (out1));
  AOI221X1 gte_16_35_g126(.A0 (in1[2]), .A1 (gte_16_35_n_0), .B0
       (gte_16_35_n_3), .B1 (gte_16_35_n_5), .C0 (in1[3]), .Y
       (gte_16_35_n_7));
  NOR3X1 gte_16_35_g127(.A (in1[3]), .B (gte_16_35_n_0), .C (in1[2]),
       .Y (gte_16_35_n_6));
  OAI22X1 gte_16_35_g128(.A0 (gte_16_35_n_2), .A1 (in2[0]), .B0
       (gte_16_35_n_1), .B1 (in2[1]), .Y (gte_16_35_n_5));
  NOR4X1 gte_16_35_g129(.A (in1[7]), .B (in1[6]), .C (in1[5]), .D
       (in1[4]), .Y (gte_16_35_n_4));
  NAND2X1 gte_16_35_g130(.A (in2[1]), .B (gte_16_35_n_1), .Y
       (gte_16_35_n_3));
  INVX1 gte_16_35_g131(.A (in1[0]), .Y (gte_16_35_n_2));
  INVX1 gte_16_35_g132(.A (in1[1]), .Y (gte_16_35_n_1));
  INVX1 gte_16_35_g133(.A (in2[2]), .Y (gte_16_35_n_0));
endmodule


