`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:45:20 CST (Jun  9 2025 08:45:20 UTC)

module dut_LessThan_1U_166_4(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire lt_15_26_n_0, lt_15_26_n_1, lt_15_26_n_2;
  OAI21X1 lt_15_26_g104(.A0 (lt_15_26_n_0), .A1 (lt_15_26_n_2), .B0
       (lt_15_26_n_1), .Y (out1));
  AOI21X1 lt_15_26_g105(.A0 (in1[1]), .A1 (in1[0]), .B0 (in1[3]), .Y
       (lt_15_26_n_2));
  NOR4X1 lt_15_26_g106(.A (in1[7]), .B (in1[6]), .C (in1[5]), .D
       (in1[4]), .Y (lt_15_26_n_1));
  NOR2X1 lt_15_26_g107(.A (in1[3]), .B (in1[2]), .Y (lt_15_26_n_0));
endmodule


