`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:44:41 CST (Jun  9 2025 08:44:41 UTC)

module dut_GreaterThanEQ_1U_36_4(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire gte_15_26_n_0, gte_15_26_n_1, gte_15_26_n_2;
  OAI221X1 gte_15_26_g107(.A0 (in1[4]), .A1 (gte_15_26_n_0), .B0
       (in1[7]), .B1 (in1[6]), .C0 (gte_15_26_n_2), .Y (out1));
  NAND2BXL gte_15_26_g108(.AN (gte_15_26_n_0), .B (gte_15_26_n_1), .Y
       (gte_15_26_n_2));
  OAI31X1 gte_15_26_g109(.A0 (in1[2]), .A1 (in1[1]), .A2 (in1[0]), .B0
       (in1[3]), .Y (gte_15_26_n_1));
  OR2XL gte_15_26_g110(.A (in1[7]), .B (in1[5]), .Y (gte_15_26_n_0));
endmodule


