`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  4 2025 00:50:22 CST (Jun  3 2025 16:50:22 UTC)

module dut_Equal_7Ux5U_1U_4(in2, in1, out1);
  input [6:0] in2;
  input [4:0] in1;
  output out1;
  wire [6:0] in2;
  wire [4:0] in1;
  wire out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  NOR2XL g64(.A (n_6), .B (n_7), .Y (out1));
  NAND4XL g65(.A (n_0), .B (n_5), .C (n_3), .D (n_1), .Y (n_7));
  NAND2X1 g66(.A (n_4), .B (n_2), .Y (n_6));
  XNOR2X1 g71(.A (in2[4]), .B (in1[4]), .Y (n_5));
  XNOR2X1 g68(.A (in2[1]), .B (in1[1]), .Y (n_4));
  XNOR2X1 g69(.A (in2[3]), .B (in1[3]), .Y (n_3));
  XNOR2X1 g67(.A (in2[0]), .B (in1[0]), .Y (n_2));
  XNOR2X1 g70(.A (in2[2]), .B (in1[2]), .Y (n_1));
  NOR2X1 g72(.A (in2[6]), .B (in2[5]), .Y (n_0));
endmodule


