`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  4 2025 00:39:51 CST (Jun  3 2025 16:39:51 UTC)

module dut_LessThan_9Sx9S_1U_4(in2, in1, out1);
  input [8:0] in2, in1;
  output out1;
  wire [8:0] in2, in1;
  wire out1;
  wire lt_16_24_n_0, lt_16_24_n_1, lt_16_24_n_2, lt_16_24_n_3,
       lt_16_24_n_4, lt_16_24_n_5, lt_16_24_n_6, lt_16_24_n_7;
  wire lt_16_24_n_8, lt_16_24_n_9, lt_16_24_n_10, lt_16_24_n_11,
       lt_16_24_n_12, lt_16_24_n_13, lt_16_24_n_14, lt_16_24_n_15;
  wire lt_16_24_n_16, lt_16_24_n_17, lt_16_24_n_18, lt_16_24_n_19,
       lt_16_24_n_20, lt_16_24_n_21, lt_16_24_n_22, lt_16_24_n_23;
  wire n_0, n_18;
  XNOR2X1 g31(.A (n_0), .B (n_18), .Y (out1));
  XNOR2X1 g32(.A (in2[8]), .B (in1[8]), .Y (n_0));
  AOI22X1 lt_16_24_g194(.A0 (lt_16_24_n_13), .A1 (lt_16_24_n_23), .B0
       (in2[8]), .B1 (lt_16_24_n_1), .Y (n_18));
  OAI211X1 lt_16_24_g195(.A0 (lt_16_24_n_17), .A1 (lt_16_24_n_18), .B0
       (lt_16_24_n_22), .C0 (lt_16_24_n_19), .Y (lt_16_24_n_23));
  NAND4BX1 lt_16_24_g196(.AN (lt_16_24_n_17), .B (lt_16_24_n_21), .C
       (lt_16_24_n_10), .D (lt_16_24_n_14), .Y (lt_16_24_n_22));
  OAI211X1 lt_16_24_g197(.A0 (lt_16_24_n_7), .A1 (in1[3]), .B0
       (lt_16_24_n_20), .C0 (lt_16_24_n_16), .Y (lt_16_24_n_21));
  OAI221X1 lt_16_24_g198(.A0 (lt_16_24_n_11), .A1 (lt_16_24_n_15), .B0
       (lt_16_24_n_2), .B1 (in2[2]), .C0 (lt_16_24_n_12), .Y
       (lt_16_24_n_20));
  AOI32X1 lt_16_24_g199(.A0 (lt_16_24_n_9), .A1 (in2[6]), .A2
       (lt_16_24_n_4), .B0 (in2[7]), .B1 (lt_16_24_n_3), .Y
       (lt_16_24_n_19));
  AOI32X1 lt_16_24_g200(.A0 (lt_16_24_n_10), .A1 (in2[4]), .A2
       (lt_16_24_n_0), .B0 (in2[5]), .B1 (lt_16_24_n_6), .Y
       (lt_16_24_n_18));
  OAI21X1 lt_16_24_g201(.A0 (lt_16_24_n_4), .A1 (in2[6]), .B0
       (lt_16_24_n_9), .Y (lt_16_24_n_17));
  NAND3X1 lt_16_24_g202(.A (lt_16_24_n_12), .B (in2[2]), .C
       (lt_16_24_n_2), .Y (lt_16_24_n_16));
  AOI22X1 lt_16_24_g203(.A0 (in1[0]), .A1 (lt_16_24_n_8), .B0 (in1[1]),
       .B1 (lt_16_24_n_5), .Y (lt_16_24_n_15));
  NAND2BXL lt_16_24_g204(.AN (in2[4]), .B (in1[4]), .Y (lt_16_24_n_14));
  NAND2BXL lt_16_24_g205(.AN (in2[8]), .B (in1[8]), .Y (lt_16_24_n_13));
  NAND2X1 lt_16_24_g206(.A (in1[3]), .B (lt_16_24_n_7), .Y
       (lt_16_24_n_12));
  NOR2X1 lt_16_24_g207(.A (lt_16_24_n_5), .B (in1[1]), .Y
       (lt_16_24_n_11));
  NAND2BX1 lt_16_24_g208(.AN (in2[5]), .B (in1[5]), .Y (lt_16_24_n_10));
  NAND2BX1 lt_16_24_g209(.AN (in2[7]), .B (in1[7]), .Y (lt_16_24_n_9));
  INVX1 lt_16_24_g210(.A (in2[0]), .Y (lt_16_24_n_8));
  INVX1 lt_16_24_g211(.A (in2[3]), .Y (lt_16_24_n_7));
  INVX1 lt_16_24_g212(.A (in1[5]), .Y (lt_16_24_n_6));
  INVX1 lt_16_24_g213(.A (in2[1]), .Y (lt_16_24_n_5));
  INVX1 lt_16_24_g214(.A (in1[6]), .Y (lt_16_24_n_4));
  INVX1 lt_16_24_g215(.A (in1[7]), .Y (lt_16_24_n_3));
  INVX1 lt_16_24_g216(.A (in1[2]), .Y (lt_16_24_n_2));
  INVX1 lt_16_24_g217(.A (in1[8]), .Y (lt_16_24_n_1));
  INVX1 lt_16_24_g218(.A (in1[4]), .Y (lt_16_24_n_0));
endmodule


