`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:46:19 CST (Jun  9 2025 08:46:19 UTC)

module dut_LessThan_6Ux8U_1U_1(in2, in1, out1);
  input [5:0] in2;
  input [7:0] in1;
  output out1;
  wire [5:0] in2;
  wire [7:0] in1;
  wire out1;
  wire lt_16_32_n_0, lt_16_32_n_1, lt_16_32_n_2, lt_16_32_n_3,
       lt_16_32_n_4, lt_16_32_n_5, lt_16_32_n_6, lt_16_32_n_7;
  wire lt_16_32_n_8, lt_16_32_n_9, lt_16_32_n_10, lt_16_32_n_11,
       lt_16_32_n_12, lt_16_32_n_13, lt_16_32_n_14, lt_16_32_n_15;
  wire lt_16_32_n_16, lt_16_32_n_17, lt_16_32_n_18, lt_16_32_n_19,
       lt_16_32_n_20, lt_16_32_n_21, lt_16_32_n_22, lt_16_32_n_23;
  AOI21X1 lt_16_32_g134(.A0 (lt_16_32_n_18), .A1 (lt_16_32_n_23), .B0
       (lt_16_32_n_22), .Y (out1));
  OAI21X1 lt_16_32_g135(.A0 (lt_16_32_n_16), .A1 (lt_16_32_n_21), .B0
       (lt_16_32_n_20), .Y (lt_16_32_n_23));
  NOR2BX1 lt_16_32_g136(.AN (lt_16_32_n_9), .B (lt_16_32_n_19), .Y
       (lt_16_32_n_22));
  AOI21X1 lt_16_32_g137(.A0 (lt_16_32_n_0), .A1 (lt_16_32_n_14), .B0
       (lt_16_32_n_13), .Y (lt_16_32_n_21));
  AOI21X1 lt_16_32_g138(.A0 (lt_16_32_n_8), .A1 (lt_16_32_n_10), .B0
       (lt_16_32_n_11), .Y (lt_16_32_n_20));
  AOI21X1 lt_16_32_g139(.A0 (lt_16_32_n_15), .A1 (lt_16_32_n_7), .B0
       (lt_16_32_n_6), .Y (lt_16_32_n_19));
  NOR2BX1 lt_16_32_g140(.AN (lt_16_32_n_9), .B (lt_16_32_n_17), .Y
       (lt_16_32_n_18));
  OAI2BB1X1 lt_16_32_g141(.A0N (in1[4]), .A1N (lt_16_32_n_2), .B0
       (lt_16_32_n_15), .Y (lt_16_32_n_17));
  NAND2X1 lt_16_32_g142(.A (lt_16_32_n_10), .B (lt_16_32_n_12), .Y
       (lt_16_32_n_16));
  NAND2X1 lt_16_32_g143(.A (in1[1]), .B (lt_16_32_n_1), .Y
       (lt_16_32_n_14));
  NOR2X1 lt_16_32_g144(.A (lt_16_32_n_1), .B (in1[1]), .Y
       (lt_16_32_n_13));
  NAND2X1 lt_16_32_g145(.A (in1[2]), .B (lt_16_32_n_5), .Y
       (lt_16_32_n_12));
  NOR2BX1 lt_16_32_g146(.AN (in2[3]), .B (in1[3]), .Y (lt_16_32_n_11));
  NAND2X1 lt_16_32_g147(.A (in1[5]), .B (lt_16_32_n_3), .Y
       (lt_16_32_n_15));
  NOR2X2 lt_16_32_g149(.A (in1[2]), .B (lt_16_32_n_5), .Y
       (lt_16_32_n_8));
  NOR2X1 lt_16_32_g150(.A (lt_16_32_n_2), .B (in1[4]), .Y
       (lt_16_32_n_7));
  NOR2X1 lt_16_32_g151(.A (lt_16_32_n_3), .B (in1[5]), .Y
       (lt_16_32_n_6));
  NAND2X2 lt_16_32_g152(.A (in1[3]), .B (lt_16_32_n_4), .Y
       (lt_16_32_n_10));
  NOR2X1 lt_16_32_g153(.A (in1[7]), .B (in1[6]), .Y (lt_16_32_n_9));
  INVX1 lt_16_32_g155(.A (in2[2]), .Y (lt_16_32_n_5));
  CLKINVX2 lt_16_32_g156(.A (in2[3]), .Y (lt_16_32_n_4));
  INVX1 lt_16_32_g157(.A (in2[5]), .Y (lt_16_32_n_3));
  INVX1 lt_16_32_g158(.A (in2[4]), .Y (lt_16_32_n_2));
  INVX1 lt_16_32_g159(.A (in2[1]), .Y (lt_16_32_n_1));
  NAND2BX1 lt_16_32_g2(.AN (in2[0]), .B (in1[0]), .Y (lt_16_32_n_0));
endmodule


