`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:44:22 CST (Jun  9 2025 08:44:22 UTC)

module dut_GreaterThanEQ_6Ux8U_1U_4(in2, in1, out1);
  input [5:0] in2;
  input [7:0] in1;
  output out1;
  wire [5:0] in2;
  wire [7:0] in1;
  wire out1;
  wire gte_16_32_n_0, gte_16_32_n_1, gte_16_32_n_2, gte_16_32_n_3,
       gte_16_32_n_4, gte_16_32_n_5, gte_16_32_n_6, gte_16_32_n_7;
  wire gte_16_32_n_8, gte_16_32_n_9, gte_16_32_n_10, gte_16_32_n_11,
       gte_16_32_n_12, gte_16_32_n_13, gte_16_32_n_14, gte_16_32_n_15;
  wire gte_16_32_n_16;
  OAI2BB1X1 gte_16_32_g156(.A0N (gte_16_32_n_6), .A1N (gte_16_32_n_13),
       .B0 (gte_16_32_n_16), .Y (out1));
  NAND4XL gte_16_32_g157(.A (gte_16_32_n_15), .B (gte_16_32_n_6), .C
       (gte_16_32_n_7), .D (gte_16_32_n_8), .Y (gte_16_32_n_16));
  OAI211X1 gte_16_32_g158(.A0 (gte_16_32_n_3), .A1 (in1[3]), .B0
       (gte_16_32_n_14), .C0 (gte_16_32_n_11), .Y (gte_16_32_n_15));
  OAI221X1 gte_16_32_g159(.A0 (gte_16_32_n_9), .A1 (gte_16_32_n_10),
       .B0 (gte_16_32_n_2), .B1 (in2[2]), .C0 (gte_16_32_n_5), .Y
       (gte_16_32_n_14));
  OAI2BB1X1 gte_16_32_g160(.A0N (in2[5]), .A1N (gte_16_32_n_1), .B0
       (gte_16_32_n_12), .Y (gte_16_32_n_13));
  NAND3BXL gte_16_32_g161(.AN (in1[4]), .B (gte_16_32_n_7), .C
       (in2[4]), .Y (gte_16_32_n_12));
  NAND3X1 gte_16_32_g162(.A (gte_16_32_n_5), .B (in2[2]), .C
       (gte_16_32_n_2), .Y (gte_16_32_n_11));
  AOI22X1 gte_16_32_g163(.A0 (in1[0]), .A1 (gte_16_32_n_4), .B0
       (in1[1]), .B1 (gte_16_32_n_0), .Y (gte_16_32_n_10));
  NOR2X1 gte_16_32_g164(.A (gte_16_32_n_0), .B (in1[1]), .Y
       (gte_16_32_n_9));
  NAND2BXL gte_16_32_g165(.AN (in2[4]), .B (in1[4]), .Y
       (gte_16_32_n_8));
  NAND2BXL gte_16_32_g166(.AN (in2[5]), .B (in1[5]), .Y
       (gte_16_32_n_7));
  NOR2X1 gte_16_32_g167(.A (in1[7]), .B (in1[6]), .Y (gte_16_32_n_6));
  NAND2X1 gte_16_32_g168(.A (in1[3]), .B (gte_16_32_n_3), .Y
       (gte_16_32_n_5));
  INVX1 gte_16_32_g169(.A (in2[0]), .Y (gte_16_32_n_4));
  INVX1 gte_16_32_g170(.A (in2[3]), .Y (gte_16_32_n_3));
  INVX1 gte_16_32_g171(.A (in1[2]), .Y (gte_16_32_n_2));
  INVXL gte_16_32_g172(.A (in1[5]), .Y (gte_16_32_n_1));
  INVX1 gte_16_32_g173(.A (in2[1]), .Y (gte_16_32_n_0));
endmodule


