`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:46:02 CST (Jun  9 2025 08:46:02 UTC)

module dut_Add_16Ux12U_16U_1(in2, in1, out1);
  input [15:0] in2;
  input [11:0] in1;
  output [15:0] out1;
  wire [15:0] in2;
  wire [11:0] in1;
  wire [15:0] out1;
  wire UNCONNECTED, add_16_23_n_1, add_16_23_n_2, add_16_23_n_11,
       add_16_23_n_13, add_16_23_n_14, add_16_23_n_15, add_16_23_n_16;
  wire add_16_23_n_17, add_16_23_n_18, add_16_23_n_19, add_16_23_n_20,
       add_16_23_n_21, add_16_23_n_22, add_16_23_n_23, add_16_23_n_24;
  wire add_16_23_n_25, add_16_23_n_26, add_16_23_n_27, add_16_23_n_28,
       add_16_23_n_29, add_16_23_n_30, add_16_23_n_31, add_16_23_n_32;
  wire add_16_23_n_33, add_16_23_n_34, add_16_23_n_35, add_16_23_n_36,
       add_16_23_n_37, add_16_23_n_38, add_16_23_n_39, add_16_23_n_40;
  wire add_16_23_n_41, add_16_23_n_42, add_16_23_n_43, add_16_23_n_44,
       add_16_23_n_45, add_16_23_n_46, add_16_23_n_47, add_16_23_n_48;
  wire add_16_23_n_49, add_16_23_n_50, add_16_23_n_51, add_16_23_n_52,
       add_16_23_n_53, add_16_23_n_54, add_16_23_n_55, add_16_23_n_56;
  wire add_16_23_n_57, add_16_23_n_58, add_16_23_n_59, add_16_23_n_60,
       add_16_23_n_61, add_16_23_n_62, add_16_23_n_63, add_16_23_n_64;
  wire add_16_23_n_65, add_16_23_n_66, add_16_23_n_67, add_16_23_n_68,
       add_16_23_n_69, add_16_23_n_70, add_16_23_n_71, add_16_23_n_72;
  wire add_16_23_n_73, add_16_23_n_74, add_16_23_n_75, add_16_23_n_76,
       add_16_23_n_77, add_16_23_n_78, add_16_23_n_79, add_16_23_n_80;
  wire add_16_23_n_81, add_16_23_n_82, add_16_23_n_83, add_16_23_n_84,
       add_16_23_n_85, add_16_23_n_86, add_16_23_n_87, add_16_23_n_88;
  wire add_16_23_n_89, add_16_23_n_90, add_16_23_n_91, add_16_23_n_92,
       add_16_23_n_93, add_16_23_n_94, add_16_23_n_95, add_16_23_n_96;
  wire add_16_23_n_97, add_16_23_n_98, add_16_23_n_99, add_16_23_n_100,
       add_16_23_n_101, add_16_23_n_102, add_16_23_n_103,
       add_16_23_n_104;
  wire add_16_23_n_105, add_16_23_n_106, add_16_23_n_107,
       add_16_23_n_108, add_16_23_n_109, add_16_23_n_110,
       add_16_23_n_111, add_16_23_n_112;
  wire add_16_23_n_113, add_16_23_n_114, add_16_23_n_115, n_150, n_151,
       n_152, n_154, n_155;
  wire n_156, n_162;
  MXI2X1 add_16_23_g380(.A (in2[13]), .B (add_16_23_n_14), .S0
       (add_16_23_n_111), .Y (out1[13]));
  MXI2X1 add_16_23_g381(.A (in2[15]), .B (add_16_23_n_21), .S0
       (add_16_23_n_109), .Y (out1[15]));
  MXI2X1 add_16_23_g382(.A (in2[12]), .B (add_16_23_n_17), .S0
       (add_16_23_n_113), .Y (out1[12]));
  MXI2X1 add_16_23_g383(.A (add_16_23_n_55), .B (add_16_23_n_56), .S0
       (add_16_23_n_112), .Y (out1[11]));
  MXI2X1 add_16_23_g385(.A (add_16_23_n_57), .B (add_16_23_n_58), .S0
       (add_16_23_n_115), .Y (out1[9]));
  MXI2X1 add_16_23_g386(.A (in2[14]), .B (add_16_23_n_18), .S0
       (add_16_23_n_110), .Y (out1[14]));
  NOR2BX1 add_16_23_g387(.AN (add_16_23_n_40), .B (add_16_23_n_107), .Y
       (add_16_23_n_115));
  NOR2X2 add_16_23_g388(.A (add_16_23_n_75), .B (add_16_23_n_2), .Y
       (add_16_23_n_114));
  NOR2X1 add_16_23_g389(.A (add_16_23_n_87), .B (add_16_23_n_108), .Y
       (add_16_23_n_113));
  NOR2X1 add_16_23_g390(.A (add_16_23_n_89), .B (add_16_23_n_103), .Y
       (add_16_23_n_112));
  NOR2BX1 add_16_23_g391(.AN (add_16_23_n_92), .B (add_16_23_n_104), .Y
       (add_16_23_n_111));
  NOR2X1 add_16_23_g396(.A (add_16_23_n_13), .B (add_16_23_n_106), .Y
       (add_16_23_n_110));
  NOR2BX1 add_16_23_g397(.AN (add_16_23_n_91), .B (add_16_23_n_105), .Y
       (add_16_23_n_109));
  NOR2X1 add_16_23_g398(.A (add_16_23_n_80), .B (add_16_23_n_102), .Y
       (add_16_23_n_108));
  NOR2X1 add_16_23_g400(.A (add_16_23_n_37), .B (add_16_23_n_102), .Y
       (add_16_23_n_107));
  NOR2X1 add_16_23_g401(.A (add_16_23_n_83), .B (add_16_23_n_102), .Y
       (add_16_23_n_106));
  NOR2X1 add_16_23_g402(.A (add_16_23_n_85), .B (add_16_23_n_102), .Y
       (add_16_23_n_105));
  NOR2X1 add_16_23_g403(.A (add_16_23_n_82), .B (add_16_23_n_102), .Y
       (add_16_23_n_104));
  NOR2X1 add_16_23_g404(.A (add_16_23_n_79), .B (add_16_23_n_102), .Y
       (add_16_23_n_103));
  NOR2X4 add_16_23_g405(.A (add_16_23_n_88), .B (add_16_23_n_97), .Y
       (add_16_23_n_102));
  NOR2BX1 add_16_23_g407(.AN (add_16_23_n_36), .B (add_16_23_n_98), .Y
       (add_16_23_n_101));
  NOR2X1 add_16_23_g410(.A (add_16_23_n_90), .B (add_16_23_n_96), .Y
       (add_16_23_n_100));
  NOR2X1 add_16_23_g411(.A (add_16_23_n_61), .B (n_162), .Y
       (add_16_23_n_99));
  NOR2X1 add_16_23_g412(.A (add_16_23_n_35), .B (n_162), .Y
       (add_16_23_n_98));
  NOR2X4 add_16_23_g413(.A (add_16_23_n_78), .B (add_16_23_n_94), .Y
       (add_16_23_n_97));
  NOR2X1 add_16_23_g414(.A (add_16_23_n_81), .B (n_162), .Y
       (add_16_23_n_96));
  NOR2BX1 add_16_23_g415(.AN (add_16_23_n_43), .B (add_16_23_n_1), .Y
       (add_16_23_n_95));
  NOR2X6 add_16_23_g417(.A (add_16_23_n_77), .B (add_16_23_n_93), .Y
       (add_16_23_n_94));
  NOR2X4 add_16_23_g419(.A (add_16_23_n_50), .B (add_16_23_n_86), .Y
       (add_16_23_n_93));
  NAND2X1 add_16_23_g421(.A (in2[12]), .B (add_16_23_n_87), .Y
       (add_16_23_n_92));
  NAND2X1 add_16_23_g422(.A (add_16_23_n_64), .B (add_16_23_n_87), .Y
       (add_16_23_n_91));
  OAI21X1 add_16_23_g423(.A0 (add_16_23_n_24), .A1 (add_16_23_n_72),
       .B0 (add_16_23_n_30), .Y (add_16_23_n_90));
  OAI2BB1X1 add_16_23_g424(.A0N (add_16_23_n_23), .A1N
       (add_16_23_n_75), .B0 (add_16_23_n_44), .Y (add_16_23_n_89));
  OAI21X2 add_16_23_g425(.A0 (add_16_23_n_63), .A1 (add_16_23_n_72),
       .B0 (add_16_23_n_76), .Y (add_16_23_n_88));
  OAI21X2 add_16_23_g427(.A0 (add_16_23_n_66), .A1 (add_16_23_n_74),
       .B0 (add_16_23_n_73), .Y (add_16_23_n_87));
  NOR2X4 add_16_23_g428(.A (add_16_23_n_46), .B (add_16_23_n_84), .Y
       (add_16_23_n_86));
  NAND2BX1 add_16_23_g430(.AN (add_16_23_n_80), .B (add_16_23_n_64), .Y
       (add_16_23_n_85));
  NOR2X4 add_16_23_g431(.A (add_16_23_n_45), .B (add_16_23_n_25), .Y
       (add_16_23_n_84));
  OR2XL add_16_23_g432(.A (add_16_23_n_39), .B (add_16_23_n_80), .Y
       (add_16_23_n_83));
  OR2XL add_16_23_g433(.A (add_16_23_n_17), .B (add_16_23_n_80), .Y
       (add_16_23_n_82));
  OR2XL add_16_23_g435(.A (add_16_23_n_24), .B (add_16_23_n_61), .Y
       (add_16_23_n_81));
  NAND2X1 add_16_23_g436(.A (add_16_23_n_65), .B (add_16_23_n_51), .Y
       (add_16_23_n_80));
  NAND2X1 add_16_23_g437(.A (add_16_23_n_23), .B (add_16_23_n_51), .Y
       (add_16_23_n_79));
  NAND2X1 add_16_23_g438(.A (add_16_23_n_62), .B (add_16_23_n_60), .Y
       (add_16_23_n_78));
  OAI21X2 add_16_23_g439(.A0 (add_16_23_n_43), .A1 (add_16_23_n_42),
       .B0 (add_16_23_n_33), .Y (add_16_23_n_77));
  AOI2BB1X4 add_16_23_g440(.A0N (add_16_23_n_30), .A1N
       (add_16_23_n_28), .B0 (add_16_23_n_47), .Y (add_16_23_n_76));
  INVX1 add_16_23_g441(.A (add_16_23_n_74), .Y (add_16_23_n_75));
  NOR2X1 add_16_23_g442(.A (add_16_23_n_32), .B (add_16_23_n_48), .Y
       (add_16_23_n_74));
  OA21X1 add_16_23_g443(.A0 (add_16_23_n_44), .A1 (add_16_23_n_29), .B0
       (add_16_23_n_34), .Y (add_16_23_n_73));
  NOR2X2 add_16_23_g445(.A (add_16_23_n_31), .B (add_16_23_n_49), .Y
       (add_16_23_n_72));
  INVX1 add_16_23_g451(.A (add_16_23_n_65), .Y (add_16_23_n_66));
  INVX1 add_16_23_g452(.A (add_16_23_n_62), .Y (add_16_23_n_63));
  INVX1 add_16_23_g453(.A (add_16_23_n_60), .Y (add_16_23_n_61));
  NAND2BX1 add_16_23_g454(.AN (add_16_23_n_24), .B (add_16_23_n_30), .Y
       (add_16_23_n_71));
  NAND2X1 add_16_23_g455(.A (add_16_23_n_43), .B (n_154), .Y
       (add_16_23_n_70));
  NAND2BX1 add_16_23_g456(.AN (add_16_23_n_37), .B (add_16_23_n_40), .Y
       (add_16_23_n_69));
  NOR2X1 add_16_23_g457(.A (add_16_23_n_31), .B (add_16_23_n_38), .Y
       (add_16_23_n_68));
  NAND2BX1 add_16_23_g458(.AN (add_16_23_n_35), .B (add_16_23_n_36), .Y
       (add_16_23_n_67));
  NOR2X1 add_16_23_g459(.A (add_16_23_n_46), .B (add_16_23_n_45), .Y
       (add_16_23_n_59));
  NOR2X1 add_16_23_g460(.A (add_16_23_n_29), .B (add_16_23_n_22), .Y
       (add_16_23_n_65));
  NOR2X1 add_16_23_g461(.A (add_16_23_n_18), .B (add_16_23_n_39), .Y
       (add_16_23_n_64));
  NOR2X1 add_16_23_g462(.A (add_16_23_n_28), .B (add_16_23_n_24), .Y
       (add_16_23_n_62));
  NOR2X1 add_16_23_g463(.A (add_16_23_n_38), .B (add_16_23_n_35), .Y
       (add_16_23_n_60));
  INVX1 add_16_23_g464(.A (add_16_23_n_57), .Y (add_16_23_n_58));
  INVX1 add_16_23_g465(.A (add_16_23_n_55), .Y (add_16_23_n_56));
  NAND2X2 add_16_23_g471(.A (add_16_23_n_41), .B (add_16_23_n_27), .Y
       (add_16_23_n_50));
  NOR2X2 add_16_23_g472(.A (add_16_23_n_36), .B (add_16_23_n_38), .Y
       (add_16_23_n_49));
  NOR2X1 add_16_23_g473(.A (add_16_23_n_40), .B (add_16_23_n_26), .Y
       (add_16_23_n_48));
  NOR2X1 add_16_23_g474(.A (add_16_23_n_32), .B (add_16_23_n_26), .Y
       (add_16_23_n_57));
  NOR2BX1 add_16_23_g475(.AN (add_16_23_n_34), .B (add_16_23_n_29), .Y
       (add_16_23_n_55));
  NAND2X1 add_16_23_g476(.A (add_16_23_n_44), .B (add_16_23_n_23), .Y
       (add_16_23_n_54));
  NOR2BX1 add_16_23_g477(.AN (add_16_23_n_33), .B (add_16_23_n_42), .Y
       (add_16_23_n_53));
  NOR2X1 add_16_23_g478(.A (add_16_23_n_47), .B (add_16_23_n_28), .Y
       (add_16_23_n_52));
  NOR2X1 add_16_23_g479(.A (add_16_23_n_26), .B (add_16_23_n_37), .Y
       (add_16_23_n_51));
  CLKINVX2 add_16_23_g480(.A (add_16_23_n_42), .Y (add_16_23_n_41));
  NOR2X2 add_16_23_g482(.A (add_16_23_n_20), .B (add_16_23_n_15), .Y
       (add_16_23_n_46));
  NOR2X8 add_16_23_g483(.A (in2[1]), .B (in1[1]), .Y (add_16_23_n_45));
  NAND2X1 add_16_23_g484(.A (in2[10]), .B (in1[10]), .Y
       (add_16_23_n_44));
  NAND2X2 add_16_23_g485(.A (in2[2]), .B (in1[2]), .Y (add_16_23_n_43));
  NOR2X8 add_16_23_g486(.A (in2[3]), .B (in1[3]), .Y (add_16_23_n_42));
  NAND2X1 add_16_23_g487(.A (in2[8]), .B (in1[8]), .Y (add_16_23_n_40));
  NAND2X1 add_16_23_g488(.A (in2[13]), .B (in2[12]), .Y
       (add_16_23_n_39));
  NOR2X4 add_16_23_g489(.A (in2[5]), .B (in1[5]), .Y (add_16_23_n_38));
  NOR2X1 add_16_23_g490(.A (in2[8]), .B (in1[8]), .Y (add_16_23_n_37));
  NAND2X2 add_16_23_g491(.A (in2[4]), .B (in1[4]), .Y (add_16_23_n_36));
  NOR2X1 add_16_23_g492(.A (in2[4]), .B (in1[4]), .Y (add_16_23_n_35));
  INVX1 add_16_23_g494(.A (add_16_23_n_22), .Y (add_16_23_n_23));
  NAND2X1 add_16_23_g495(.A (in2[11]), .B (in1[11]), .Y
       (add_16_23_n_34));
  NAND2X1 add_16_23_g496(.A (in2[3]), .B (in1[3]), .Y (add_16_23_n_33));
  AND2X1 add_16_23_g497(.A (in2[9]), .B (in1[9]), .Y (add_16_23_n_32));
  AND2X1 add_16_23_g498(.A (in2[5]), .B (in1[5]), .Y (add_16_23_n_31));
  NAND2X2 add_16_23_g499(.A (in2[6]), .B (in1[6]), .Y (add_16_23_n_30));
  NOR2X1 add_16_23_g500(.A (in2[11]), .B (in1[11]), .Y
       (add_16_23_n_29));
  NOR2X4 add_16_23_g501(.A (in2[7]), .B (in1[7]), .Y (add_16_23_n_28));
  NAND2X2 add_16_23_g502(.A (add_16_23_n_19), .B (add_16_23_n_16), .Y
       (add_16_23_n_27));
  NOR2X1 add_16_23_g503(.A (in2[9]), .B (in1[9]), .Y (add_16_23_n_26));
  NAND2X4 add_16_23_g504(.A (in2[0]), .B (in1[0]), .Y (add_16_23_n_25));
  NOR2X4 add_16_23_g505(.A (in2[6]), .B (in1[6]), .Y (add_16_23_n_24));
  NOR2X1 add_16_23_g506(.A (in2[10]), .B (in1[10]), .Y
       (add_16_23_n_22));
  INVX1 add_16_23_g507(.A (in2[15]), .Y (add_16_23_n_21));
  CLKINVX2 add_16_23_g508(.A (in2[1]), .Y (add_16_23_n_20));
  CLKINVX3 add_16_23_g509(.A (in2[2]), .Y (add_16_23_n_19));
  INVX1 add_16_23_g510(.A (in2[14]), .Y (add_16_23_n_18));
  INVX1 add_16_23_g511(.A (in2[12]), .Y (add_16_23_n_17));
  CLKINVX2 add_16_23_g512(.A (in1[2]), .Y (add_16_23_n_16));
  CLKINVX2 add_16_23_g513(.A (in1[1]), .Y (add_16_23_n_15));
  INVX1 add_16_23_g514(.A (in2[13]), .Y (add_16_23_n_14));
  NOR2BX1 add_16_23_g2(.AN (add_16_23_n_87), .B (add_16_23_n_39), .Y
       (add_16_23_n_13));
  XNOR2X1 add_16_23_g516(.A (add_16_23_n_25), .B (add_16_23_n_59), .Y
       (out1[1]));
  NOR2BX1 add_16_23_g517(.AN (add_16_23_n_72), .B (add_16_23_n_99), .Y
       (add_16_23_n_11));
  CLKXOR2X1 add_16_23_g518(.A (add_16_23_n_71), .B (add_16_23_n_11), .Y
       (out1[6]));
  CLKXOR2X1 add_16_23_g519(.A (add_16_23_n_70), .B (n_150), .Y
       (out1[2]));
  CLKXOR2X1 add_16_23_g520(.A (add_16_23_n_69), .B (add_16_23_n_102),
       .Y (out1[8]));
  XNOR2XL add_16_23_g521(.A (add_16_23_n_68), .B (add_16_23_n_101), .Y
       (out1[5]));
  CLKXOR2X1 add_16_23_g522(.A (add_16_23_n_67), .B (n_162), .Y
       (out1[4]));
  CLKXOR2X1 add_16_23_g523(.A (add_16_23_n_54), .B (add_16_23_n_114),
       .Y (out1[10]));
  XNOR2X1 add_16_23_g524(.A (add_16_23_n_53), .B (add_16_23_n_95), .Y
       (out1[3]));
  XNOR2XL add_16_23_g525(.A (add_16_23_n_52), .B (add_16_23_n_100), .Y
       (out1[7]));
  NOR2BX2 add_16_23_g526(.AN (add_16_23_n_51), .B (add_16_23_n_102), .Y
       (add_16_23_n_2));
  NOR2BX1 add_16_23_g527(.AN (n_155), .B (n_151), .Y (add_16_23_n_1));
  CLKXOR2X1 add_16_23_g528(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  INVXL fopt(.A (n_152), .Y (n_150));
  INVXL fopt1(.A (n_152), .Y (n_151));
  INVXL fopt2(.A (add_16_23_n_86), .Y (n_152));
  INVXL fopt529(.A (n_156), .Y (n_154));
  INVXL fopt530(.A (n_156), .Y (n_155));
  INVXL fopt531(.A (add_16_23_n_27), .Y (n_156));
  ADDHX4 add_16_23_g535(.A (in2[7]), .B (in1[7]), .CO (add_16_23_n_47),
       .S (UNCONNECTED));
  BUFX3 fopt536(.A (add_16_23_n_94), .Y (n_162));
endmodule


