`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  4 2025 00:51:21 CST (Jun  3 2025 16:51:21 UTC)

module dut_Equal_7Ux2U_1U_1(in2, in1, out1);
  input [6:0] in2;
  input [1:0] in1;
  output out1;
  wire [6:0] in2;
  wire [1:0] in1;
  wire out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13;
  NOR2X1 g50(.A (n_11), .B (n_13), .Y (out1));
  NAND2X1 g51(.A (n_12), .B (n_10), .Y (n_13));
  NAND2X1 g55(.A (n_6), .B (n_8), .Y (n_12));
  NAND2X1 g52(.A (n_4), .B (n_9), .Y (n_11));
  NAND2X1 g54(.A (n_5), .B (n_7), .Y (n_10));
  NOR3X2 g53(.A (in2[6]), .B (in2[3]), .C (in2[2]), .Y (n_9));
  NAND2X2 g56(.A (n_1), .B (n_0), .Y (n_8));
  NAND2X2 g58(.A (n_3), .B (n_2), .Y (n_7));
  NAND2X2 g60(.A (in2[1]), .B (in1[1]), .Y (n_6));
  NAND2X1 g57(.A (in2[0]), .B (in1[0]), .Y (n_5));
  NOR2X1 g59(.A (in2[5]), .B (in2[4]), .Y (n_4));
  CLKINVX3 g61(.A (in2[0]), .Y (n_3));
  INVX2 g62(.A (in1[0]), .Y (n_2));
  CLKINVX4 g63(.A (in2[1]), .Y (n_1));
  INVX2 g64(.A (in1[1]), .Y (n_0));
endmodule


