`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:46:27 CST (Jun  9 2025 08:46:27 UTC)

module dut_LessThan_1U_7_1(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire lt_15_26_n_0, lt_15_26_n_1, lt_15_26_n_2, n_13;
  NOR2X1 lt_15_26_g108(.A (n_13), .B (lt_15_26_n_2), .Y (out1));
  NOR2X1 lt_15_26_g110(.A (lt_15_26_n_1), .B (lt_15_26_n_0), .Y
       (lt_15_26_n_2));
  OR2XL lt_15_26_g2(.A (in1[7]), .B (in1[4]), .Y (lt_15_26_n_1));
  OR2XL lt_15_26_g117(.A (in1[3]), .B (in1[2]), .Y (lt_15_26_n_0));
  AOI21X1 g2(.A0 (in1[5]), .A1 (in1[6]), .B0 (in1[7]), .Y (n_13));
endmodule


