`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:47:21 CST (Jun  9 2025 08:47:21 UTC)

module dut_LessThan_1U_186_1(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire lt_15_26_n_0, lt_15_26_n_1, lt_15_26_n_2;
  OAI21X4 lt_15_26_g112(.A0 (in1[2]), .A1 (in1[1]), .B0 (in1[3]), .Y
       (lt_15_26_n_2));
  NAND2X2 lt_15_26_g113(.A (in1[5]), .B (in1[4]), .Y (lt_15_26_n_1));
  NOR2X2 lt_15_26_g114(.A (in1[7]), .B (in1[6]), .Y (lt_15_26_n_0));
  OAI21X2 g2(.A0 (lt_15_26_n_1), .A1 (lt_15_26_n_2), .B0
       (lt_15_26_n_0), .Y (out1));
endmodule


