`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:44:34 CST (Jun  9 2025 08:44:34 UTC)

module dut_GreaterThanEQ_1U_18_4(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire gte_15_26_n_0, gte_15_26_n_1;
  OAI221X1 gte_15_26_g100(.A0 (in1[7]), .A1 (in1[5]), .B0 (in1[7]), .B1
       (in1[6]), .C0 (gte_15_26_n_1), .Y (out1));
  OR4X1 gte_15_26_g101(.A (in1[7]), .B (in1[4]), .C (in1[1]), .D
       (gte_15_26_n_0), .Y (gte_15_26_n_1));
  OR2XL gte_15_26_g102(.A (in1[3]), .B (in1[2]), .Y (gte_15_26_n_0));
endmodule


