`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:45:40 CST (Jun  9 2025 08:45:40 UTC)

module dut_LessThan_1U_220_4(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire lt_15_26_n_0, lt_15_26_n_1, lt_15_26_n_2;
  AOI22X1 lt_15_26_g112(.A0 (lt_15_26_n_0), .A1 (lt_15_26_n_2), .B0
       (lt_15_26_n_1), .B1 (lt_15_26_n_0), .Y (out1));
  NOR4X1 lt_15_26_g113(.A (in1[3]), .B (in1[2]), .C (in1[1]), .D
       (in1[0]), .Y (lt_15_26_n_2));
  NAND2X1 lt_15_26_g114(.A (in1[5]), .B (in1[4]), .Y (lt_15_26_n_1));
  NOR2X1 lt_15_26_g115(.A (in1[7]), .B (in1[6]), .Y (lt_15_26_n_0));
endmodule


