`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:46:22 CST (Jun  9 2025 08:46:22 UTC)

module dut_GreaterThanEQ_4Ux8U_1U_1(in2, in1, out1);
  input [3:0] in2;
  input [7:0] in1;
  output out1;
  wire [3:0] in2;
  wire [7:0] in1;
  wire out1;
  wire gte_16_34_n_0, gte_16_34_n_1, gte_16_34_n_2, gte_16_34_n_3,
       gte_16_34_n_4, gte_16_34_n_5, gte_16_34_n_6, gte_16_34_n_7;
  wire gte_16_34_n_8, gte_16_34_n_9, gte_16_34_n_10, gte_16_34_n_11,
       gte_16_34_n_12, gte_16_34_n_13, gte_16_34_n_14, gte_16_34_n_15;
  AOI21X1 gte_16_34_g121(.A0 (gte_16_34_n_14), .A1 (gte_16_34_n_15),
       .B0 (gte_16_34_n_11), .Y (out1));
  OAI21X1 gte_16_34_g122(.A0 (gte_16_34_n_2), .A1 (gte_16_34_n_12), .B0
       (gte_16_34_n_13), .Y (gte_16_34_n_15));
  AOI21X2 gte_16_34_g123(.A0 (gte_16_34_n_1), .A1 (gte_16_34_n_7), .B0
       (gte_16_34_n_10), .Y (gte_16_34_n_14));
  NOR2X1 gte_16_34_g124(.A (gte_16_34_n_6), .B (gte_16_34_n_3), .Y
       (gte_16_34_n_13));
  NOR2X1 gte_16_34_g125(.A (gte_16_34_n_0), .B (gte_16_34_n_4), .Y
       (gte_16_34_n_12));
  NAND2X1 gte_16_34_g126(.A (gte_16_34_n_8), .B (gte_16_34_n_9), .Y
       (gte_16_34_n_11));
  NOR2BX1 gte_16_34_g131(.AN (in2[3]), .B (in1[3]), .Y
       (gte_16_34_n_10));
  NOR2X1 gte_16_34_g132(.A (in1[5]), .B (in1[4]), .Y (gte_16_34_n_9));
  NOR2X1 gte_16_34_g133(.A (in1[7]), .B (in1[6]), .Y (gte_16_34_n_8));
  INVX1 gte_16_34_g135(.A (gte_16_34_n_6), .Y (gte_16_34_n_7));
  NOR2X1 gte_16_34_g136(.A (in2[3]), .B (gte_16_34_n_5), .Y
       (gte_16_34_n_6));
  INVX1 gte_16_34_g139(.A (in1[3]), .Y (gte_16_34_n_5));
  NOR2BX1 gte_16_34_g2(.AN (in1[0]), .B (in2[0]), .Y (gte_16_34_n_4));
  NOR2BX1 gte_16_34_g143(.AN (in1[2]), .B (in2[2]), .Y (gte_16_34_n_3));
  NOR2BX1 gte_16_34_g144(.AN (in2[1]), .B (in1[1]), .Y (gte_16_34_n_2));
  NOR2BX1 gte_16_34_g145(.AN (in2[2]), .B (in1[2]), .Y (gte_16_34_n_1));
  NOR2BX1 gte_16_34_g146(.AN (in1[1]), .B (in2[1]), .Y (gte_16_34_n_0));
endmodule


