`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:46:47 CST (Jun  9 2025 08:46:47 UTC)

module dut_GreaterThanEQ_1U_61_1(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire gte_15_26_n_0, gte_15_26_n_1, gte_15_26_n_2, gte_15_26_n_3;
  OAI22X1 gte_15_26_g120(.A0 (gte_15_26_n_3), .A1 (gte_15_26_n_2), .B0
       (in1[7]), .B1 (in1[6]), .Y (out1));
  NAND2BX1 gte_15_26_g121(.AN (in1[7]), .B (gte_15_26_n_0), .Y
       (gte_15_26_n_3));
  AOI2BB1X1 gte_15_26_g122(.A0N (in1[3]), .A1N (in1[1]), .B0
       (gte_15_26_n_1), .Y (gte_15_26_n_2));
  NOR2X6 gte_15_26_g123(.A (in1[3]), .B (in1[2]), .Y (gte_15_26_n_1));
  NOR2X6 gte_15_26_g124(.A (in1[5]), .B (in1[4]), .Y (gte_15_26_n_0));
endmodule


