`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:44:08 CST (Jun  9 2025 08:44:08 UTC)

module dut_Add_32Sx13U_32S_4(in2, in1, out1);
  input [31:0] in2;
  input [12:0] in1;
  output [31:0] out1;
  wire [31:0] in2;
  wire [12:0] in1;
  wire [31:0] out1;
  wire add_16_23_n_0, add_16_23_n_1, add_16_23_n_2, add_16_23_n_3,
       add_16_23_n_4, add_16_23_n_5, add_16_23_n_6, add_16_23_n_7;
  wire add_16_23_n_8, add_16_23_n_9, add_16_23_n_10, add_16_23_n_11,
       add_16_23_n_12, add_16_23_n_13, add_16_23_n_14, add_16_23_n_15;
  wire add_16_23_n_16, add_16_23_n_17, add_16_23_n_18, add_16_23_n_19,
       add_16_23_n_20, add_16_23_n_21, add_16_23_n_22, add_16_23_n_23;
  wire add_16_23_n_24, add_16_23_n_25, add_16_23_n_26, add_16_23_n_27,
       add_16_23_n_28, add_16_23_n_29, add_16_23_n_30, add_16_23_n_31;
  wire add_16_23_n_32, add_16_23_n_33, add_16_23_n_34, add_16_23_n_35,
       add_16_23_n_36, add_16_23_n_37, add_16_23_n_38, add_16_23_n_39;
  wire add_16_23_n_40, add_16_23_n_41, add_16_23_n_42, add_16_23_n_43,
       add_16_23_n_44, add_16_23_n_45, add_16_23_n_46, add_16_23_n_47;
  wire add_16_23_n_48, add_16_23_n_49, add_16_23_n_50, add_16_23_n_52,
       add_16_23_n_53, add_16_23_n_55, add_16_23_n_56, add_16_23_n_58;
  wire add_16_23_n_59, add_16_23_n_61, add_16_23_n_63, add_16_23_n_64,
       add_16_23_n_65, add_16_23_n_68, add_16_23_n_69, add_16_23_n_71;
  wire add_16_23_n_72, add_16_23_n_73, add_16_23_n_75, add_16_23_n_76,
       add_16_23_n_79, add_16_23_n_81, add_16_23_n_82, add_16_23_n_83;
  wire add_16_23_n_84, add_16_23_n_85, add_16_23_n_88, add_16_23_n_89,
       add_16_23_n_90, add_16_23_n_91, add_16_23_n_92, add_16_23_n_93;
  wire add_16_23_n_94, add_16_23_n_100, add_16_23_n_101,
       add_16_23_n_102, add_16_23_n_103, add_16_23_n_107;
  XNOR2X1 add_16_23_g662(.A (in2[31]), .B (add_16_23_n_107), .Y
       (out1[31]));
  XNOR2X1 add_16_23_g663(.A (in2[23]), .B (add_16_23_n_102), .Y
       (out1[23]));
  XNOR2X1 add_16_23_g664(.A (in2[27]), .B (add_16_23_n_101), .Y
       (out1[27]));
  XNOR2X1 add_16_23_g665(.A (in2[29]), .B (add_16_23_n_103), .Y
       (out1[29]));
  XNOR2X1 add_16_23_g666(.A (in2[15]), .B (add_16_23_n_92), .Y
       (out1[15]));
  XNOR2X1 add_16_23_g667(.A (in2[25]), .B (add_16_23_n_91), .Y
       (out1[25]));
  XNOR2X1 add_16_23_g668(.A (in2[19]), .B (add_16_23_n_89), .Y
       (out1[19]));
  XNOR2X1 add_16_23_g669(.A (in2[21]), .B (add_16_23_n_90), .Y
       (out1[21]));
  XNOR2X1 add_16_23_g670(.A (in2[30]), .B (add_16_23_n_100), .Y
       (out1[30]));
  XNOR2X1 add_16_23_g671(.A (in2[17]), .B (add_16_23_n_0), .Y
       (out1[17]));
  NAND2BX1 add_16_23_g672(.AN (add_16_23_n_100), .B (in2[30]), .Y
       (add_16_23_n_107));
  XNOR2X1 add_16_23_g673(.A (in2[28]), .B (add_16_23_n_88), .Y
       (out1[28]));
  XNOR2X1 add_16_23_g674(.A (in2[22]), .B (add_16_23_n_93), .Y
       (out1[22]));
  XNOR2X1 add_16_23_g675(.A (in2[26]), .B (add_16_23_n_94), .Y
       (out1[26]));
  NAND2BX1 add_16_23_g676(.AN (add_16_23_n_88), .B (in2[28]), .Y
       (add_16_23_n_103));
  NAND2BX1 add_16_23_g677(.AN (add_16_23_n_93), .B (in2[22]), .Y
       (add_16_23_n_102));
  NAND2BX1 add_16_23_g678(.AN (add_16_23_n_94), .B (in2[26]), .Y
       (add_16_23_n_101));
  NAND3BXL add_16_23_g679(.AN (add_16_23_n_88), .B (in2[29]), .C
       (in2[28]), .Y (add_16_23_n_100));
  XNOR2X1 add_16_23_g680(.A (in2[14]), .B (add_16_23_n_81), .Y
       (out1[14]));
  XOR2XL add_16_23_g681(.A (in2[24]), .B (add_16_23_n_82), .Y
       (out1[24]));
  XOR2XL add_16_23_g682(.A (in2[13]), .B (add_16_23_n_83), .Y
       (out1[13]));
  XOR2XL add_16_23_g683(.A (in2[20]), .B (add_16_23_n_85), .Y
       (out1[20]));
  XOR2XL add_16_23_g684(.A (in2[18]), .B (add_16_23_n_84), .Y
       (out1[18]));
  NAND2BX1 add_16_23_g685(.AN (add_16_23_n_14), .B (add_16_23_n_82), .Y
       (add_16_23_n_94));
  NAND2BX1 add_16_23_g686(.AN (add_16_23_n_12), .B (add_16_23_n_85), .Y
       (add_16_23_n_93));
  NAND2BX1 add_16_23_g687(.AN (add_16_23_n_81), .B (in2[14]), .Y
       (add_16_23_n_92));
  NAND2X1 add_16_23_g688(.A (in2[24]), .B (add_16_23_n_82), .Y
       (add_16_23_n_91));
  NAND2X1 add_16_23_g689(.A (in2[20]), .B (add_16_23_n_85), .Y
       (add_16_23_n_90));
  NAND2X1 add_16_23_g690(.A (in2[18]), .B (add_16_23_n_84), .Y
       (add_16_23_n_89));
  NAND4BX1 add_16_23_g691(.AN (add_16_23_n_14), .B (add_16_23_n_82), .C
       (in2[27]), .D (in2[26]), .Y (add_16_23_n_88));
  XNOR2X1 add_16_23_g692(.A (in2[16]), .B (add_16_23_n_76), .Y
       (out1[16]));
  XNOR2X1 add_16_23_g693(.A (add_16_23_n_32), .B (add_16_23_n_79), .Y
       (out1[11]));
  NOR2X1 add_16_23_g694(.A (add_16_23_n_34), .B (add_16_23_n_76), .Y
       (add_16_23_n_85));
  NOR2X1 add_16_23_g695(.A (add_16_23_n_10), .B (add_16_23_n_76), .Y
       (add_16_23_n_84));
  OAI21X1 add_16_23_g697(.A0 (add_16_23_n_19), .A1 (add_16_23_n_75),
       .B0 (add_16_23_n_17), .Y (add_16_23_n_83));
  NOR4X1 add_16_23_g698(.A (add_16_23_n_76), .B (add_16_23_n_34), .C
       (add_16_23_n_16), .D (add_16_23_n_12), .Y (add_16_23_n_82));
  AOI2BB1XL add_16_23_g699(.A0N (add_16_23_n_36), .A1N
       (add_16_23_n_75), .B0 (add_16_23_n_43), .Y (add_16_23_n_81));
  XNOR2X1 add_16_23_g700(.A (add_16_23_n_41), .B (add_16_23_n_75), .Y
       (out1[12]));
  OAI21X1 add_16_23_g701(.A0 (add_16_23_n_22), .A1 (add_16_23_n_72),
       .B0 (add_16_23_n_18), .Y (add_16_23_n_79));
  XNOR2X1 add_16_23_g702(.A (add_16_23_n_39), .B (add_16_23_n_72), .Y
       (out1[10]));
  XNOR2X1 add_16_23_g703(.A (add_16_23_n_37), .B (add_16_23_n_71), .Y
       (out1[9]));
  AOI221X1 add_16_23_g705(.A0 (add_16_23_n_48), .A1 (add_16_23_n_53),
       .B0 (add_16_23_n_48), .B1 (add_16_23_n_73), .C0
       (add_16_23_n_49), .Y (add_16_23_n_76));
  NOR2X1 add_16_23_g706(.A (add_16_23_n_53), .B (add_16_23_n_73), .Y
       (add_16_23_n_75));
  XNOR2X1 add_16_23_g707(.A (add_16_23_n_33), .B (add_16_23_n_68), .Y
       (out1[7]));
  AND2XL add_16_23_g708(.A (add_16_23_n_44), .B (add_16_23_n_69), .Y
       (add_16_23_n_73));
  NOR2X1 add_16_23_g709(.A (add_16_23_n_46), .B (add_16_23_n_69), .Y
       (add_16_23_n_72));
  OAI21X1 add_16_23_g710(.A0 (add_16_23_n_9), .A1 (add_16_23_n_65), .B0
       (add_16_23_n_21), .Y (add_16_23_n_71));
  XNOR2X1 add_16_23_g711(.A (add_16_23_n_31), .B (add_16_23_n_65), .Y
       (out1[8]));
  NOR3X1 add_16_23_g712(.A (add_16_23_n_65), .B (add_16_23_n_23), .C
       (add_16_23_n_9), .Y (add_16_23_n_69));
  OAI21X1 add_16_23_g713(.A0 (add_16_23_n_1), .A1 (add_16_23_n_64), .B0
       (add_16_23_n_5), .Y (add_16_23_n_68));
  XNOR2X1 add_16_23_g714(.A (add_16_23_n_42), .B (add_16_23_n_64), .Y
       (out1[6]));
  XNOR2X1 add_16_23_g715(.A (add_16_23_n_38), .B (add_16_23_n_63), .Y
       (out1[5]));
  AOI221X1 add_16_23_g716(.A0 (add_16_23_n_35), .A1 (add_16_23_n_45),
       .B0 (add_16_23_n_35), .B1 (add_16_23_n_61), .C0
       (add_16_23_n_47), .Y (add_16_23_n_65));
  NOR2X1 add_16_23_g717(.A (add_16_23_n_45), .B (add_16_23_n_61), .Y
       (add_16_23_n_64));
  OAI2BB1X1 add_16_23_g718(.A0N (add_16_23_n_8), .A1N (add_16_23_n_59),
       .B0 (add_16_23_n_3), .Y (add_16_23_n_63));
  XNOR2X1 add_16_23_g719(.A (add_16_23_n_30), .B (add_16_23_n_59), .Y
       (out1[4]));
  NOR3BX1 add_16_23_g720(.AN (add_16_23_n_59), .B (add_16_23_n_2), .C
       (add_16_23_n_7), .Y (add_16_23_n_61));
  XNOR2X1 add_16_23_g721(.A (add_16_23_n_29), .B (add_16_23_n_58), .Y
       (out1[3]));
  OAI221X1 add_16_23_g722(.A0 (add_16_23_n_24), .A1 (add_16_23_n_56),
       .B0 (add_16_23_n_6), .B1 (add_16_23_n_24), .C0 (add_16_23_n_28),
       .Y (add_16_23_n_59));
  NAND2X1 add_16_23_g723(.A (add_16_23_n_6), .B (add_16_23_n_56), .Y
       (add_16_23_n_58));
  XNOR2X1 add_16_23_g724(.A (add_16_23_n_40), .B (add_16_23_n_55), .Y
       (out1[2]));
  NAND2BX1 add_16_23_g725(.AN (add_16_23_n_15), .B (add_16_23_n_55), .Y
       (add_16_23_n_56));
  ADDFX1 add_16_23_g726(.A (add_16_23_n_50), .B (in1[1]), .CI (in2[1]),
       .CO (add_16_23_n_55), .S (out1[1]));
  OAI211X1 add_16_23_g727(.A0 (add_16_23_n_18), .A1 (add_16_23_n_4),
       .B0 (add_16_23_n_52), .C0 (add_16_23_n_25), .Y (add_16_23_n_53));
  NAND2X1 add_16_23_g728(.A (add_16_23_n_44), .B (add_16_23_n_46), .Y
       (add_16_23_n_52));
  ADDHX1 add_16_23_g729(.A (in2[0]), .B (in1[0]), .CO (add_16_23_n_50),
       .S (out1[0]));
  NOR2BX1 add_16_23_g730(.AN (add_16_23_n_43), .B (add_16_23_n_27), .Y
       (add_16_23_n_49));
  NOR2X1 add_16_23_g731(.A (add_16_23_n_27), .B (add_16_23_n_36), .Y
       (add_16_23_n_48));
  OAI21X1 add_16_23_g732(.A0 (add_16_23_n_5), .A1 (add_16_23_n_20), .B0
       (add_16_23_n_26), .Y (add_16_23_n_47));
  OAI21X1 add_16_23_g733(.A0 (add_16_23_n_21), .A1 (add_16_23_n_23),
       .B0 (add_16_23_n_13), .Y (add_16_23_n_46));
  OAI21X1 add_16_23_g734(.A0 (add_16_23_n_3), .A1 (add_16_23_n_2), .B0
       (add_16_23_n_11), .Y (add_16_23_n_45));
  NOR2BX1 add_16_23_g735(.AN (add_16_23_n_5), .B (add_16_23_n_1), .Y
       (add_16_23_n_42));
  NOR2BX1 add_16_23_g736(.AN (add_16_23_n_17), .B (add_16_23_n_19), .Y
       (add_16_23_n_41));
  NAND2BX1 add_16_23_g737(.AN (add_16_23_n_15), .B (add_16_23_n_6), .Y
       (add_16_23_n_40));
  NOR2BX1 add_16_23_g738(.AN (add_16_23_n_18), .B (add_16_23_n_22), .Y
       (add_16_23_n_39));
  NAND2BX1 add_16_23_g739(.AN (add_16_23_n_2), .B (add_16_23_n_11), .Y
       (add_16_23_n_38));
  NAND2BX1 add_16_23_g740(.AN (add_16_23_n_23), .B (add_16_23_n_13), .Y
       (add_16_23_n_37));
  NOR2X1 add_16_23_g741(.A (add_16_23_n_4), .B (add_16_23_n_22), .Y
       (add_16_23_n_44));
  NOR2BX1 add_16_23_g742(.AN (in2[13]), .B (add_16_23_n_17), .Y
       (add_16_23_n_43));
  NAND2BX1 add_16_23_g743(.AN (add_16_23_n_20), .B (add_16_23_n_26), .Y
       (add_16_23_n_33));
  NAND2BX1 add_16_23_g744(.AN (add_16_23_n_19), .B (in2[13]), .Y
       (add_16_23_n_36));
  NAND2BX1 add_16_23_g745(.AN (add_16_23_n_4), .B (add_16_23_n_25), .Y
       (add_16_23_n_32));
  NOR2BX1 add_16_23_g746(.AN (add_16_23_n_21), .B (add_16_23_n_9), .Y
       (add_16_23_n_31));
  NOR2X1 add_16_23_g747(.A (add_16_23_n_20), .B (add_16_23_n_1), .Y
       (add_16_23_n_35));
  NAND2X1 add_16_23_g748(.A (add_16_23_n_3), .B (add_16_23_n_8), .Y
       (add_16_23_n_30));
  NAND2BX1 add_16_23_g749(.AN (add_16_23_n_24), .B (add_16_23_n_28), .Y
       (add_16_23_n_29));
  NAND3BXL add_16_23_g750(.AN (add_16_23_n_10), .B (in2[19]), .C
       (in2[18]), .Y (add_16_23_n_34));
  NAND2X1 add_16_23_g751(.A (in2[23]), .B (in2[22]), .Y
       (add_16_23_n_16));
  NAND2X1 add_16_23_g752(.A (in2[3]), .B (in1[3]), .Y (add_16_23_n_28));
  NAND2X1 add_16_23_g753(.A (in2[15]), .B (in2[14]), .Y
       (add_16_23_n_27));
  NAND2X1 add_16_23_g754(.A (in2[7]), .B (in1[7]), .Y (add_16_23_n_26));
  NAND2X1 add_16_23_g755(.A (in2[11]), .B (in1[11]), .Y
       (add_16_23_n_25));
  NOR2X1 add_16_23_g756(.A (in2[3]), .B (in1[3]), .Y (add_16_23_n_24));
  NOR2X1 add_16_23_g757(.A (in2[9]), .B (in1[9]), .Y (add_16_23_n_23));
  NOR2X1 add_16_23_g758(.A (in2[10]), .B (in1[10]), .Y
       (add_16_23_n_22));
  NAND2X1 add_16_23_g759(.A (in2[8]), .B (in1[8]), .Y (add_16_23_n_21));
  NOR2X1 add_16_23_g760(.A (in2[7]), .B (in1[7]), .Y (add_16_23_n_20));
  NOR2X1 add_16_23_g761(.A (in2[12]), .B (in1[12]), .Y
       (add_16_23_n_19));
  NAND2X1 add_16_23_g762(.A (in2[10]), .B (in1[10]), .Y
       (add_16_23_n_18));
  NAND2X1 add_16_23_g763(.A (in2[12]), .B (in1[12]), .Y
       (add_16_23_n_17));
  INVX1 add_16_23_g764(.A (add_16_23_n_7), .Y (add_16_23_n_8));
  NOR2X1 add_16_23_g765(.A (in2[2]), .B (in1[2]), .Y (add_16_23_n_15));
  NAND2X1 add_16_23_g766(.A (in2[25]), .B (in2[24]), .Y
       (add_16_23_n_14));
  NAND2X1 add_16_23_g767(.A (in2[9]), .B (in1[9]), .Y (add_16_23_n_13));
  NAND2X1 add_16_23_g768(.A (in2[21]), .B (in2[20]), .Y
       (add_16_23_n_12));
  NAND2X1 add_16_23_g769(.A (in2[5]), .B (in1[5]), .Y (add_16_23_n_11));
  NAND2X1 add_16_23_g770(.A (in2[17]), .B (in2[16]), .Y
       (add_16_23_n_10));
  NOR2X1 add_16_23_g771(.A (in2[8]), .B (in1[8]), .Y (add_16_23_n_9));
  NOR2X1 add_16_23_g772(.A (in2[4]), .B (in1[4]), .Y (add_16_23_n_7));
  NAND2X1 add_16_23_g773(.A (in2[2]), .B (in1[2]), .Y (add_16_23_n_6));
  NAND2X1 add_16_23_g774(.A (in2[6]), .B (in1[6]), .Y (add_16_23_n_5));
  NOR2X1 add_16_23_g775(.A (in2[11]), .B (in1[11]), .Y (add_16_23_n_4));
  NAND2X1 add_16_23_g776(.A (in2[4]), .B (in1[4]), .Y (add_16_23_n_3));
  NOR2X1 add_16_23_g777(.A (in2[5]), .B (in1[5]), .Y (add_16_23_n_2));
  NOR2X1 add_16_23_g778(.A (in2[6]), .B (in1[6]), .Y (add_16_23_n_1));
  NAND2BX1 add_16_23_g2(.AN (add_16_23_n_76), .B (in2[16]), .Y
       (add_16_23_n_0));
endmodule


