`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:44:51 CST (Jun  9 2025 08:44:51 UTC)

module dut_GreaterThanEQ_1U_62_4(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire gte_15_26_n_0, gte_15_26_n_1, gte_15_26_n_2;
  OAI32X1 gte_15_26_g116(.A0 (gte_15_26_n_2), .A1 (in1[7]), .A2
       (gte_15_26_n_0), .B0 (in1[7]), .B1 (in1[6]), .Y (out1));
  INVX1 gte_15_26_g117(.A (gte_15_26_n_1), .Y (gte_15_26_n_2));
  OAI211X1 gte_15_26_g118(.A0 (in1[1]), .A1 (in1[0]), .B0 (in1[3]), .C0
       (in1[2]), .Y (gte_15_26_n_1));
  OR2XL gte_15_26_g119(.A (in1[5]), .B (in1[4]), .Y (gte_15_26_n_0));
endmodule


