`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:45:18 CST (Jun  9 2025 08:45:18 UTC)

module dut_GreaterThanEQ_1U_148_4(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire gte_15_26_n_0;
  AOI21X1 gte_15_26_g107(.A0 (in1[3]), .A1 (in1[2]), .B0
       (gte_15_26_n_0), .Y (out1));
  OR4X1 gte_15_26_g108(.A (in1[7]), .B (in1[6]), .C (in1[5]), .D
       (in1[4]), .Y (gte_15_26_n_0));
endmodule


