`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:47:04 CST (Jun  9 2025 08:47:04 UTC)

module dut_LessThan_1U_114_1(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire lt_15_26_n_0, lt_15_26_n_1, lt_15_26_n_2;
  NAND3X2 lt_15_26_g105(.A (lt_15_26_n_1), .B (lt_15_26_n_0), .C
       (lt_15_26_n_2), .Y (out1));
  NOR2X2 lt_15_26_g106(.A (in1[5]), .B (in1[4]), .Y (lt_15_26_n_2));
  NAND2X2 lt_15_26_g107(.A (in1[3]), .B (in1[2]), .Y (lt_15_26_n_1));
  NOR2X6 lt_15_26_g108(.A (in1[7]), .B (in1[6]), .Y (lt_15_26_n_0));
endmodule


