`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:45:29 CST (Jun  9 2025 08:45:29 UTC)

module dut_GreaterThanEQ_1U_190_4(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire gte_15_26_n_0, gte_15_26_n_1, gte_15_26_n_2;
  OAI32X1 gte_15_26_g105(.A0 (gte_15_26_n_2), .A1 (in1[4]), .A2
       (gte_15_26_n_0), .B0 (in1[5]), .B1 (gte_15_26_n_0), .Y (out1));
  NOR2BX1 gte_15_26_g106(.AN (in1[3]), .B (gte_15_26_n_1), .Y
       (gte_15_26_n_2));
  NOR3X1 gte_15_26_g107(.A (in1[2]), .B (in1[1]), .C (in1[0]), .Y
       (gte_15_26_n_1));
  OR2XL gte_15_26_g108(.A (in1[7]), .B (in1[6]), .Y (gte_15_26_n_0));
endmodule


