`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  4 2025 00:51:22 CST (Jun  3 2025 16:51:22 UTC)

module dut_Equal_7Ux4U_1U_1(in2, in1, out1);
  input [6:0] in2;
  input [3:0] in1;
  output out1;
  wire [6:0] in2;
  wire [3:0] in1;
  wire out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21;
  NOR4X2 g74(.A (n_17), .B (n_19), .C (n_18), .D (n_21), .Y (out1));
  NAND2X2 g75(.A (n_16), .B (n_20), .Y (n_21));
  NAND2X1 g79(.A (n_8), .B (n_13), .Y (n_20));
  NOR2X1 g77(.A (n_9), .B (n_15), .Y (n_19));
  NOR2X1 g80(.A (n_11), .B (n_14), .Y (n_18));
  NOR2X1 g78(.A (n_10), .B (n_12), .Y (n_17));
  NOR3X4 g76(.A (in2[4]), .B (in2[6]), .C (in2[5]), .Y (n_16));
  NOR2X2 g87(.A (n_7), .B (n_4), .Y (n_15));
  NOR2X1 g88(.A (n_6), .B (n_0), .Y (n_14));
  NAND2X2 g81(.A (n_2), .B (n_3), .Y (n_13));
  NOR2X4 g82(.A (n_1), .B (n_5), .Y (n_12));
  NOR2X1 g84(.A (in2[0]), .B (in1[0]), .Y (n_11));
  NOR2X2 g85(.A (in2[2]), .B (in1[2]), .Y (n_10));
  NOR2X1 g86(.A (in2[1]), .B (in1[1]), .Y (n_9));
  NAND2X1 g83(.A (in2[3]), .B (in1[3]), .Y (n_8));
  CLKINVX3 g92(.A (in2[1]), .Y (n_7));
  INVX1 g94(.A (in2[0]), .Y (n_6));
  CLKINVX3 g91(.A (in1[2]), .Y (n_5));
  INVX2 g95(.A (in1[1]), .Y (n_4));
  INVX2 g90(.A (in1[3]), .Y (n_3));
  CLKINVX4 g93(.A (in2[3]), .Y (n_2));
  CLKINVX12 g89(.A (in2[2]), .Y (n_1));
  INVX1 g96(.A (in1[0]), .Y (n_0));
endmodule


