`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  4 2025 00:39:48 CST (Jun  3 2025 16:39:48 UTC)

module dut_Add_8Ux1U_8U_4(in2, in1, out1);
  input [7:0] in2;
  input in1;
  output [7:0] out1;
  wire [7:0] in2;
  wire in1;
  wire [7:0] out1;
  wire inc_add_16_23_1_n_0, inc_add_16_23_1_n_2, inc_add_16_23_1_n_4,
       inc_add_16_23_1_n_5, inc_add_16_23_1_n_7, inc_add_16_23_1_n_8,
       inc_add_16_23_1_n_10;
  XNOR2X1 inc_add_16_23_1_g68(.A (in2[7]), .B (inc_add_16_23_1_n_10),
       .Y (out1[7]));
  XNOR2X1 inc_add_16_23_1_g69(.A (in2[5]), .B (inc_add_16_23_1_n_8), .Y
       (out1[5]));
  XNOR2X1 inc_add_16_23_1_g70(.A (in2[3]), .B (inc_add_16_23_1_n_5), .Y
       (out1[3]));
  XNOR2X1 inc_add_16_23_1_g71(.A (in2[6]), .B (inc_add_16_23_1_n_7), .Y
       (out1[6]));
  NAND2BX1 inc_add_16_23_1_g72(.AN (inc_add_16_23_1_n_7), .B (in2[6]),
       .Y (inc_add_16_23_1_n_10));
  XNOR2X1 inc_add_16_23_1_g73(.A (in2[4]), .B (inc_add_16_23_1_n_4), .Y
       (out1[4]));
  NAND2BX1 inc_add_16_23_1_g74(.AN (inc_add_16_23_1_n_4), .B (in2[4]),
       .Y (inc_add_16_23_1_n_8));
  NAND3BXL inc_add_16_23_1_g75(.AN (inc_add_16_23_1_n_4), .B (in2[5]),
       .C (in2[4]), .Y (inc_add_16_23_1_n_7));
  XNOR2X1 inc_add_16_23_1_g76(.A (in2[2]), .B (inc_add_16_23_1_n_2), .Y
       (out1[2]));
  NAND2BX1 inc_add_16_23_1_g77(.AN (inc_add_16_23_1_n_2), .B (in2[2]),
       .Y (inc_add_16_23_1_n_5));
  NAND3BXL inc_add_16_23_1_g78(.AN (inc_add_16_23_1_n_2), .B (in2[3]),
       .C (in2[2]), .Y (inc_add_16_23_1_n_4));
  XNOR2X1 inc_add_16_23_1_g79(.A (in2[1]), .B (inc_add_16_23_1_n_0), .Y
       (out1[1]));
  NAND2BX1 inc_add_16_23_1_g80(.AN (inc_add_16_23_1_n_0), .B (in2[1]),
       .Y (inc_add_16_23_1_n_2));
  XOR2XL inc_add_16_23_1_g81(.A (in2[0]), .B (in1), .Y (out1[0]));
  NAND2X1 inc_add_16_23_1_g82(.A (in2[0]), .B (in1), .Y
       (inc_add_16_23_1_n_0));
endmodule


