`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:46:29 CST (Jun  9 2025 08:46:29 UTC)

module dut_LessThan_1U_11_1(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  AO21XL g2(.A0 (in1[5]), .A1 (in1[6]), .B0 (in1[7]), .Y (out1));
endmodule


