`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:45:11 CST (Jun  9 2025 08:45:11 UTC)

module dut_N_Mux_1_2_122_4(in2, ctrl1, out1);
  input in2, ctrl1;
  output out1;
  wire in2, ctrl1;
  wire out1;
  OR2XL g3(.A (in2), .B (ctrl1), .Y (out1));
endmodule


