`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:47:31 CST (Jun  9 2025 08:47:31 UTC)

module dut_GreaterThanEQ_1U_215_1(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire gte_15_26_n_0, gte_15_26_n_1, gte_15_26_n_2, gte_15_26_n_3,
       gte_15_26_n_4, gte_15_26_n_5;
  NAND2X1 gte_15_26_g114(.A (gte_15_26_n_4), .B (gte_15_26_n_5), .Y
       (out1));
  OAI21X1 gte_15_26_g115(.A0 (gte_15_26_n_2), .A1 (gte_15_26_n_3), .B0
       (gte_15_26_n_1), .Y (gte_15_26_n_5));
  NAND2X1 gte_15_26_g116(.A (gte_15_26_n_0), .B (gte_15_26_n_1), .Y
       (gte_15_26_n_4));
  NOR3X6 gte_15_26_g117(.A (in1[3]), .B (in1[1]), .C (in1[0]), .Y
       (gte_15_26_n_3));
  NOR2X1 gte_15_26_g118(.A (in1[3]), .B (in1[2]), .Y (gte_15_26_n_2));
  NOR2X1 gte_15_26_g119(.A (in1[7]), .B (in1[6]), .Y (gte_15_26_n_1));
  NAND2X1 gte_15_26_g120(.A (in1[5]), .B (in1[4]), .Y (gte_15_26_n_0));
endmodule


