`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:46:53 CST (Jun  9 2025 08:46:53 UTC)

module dut_LessThan_1U_80_1(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire lt_15_26_n_0, lt_15_26_n_1, lt_15_26_n_2, lt_15_26_n_3,
       lt_15_26_n_4, lt_15_26_n_5;
  NOR2X1 lt_15_26_g116(.A (lt_15_26_n_4), .B (lt_15_26_n_5), .Y (out1));
  NOR2X1 lt_15_26_g117(.A (lt_15_26_n_0), .B (lt_15_26_n_3), .Y
       (lt_15_26_n_5));
  NOR2X1 lt_15_26_g118(.A (lt_15_26_n_1), .B (lt_15_26_n_0), .Y
       (lt_15_26_n_4));
  AOI2BB1X1 lt_15_26_g119(.A0N (in1[1]), .A1N (in1[0]), .B0
       (lt_15_26_n_2), .Y (lt_15_26_n_3));
  NAND2X2 lt_15_26_g120(.A (in1[3]), .B (in1[2]), .Y (lt_15_26_n_2));
  AND2XL lt_15_26_g2(.A (in1[5]), .B (in1[4]), .Y (lt_15_26_n_1));
  OR2XL lt_15_26_g127(.A (in1[7]), .B (in1[6]), .Y (lt_15_26_n_0));
endmodule


