`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:46:39 CST (Jun  9 2025 08:46:39 UTC)

module dut_GreaterThanEQ_1U_40_1(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire gte_15_26_n_2, gte_15_26_n_3, gte_15_26_n_5, gte_15_26_n_6,
       n_17, n_18;
  OAI21X2 gte_15_26_g112(.A0 (gte_15_26_n_3), .A1 (n_18), .B0
       (gte_15_26_n_6), .Y (out1));
  NOR2X1 gte_15_26_g114(.A (gte_15_26_n_2), .B (gte_15_26_n_5), .Y
       (gte_15_26_n_6));
  NOR3X1 gte_15_26_g115(.A (in1[7]), .B (in1[5]), .C (in1[4]), .Y
       (gte_15_26_n_5));
  OR2XL gte_15_26_g117(.A (in1[7]), .B (in1[5]), .Y (gte_15_26_n_3));
  NOR2X1 gte_15_26_g118(.A (in1[7]), .B (in1[6]), .Y (gte_15_26_n_2));
  NAND2BX4 g2(.AN (in1[3]), .B (n_17), .Y (n_18));
  NAND3X8 g3(.A (in1[1]), .B (in1[0]), .C (in1[2]), .Y (n_17));
endmodule


