`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:44:46 CST (Jun  9 2025 08:44:46 UTC)

module dut_GreaterThanEQ_1U_48_4(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire gte_15_26_n_0, gte_15_26_n_1, gte_15_26_n_2;
  OAI221X1 gte_15_26_g103(.A0 (in1[4]), .A1 (gte_15_26_n_1), .B0
       (in1[7]), .B1 (in1[6]), .C0 (gte_15_26_n_2), .Y (out1));
  OR4X1 gte_15_26_g104(.A (gte_15_26_n_1), .B (gte_15_26_n_0), .C
       (in1[3]), .D (in1[2]), .Y (gte_15_26_n_2));
  OR2XL gte_15_26_g105(.A (in1[7]), .B (in1[5]), .Y (gte_15_26_n_1));
  AND2XL gte_15_26_g106(.A (in1[1]), .B (in1[0]), .Y (gte_15_26_n_0));
endmodule


