`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:45:18 CST (Jun  9 2025 08:45:18 UTC)

module dut_LessThan_1U_149_4(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire lt_15_26_n_0, lt_15_26_n_1;
  NAND2X1 lt_15_26_g103(.A (lt_15_26_n_1), .B (lt_15_26_n_0), .Y
       (out1));
  OAI22X1 lt_15_26_g104(.A0 (in1[3]), .A1 (in1[1]), .B0 (in1[3]), .B1
       (in1[2]), .Y (lt_15_26_n_1));
  NOR4X1 lt_15_26_g105(.A (in1[7]), .B (in1[6]), .C (in1[5]), .D
       (in1[4]), .Y (lt_15_26_n_0));
endmodule


