`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:46:23 CST (Jun  9 2025 08:46:23 UTC)

module dut_OrReduction_6U_1U_1(in1, out1);
  input [5:0] in1;
  output out1;
  wire [5:0] in1;
  wire out1;
  wire n_0, n_1, n_2;
  NAND3X2 g20(.A (n_0), .B (n_1), .C (n_2), .Y (out1));
  NOR2X2 g21(.A (in1[3]), .B (in1[2]), .Y (n_2));
  NOR2X4 g23(.A (in1[5]), .B (in1[4]), .Y (n_1));
  NOR2X6 g22(.A (in1[1]), .B (in1[0]), .Y (n_0));
endmodule


