`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:46:22 CST (Jun  9 2025 08:46:22 UTC)

module dut_LessThan_4Ux8U_1U_1(in2, in1, out1);
  input [3:0] in2;
  input [7:0] in1;
  output out1;
  wire [3:0] in2;
  wire [7:0] in1;
  wire out1;
  wire lt_16_34_n_0, lt_16_34_n_1, lt_16_34_n_2, lt_16_34_n_3,
       lt_16_34_n_4, lt_16_34_n_5, lt_16_34_n_6, lt_16_34_n_7;
  wire lt_16_34_n_8, lt_16_34_n_9, lt_16_34_n_10, lt_16_34_n_11,
       lt_16_34_n_12, lt_16_34_n_13, lt_16_34_n_14, lt_16_34_n_15;
  wire lt_16_34_n_16;
  OAI21X1 lt_16_34_g114(.A0 (lt_16_34_n_14), .A1 (lt_16_34_n_16), .B0
       (lt_16_34_n_10), .Y (out1));
  NOR2X1 lt_16_34_g115(.A (lt_16_34_n_13), .B (lt_16_34_n_15), .Y
       (lt_16_34_n_16));
  NOR2X1 lt_16_34_g116(.A (lt_16_34_n_1), .B (lt_16_34_n_11), .Y
       (lt_16_34_n_15));
  NAND2X1 lt_16_34_g117(.A (lt_16_34_n_7), .B (lt_16_34_n_12), .Y
       (lt_16_34_n_14));
  NAND2X1 lt_16_34_g118(.A (lt_16_34_n_2), .B (lt_16_34_n_8), .Y
       (lt_16_34_n_13));
  NAND2X1 lt_16_34_g119(.A (lt_16_34_n_2), .B (lt_16_34_n_9), .Y
       (lt_16_34_n_12));
  NOR2X1 lt_16_34_g120(.A (lt_16_34_n_0), .B (lt_16_34_n_3), .Y
       (lt_16_34_n_11));
  AND2XL lt_16_34_g121(.A (lt_16_34_n_5), .B (lt_16_34_n_6), .Y
       (lt_16_34_n_10));
  NOR2X1 lt_16_34_g124(.A (lt_16_34_n_4), .B (in1[2]), .Y
       (lt_16_34_n_9));
  NAND2X1 lt_16_34_g125(.A (in1[2]), .B (lt_16_34_n_4), .Y
       (lt_16_34_n_8));
  NAND2BX1 lt_16_34_g126(.AN (in1[3]), .B (in2[3]), .Y (lt_16_34_n_7));
  NOR2X1 lt_16_34_g127(.A (in1[5]), .B (in1[4]), .Y (lt_16_34_n_6));
  NOR2X1 lt_16_34_g128(.A (in1[7]), .B (in1[6]), .Y (lt_16_34_n_5));
  INVX1 lt_16_34_g134(.A (in2[2]), .Y (lt_16_34_n_4));
  NOR2BX1 lt_16_34_g2(.AN (in1[0]), .B (in2[0]), .Y (lt_16_34_n_3));
  NAND2BX4 lt_16_34_g136(.AN (in2[3]), .B (in1[3]), .Y (lt_16_34_n_2));
  NOR2BX1 lt_16_34_g137(.AN (in2[1]), .B (in1[1]), .Y (lt_16_34_n_1));
  NOR2BX1 lt_16_34_g138(.AN (in1[1]), .B (in2[1]), .Y (lt_16_34_n_0));
endmodule


