`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:44:10 CST (Jun  9 2025 08:44:10 UTC)

module dut_Add_16Ux11U_16U_4(in2, in1, out1);
  input [15:0] in2;
  input [10:0] in1;
  output [15:0] out1;
  wire [15:0] in2;
  wire [10:0] in1;
  wire [15:0] out1;
  wire add_16_23_n_0, add_16_23_n_1, add_16_23_n_2, add_16_23_n_3,
       add_16_23_n_4, add_16_23_n_5, add_16_23_n_6, add_16_23_n_7;
  wire add_16_23_n_8, add_16_23_n_9, add_16_23_n_10, add_16_23_n_11,
       add_16_23_n_12, add_16_23_n_13, add_16_23_n_14, add_16_23_n_15;
  wire add_16_23_n_16, add_16_23_n_17, add_16_23_n_18, add_16_23_n_19,
       add_16_23_n_20, add_16_23_n_21, add_16_23_n_22, add_16_23_n_23;
  wire add_16_23_n_24, add_16_23_n_25, add_16_23_n_26, add_16_23_n_27,
       add_16_23_n_28, add_16_23_n_29, add_16_23_n_30, add_16_23_n_31;
  wire add_16_23_n_32, add_16_23_n_33, add_16_23_n_34, add_16_23_n_37,
       add_16_23_n_38, add_16_23_n_40, add_16_23_n_41, add_16_23_n_43;
  wire add_16_23_n_45, add_16_23_n_46, add_16_23_n_47, add_16_23_n_50,
       add_16_23_n_51, add_16_23_n_53, add_16_23_n_54, add_16_23_n_56;
  wire add_16_23_n_59, add_16_23_n_60, add_16_23_n_61, add_16_23_n_63;
  XNOR2X1 add_16_23_g334(.A (in2[15]), .B (add_16_23_n_63), .Y
       (out1[15]));
  XNOR2X1 add_16_23_g335(.A (in2[13]), .B (add_16_23_n_61), .Y
       (out1[13]));
  XNOR2X1 add_16_23_g336(.A (in2[14]), .B (add_16_23_n_60), .Y
       (out1[14]));
  XOR2XL add_16_23_g337(.A (in2[11]), .B (add_16_23_n_59), .Y
       (out1[11]));
  NAND2BX1 add_16_23_g338(.AN (add_16_23_n_60), .B (in2[14]), .Y
       (add_16_23_n_63));
  XNOR2X1 add_16_23_g339(.A (in2[12]), .B (add_16_23_n_56), .Y
       (out1[12]));
  NAND2BX1 add_16_23_g340(.AN (add_16_23_n_56), .B (in2[12]), .Y
       (add_16_23_n_61));
  NAND3BXL add_16_23_g341(.AN (add_16_23_n_56), .B (in2[13]), .C
       (in2[12]), .Y (add_16_23_n_60));
  OAI21X1 add_16_23_g342(.A0 (add_16_23_n_15), .A1 (add_16_23_n_54),
       .B0 (add_16_23_n_6), .Y (add_16_23_n_59));
  XNOR2X1 add_16_23_g343(.A (add_16_23_n_28), .B (add_16_23_n_54), .Y
       (out1[10]));
  XNOR2X1 add_16_23_g344(.A (add_16_23_n_21), .B (add_16_23_n_53), .Y
       (out1[9]));
  AOI221X1 add_16_23_g345(.A0 (add_16_23_n_30), .A1 (add_16_23_n_33),
       .B0 (add_16_23_n_30), .B1 (add_16_23_n_50), .C0
       (add_16_23_n_24), .Y (add_16_23_n_56));
  XNOR2X1 add_16_23_g346(.A (add_16_23_n_23), .B (add_16_23_n_51), .Y
       (out1[7]));
  NOR2X1 add_16_23_g347(.A (add_16_23_n_33), .B (add_16_23_n_50), .Y
       (add_16_23_n_54));
  OAI21X1 add_16_23_g348(.A0 (add_16_23_n_13), .A1 (add_16_23_n_47),
       .B0 (add_16_23_n_1), .Y (add_16_23_n_53));
  XNOR2X1 add_16_23_g349(.A (add_16_23_n_22), .B (add_16_23_n_47), .Y
       (out1[8]));
  OAI21X1 add_16_23_g350(.A0 (add_16_23_n_12), .A1 (add_16_23_n_46),
       .B0 (add_16_23_n_16), .Y (add_16_23_n_51));
  NOR3X1 add_16_23_g351(.A (add_16_23_n_47), .B (add_16_23_n_3), .C
       (add_16_23_n_13), .Y (add_16_23_n_50));
  XNOR2X1 add_16_23_g352(.A (add_16_23_n_20), .B (add_16_23_n_46), .Y
       (out1[6]));
  XNOR2X1 add_16_23_g353(.A (add_16_23_n_19), .B (add_16_23_n_45), .Y
       (out1[5]));
  AOI221X1 add_16_23_g354(.A0 (add_16_23_n_29), .A1 (add_16_23_n_31),
       .B0 (add_16_23_n_29), .B1 (add_16_23_n_43), .C0
       (add_16_23_n_32), .Y (add_16_23_n_47));
  NOR2X1 add_16_23_g355(.A (add_16_23_n_31), .B (add_16_23_n_43), .Y
       (add_16_23_n_46));
  OAI2BB1X1 add_16_23_g356(.A0N (add_16_23_n_5), .A1N (add_16_23_n_41),
       .B0 (add_16_23_n_10), .Y (add_16_23_n_45));
  XNOR2X1 add_16_23_g357(.A (add_16_23_n_27), .B (add_16_23_n_41), .Y
       (out1[4]));
  NOR3BX1 add_16_23_g358(.AN (add_16_23_n_41), .B (add_16_23_n_0), .C
       (add_16_23_n_4), .Y (add_16_23_n_43));
  XNOR2X1 add_16_23_g359(.A (add_16_23_n_25), .B (add_16_23_n_40), .Y
       (out1[3]));
  OAI221X1 add_16_23_g360(.A0 (add_16_23_n_11), .A1 (add_16_23_n_38),
       .B0 (add_16_23_n_2), .B1 (add_16_23_n_11), .C0 (add_16_23_n_9),
       .Y (add_16_23_n_41));
  NAND2X1 add_16_23_g361(.A (add_16_23_n_2), .B (add_16_23_n_38), .Y
       (add_16_23_n_40));
  XNOR2X1 add_16_23_g362(.A (add_16_23_n_26), .B (add_16_23_n_37), .Y
       (out1[2]));
  NAND2BX1 add_16_23_g363(.AN (add_16_23_n_7), .B (add_16_23_n_37), .Y
       (add_16_23_n_38));
  ADDFX1 add_16_23_g364(.A (add_16_23_n_34), .B (in1[1]), .CI (in2[1]),
       .CO (add_16_23_n_37), .S (out1[1]));
  ADDHX1 add_16_23_g365(.A (in2[0]), .B (in1[0]), .CO (add_16_23_n_34),
       .S (out1[0]));
  OAI21X1 add_16_23_g366(.A0 (add_16_23_n_1), .A1 (add_16_23_n_3), .B0
       (add_16_23_n_17), .Y (add_16_23_n_33));
  OAI21X1 add_16_23_g367(.A0 (add_16_23_n_16), .A1 (add_16_23_n_14),
       .B0 (add_16_23_n_18), .Y (add_16_23_n_32));
  OAI21X1 add_16_23_g368(.A0 (add_16_23_n_10), .A1 (add_16_23_n_0), .B0
       (add_16_23_n_8), .Y (add_16_23_n_31));
  NOR2BX1 add_16_23_g369(.AN (add_16_23_n_6), .B (add_16_23_n_15), .Y
       (add_16_23_n_28));
  NAND2X1 add_16_23_g370(.A (add_16_23_n_10), .B (add_16_23_n_5), .Y
       (add_16_23_n_27));
  NAND2BX1 add_16_23_g371(.AN (add_16_23_n_7), .B (add_16_23_n_2), .Y
       (add_16_23_n_26));
  NAND2BX1 add_16_23_g372(.AN (add_16_23_n_11), .B (add_16_23_n_9), .Y
       (add_16_23_n_25));
  NOR2BX1 add_16_23_g373(.AN (in2[11]), .B (add_16_23_n_15), .Y
       (add_16_23_n_30));
  NOR2X1 add_16_23_g374(.A (add_16_23_n_14), .B (add_16_23_n_12), .Y
       (add_16_23_n_29));
  NOR2BX1 add_16_23_g375(.AN (in2[11]), .B (add_16_23_n_6), .Y
       (add_16_23_n_24));
  NAND2BX1 add_16_23_g376(.AN (add_16_23_n_14), .B (add_16_23_n_18), .Y
       (add_16_23_n_23));
  NOR2BX1 add_16_23_g377(.AN (add_16_23_n_1), .B (add_16_23_n_13), .Y
       (add_16_23_n_22));
  NAND2BX1 add_16_23_g378(.AN (add_16_23_n_3), .B (add_16_23_n_17), .Y
       (add_16_23_n_21));
  NOR2BX1 add_16_23_g379(.AN (add_16_23_n_16), .B (add_16_23_n_12), .Y
       (add_16_23_n_20));
  NAND2BX1 add_16_23_g380(.AN (add_16_23_n_0), .B (add_16_23_n_8), .Y
       (add_16_23_n_19));
  NAND2X1 add_16_23_g381(.A (in2[7]), .B (in1[7]), .Y (add_16_23_n_18));
  NAND2X1 add_16_23_g382(.A (in2[9]), .B (in1[9]), .Y (add_16_23_n_17));
  NAND2X1 add_16_23_g383(.A (in2[6]), .B (in1[6]), .Y (add_16_23_n_16));
  NOR2X1 add_16_23_g384(.A (in2[10]), .B (in1[10]), .Y
       (add_16_23_n_15));
  NOR2X1 add_16_23_g385(.A (in2[7]), .B (in1[7]), .Y (add_16_23_n_14));
  NOR2X1 add_16_23_g386(.A (in2[8]), .B (in1[8]), .Y (add_16_23_n_13));
  NOR2X1 add_16_23_g387(.A (in2[6]), .B (in1[6]), .Y (add_16_23_n_12));
  NOR2X1 add_16_23_g388(.A (in2[3]), .B (in1[3]), .Y (add_16_23_n_11));
  NAND2X1 add_16_23_g389(.A (in2[4]), .B (in1[4]), .Y (add_16_23_n_10));
  INVX1 add_16_23_g390(.A (add_16_23_n_4), .Y (add_16_23_n_5));
  NAND2X1 add_16_23_g391(.A (in2[3]), .B (in1[3]), .Y (add_16_23_n_9));
  NAND2X1 add_16_23_g392(.A (in2[5]), .B (in1[5]), .Y (add_16_23_n_8));
  NOR2X1 add_16_23_g393(.A (in2[2]), .B (in1[2]), .Y (add_16_23_n_7));
  NAND2X1 add_16_23_g394(.A (in2[10]), .B (in1[10]), .Y
       (add_16_23_n_6));
  NOR2X1 add_16_23_g395(.A (in2[4]), .B (in1[4]), .Y (add_16_23_n_4));
  NOR2X1 add_16_23_g396(.A (in2[9]), .B (in1[9]), .Y (add_16_23_n_3));
  NAND2X1 add_16_23_g397(.A (in2[2]), .B (in1[2]), .Y (add_16_23_n_2));
  NAND2X1 add_16_23_g398(.A (in2[8]), .B (in1[8]), .Y (add_16_23_n_1));
  NOR2X1 add_16_23_g399(.A (in2[5]), .B (in1[5]), .Y (add_16_23_n_0));
endmodule


