`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:46:20 CST (Jun  9 2025 08:46:20 UTC)

module dut_LessThan_5Ux8U_1U_1(in2, in1, out1);
  input [4:0] in2;
  input [7:0] in1;
  output out1;
  wire [4:0] in2;
  wire [7:0] in1;
  wire out1;
  wire lt_16_33_n_0, lt_16_33_n_1, lt_16_33_n_2, lt_16_33_n_3,
       lt_16_33_n_4, lt_16_33_n_5, lt_16_33_n_6, lt_16_33_n_7;
  wire lt_16_33_n_8, lt_16_33_n_9, lt_16_33_n_10, lt_16_33_n_11,
       lt_16_33_n_12, lt_16_33_n_13, lt_16_33_n_14, lt_16_33_n_15;
  wire lt_16_33_n_16, lt_16_33_n_17;
  AOI21X1 lt_16_33_g143(.A0 (lt_16_33_n_14), .A1 (lt_16_33_n_17), .B0
       (lt_16_33_n_16), .Y (out1));
  OAI21X1 lt_16_33_g144(.A0 (lt_16_33_n_12), .A1 (lt_16_33_n_15), .B0
       (lt_16_33_n_13), .Y (lt_16_33_n_17));
  NOR4X1 lt_16_33_g145(.A (in1[7]), .B (in1[6]), .C (in1[5]), .D
       (lt_16_33_n_11), .Y (lt_16_33_n_16));
  AOI21X1 lt_16_33_g146(.A0 (lt_16_33_n_0), .A1 (lt_16_33_n_6), .B0
       (lt_16_33_n_5), .Y (lt_16_33_n_15));
  NOR4X1 lt_16_33_g147(.A (in1[7]), .B (in1[6]), .C (in1[5]), .D
       (lt_16_33_n_4), .Y (lt_16_33_n_14));
  AOI21X1 lt_16_33_g148(.A0 (lt_16_33_n_8), .A1 (lt_16_33_n_9), .B0
       (lt_16_33_n_10), .Y (lt_16_33_n_13));
  NAND2X1 lt_16_33_g149(.A (lt_16_33_n_9), .B (lt_16_33_n_7), .Y
       (lt_16_33_n_12));
  NAND2BX1 lt_16_33_g151(.AN (in1[4]), .B (in2[4]), .Y (lt_16_33_n_11));
  NOR2BX1 lt_16_33_g152(.AN (in2[3]), .B (in1[3]), .Y (lt_16_33_n_10));
  NAND2X2 lt_16_33_g153(.A (in1[3]), .B (lt_16_33_n_3), .Y
       (lt_16_33_n_9));
  NOR2X2 lt_16_33_g154(.A (in1[2]), .B (lt_16_33_n_2), .Y
       (lt_16_33_n_8));
  NAND2X1 lt_16_33_g155(.A (in1[2]), .B (lt_16_33_n_2), .Y
       (lt_16_33_n_7));
  NAND2X1 lt_16_33_g156(.A (in1[1]), .B (lt_16_33_n_1), .Y
       (lt_16_33_n_6));
  NOR2X1 lt_16_33_g157(.A (lt_16_33_n_1), .B (in1[1]), .Y
       (lt_16_33_n_5));
  NOR2BX1 lt_16_33_g158(.AN (in1[4]), .B (in2[4]), .Y (lt_16_33_n_4));
  CLKINVX2 lt_16_33_g159(.A (in2[3]), .Y (lt_16_33_n_3));
  INVX1 lt_16_33_g160(.A (in2[2]), .Y (lt_16_33_n_2));
  INVX1 lt_16_33_g162(.A (in2[1]), .Y (lt_16_33_n_1));
  NAND2BX1 lt_16_33_g2(.AN (in2[0]), .B (in1[0]), .Y (lt_16_33_n_0));
endmodule


