`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:47:28 CST (Jun  9 2025 08:47:28 UTC)

module dut_GreaterThanEQ_1U_207_1(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire gte_15_26_n_0, gte_15_26_n_1, gte_15_26_n_2, gte_15_26_n_3,
       gte_15_26_n_4;
  NAND2X1 gte_15_26_g112(.A (gte_15_26_n_3), .B (gte_15_26_n_2), .Y
       (gte_15_26_n_4));
  NOR2X6 gte_15_26_g113(.A (in1[3]), .B (in1[2]), .Y (gte_15_26_n_3));
  NOR2X2 gte_15_26_g116(.A (in1[1]), .B (in1[0]), .Y (gte_15_26_n_2));
  CLKAND2X3 gte_15_26_g2(.A (in1[5]), .B (in1[4]), .Y (gte_15_26_n_1));
  OR2XL gte_15_26_g121(.A (in1[7]), .B (in1[6]), .Y (gte_15_26_n_0));
  AOI21X1 g2(.A0 (gte_15_26_n_1), .A1 (gte_15_26_n_4), .B0
       (gte_15_26_n_0), .Y (out1));
endmodule


