`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:46:04 CST (Jun  9 2025 08:46:04 UTC)

module dut_Add_16Ux10U_16U_1(in2, in1, out1);
  input [15:0] in2;
  input [9:0] in1;
  output [15:0] out1;
  wire [15:0] in2;
  wire [9:0] in1;
  wire [15:0] out1;
  wire add_16_23_n_1, add_16_23_n_6, add_16_23_n_10, add_16_23_n_12,
       add_16_23_n_13, add_16_23_n_14, add_16_23_n_15, add_16_23_n_16;
  wire add_16_23_n_17, add_16_23_n_18, add_16_23_n_19, add_16_23_n_20,
       add_16_23_n_22, add_16_23_n_23, add_16_23_n_24, add_16_23_n_25;
  wire add_16_23_n_26, add_16_23_n_27, add_16_23_n_28, add_16_23_n_29,
       add_16_23_n_30, add_16_23_n_31, add_16_23_n_32, add_16_23_n_33;
  wire add_16_23_n_34, add_16_23_n_35, add_16_23_n_36, add_16_23_n_37,
       add_16_23_n_38, add_16_23_n_40, add_16_23_n_41, add_16_23_n_42;
  wire add_16_23_n_43, add_16_23_n_44, add_16_23_n_45, add_16_23_n_46,
       add_16_23_n_47, add_16_23_n_48, add_16_23_n_49, add_16_23_n_50;
  wire add_16_23_n_51, add_16_23_n_52, add_16_23_n_53, add_16_23_n_54,
       add_16_23_n_55, add_16_23_n_56, add_16_23_n_57, add_16_23_n_58;
  wire add_16_23_n_59, add_16_23_n_60, add_16_23_n_61, add_16_23_n_62,
       add_16_23_n_63, add_16_23_n_64, add_16_23_n_65, add_16_23_n_66;
  wire add_16_23_n_67, add_16_23_n_68, add_16_23_n_69, add_16_23_n_70,
       add_16_23_n_71, add_16_23_n_72, add_16_23_n_73, add_16_23_n_74;
  wire add_16_23_n_75, add_16_23_n_76, add_16_23_n_77, add_16_23_n_78,
       add_16_23_n_79, add_16_23_n_80, add_16_23_n_81, add_16_23_n_82;
  wire add_16_23_n_83, add_16_23_n_84, add_16_23_n_85, add_16_23_n_86,
       add_16_23_n_87, add_16_23_n_88, add_16_23_n_89, add_16_23_n_90;
  wire add_16_23_n_91, add_16_23_n_92, add_16_23_n_93, add_16_23_n_94,
       add_16_23_n_95, add_16_23_n_96, add_16_23_n_97, add_16_23_n_98;
  wire add_16_23_n_99, add_16_23_n_100, add_16_23_n_101,
       add_16_23_n_102, add_16_23_n_103, add_16_23_n_104,
       add_16_23_n_105, add_16_23_n_106;
  wire n_141, n_143, n_144, n_145, n_146, n_148, n_149, n_150;
  wire n_152, n_153, n_154, n_156, n_157, n_158, n_160, n_161;
  wire n_162, n_164, n_165, n_167;
  MXI2X1 add_16_23_g372(.A (in2[13]), .B (add_16_23_n_14), .S0
       (add_16_23_n_100), .Y (out1[13]));
  MXI2X1 add_16_23_g373(.A (in2[11]), .B (add_16_23_n_15), .S0
       (add_16_23_n_104), .Y (out1[11]));
  MXI2X1 add_16_23_g374(.A (in2[10]), .B (add_16_23_n_12), .S0
       (add_16_23_n_105), .Y (out1[10]));
  MXI2X1 add_16_23_g375(.A (add_16_23_n_50), .B (add_16_23_n_51), .S0
       (add_16_23_n_106), .Y (out1[9]));
  MXI2X1 add_16_23_g376(.A (in2[15]), .B (add_16_23_n_19), .S0
       (add_16_23_n_101), .Y (out1[15]));
  MXI2X1 add_16_23_g377(.A (in2[12]), .B (add_16_23_n_13), .S0
       (add_16_23_n_103), .Y (out1[12]));
  MXI2X1 add_16_23_g378(.A (in2[14]), .B (add_16_23_n_17), .S0
       (add_16_23_n_102), .Y (out1[14]));
  NOR2BX1 add_16_23_g380(.AN (add_16_23_n_23), .B (add_16_23_n_99), .Y
       (add_16_23_n_106));
  NOR2X1 add_16_23_g381(.A (add_16_23_n_66), .B (add_16_23_n_6), .Y
       (add_16_23_n_105));
  NOR2BX1 add_16_23_g382(.AN (add_16_23_n_73), .B (add_16_23_n_96), .Y
       (add_16_23_n_104));
  NOR2X1 add_16_23_g383(.A (add_16_23_n_75), .B (add_16_23_n_98), .Y
       (add_16_23_n_103));
  NOR2X1 add_16_23_g387(.A (add_16_23_n_83), .B (add_16_23_n_95), .Y
       (add_16_23_n_102));
  NOR2X1 add_16_23_g388(.A (add_16_23_n_81), .B (add_16_23_n_94), .Y
       (add_16_23_n_101));
  NOR2BX1 add_16_23_g389(.AN (add_16_23_n_82), .B (add_16_23_n_97), .Y
       (add_16_23_n_100));
  NOR2X1 add_16_23_g391(.A (add_16_23_n_25), .B (add_16_23_n_93), .Y
       (add_16_23_n_99));
  NOR2X1 add_16_23_g392(.A (add_16_23_n_69), .B (add_16_23_n_93), .Y
       (add_16_23_n_98));
  NOR2X1 add_16_23_g393(.A (add_16_23_n_74), .B (add_16_23_n_93), .Y
       (add_16_23_n_97));
  NOR2X1 add_16_23_g394(.A (add_16_23_n_70), .B (add_16_23_n_93), .Y
       (add_16_23_n_96));
  NOR2BX1 add_16_23_g395(.AN (add_16_23_n_76), .B (add_16_23_n_93), .Y
       (add_16_23_n_95));
  NOR2X1 add_16_23_g396(.A (add_16_23_n_72), .B (add_16_23_n_93), .Y
       (add_16_23_n_94));
  NOR2X4 add_16_23_g397(.A (add_16_23_n_79), .B (add_16_23_n_88), .Y
       (add_16_23_n_93));
  NOR2BX1 add_16_23_g399(.AN (n_152), .B (add_16_23_n_89), .Y
       (add_16_23_n_92));
  NOR2X1 add_16_23_g402(.A (add_16_23_n_80), .B (add_16_23_n_87), .Y
       (add_16_23_n_91));
  NOR2X1 add_16_23_g403(.A (add_16_23_n_47), .B (add_16_23_n_85), .Y
       (add_16_23_n_90));
  NOR2X1 add_16_23_g404(.A (add_16_23_n_26), .B (add_16_23_n_85), .Y
       (add_16_23_n_89));
  NOR2X4 add_16_23_g405(.A (add_16_23_n_68), .B (add_16_23_n_85), .Y
       (add_16_23_n_88));
  NOR2X1 add_16_23_g406(.A (add_16_23_n_71), .B (add_16_23_n_85), .Y
       (add_16_23_n_87));
  NOR2BX1 add_16_23_g407(.AN (add_16_23_n_36), .B (add_16_23_n_1), .Y
       (add_16_23_n_86));
  NOR2X4 add_16_23_g409(.A (add_16_23_n_64), .B (add_16_23_n_84), .Y
       (add_16_23_n_85));
  NOR2X4 add_16_23_g411(.A (add_16_23_n_54), .B (add_16_23_n_78), .Y
       (add_16_23_n_84));
  NOR2BX1 add_16_23_g412(.AN (add_16_23_n_75), .B (add_16_23_n_28), .Y
       (add_16_23_n_83));
  NAND2X1 add_16_23_g413(.A (in2[12]), .B (add_16_23_n_75), .Y
       (add_16_23_n_82));
  AND2XL add_16_23_g414(.A (add_16_23_n_59), .B (add_16_23_n_75), .Y
       (add_16_23_n_81));
  OAI21X1 add_16_23_g415(.A0 (n_144), .A1 (add_16_23_n_67), .B0
       (n_161), .Y (add_16_23_n_80));
  OAI21X2 add_16_23_g416(.A0 (add_16_23_n_62), .A1 (add_16_23_n_67),
       .B0 (add_16_23_n_63), .Y (add_16_23_n_79));
  NOR2X6 add_16_23_g417(.A (add_16_23_n_31), .B (add_16_23_n_77), .Y
       (add_16_23_n_78));
  NOR2X6 add_16_23_g419(.A (add_16_23_n_41), .B (add_16_23_n_24), .Y
       (add_16_23_n_77));
  NOR2XL add_16_23_g420(.A (add_16_23_n_28), .B (add_16_23_n_69), .Y
       (add_16_23_n_76));
  NOR2X1 add_16_23_g421(.A (add_16_23_n_43), .B (add_16_23_n_65), .Y
       (add_16_23_n_75));
  OR2XL add_16_23_g422(.A (add_16_23_n_13), .B (add_16_23_n_69), .Y
       (add_16_23_n_74));
  NAND2XL add_16_23_g423(.A (in2[10]), .B (add_16_23_n_66), .Y
       (add_16_23_n_73));
  NAND2BX1 add_16_23_g424(.AN (add_16_23_n_69), .B (add_16_23_n_59), .Y
       (add_16_23_n_72));
  OR2XL add_16_23_g426(.A (n_146), .B (add_16_23_n_47), .Y
       (add_16_23_n_71));
  NAND2X1 add_16_23_g427(.A (in2[10]), .B (add_16_23_n_56), .Y
       (add_16_23_n_70));
  NAND2BX2 add_16_23_g428(.AN (add_16_23_n_43), .B (add_16_23_n_56), .Y
       (add_16_23_n_69));
  NAND2X2 add_16_23_g429(.A (add_16_23_n_61), .B (add_16_23_n_46), .Y
       (add_16_23_n_68));
  NOR2X2 add_16_23_g431(.A (add_16_23_n_29), .B (add_16_23_n_45), .Y
       (add_16_23_n_67));
  INVX1 add_16_23_g432(.A (add_16_23_n_65), .Y (add_16_23_n_66));
  NOR2BX1 add_16_23_g433(.AN (add_16_23_n_32), .B (add_16_23_n_55), .Y
       (add_16_23_n_65));
  OAI21X2 add_16_23_g434(.A0 (add_16_23_n_36), .A1 (add_16_23_n_38),
       .B0 (add_16_23_n_30), .Y (add_16_23_n_64));
  AOI2BB1X1 add_16_23_g435(.A0N (add_16_23_n_35), .A1N
       (add_16_23_n_33), .B0 (add_16_23_n_42), .Y (add_16_23_n_63));
  INVX1 add_16_23_g436(.A (add_16_23_n_61), .Y (add_16_23_n_62));
  NOR2X1 add_16_23_g441(.A (add_16_23_n_23), .B (add_16_23_n_34), .Y
       (add_16_23_n_55));
  NAND2X4 add_16_23_g442(.A (n_164), .B (add_16_23_n_37), .Y
       (add_16_23_n_54));
  NOR2X1 add_16_23_g443(.A (add_16_23_n_33), .B (add_16_23_n_22), .Y
       (add_16_23_n_61));
  NAND2BX1 add_16_23_g444(.AN (n_143), .B (n_160), .Y (add_16_23_n_60));
  NOR2X1 add_16_23_g445(.A (add_16_23_n_17), .B (add_16_23_n_28), .Y
       (add_16_23_n_59));
  NAND2X1 add_16_23_g446(.A (add_16_23_n_36), .B (n_156), .Y
       (add_16_23_n_58));
  NOR2X1 add_16_23_g447(.A (add_16_23_n_29), .B (add_16_23_n_40), .Y
       (add_16_23_n_57));
  NOR2X1 add_16_23_g448(.A (add_16_23_n_34), .B (add_16_23_n_25), .Y
       (add_16_23_n_56));
  INVX1 add_16_23_g451(.A (add_16_23_n_50), .Y (add_16_23_n_51));
  INVX1 add_16_23_g454(.A (add_16_23_n_46), .Y (add_16_23_n_47));
  NOR2X2 add_16_23_g456(.A (add_16_23_n_27), .B (add_16_23_n_40), .Y
       (add_16_23_n_45));
  NAND2BX1 add_16_23_g457(.AN (add_16_23_n_26), .B (n_153), .Y
       (add_16_23_n_53));
  NAND2X1 add_16_23_g458(.A (add_16_23_n_30), .B (n_165), .Y
       (add_16_23_n_52));
  NOR2BX1 add_16_23_g459(.AN (add_16_23_n_32), .B (add_16_23_n_34), .Y
       (add_16_23_n_50));
  NOR2X1 add_16_23_g460(.A (add_16_23_n_42), .B (add_16_23_n_33), .Y
       (add_16_23_n_49));
  NAND2BX1 add_16_23_g461(.AN (add_16_23_n_25), .B (add_16_23_n_23), .Y
       (add_16_23_n_48));
  NOR2X1 add_16_23_g462(.A (add_16_23_n_31), .B (add_16_23_n_41), .Y
       (add_16_23_n_44));
  NOR2X1 add_16_23_g463(.A (add_16_23_n_40), .B (add_16_23_n_26), .Y
       (add_16_23_n_46));
  NAND2X1 add_16_23_g466(.A (in2[11]), .B (in2[10]), .Y
       (add_16_23_n_43));
  AND2X1 add_16_23_g467(.A (in2[7]), .B (in1[7]), .Y (add_16_23_n_42));
  NOR2X8 add_16_23_g468(.A (in2[1]), .B (in1[1]), .Y (add_16_23_n_41));
  NOR2X4 add_16_23_g469(.A (in2[5]), .B (in1[5]), .Y (add_16_23_n_40));
  NOR2X8 add_16_23_g470(.A (in2[3]), .B (in1[3]), .Y (add_16_23_n_38));
  NAND2X4 add_16_23_g471(.A (add_16_23_n_20), .B (add_16_23_n_16), .Y
       (add_16_23_n_37));
  NAND2X2 add_16_23_g472(.A (in2[2]), .B (in1[2]), .Y (add_16_23_n_36));
  NAND2X1 add_16_23_g473(.A (in2[6]), .B (in1[6]), .Y (add_16_23_n_35));
  NOR2X2 add_16_23_g474(.A (in2[9]), .B (in1[9]), .Y (add_16_23_n_34));
  NOR2X4 add_16_23_g475(.A (in2[7]), .B (in1[7]), .Y (add_16_23_n_33));
  NAND2X1 add_16_23_g476(.A (in2[9]), .B (in1[9]), .Y (add_16_23_n_32));
  NOR2X6 add_16_23_g477(.A (n_167), .B (add_16_23_n_18), .Y
       (add_16_23_n_31));
  NAND2X1 add_16_23_g478(.A (in2[3]), .B (in1[3]), .Y (add_16_23_n_30));
  AND2X1 add_16_23_g479(.A (in2[5]), .B (in1[5]), .Y (add_16_23_n_29));
  NAND2X1 add_16_23_g480(.A (in2[13]), .B (in2[12]), .Y
       (add_16_23_n_28));
  NAND2X2 add_16_23_g481(.A (in2[4]), .B (in1[4]), .Y (add_16_23_n_27));
  NOR2X1 add_16_23_g482(.A (in2[4]), .B (in1[4]), .Y (add_16_23_n_26));
  NOR2X1 add_16_23_g483(.A (in2[8]), .B (in1[8]), .Y (add_16_23_n_25));
  NAND2X8 add_16_23_g484(.A (in2[0]), .B (in1[0]), .Y (add_16_23_n_24));
  NAND2X2 add_16_23_g485(.A (in2[8]), .B (in1[8]), .Y (add_16_23_n_23));
  NOR2X2 add_16_23_g486(.A (in2[6]), .B (in1[6]), .Y (add_16_23_n_22));
  CLKINVX4 add_16_23_g488(.A (in2[2]), .Y (add_16_23_n_20));
  INVX1 add_16_23_g489(.A (in2[15]), .Y (add_16_23_n_19));
  CLKINVX2 add_16_23_g490(.A (in1[1]), .Y (add_16_23_n_18));
  INVX1 add_16_23_g491(.A (in2[14]), .Y (add_16_23_n_17));
  CLKINVX2 add_16_23_g492(.A (in1[2]), .Y (add_16_23_n_16));
  INVX1 add_16_23_g493(.A (in2[11]), .Y (add_16_23_n_15));
  INVX1 add_16_23_g494(.A (in2[13]), .Y (add_16_23_n_14));
  INVX1 add_16_23_g496(.A (in2[12]), .Y (add_16_23_n_13));
  INVX1 add_16_23_g497(.A (in2[10]), .Y (add_16_23_n_12));
  XNOR2X1 add_16_23_g2(.A (add_16_23_n_24), .B (add_16_23_n_44), .Y
       (out1[1]));
  NOR2BX1 add_16_23_g498(.AN (add_16_23_n_67), .B (add_16_23_n_90), .Y
       (add_16_23_n_10));
  CLKXOR2X1 add_16_23_g499(.A (add_16_23_n_60), .B (add_16_23_n_10), .Y
       (out1[6]));
  CLKXOR2X1 add_16_23_g500(.A (add_16_23_n_58), .B (n_148), .Y
       (out1[2]));
  XNOR2XL add_16_23_g501(.A (add_16_23_n_57), .B (add_16_23_n_92), .Y
       (out1[5]));
  NOR2BX1 add_16_23_g502(.AN (add_16_23_n_56), .B (add_16_23_n_93), .Y
       (add_16_23_n_6));
  CLKXOR2X1 add_16_23_g503(.A (add_16_23_n_53), .B (n_141), .Y
       (out1[4]));
  CLKXOR2X1 add_16_23_g504(.A (add_16_23_n_52), .B (add_16_23_n_86), .Y
       (out1[3]));
  XNOR2XL add_16_23_g505(.A (add_16_23_n_49), .B (add_16_23_n_91), .Y
       (out1[7]));
  CLKXOR2X1 add_16_23_g506(.A (add_16_23_n_48), .B (add_16_23_n_93), .Y
       (out1[8]));
  NOR2BX1 add_16_23_g507(.AN (n_157), .B (n_149), .Y (add_16_23_n_1));
  CLKXOR2X1 add_16_23_g508(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  BUFX2 fopt(.A (add_16_23_n_85), .Y (n_141));
  INVXL fopt509(.A (n_145), .Y (n_143));
  INVXL fopt1(.A (n_145), .Y (n_144));
  INVXL fopt2(.A (n_146), .Y (n_145));
  BUFX2 fopt3(.A (add_16_23_n_22), .Y (n_146));
  INVXL fopt510(.A (n_150), .Y (n_148));
  INVXL fopt511(.A (n_150), .Y (n_149));
  INVXL fopt512(.A (add_16_23_n_78), .Y (n_150));
  INVXL fopt513(.A (n_154), .Y (n_152));
  INVXL fopt514(.A (n_154), .Y (n_153));
  INVXL fopt515(.A (add_16_23_n_27), .Y (n_154));
  INVXL fopt516(.A (n_158), .Y (n_156));
  INVXL fopt517(.A (n_158), .Y (n_157));
  INVXL fopt518(.A (add_16_23_n_37), .Y (n_158));
  INVXL fopt519(.A (n_162), .Y (n_160));
  INVXL fopt520(.A (n_162), .Y (n_161));
  INVXL fopt521(.A (add_16_23_n_35), .Y (n_162));
  CLKINVX4 fopt522(.A (add_16_23_n_38), .Y (n_164));
  INVXL fopt523(.A (add_16_23_n_38), .Y (n_165));
  CLKINVX3 fopt524(.A (in2[1]), .Y (n_167));
endmodule


