`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:46:57 CST (Jun  9 2025 08:46:57 UTC)

module dut_LessThan_1U_90_1(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire lt_15_26_n_0, lt_15_26_n_2, lt_15_26_n_4, lt_15_26_n_5,
       lt_15_26_n_7, n_17, n_18;
  NOR2X1 lt_15_26_g123(.A (lt_15_26_n_4), .B (lt_15_26_n_7), .Y (out1));
  NOR2X1 lt_15_26_g124(.A (lt_15_26_n_5), .B (n_18), .Y (lt_15_26_n_7));
  NAND2BX1 lt_15_26_g126(.AN (in1[5]), .B (lt_15_26_n_0), .Y
       (lt_15_26_n_5));
  NOR2BX1 lt_15_26_g127(.AN (lt_15_26_n_0), .B (lt_15_26_n_2), .Y
       (lt_15_26_n_4));
  OR2XL lt_15_26_g129(.A (in1[5]), .B (in1[4]), .Y (lt_15_26_n_2));
  NOR2X4 lt_15_26_g131(.A (in1[7]), .B (in1[6]), .Y (lt_15_26_n_0));
  NAND2BX2 g2(.AN (in1[3]), .B (n_17), .Y (n_18));
  OAI21X4 g3(.A0 (in1[1]), .A1 (in1[0]), .B0 (in1[2]), .Y (n_17));
endmodule


