`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:47:23 CST (Jun  9 2025 08:47:23 UTC)

module dut_GreaterThanEQ_1U_194_1(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire gte_15_26_n_0, gte_15_26_n_1, gte_15_26_n_2, gte_15_26_n_3,
       gte_15_26_n_4;
  OAI21X1 gte_15_26_g104(.A0 (gte_15_26_n_3), .A1 (gte_15_26_n_4), .B0
       (gte_15_26_n_2), .Y (out1));
  NOR2BX2 gte_15_26_g105(.AN (in1[3]), .B (gte_15_26_n_1), .Y
       (gte_15_26_n_4));
  NAND2BX1 gte_15_26_g106(.AN (in1[4]), .B (gte_15_26_n_0), .Y
       (gte_15_26_n_3));
  NAND2BX1 gte_15_26_g107(.AN (in1[5]), .B (gte_15_26_n_0), .Y
       (gte_15_26_n_2));
  AOI21X4 gte_15_26_g108(.A0 (in1[1]), .A1 (in1[0]), .B0 (in1[2]), .Y
       (gte_15_26_n_1));
  NOR2X2 gte_15_26_g109(.A (in1[7]), .B (in1[6]), .Y (gte_15_26_n_0));
endmodule


