`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:44:12 CST (Jun  9 2025 08:44:12 UTC)

module dut_Add_13Ux12U_14U_4(in2, in1, out1);
  input [12:0] in2;
  input [11:0] in1;
  output [13:0] out1;
  wire [12:0] in2;
  wire [11:0] in1;
  wire [13:0] out1;
  wire add_16_31_n_0, add_16_31_n_1, add_16_31_n_2, add_16_31_n_3,
       add_16_31_n_4, add_16_31_n_5, add_16_31_n_6, add_16_31_n_7;
  wire add_16_31_n_8, add_16_31_n_9, add_16_31_n_10, add_16_31_n_11,
       add_16_31_n_12, add_16_31_n_13, add_16_31_n_14, add_16_31_n_15;
  wire add_16_31_n_16, add_16_31_n_17, add_16_31_n_18, add_16_31_n_19,
       add_16_31_n_20, add_16_31_n_21, add_16_31_n_22, add_16_31_n_23;
  wire add_16_31_n_24, add_16_31_n_25, add_16_31_n_26, add_16_31_n_27,
       add_16_31_n_28, add_16_31_n_29, add_16_31_n_30, add_16_31_n_31;
  wire add_16_31_n_32, add_16_31_n_33, add_16_31_n_34, add_16_31_n_35,
       add_16_31_n_36, add_16_31_n_37, add_16_31_n_40, add_16_31_n_41;
  wire add_16_31_n_43, add_16_31_n_44, add_16_31_n_46, add_16_31_n_48,
       add_16_31_n_49, add_16_31_n_50, add_16_31_n_53, add_16_31_n_54;
  wire add_16_31_n_56, add_16_31_n_57, add_16_31_n_59, add_16_31_n_62;
  XNOR2X1 add_16_31_g279(.A (add_16_31_n_30), .B (add_16_31_n_62), .Y
       (out1[11]));
  XNOR2X1 add_16_31_g280(.A (in2[12]), .B (add_16_31_n_59), .Y
       (out1[12]));
  NOR2BX1 add_16_31_g281(.AN (in2[12]), .B (add_16_31_n_59), .Y
       (out1[13]));
  OAI21X1 add_16_31_g282(.A0 (add_16_31_n_15), .A1 (add_16_31_n_57),
       .B0 (add_16_31_n_16), .Y (add_16_31_n_62));
  XNOR2X1 add_16_31_g283(.A (add_16_31_n_29), .B (add_16_31_n_57), .Y
       (out1[10]));
  XNOR2X1 add_16_31_g284(.A (add_16_31_n_27), .B (add_16_31_n_56), .Y
       (out1[9]));
  AOI221X1 add_16_31_g285(.A0 (add_16_31_n_31), .A1 (add_16_31_n_35),
       .B0 (add_16_31_n_31), .B1 (add_16_31_n_54), .C0
       (add_16_31_n_34), .Y (add_16_31_n_59));
  XNOR2X1 add_16_31_g286(.A (add_16_31_n_24), .B (add_16_31_n_53), .Y
       (out1[7]));
  NOR2X1 add_16_31_g287(.A (add_16_31_n_35), .B (add_16_31_n_54), .Y
       (add_16_31_n_57));
  OAI21X1 add_16_31_g288(.A0 (add_16_31_n_6), .A1 (add_16_31_n_50), .B0
       (add_16_31_n_12), .Y (add_16_31_n_56));
  XNOR2X1 add_16_31_g289(.A (add_16_31_n_26), .B (add_16_31_n_50), .Y
       (out1[8]));
  NOR3X1 add_16_31_g290(.A (add_16_31_n_50), .B (add_16_31_n_8), .C
       (add_16_31_n_6), .Y (add_16_31_n_54));
  OAI21X1 add_16_31_g291(.A0 (add_16_31_n_13), .A1 (add_16_31_n_49),
       .B0 (add_16_31_n_14), .Y (add_16_31_n_53));
  XNOR2X1 add_16_31_g292(.A (add_16_31_n_22), .B (add_16_31_n_49), .Y
       (out1[6]));
  XNOR2X1 add_16_31_g293(.A (add_16_31_n_23), .B (add_16_31_n_48), .Y
       (out1[5]));
  AOI221X1 add_16_31_g294(.A0 (add_16_31_n_32), .A1 (add_16_31_n_33),
       .B0 (add_16_31_n_32), .B1 (add_16_31_n_46), .C0
       (add_16_31_n_36), .Y (add_16_31_n_50));
  NOR2X1 add_16_31_g295(.A (add_16_31_n_33), .B (add_16_31_n_46), .Y
       (add_16_31_n_49));
  OAI2BB1X1 add_16_31_g296(.A0N (add_16_31_n_2), .A1N (add_16_31_n_44),
       .B0 (add_16_31_n_7), .Y (add_16_31_n_48));
  XNOR2X1 add_16_31_g297(.A (add_16_31_n_21), .B (add_16_31_n_44), .Y
       (out1[4]));
  NOR3BX1 add_16_31_g298(.AN (add_16_31_n_44), .B (add_16_31_n_0), .C
       (add_16_31_n_1), .Y (add_16_31_n_46));
  XNOR2X1 add_16_31_g299(.A (add_16_31_n_25), .B (add_16_31_n_43), .Y
       (out1[3]));
  OAI221X1 add_16_31_g300(.A0 (add_16_31_n_5), .A1 (add_16_31_n_41),
       .B0 (add_16_31_n_4), .B1 (add_16_31_n_5), .C0 (add_16_31_n_9),
       .Y (add_16_31_n_44));
  NAND2X1 add_16_31_g301(.A (add_16_31_n_4), .B (add_16_31_n_41), .Y
       (add_16_31_n_43));
  XNOR2X1 add_16_31_g302(.A (add_16_31_n_28), .B (add_16_31_n_40), .Y
       (out1[2]));
  NAND2BX1 add_16_31_g303(.AN (add_16_31_n_18), .B (add_16_31_n_40), .Y
       (add_16_31_n_41));
  ADDFX1 add_16_31_g304(.A (add_16_31_n_37), .B (in1[1]), .CI (in2[1]),
       .CO (add_16_31_n_40), .S (out1[1]));
  ADDHX1 add_16_31_g305(.A (in2[0]), .B (in1[0]), .CO (add_16_31_n_37),
       .S (out1[0]));
  OAI21X1 add_16_31_g306(.A0 (add_16_31_n_14), .A1 (add_16_31_n_11),
       .B0 (add_16_31_n_20), .Y (add_16_31_n_36));
  OAI21X1 add_16_31_g307(.A0 (add_16_31_n_12), .A1 (add_16_31_n_8), .B0
       (add_16_31_n_19), .Y (add_16_31_n_35));
  OAI21X1 add_16_31_g308(.A0 (add_16_31_n_16), .A1 (add_16_31_n_3), .B0
       (add_16_31_n_10), .Y (add_16_31_n_34));
  OAI21X1 add_16_31_g309(.A0 (add_16_31_n_7), .A1 (add_16_31_n_0), .B0
       (add_16_31_n_17), .Y (add_16_31_n_33));
  NAND2BX1 add_16_31_g310(.AN (add_16_31_n_3), .B (add_16_31_n_10), .Y
       (add_16_31_n_30));
  NOR2X1 add_16_31_g311(.A (add_16_31_n_11), .B (add_16_31_n_13), .Y
       (add_16_31_n_32));
  NOR2BX1 add_16_31_g312(.AN (add_16_31_n_16), .B (add_16_31_n_15), .Y
       (add_16_31_n_29));
  NAND2BX1 add_16_31_g313(.AN (add_16_31_n_18), .B (add_16_31_n_4), .Y
       (add_16_31_n_28));
  NAND2BX1 add_16_31_g314(.AN (add_16_31_n_8), .B (add_16_31_n_19), .Y
       (add_16_31_n_27));
  NOR2X1 add_16_31_g315(.A (add_16_31_n_3), .B (add_16_31_n_15), .Y
       (add_16_31_n_31));
  NOR2BX1 add_16_31_g316(.AN (add_16_31_n_12), .B (add_16_31_n_6), .Y
       (add_16_31_n_26));
  NAND2BX1 add_16_31_g317(.AN (add_16_31_n_5), .B (add_16_31_n_9), .Y
       (add_16_31_n_25));
  NAND2BX1 add_16_31_g318(.AN (add_16_31_n_11), .B (add_16_31_n_20), .Y
       (add_16_31_n_24));
  NAND2BX1 add_16_31_g319(.AN (add_16_31_n_0), .B (add_16_31_n_17), .Y
       (add_16_31_n_23));
  NOR2BX1 add_16_31_g320(.AN (add_16_31_n_14), .B (add_16_31_n_13), .Y
       (add_16_31_n_22));
  NAND2X1 add_16_31_g321(.A (add_16_31_n_7), .B (add_16_31_n_2), .Y
       (add_16_31_n_21));
  NAND2X1 add_16_31_g322(.A (in2[7]), .B (in1[7]), .Y (add_16_31_n_20));
  NAND2X1 add_16_31_g323(.A (in2[9]), .B (in1[9]), .Y (add_16_31_n_19));
  NOR2X1 add_16_31_g324(.A (in2[2]), .B (in1[2]), .Y (add_16_31_n_18));
  NAND2X1 add_16_31_g325(.A (in2[5]), .B (in1[5]), .Y (add_16_31_n_17));
  NAND2X1 add_16_31_g326(.A (in2[10]), .B (in1[10]), .Y
       (add_16_31_n_16));
  NOR2X1 add_16_31_g327(.A (in2[10]), .B (in1[10]), .Y
       (add_16_31_n_15));
  NAND2X1 add_16_31_g328(.A (in2[6]), .B (in1[6]), .Y (add_16_31_n_14));
  NOR2X1 add_16_31_g329(.A (in2[6]), .B (in1[6]), .Y (add_16_31_n_13));
  NAND2X1 add_16_31_g330(.A (in2[8]), .B (in1[8]), .Y (add_16_31_n_12));
  NOR2X1 add_16_31_g331(.A (in2[7]), .B (in1[7]), .Y (add_16_31_n_11));
  INVX1 add_16_31_g332(.A (add_16_31_n_1), .Y (add_16_31_n_2));
  NAND2X1 add_16_31_g333(.A (in2[11]), .B (in1[11]), .Y
       (add_16_31_n_10));
  NAND2X1 add_16_31_g334(.A (in2[3]), .B (in1[3]), .Y (add_16_31_n_9));
  NOR2X1 add_16_31_g335(.A (in2[9]), .B (in1[9]), .Y (add_16_31_n_8));
  NAND2X1 add_16_31_g336(.A (in2[4]), .B (in1[4]), .Y (add_16_31_n_7));
  NOR2X1 add_16_31_g337(.A (in2[8]), .B (in1[8]), .Y (add_16_31_n_6));
  NOR2X1 add_16_31_g338(.A (in2[3]), .B (in1[3]), .Y (add_16_31_n_5));
  NAND2X1 add_16_31_g339(.A (in2[2]), .B (in1[2]), .Y (add_16_31_n_4));
  NOR2X1 add_16_31_g340(.A (in2[11]), .B (in1[11]), .Y (add_16_31_n_3));
  NOR2X1 add_16_31_g341(.A (in2[4]), .B (in1[4]), .Y (add_16_31_n_1));
  NOR2X1 add_16_31_g342(.A (in2[5]), .B (in1[5]), .Y (add_16_31_n_0));
endmodule


