`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:46:50 CST (Jun  9 2025 08:46:50 UTC)

module dut_LessThan_1U_71_1(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire lt_15_26_n_0, lt_15_26_n_1;
  AOI2BB2X2 lt_15_26_g125(.A0N (in1[7]), .A1N (in1[6]), .B0
       (lt_15_26_n_0), .B1 (lt_15_26_n_1), .Y (out1));
  NOR3X6 lt_15_26_g126(.A (in1[1]), .B (in1[3]), .C (in1[2]), .Y
       (lt_15_26_n_1));
  NOR3X4 lt_15_26_g127(.A (in1[7]), .B (in1[5]), .C (in1[4]), .Y
       (lt_15_26_n_0));
endmodule


