`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:45:31 CST (Jun  9 2025 08:45:31 UTC)

module dut_LessThan_1U_195_4(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire lt_15_26_n_0, lt_15_26_n_1, lt_15_26_n_2, lt_15_26_n_3;
  AOI32X1 lt_15_26_g116(.A0 (lt_15_26_n_3), .A1 (lt_15_26_n_1), .A2
       (lt_15_26_n_2), .B0 (lt_15_26_n_0), .B1 (lt_15_26_n_2), .Y
       (out1));
  OAI32X1 lt_15_26_g117(.A0 (in1[3]), .A1 (in1[1]), .A2 (in1[0]), .B0
       (in1[3]), .B1 (in1[2]), .Y (lt_15_26_n_3));
  NOR2X1 lt_15_26_g118(.A (in1[7]), .B (in1[6]), .Y (lt_15_26_n_2));
  INVX1 lt_15_26_g119(.A (in1[4]), .Y (lt_15_26_n_1));
  INVX1 lt_15_26_g120(.A (in1[5]), .Y (lt_15_26_n_0));
endmodule


