`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:44:25 CST (Jun  9 2025 08:44:25 UTC)

module dut_OrReduction_5U_1U_4(in1, out1);
  input [4:0] in1;
  output out1;
  wire [4:0] in1;
  wire out1;
  wire n_0;
  OR4X1 g8(.A (in1[3]), .B (in1[2]), .C (in1[1]), .D (n_0), .Y (out1));
  OR2XL g9(.A (in1[4]), .B (in1[0]), .Y (n_0));
endmodule


