`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:44:05 CST (Jun  9 2025 08:44:05 UTC)

module dut_Add_32Sx16U_32S_4(in2, in1, out1);
  input [31:0] in2;
  input [15:0] in1;
  output [31:0] out1;
  wire [31:0] in2;
  wire [15:0] in1;
  wire [31:0] out1;
  wire add_16_23_n_0, add_16_23_n_1, add_16_23_n_2, add_16_23_n_3,
       add_16_23_n_4, add_16_23_n_5, add_16_23_n_6, add_16_23_n_7;
  wire add_16_23_n_8, add_16_23_n_9, add_16_23_n_10, add_16_23_n_11,
       add_16_23_n_12, add_16_23_n_13, add_16_23_n_14, add_16_23_n_15;
  wire add_16_23_n_16, add_16_23_n_17, add_16_23_n_18, add_16_23_n_19,
       add_16_23_n_20, add_16_23_n_21, add_16_23_n_22, add_16_23_n_23;
  wire add_16_23_n_24, add_16_23_n_25, add_16_23_n_26, add_16_23_n_27,
       add_16_23_n_28, add_16_23_n_29, add_16_23_n_30, add_16_23_n_31;
  wire add_16_23_n_32, add_16_23_n_33, add_16_23_n_34, add_16_23_n_35,
       add_16_23_n_36, add_16_23_n_37, add_16_23_n_38, add_16_23_n_39;
  wire add_16_23_n_40, add_16_23_n_41, add_16_23_n_42, add_16_23_n_43,
       add_16_23_n_44, add_16_23_n_45, add_16_23_n_46, add_16_23_n_47;
  wire add_16_23_n_48, add_16_23_n_49, add_16_23_n_50, add_16_23_n_51,
       add_16_23_n_52, add_16_23_n_53, add_16_23_n_54, add_16_23_n_55;
  wire add_16_23_n_56, add_16_23_n_57, add_16_23_n_58, add_16_23_n_60,
       add_16_23_n_61, add_16_23_n_62, add_16_23_n_63, add_16_23_n_65;
  wire add_16_23_n_66, add_16_23_n_68, add_16_23_n_69, add_16_23_n_71,
       add_16_23_n_73, add_16_23_n_74, add_16_23_n_75, add_16_23_n_78;
  wire add_16_23_n_79, add_16_23_n_81, add_16_23_n_82, add_16_23_n_83,
       add_16_23_n_85, add_16_23_n_88, add_16_23_n_89, add_16_23_n_91;
  wire add_16_23_n_92, add_16_23_n_93, add_16_23_n_94, add_16_23_n_95,
       add_16_23_n_98, add_16_23_n_99, add_16_23_n_100, add_16_23_n_101;
  wire add_16_23_n_102, add_16_23_n_103, add_16_23_n_109,
       add_16_23_n_110, add_16_23_n_111, add_16_23_n_112,
       add_16_23_n_113, add_16_23_n_117;
  XNOR2X1 add_16_23_g687(.A (in2[31]), .B (add_16_23_n_117), .Y
       (out1[31]));
  XNOR2X1 add_16_23_g688(.A (in2[23]), .B (add_16_23_n_111), .Y
       (out1[23]));
  XNOR2X1 add_16_23_g689(.A (in2[27]), .B (add_16_23_n_112), .Y
       (out1[27]));
  XNOR2X1 add_16_23_g690(.A (in2[29]), .B (add_16_23_n_110), .Y
       (out1[29]));
  XNOR2X1 add_16_23_g691(.A (in2[25]), .B (add_16_23_n_101), .Y
       (out1[25]));
  XNOR2X1 add_16_23_g692(.A (in2[21]), .B (add_16_23_n_100), .Y
       (out1[21]));
  XNOR2X1 add_16_23_g693(.A (in2[19]), .B (add_16_23_n_99), .Y
       (out1[19]));
  XNOR2X1 add_16_23_g694(.A (in2[30]), .B (add_16_23_n_113), .Y
       (out1[30]));
  XNOR2X1 add_16_23_g695(.A (in2[17]), .B (add_16_23_n_0), .Y
       (out1[17]));
  XNOR2X1 add_16_23_g696(.A (add_16_23_n_40), .B (add_16_23_n_109), .Y
       (out1[15]));
  NAND2BX1 add_16_23_g697(.AN (add_16_23_n_113), .B (in2[30]), .Y
       (add_16_23_n_117));
  XNOR2X1 add_16_23_g698(.A (in2[28]), .B (add_16_23_n_98), .Y
       (out1[28]));
  XNOR2X1 add_16_23_g699(.A (in2[22]), .B (add_16_23_n_102), .Y
       (out1[22]));
  XNOR2X1 add_16_23_g700(.A (in2[26]), .B (add_16_23_n_103), .Y
       (out1[26]));
  NAND2BX1 add_16_23_g701(.AN (add_16_23_n_103), .B (in2[26]), .Y
       (add_16_23_n_112));
  NAND2BX1 add_16_23_g702(.AN (add_16_23_n_102), .B (in2[22]), .Y
       (add_16_23_n_111));
  NAND2BX1 add_16_23_g703(.AN (add_16_23_n_98), .B (in2[28]), .Y
       (add_16_23_n_110));
  OAI21X1 add_16_23_g704(.A0 (add_16_23_n_6), .A1 (add_16_23_n_93), .B0
       (add_16_23_n_1), .Y (add_16_23_n_109));
  NAND3BXL add_16_23_g705(.AN (add_16_23_n_98), .B (in2[29]), .C
       (in2[28]), .Y (add_16_23_n_113));
  XOR2XL add_16_23_g706(.A (in2[24]), .B (add_16_23_n_91), .Y
       (out1[24]));
  XNOR2X1 add_16_23_g707(.A (add_16_23_n_44), .B (add_16_23_n_92), .Y
       (out1[13]));
  XNOR2X1 add_16_23_g708(.A (add_16_23_n_38), .B (add_16_23_n_93), .Y
       (out1[14]));
  XOR2XL add_16_23_g709(.A (in2[20]), .B (add_16_23_n_95), .Y
       (out1[20]));
  XOR2XL add_16_23_g710(.A (in2[18]), .B (add_16_23_n_94), .Y
       (out1[18]));
  NAND2BX1 add_16_23_g711(.AN (add_16_23_n_31), .B (add_16_23_n_91), .Y
       (add_16_23_n_103));
  NAND2BX1 add_16_23_g712(.AN (add_16_23_n_17), .B (add_16_23_n_95), .Y
       (add_16_23_n_102));
  NAND2X1 add_16_23_g713(.A (in2[24]), .B (add_16_23_n_91), .Y
       (add_16_23_n_101));
  NAND2X1 add_16_23_g714(.A (in2[20]), .B (add_16_23_n_95), .Y
       (add_16_23_n_100));
  NAND2X1 add_16_23_g715(.A (in2[18]), .B (add_16_23_n_94), .Y
       (add_16_23_n_99));
  NAND4BX1 add_16_23_g716(.AN (add_16_23_n_31), .B (add_16_23_n_91), .C
       (in2[27]), .D (in2[26]), .Y (add_16_23_n_98));
  XNOR2X1 add_16_23_g717(.A (in2[16]), .B (add_16_23_n_88), .Y
       (out1[16]));
  XNOR2X1 add_16_23_g718(.A (add_16_23_n_37), .B (add_16_23_n_89), .Y
       (out1[11]));
  NOR2X1 add_16_23_g719(.A (add_16_23_n_42), .B (add_16_23_n_88), .Y
       (add_16_23_n_95));
  NOR2X1 add_16_23_g720(.A (add_16_23_n_33), .B (add_16_23_n_88), .Y
       (add_16_23_n_94));
  AOI21X1 add_16_23_g722(.A0 (add_16_23_n_50), .A1 (add_16_23_n_85),
       .B0 (add_16_23_n_55), .Y (add_16_23_n_93));
  OAI2BB1X1 add_16_23_g723(.A0N (add_16_23_n_26), .A1N
       (add_16_23_n_85), .B0 (add_16_23_n_3), .Y (add_16_23_n_92));
  NOR4X1 add_16_23_g724(.A (add_16_23_n_88), .B (add_16_23_n_42), .C
       (add_16_23_n_18), .D (add_16_23_n_17), .Y (add_16_23_n_91));
  XNOR2X1 add_16_23_g725(.A (add_16_23_n_41), .B (add_16_23_n_85), .Y
       (out1[12]));
  OAI21X1 add_16_23_g726(.A0 (add_16_23_n_9), .A1 (add_16_23_n_82), .B0
       (add_16_23_n_19), .Y (add_16_23_n_89));
  AOI221X1 add_16_23_g728(.A0 (add_16_23_n_57), .A1 (add_16_23_n_62),
       .B0 (add_16_23_n_57), .B1 (add_16_23_n_83), .C0
       (add_16_23_n_63), .Y (add_16_23_n_88));
  XNOR2X1 add_16_23_g729(.A (add_16_23_n_46), .B (add_16_23_n_82), .Y
       (out1[10]));
  XNOR2X1 add_16_23_g730(.A (add_16_23_n_39), .B (add_16_23_n_81), .Y
       (out1[9]));
  OR2X1 add_16_23_g731(.A (add_16_23_n_62), .B (add_16_23_n_83), .Y
       (add_16_23_n_85));
  XNOR2X1 add_16_23_g732(.A (add_16_23_n_35), .B (add_16_23_n_78), .Y
       (out1[7]));
  AND2XL add_16_23_g733(.A (add_16_23_n_52), .B (add_16_23_n_79), .Y
       (add_16_23_n_83));
  NOR2X1 add_16_23_g734(.A (add_16_23_n_56), .B (add_16_23_n_79), .Y
       (add_16_23_n_82));
  OAI21X1 add_16_23_g735(.A0 (add_16_23_n_4), .A1 (add_16_23_n_75), .B0
       (add_16_23_n_21), .Y (add_16_23_n_81));
  XNOR2X1 add_16_23_g736(.A (add_16_23_n_36), .B (add_16_23_n_75), .Y
       (out1[8]));
  NOR3X1 add_16_23_g737(.A (add_16_23_n_75), .B (add_16_23_n_22), .C
       (add_16_23_n_4), .Y (add_16_23_n_79));
  OAI21X1 add_16_23_g738(.A0 (add_16_23_n_23), .A1 (add_16_23_n_74),
       .B0 (add_16_23_n_2), .Y (add_16_23_n_78));
  XNOR2X1 add_16_23_g739(.A (add_16_23_n_34), .B (add_16_23_n_74), .Y
       (out1[6]));
  XNOR2X1 add_16_23_g740(.A (add_16_23_n_47), .B (add_16_23_n_73), .Y
       (out1[5]));
  AOI221X1 add_16_23_g741(.A0 (add_16_23_n_43), .A1 (add_16_23_n_54),
       .B0 (add_16_23_n_43), .B1 (add_16_23_n_71), .C0
       (add_16_23_n_53), .Y (add_16_23_n_75));
  NOR2X1 add_16_23_g742(.A (add_16_23_n_54), .B (add_16_23_n_71), .Y
       (add_16_23_n_74));
  OAI2BB1X1 add_16_23_g743(.A0N (add_16_23_n_13), .A1N
       (add_16_23_n_69), .B0 (add_16_23_n_11), .Y (add_16_23_n_73));
  XNOR2X1 add_16_23_g744(.A (add_16_23_n_49), .B (add_16_23_n_69), .Y
       (out1[4]));
  NOR3BX1 add_16_23_g745(.AN (add_16_23_n_69), .B (add_16_23_n_20), .C
       (add_16_23_n_12), .Y (add_16_23_n_71));
  XNOR2X1 add_16_23_g746(.A (add_16_23_n_48), .B (add_16_23_n_68), .Y
       (out1[3]));
  OAI221X1 add_16_23_g747(.A0 (add_16_23_n_10), .A1 (add_16_23_n_66),
       .B0 (add_16_23_n_25), .B1 (add_16_23_n_10), .C0
       (add_16_23_n_28), .Y (add_16_23_n_69));
  NAND2X1 add_16_23_g748(.A (add_16_23_n_25), .B (add_16_23_n_66), .Y
       (add_16_23_n_68));
  XNOR2X1 add_16_23_g749(.A (add_16_23_n_45), .B (add_16_23_n_65), .Y
       (out1[2]));
  NAND2BX1 add_16_23_g750(.AN (add_16_23_n_32), .B (add_16_23_n_65), .Y
       (add_16_23_n_66));
  ADDFX1 add_16_23_g751(.A (add_16_23_n_58), .B (in1[1]), .CI (in2[1]),
       .CO (add_16_23_n_65), .S (out1[1]));
  OAI211X1 add_16_23_g752(.A0 (add_16_23_n_1), .A1 (add_16_23_n_7), .B0
       (add_16_23_n_60), .C0 (add_16_23_n_30), .Y (add_16_23_n_63));
  OAI211X1 add_16_23_g753(.A0 (add_16_23_n_19), .A1 (add_16_23_n_24),
       .B0 (add_16_23_n_61), .C0 (add_16_23_n_15), .Y (add_16_23_n_62));
  NAND2X1 add_16_23_g754(.A (add_16_23_n_52), .B (add_16_23_n_56), .Y
       (add_16_23_n_61));
  NAND2X1 add_16_23_g755(.A (add_16_23_n_51), .B (add_16_23_n_55), .Y
       (add_16_23_n_60));
  ADDHX1 add_16_23_g756(.A (in2[0]), .B (in1[0]), .CO (add_16_23_n_58),
       .S (out1[0]));
  AND2X1 add_16_23_g757(.A (add_16_23_n_51), .B (add_16_23_n_50), .Y
       (add_16_23_n_57));
  OAI21X1 add_16_23_g758(.A0 (add_16_23_n_21), .A1 (add_16_23_n_22),
       .B0 (add_16_23_n_29), .Y (add_16_23_n_56));
  OAI21X1 add_16_23_g759(.A0 (add_16_23_n_3), .A1 (add_16_23_n_8), .B0
       (add_16_23_n_27), .Y (add_16_23_n_55));
  OAI21X1 add_16_23_g760(.A0 (add_16_23_n_11), .A1 (add_16_23_n_20),
       .B0 (add_16_23_n_14), .Y (add_16_23_n_54));
  OAI21X1 add_16_23_g761(.A0 (add_16_23_n_2), .A1 (add_16_23_n_5), .B0
       (add_16_23_n_16), .Y (add_16_23_n_53));
  NAND2X1 add_16_23_g762(.A (add_16_23_n_11), .B (add_16_23_n_13), .Y
       (add_16_23_n_49));
  NAND2BX1 add_16_23_g763(.AN (add_16_23_n_10), .B (add_16_23_n_28), .Y
       (add_16_23_n_48));
  NOR2X1 add_16_23_g764(.A (add_16_23_n_24), .B (add_16_23_n_9), .Y
       (add_16_23_n_52));
  NAND2BX1 add_16_23_g765(.AN (add_16_23_n_20), .B (add_16_23_n_14), .Y
       (add_16_23_n_47));
  NOR2BX1 add_16_23_g766(.AN (add_16_23_n_19), .B (add_16_23_n_9), .Y
       (add_16_23_n_46));
  NAND2BX1 add_16_23_g767(.AN (add_16_23_n_32), .B (add_16_23_n_25), .Y
       (add_16_23_n_45));
  NOR2X1 add_16_23_g768(.A (add_16_23_n_7), .B (add_16_23_n_6), .Y
       (add_16_23_n_51));
  NAND2BX1 add_16_23_g769(.AN (add_16_23_n_8), .B (add_16_23_n_27), .Y
       (add_16_23_n_44));
  NOR2BX1 add_16_23_g770(.AN (add_16_23_n_26), .B (add_16_23_n_8), .Y
       (add_16_23_n_50));
  NAND2X1 add_16_23_g771(.A (add_16_23_n_3), .B (add_16_23_n_26), .Y
       (add_16_23_n_41));
  NAND2BX1 add_16_23_g772(.AN (add_16_23_n_7), .B (add_16_23_n_30), .Y
       (add_16_23_n_40));
  NAND2BX1 add_16_23_g773(.AN (add_16_23_n_22), .B (add_16_23_n_29), .Y
       (add_16_23_n_39));
  NOR2BX1 add_16_23_g774(.AN (add_16_23_n_1), .B (add_16_23_n_6), .Y
       (add_16_23_n_38));
  NOR2X1 add_16_23_g775(.A (add_16_23_n_5), .B (add_16_23_n_23), .Y
       (add_16_23_n_43));
  NAND2BX1 add_16_23_g776(.AN (add_16_23_n_24), .B (add_16_23_n_15), .Y
       (add_16_23_n_37));
  NOR2BX1 add_16_23_g777(.AN (add_16_23_n_21), .B (add_16_23_n_4), .Y
       (add_16_23_n_36));
  NAND2BX1 add_16_23_g778(.AN (add_16_23_n_5), .B (add_16_23_n_16), .Y
       (add_16_23_n_35));
  NOR2BX1 add_16_23_g779(.AN (add_16_23_n_2), .B (add_16_23_n_23), .Y
       (add_16_23_n_34));
  NAND3BXL add_16_23_g780(.AN (add_16_23_n_33), .B (in2[19]), .C
       (in2[18]), .Y (add_16_23_n_42));
  NAND2X1 add_16_23_g781(.A (in2[23]), .B (in2[22]), .Y
       (add_16_23_n_18));
  NAND2X1 add_16_23_g782(.A (in2[17]), .B (in2[16]), .Y
       (add_16_23_n_33));
  NOR2X1 add_16_23_g783(.A (in2[2]), .B (in1[2]), .Y (add_16_23_n_32));
  NAND2X1 add_16_23_g784(.A (in2[25]), .B (in2[24]), .Y
       (add_16_23_n_31));
  NAND2X1 add_16_23_g785(.A (in2[15]), .B (in1[15]), .Y
       (add_16_23_n_30));
  NAND2X1 add_16_23_g786(.A (in2[9]), .B (in1[9]), .Y (add_16_23_n_29));
  NAND2X1 add_16_23_g787(.A (in2[3]), .B (in1[3]), .Y (add_16_23_n_28));
  NAND2X1 add_16_23_g788(.A (in2[13]), .B (in1[13]), .Y
       (add_16_23_n_27));
  OR2X1 add_16_23_g789(.A (in2[12]), .B (in1[12]), .Y (add_16_23_n_26));
  NAND2X1 add_16_23_g790(.A (in2[2]), .B (in1[2]), .Y (add_16_23_n_25));
  NOR2X1 add_16_23_g791(.A (in2[11]), .B (in1[11]), .Y
       (add_16_23_n_24));
  NOR2X1 add_16_23_g792(.A (in2[6]), .B (in1[6]), .Y (add_16_23_n_23));
  NOR2X1 add_16_23_g793(.A (in2[9]), .B (in1[9]), .Y (add_16_23_n_22));
  NAND2X1 add_16_23_g794(.A (in2[8]), .B (in1[8]), .Y (add_16_23_n_21));
  NOR2X1 add_16_23_g795(.A (in2[5]), .B (in1[5]), .Y (add_16_23_n_20));
  NAND2X1 add_16_23_g796(.A (in2[10]), .B (in1[10]), .Y
       (add_16_23_n_19));
  INVX1 add_16_23_g797(.A (add_16_23_n_12), .Y (add_16_23_n_13));
  NAND2X1 add_16_23_g798(.A (in2[21]), .B (in2[20]), .Y
       (add_16_23_n_17));
  NAND2X1 add_16_23_g799(.A (in2[7]), .B (in1[7]), .Y (add_16_23_n_16));
  NAND2X1 add_16_23_g800(.A (in2[11]), .B (in1[11]), .Y
       (add_16_23_n_15));
  NAND2X1 add_16_23_g801(.A (in2[5]), .B (in1[5]), .Y (add_16_23_n_14));
  NOR2X1 add_16_23_g802(.A (in2[4]), .B (in1[4]), .Y (add_16_23_n_12));
  NAND2X1 add_16_23_g803(.A (in2[4]), .B (in1[4]), .Y (add_16_23_n_11));
  NOR2X1 add_16_23_g804(.A (in2[3]), .B (in1[3]), .Y (add_16_23_n_10));
  NOR2X1 add_16_23_g805(.A (in2[10]), .B (in1[10]), .Y (add_16_23_n_9));
  NOR2X1 add_16_23_g806(.A (in2[13]), .B (in1[13]), .Y (add_16_23_n_8));
  NOR2X1 add_16_23_g807(.A (in2[15]), .B (in1[15]), .Y (add_16_23_n_7));
  NOR2X1 add_16_23_g808(.A (in2[14]), .B (in1[14]), .Y (add_16_23_n_6));
  NOR2X1 add_16_23_g809(.A (in2[7]), .B (in1[7]), .Y (add_16_23_n_5));
  NOR2X1 add_16_23_g810(.A (in2[8]), .B (in1[8]), .Y (add_16_23_n_4));
  NAND2X1 add_16_23_g811(.A (in2[12]), .B (in1[12]), .Y
       (add_16_23_n_3));
  NAND2X1 add_16_23_g812(.A (in2[6]), .B (in1[6]), .Y (add_16_23_n_2));
  NAND2X1 add_16_23_g813(.A (in2[14]), .B (in1[14]), .Y
       (add_16_23_n_1));
  NAND2BX1 add_16_23_g2(.AN (add_16_23_n_88), .B (in2[16]), .Y
       (add_16_23_n_0));
endmodule


