`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  4 2025 00:51:20 CST (Jun  3 2025 16:51:20 UTC)

module dut_Equal_7Ux1U_1U_1(in2, in1, out1);
  input [6:0] in2;
  input in1;
  output out1;
  wire [6:0] in2;
  wire in1;
  wire out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  NOR3X2 g45(.A (in2[1]), .B (n_6), .C (n_7), .Y (out1));
  NAND2X2 g46(.A (n_3), .B (n_4), .Y (n_7));
  NOR2X1 g48(.A (n_2), .B (n_5), .Y (n_6));
  NOR2X2 g50(.A (n_1), .B (n_0), .Y (n_5));
  NOR3X6 g47(.A (in2[6]), .B (in2[3]), .C (in2[2]), .Y (n_4));
  NOR2X1 g51(.A (in2[5]), .B (in2[4]), .Y (n_3));
  NOR2X1 g49(.A (in2[0]), .B (in1), .Y (n_2));
  CLKINVX2 g52(.A (in2[0]), .Y (n_1));
  INVX1 g53(.A (in1), .Y (n_0));
endmodule


