`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:44:07 CST (Jun  9 2025 08:44:07 UTC)

module dut_Add_16Ux14U_16U_4(in2, in1, out1);
  input [15:0] in2;
  input [13:0] in1;
  output [15:0] out1;
  wire [15:0] in2;
  wire [13:0] in1;
  wire [15:0] out1;
  wire add_16_23_n_0, add_16_23_n_1, add_16_23_n_2, add_16_23_n_3,
       add_16_23_n_4, add_16_23_n_5, add_16_23_n_6, add_16_23_n_7;
  wire add_16_23_n_8, add_16_23_n_9, add_16_23_n_10, add_16_23_n_11,
       add_16_23_n_12, add_16_23_n_13, add_16_23_n_14, add_16_23_n_15;
  wire add_16_23_n_16, add_16_23_n_17, add_16_23_n_18, add_16_23_n_19,
       add_16_23_n_20, add_16_23_n_21, add_16_23_n_22, add_16_23_n_23;
  wire add_16_23_n_24, add_16_23_n_25, add_16_23_n_26, add_16_23_n_27,
       add_16_23_n_28, add_16_23_n_29, add_16_23_n_30, add_16_23_n_31;
  wire add_16_23_n_32, add_16_23_n_33, add_16_23_n_34, add_16_23_n_35,
       add_16_23_n_36, add_16_23_n_37, add_16_23_n_38, add_16_23_n_39;
  wire add_16_23_n_40, add_16_23_n_41, add_16_23_n_42, add_16_23_n_43,
       add_16_23_n_46, add_16_23_n_47, add_16_23_n_49, add_16_23_n_50;
  wire add_16_23_n_52, add_16_23_n_54, add_16_23_n_55, add_16_23_n_56,
       add_16_23_n_59, add_16_23_n_60, add_16_23_n_62, add_16_23_n_63;
  wire add_16_23_n_65, add_16_23_n_68, add_16_23_n_69, add_16_23_n_71,
       add_16_23_n_73, add_16_23_n_75;
  XNOR2X1 add_16_23_g343(.A (in2[15]), .B (add_16_23_n_75), .Y
       (out1[15]));
  XOR2XL add_16_23_g344(.A (in2[14]), .B (add_16_23_n_73), .Y
       (out1[14]));
  NAND2X1 add_16_23_g345(.A (in2[14]), .B (add_16_23_n_73), .Y
       (add_16_23_n_75));
  XNOR2X1 add_16_23_g346(.A (add_16_23_n_33), .B (add_16_23_n_71), .Y
       (out1[13]));
  OAI221X1 add_16_23_g347(.A0 (add_16_23_n_15), .A1 (add_16_23_n_69),
       .B0 (add_16_23_n_2), .B1 (add_16_23_n_15), .C0 (add_16_23_n_9),
       .Y (add_16_23_n_73));
  XNOR2X1 add_16_23_g348(.A (add_16_23_n_28), .B (add_16_23_n_68), .Y
       (out1[11]));
  NAND2XL add_16_23_g349(.A (add_16_23_n_2), .B (add_16_23_n_69), .Y
       (add_16_23_n_71));
  XNOR2X1 add_16_23_g350(.A (add_16_23_n_38), .B (add_16_23_n_65), .Y
       (out1[12]));
  OR2XL add_16_23_g351(.A (add_16_23_n_11), .B (add_16_23_n_65), .Y
       (add_16_23_n_69));
  OAI21X1 add_16_23_g352(.A0 (add_16_23_n_6), .A1 (add_16_23_n_63), .B0
       (add_16_23_n_8), .Y (add_16_23_n_68));
  XNOR2X1 add_16_23_g353(.A (add_16_23_n_36), .B (add_16_23_n_63), .Y
       (out1[10]));
  XNOR2X1 add_16_23_g354(.A (add_16_23_n_27), .B (add_16_23_n_62), .Y
       (out1[9]));
  AOI221X1 add_16_23_g355(.A0 (add_16_23_n_30), .A1 (add_16_23_n_42),
       .B0 (add_16_23_n_30), .B1 (add_16_23_n_59), .C0
       (add_16_23_n_41), .Y (add_16_23_n_65));
  XNOR2X1 add_16_23_g356(.A (add_16_23_n_37), .B (add_16_23_n_60), .Y
       (out1[7]));
  NOR2X1 add_16_23_g357(.A (add_16_23_n_42), .B (add_16_23_n_59), .Y
       (add_16_23_n_63));
  OAI21X1 add_16_23_g358(.A0 (add_16_23_n_7), .A1 (add_16_23_n_56), .B0
       (add_16_23_n_13), .Y (add_16_23_n_62));
  XNOR2X1 add_16_23_g359(.A (add_16_23_n_29), .B (add_16_23_n_56), .Y
       (out1[8]));
  OAI21X1 add_16_23_g360(.A0 (add_16_23_n_19), .A1 (add_16_23_n_55),
       .B0 (add_16_23_n_5), .Y (add_16_23_n_60));
  NOR3X1 add_16_23_g361(.A (add_16_23_n_56), .B (add_16_23_n_20), .C
       (add_16_23_n_7), .Y (add_16_23_n_59));
  XNOR2X1 add_16_23_g362(.A (add_16_23_n_32), .B (add_16_23_n_55), .Y
       (out1[6]));
  XNOR2X1 add_16_23_g363(.A (add_16_23_n_26), .B (add_16_23_n_54), .Y
       (out1[5]));
  AOI221X1 add_16_23_g364(.A0 (add_16_23_n_31), .A1 (add_16_23_n_39),
       .B0 (add_16_23_n_31), .B1 (add_16_23_n_52), .C0
       (add_16_23_n_40), .Y (add_16_23_n_56));
  NOR2X1 add_16_23_g365(.A (add_16_23_n_39), .B (add_16_23_n_52), .Y
       (add_16_23_n_55));
  OAI2BB1X1 add_16_23_g366(.A0N (add_16_23_n_1), .A1N (add_16_23_n_50),
       .B0 (add_16_23_n_18), .Y (add_16_23_n_54));
  XNOR2X1 add_16_23_g367(.A (add_16_23_n_25), .B (add_16_23_n_50), .Y
       (out1[4]));
  NOR3BX1 add_16_23_g368(.AN (add_16_23_n_50), .B (add_16_23_n_17), .C
       (add_16_23_n_0), .Y (add_16_23_n_52));
  XNOR2X1 add_16_23_g369(.A (add_16_23_n_35), .B (add_16_23_n_49), .Y
       (out1[3]));
  OAI221X1 add_16_23_g370(.A0 (add_16_23_n_14), .A1 (add_16_23_n_47),
       .B0 (add_16_23_n_4), .B1 (add_16_23_n_14), .C0 (add_16_23_n_21),
       .Y (add_16_23_n_50));
  NAND2X1 add_16_23_g371(.A (add_16_23_n_4), .B (add_16_23_n_47), .Y
       (add_16_23_n_49));
  XNOR2X1 add_16_23_g372(.A (add_16_23_n_34), .B (add_16_23_n_46), .Y
       (out1[2]));
  NAND2BX1 add_16_23_g373(.AN (add_16_23_n_22), .B (add_16_23_n_46), .Y
       (add_16_23_n_47));
  ADDFX1 add_16_23_g374(.A (add_16_23_n_43), .B (in1[1]), .CI (in2[1]),
       .CO (add_16_23_n_46), .S (out1[1]));
  ADDHX1 add_16_23_g375(.A (in2[0]), .B (in1[0]), .CO (add_16_23_n_43),
       .S (out1[0]));
  OAI21X1 add_16_23_g376(.A0 (add_16_23_n_13), .A1 (add_16_23_n_20),
       .B0 (add_16_23_n_23), .Y (add_16_23_n_42));
  OAI21X1 add_16_23_g377(.A0 (add_16_23_n_8), .A1 (add_16_23_n_3), .B0
       (add_16_23_n_12), .Y (add_16_23_n_41));
  OAI21X1 add_16_23_g378(.A0 (add_16_23_n_5), .A1 (add_16_23_n_16), .B0
       (add_16_23_n_10), .Y (add_16_23_n_40));
  OAI21X1 add_16_23_g379(.A0 (add_16_23_n_18), .A1 (add_16_23_n_17),
       .B0 (add_16_23_n_24), .Y (add_16_23_n_39));
  NOR2BX1 add_16_23_g380(.AN (add_16_23_n_2), .B (add_16_23_n_11), .Y
       (add_16_23_n_38));
  NAND2BX1 add_16_23_g381(.AN (add_16_23_n_16), .B (add_16_23_n_10), .Y
       (add_16_23_n_37));
  NOR2BX1 add_16_23_g382(.AN (add_16_23_n_8), .B (add_16_23_n_6), .Y
       (add_16_23_n_36));
  NAND2BX1 add_16_23_g383(.AN (add_16_23_n_14), .B (add_16_23_n_21), .Y
       (add_16_23_n_35));
  NAND2BX1 add_16_23_g384(.AN (add_16_23_n_22), .B (add_16_23_n_4), .Y
       (add_16_23_n_34));
  NAND2BX1 add_16_23_g385(.AN (add_16_23_n_15), .B (add_16_23_n_9), .Y
       (add_16_23_n_33));
  NOR2BX1 add_16_23_g386(.AN (add_16_23_n_5), .B (add_16_23_n_19), .Y
       (add_16_23_n_32));
  NOR2BX1 add_16_23_g387(.AN (add_16_23_n_13), .B (add_16_23_n_7), .Y
       (add_16_23_n_29));
  NAND2BX1 add_16_23_g388(.AN (add_16_23_n_3), .B (add_16_23_n_12), .Y
       (add_16_23_n_28));
  NOR2X1 add_16_23_g389(.A (add_16_23_n_16), .B (add_16_23_n_19), .Y
       (add_16_23_n_31));
  NAND2BX1 add_16_23_g390(.AN (add_16_23_n_20), .B (add_16_23_n_23), .Y
       (add_16_23_n_27));
  NAND2BX1 add_16_23_g391(.AN (add_16_23_n_17), .B (add_16_23_n_24), .Y
       (add_16_23_n_26));
  NOR2X1 add_16_23_g392(.A (add_16_23_n_3), .B (add_16_23_n_6), .Y
       (add_16_23_n_30));
  NAND2X1 add_16_23_g393(.A (add_16_23_n_18), .B (add_16_23_n_1), .Y
       (add_16_23_n_25));
  NAND2X1 add_16_23_g394(.A (in2[5]), .B (in1[5]), .Y (add_16_23_n_24));
  NAND2X1 add_16_23_g395(.A (in2[9]), .B (in1[9]), .Y (add_16_23_n_23));
  NOR2X1 add_16_23_g396(.A (in2[2]), .B (in1[2]), .Y (add_16_23_n_22));
  NAND2X1 add_16_23_g397(.A (in2[3]), .B (in1[3]), .Y (add_16_23_n_21));
  NOR2X1 add_16_23_g398(.A (in2[9]), .B (in1[9]), .Y (add_16_23_n_20));
  NOR2X1 add_16_23_g399(.A (in2[6]), .B (in1[6]), .Y (add_16_23_n_19));
  NAND2X1 add_16_23_g400(.A (in2[4]), .B (in1[4]), .Y (add_16_23_n_18));
  NOR2X1 add_16_23_g401(.A (in2[5]), .B (in1[5]), .Y (add_16_23_n_17));
  NOR2X1 add_16_23_g402(.A (in2[7]), .B (in1[7]), .Y (add_16_23_n_16));
  NOR2X1 add_16_23_g403(.A (in2[13]), .B (in1[13]), .Y
       (add_16_23_n_15));
  NOR2X1 add_16_23_g404(.A (in2[3]), .B (in1[3]), .Y (add_16_23_n_14));
  NAND2X1 add_16_23_g405(.A (in2[8]), .B (in1[8]), .Y (add_16_23_n_13));
  INVX1 add_16_23_g406(.A (add_16_23_n_0), .Y (add_16_23_n_1));
  NAND2X1 add_16_23_g407(.A (in2[11]), .B (in1[11]), .Y
       (add_16_23_n_12));
  NOR2X1 add_16_23_g408(.A (in2[12]), .B (in1[12]), .Y
       (add_16_23_n_11));
  NAND2X1 add_16_23_g409(.A (in2[7]), .B (in1[7]), .Y (add_16_23_n_10));
  NAND2X1 add_16_23_g410(.A (in2[13]), .B (in1[13]), .Y
       (add_16_23_n_9));
  NAND2X1 add_16_23_g411(.A (in2[10]), .B (in1[10]), .Y
       (add_16_23_n_8));
  NOR2X1 add_16_23_g412(.A (in2[8]), .B (in1[8]), .Y (add_16_23_n_7));
  NOR2X1 add_16_23_g413(.A (in2[10]), .B (in1[10]), .Y (add_16_23_n_6));
  NAND2X1 add_16_23_g414(.A (in2[6]), .B (in1[6]), .Y (add_16_23_n_5));
  NAND2X1 add_16_23_g415(.A (in2[2]), .B (in1[2]), .Y (add_16_23_n_4));
  NOR2X1 add_16_23_g416(.A (in2[11]), .B (in1[11]), .Y (add_16_23_n_3));
  NAND2X1 add_16_23_g417(.A (in2[12]), .B (in1[12]), .Y
       (add_16_23_n_2));
  NOR2X1 add_16_23_g418(.A (in2[4]), .B (in1[4]), .Y (add_16_23_n_0));
endmodule


