`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:46:25 CST (Jun  9 2025 08:46:25 UTC)

module dut_LessThanEQ_16Ux16U_1U_1(in2, in1, out1);
  input [15:0] in2, in1;
  output out1;
  wire [15:0] in2, in1;
  wire out1;
  wire lte_16_23_n_0, lte_16_23_n_1, lte_16_23_n_2, lte_16_23_n_3,
       lte_16_23_n_4, lte_16_23_n_5, lte_16_23_n_6, lte_16_23_n_7;
  wire lte_16_23_n_8, lte_16_23_n_9, lte_16_23_n_10, lte_16_23_n_11,
       lte_16_23_n_12, lte_16_23_n_13, lte_16_23_n_14, lte_16_23_n_15;
  wire lte_16_23_n_16, lte_16_23_n_17, lte_16_23_n_18, lte_16_23_n_19,
       lte_16_23_n_20, lte_16_23_n_21, lte_16_23_n_22, lte_16_23_n_23;
  wire lte_16_23_n_24, lte_16_23_n_25, lte_16_23_n_26, lte_16_23_n_27,
       lte_16_23_n_28, lte_16_23_n_29, lte_16_23_n_30, lte_16_23_n_31;
  wire lte_16_23_n_32, lte_16_23_n_33, lte_16_23_n_34, lte_16_23_n_35,
       lte_16_23_n_36, lte_16_23_n_37, lte_16_23_n_38, lte_16_23_n_39;
  wire lte_16_23_n_40, lte_16_23_n_41, lte_16_23_n_42, lte_16_23_n_43,
       lte_16_23_n_44, lte_16_23_n_45, lte_16_23_n_46, lte_16_23_n_47;
  wire lte_16_23_n_48, lte_16_23_n_49, lte_16_23_n_50, lte_16_23_n_51,
       lte_16_23_n_52, lte_16_23_n_53, lte_16_23_n_54, lte_16_23_n_55;
  wire lte_16_23_n_56, lte_16_23_n_57;
  OAI21X1 lte_16_23_g316(.A0 (lte_16_23_n_51), .A1 (lte_16_23_n_57),
       .B0 (lte_16_23_n_56), .Y (out1));
  AOI21X1 lte_16_23_g317(.A0 (lte_16_23_n_42), .A1 (lte_16_23_n_55),
       .B0 (lte_16_23_n_52), .Y (lte_16_23_n_57));
  AOI2BB1X1 lte_16_23_g318(.A0N (lte_16_23_n_41), .A1N
       (lte_16_23_n_53), .B0 (lte_16_23_n_54), .Y (lte_16_23_n_56));
  NAND2X1 lte_16_23_g319(.A (lte_16_23_n_50), .B (lte_16_23_n_45), .Y
       (lte_16_23_n_55));
  OAI21X1 lte_16_23_g320(.A0 (lte_16_23_n_35), .A1 (lte_16_23_n_49),
       .B0 (lte_16_23_n_47), .Y (lte_16_23_n_54));
  AOI21X1 lte_16_23_g321(.A0 (lte_16_23_n_37), .A1 (lte_16_23_n_46),
       .B0 (lte_16_23_n_43), .Y (lte_16_23_n_53));
  OAI21X1 lte_16_23_g322(.A0 (lte_16_23_n_39), .A1 (lte_16_23_n_48),
       .B0 (lte_16_23_n_44), .Y (lte_16_23_n_52));
  OR2XL lte_16_23_g323(.A (lte_16_23_n_41), .B (lte_16_23_n_40), .Y
       (lte_16_23_n_51));
  OAI21X1 lte_16_23_g324(.A0 (lte_16_23_n_20), .A1 (lte_16_23_n_32),
       .B0 (lte_16_23_n_36), .Y (lte_16_23_n_50));
  AOI31X1 lte_16_23_g325(.A0 (lte_16_23_n_1), .A1 (in1[12]), .A2
       (lte_16_23_n_14), .B0 (lte_16_23_n_25), .Y (lte_16_23_n_49));
  AOI22X1 lte_16_23_g326(.A0 (lte_16_23_n_26), .A1 (lte_16_23_n_0), .B0
       (in1[5]), .B1 (lte_16_23_n_11), .Y (lte_16_23_n_48));
  AOI31X1 lte_16_23_g327(.A0 (lte_16_23_n_9), .A1 (in1[14]), .A2
       (lte_16_23_n_4), .B0 (lte_16_23_n_27), .Y (lte_16_23_n_47));
  NAND2X1 lte_16_23_g328(.A (lte_16_23_n_24), .B (lte_16_23_n_33), .Y
       (lte_16_23_n_46));
  AOI22X1 lte_16_23_g329(.A0 (lte_16_23_n_22), .A1 (lte_16_23_n_31),
       .B0 (in1[3]), .B1 (lte_16_23_n_13), .Y (lte_16_23_n_45));
  AOI31X1 lte_16_23_g330(.A0 (lte_16_23_n_28), .A1 (in1[6]), .A2
       (lte_16_23_n_7), .B0 (lte_16_23_n_19), .Y (lte_16_23_n_44));
  NAND2X1 lte_16_23_g331(.A (lte_16_23_n_23), .B (lte_16_23_n_34), .Y
       (lte_16_23_n_43));
  NOR2X1 lte_16_23_g332(.A (lte_16_23_n_39), .B (lte_16_23_n_38), .Y
       (lte_16_23_n_42));
  NAND2BX1 lte_16_23_g333(.AN (lte_16_23_n_35), .B (lte_16_23_n_6), .Y
       (lte_16_23_n_41));
  NAND3X1 lte_16_23_g334(.A (lte_16_23_n_18), .B (lte_16_23_n_2), .C
       (lte_16_23_n_37), .Y (lte_16_23_n_40));
  OAI21X1 lte_16_23_g335(.A0 (lte_16_23_n_7), .A1 (in1[6]), .B0
       (lte_16_23_n_28), .Y (lte_16_23_n_39));
  OAI2BB1X1 lte_16_23_g336(.A0N (in2[4]), .A1N (lte_16_23_n_12), .B0
       (lte_16_23_n_0), .Y (lte_16_23_n_38));
  AOI21X2 lte_16_23_g337(.A0 (in2[10]), .A1 (lte_16_23_n_17), .B0
       (lte_16_23_n_29), .Y (lte_16_23_n_37));
  AOI21X1 lte_16_23_g338(.A0 (in2[2]), .A1 (lte_16_23_n_8), .B0
       (lte_16_23_n_30), .Y (lte_16_23_n_36));
  OAI2BB1X1 lte_16_23_g340(.A0N (in2[14]), .A1N (lte_16_23_n_16), .B0
       (lte_16_23_n_4), .Y (lte_16_23_n_35));
  NAND3BX1 lte_16_23_g341(.AN (in2[10]), .B (in1[10]), .C
       (lte_16_23_n_3), .Y (lte_16_23_n_34));
  NAND2X1 lte_16_23_g342(.A (lte_16_23_n_2), .B (lte_16_23_n_21), .Y
       (lte_16_23_n_33));
  AOI21X1 lte_16_23_g343(.A0 (in2[1]), .A1 (lte_16_23_n_15), .B0
       (lte_16_23_n_5), .Y (lte_16_23_n_32));
  INVX1 lte_16_23_g344(.A (lte_16_23_n_30), .Y (lte_16_23_n_31));
  INVX1 lte_16_23_g345(.A (lte_16_23_n_3), .Y (lte_16_23_n_29));
  NOR2BX1 lte_16_23_g346(.AN (in1[15]), .B (in2[15]), .Y
       (lte_16_23_n_27));
  NOR2X1 lte_16_23_g347(.A (lte_16_23_n_12), .B (in2[4]), .Y
       (lte_16_23_n_26));
  NOR2BX1 lte_16_23_g348(.AN (in1[13]), .B (in2[13]), .Y
       (lte_16_23_n_25));
  NAND2BXL lte_16_23_g349(.AN (in2[9]), .B (in1[9]), .Y
       (lte_16_23_n_24));
  NOR2X2 lte_16_23_g350(.A (in1[3]), .B (lte_16_23_n_13), .Y
       (lte_16_23_n_30));
  NAND2X1 lte_16_23_g354(.A (in2[7]), .B (lte_16_23_n_10), .Y
       (lte_16_23_n_28));
  NAND2BXL lte_16_23_g356(.AN (in2[11]), .B (in1[11]), .Y
       (lte_16_23_n_23));
  NOR2X1 lte_16_23_g357(.A (lte_16_23_n_8), .B (in2[2]), .Y
       (lte_16_23_n_22));
  NOR2BX1 lte_16_23_g358(.AN (in1[8]), .B (in2[8]), .Y
       (lte_16_23_n_21));
  NOR2X1 lte_16_23_g359(.A (lte_16_23_n_15), .B (in2[1]), .Y
       (lte_16_23_n_20));
  NOR2X1 lte_16_23_g361(.A (lte_16_23_n_10), .B (in2[7]), .Y
       (lte_16_23_n_19));
  NAND2BXL lte_16_23_g362(.AN (in1[8]), .B (in2[8]), .Y
       (lte_16_23_n_18));
  INVX1 lte_16_23_g366(.A (in1[10]), .Y (lte_16_23_n_17));
  INVX1 lte_16_23_g367(.A (in1[14]), .Y (lte_16_23_n_16));
  INVX1 lte_16_23_g368(.A (in1[1]), .Y (lte_16_23_n_15));
  INVX1 lte_16_23_g369(.A (in2[12]), .Y (lte_16_23_n_14));
  INVX1 lte_16_23_g371(.A (in2[3]), .Y (lte_16_23_n_13));
  INVX1 lte_16_23_g373(.A (in1[4]), .Y (lte_16_23_n_12));
  INVX1 lte_16_23_g374(.A (in2[5]), .Y (lte_16_23_n_11));
  INVX1 lte_16_23_g375(.A (in1[7]), .Y (lte_16_23_n_10));
  INVX1 lte_16_23_g377(.A (in2[14]), .Y (lte_16_23_n_9));
  INVX1 lte_16_23_g378(.A (in1[2]), .Y (lte_16_23_n_8));
  INVX1 lte_16_23_g381(.A (in2[6]), .Y (lte_16_23_n_7));
  OA21X1 lte_16_23_g2(.A0 (lte_16_23_n_14), .A1 (in1[12]), .B0
       (lte_16_23_n_1), .Y (lte_16_23_n_6));
  NOR2BX1 lte_16_23_g382(.AN (in2[0]), .B (in1[0]), .Y (lte_16_23_n_5));
  NAND2BX1 lte_16_23_g383(.AN (in1[15]), .B (in2[15]), .Y
       (lte_16_23_n_4));
  NAND2BX4 lte_16_23_g384(.AN (in1[11]), .B (in2[11]), .Y
       (lte_16_23_n_3));
  NAND2BX4 lte_16_23_g385(.AN (in1[9]), .B (in2[9]), .Y
       (lte_16_23_n_2));
  NAND2BX1 lte_16_23_g386(.AN (in1[13]), .B (in2[13]), .Y
       (lte_16_23_n_1));
  NAND2BX1 lte_16_23_g387(.AN (in1[5]), .B (in2[5]), .Y
       (lte_16_23_n_0));
endmodule


