`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:47:38 CST (Jun  9 2025 08:47:38 UTC)

module dut_LessThan_1U_235_1(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire lt_15_26_n_0, lt_15_26_n_1, lt_15_26_n_2;
  NAND2X4 lt_15_26_g115(.A (in1[5]), .B (in1[4]), .Y (lt_15_26_n_1));
  NOR2X6 lt_15_26_g116(.A (in1[7]), .B (in1[6]), .Y (lt_15_26_n_0));
  CLKINVX2 g117(.A (in1[3]), .Y (lt_15_26_n_2));
  OAI21X2 g2(.A0 (lt_15_26_n_2), .A1 (lt_15_26_n_1), .B0
       (lt_15_26_n_0), .Y (out1));
endmodule


