`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:46:20 CST (Jun  9 2025 08:46:20 UTC)

module dut_OrReduction_3U_1U_1(in1, out1);
  input [2:0] in1;
  output out1;
  wire [2:0] in1;
  wire out1;
  wire n_0;
  NAND2BX2 g6(.AN (in1[0]), .B (n_0), .Y (out1));
  NOR2X4 g7(.A (in1[2]), .B (in1[1]), .Y (n_0));
endmodule


