`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:46:55 CST (Jun  9 2025 08:46:55 UTC)

module dut_LessThan_1U_85_1(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire lt_15_26_n_0, lt_15_26_n_1, lt_15_26_n_2, lt_15_26_n_3,
       lt_15_26_n_4, lt_15_26_n_5, lt_15_26_n_6, lt_15_26_n_7;
  wire lt_15_26_n_8;
  NOR2X1 lt_15_26_g117(.A (lt_15_26_n_5), .B (lt_15_26_n_8), .Y (out1));
  NOR2X1 lt_15_26_g118(.A (lt_15_26_n_6), .B (lt_15_26_n_7), .Y
       (lt_15_26_n_8));
  AOI21X1 lt_15_26_g119(.A0 (lt_15_26_n_0), .A1 (lt_15_26_n_4), .B0
       (lt_15_26_n_2), .Y (lt_15_26_n_7));
  NAND2BX1 lt_15_26_g120(.AN (in1[5]), .B (lt_15_26_n_1), .Y
       (lt_15_26_n_6));
  NOR2BX1 lt_15_26_g121(.AN (lt_15_26_n_1), .B (lt_15_26_n_3), .Y
       (lt_15_26_n_5));
  NAND2X6 lt_15_26_g122(.A (in1[1]), .B (in1[0]), .Y (lt_15_26_n_4));
  OR2XL lt_15_26_g123(.A (in1[5]), .B (in1[4]), .Y (lt_15_26_n_3));
  NOR2X1 lt_15_26_g124(.A (in1[3]), .B (in1[2]), .Y (lt_15_26_n_2));
  NOR2X4 lt_15_26_g125(.A (in1[7]), .B (in1[6]), .Y (lt_15_26_n_1));
  CLKINVX2 lt_15_26_g126(.A (in1[3]), .Y (lt_15_26_n_0));
endmodule


