`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:44:44 CST (Jun  9 2025 08:44:44 UTC)

module dut_LessThan_1U_45_4(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire lt_15_26_n_0, lt_15_26_n_1;
  AOI2BB1X1 lt_15_26_g118(.A0N (in1[7]), .A1N (in1[6]), .B0
       (lt_15_26_n_1), .Y (out1));
  NOR4X1 lt_15_26_g119(.A (lt_15_26_n_0), .B (in1[7]), .C (in1[5]), .D
       (in1[4]), .Y (lt_15_26_n_1));
  AND3XL lt_15_26_g120(.A (in1[1]), .B (in1[3]), .C (in1[2]), .Y
       (lt_15_26_n_0));
endmodule


