`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:46:36 CST (Jun  9 2025 08:46:36 UTC)

module dut_GreaterThanEQ_1U_32_1(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire gte_15_26_n_0, gte_15_26_n_1, gte_15_26_n_2, gte_15_26_n_3,
       gte_15_26_n_4, gte_15_26_n_5;
  OAI21X1 gte_15_26_g108(.A0 (gte_15_26_n_1), .A1 (gte_15_26_n_5), .B0
       (gte_15_26_n_4), .Y (out1));
  NOR2BX2 gte_15_26_g109(.AN (in1[3]), .B (gte_15_26_n_3), .Y
       (gte_15_26_n_5));
  NOR2X1 gte_15_26_g110(.A (gte_15_26_n_0), .B (gte_15_26_n_2), .Y
       (gte_15_26_n_4));
  AOI21X4 gte_15_26_g111(.A0 (in1[1]), .A1 (in1[0]), .B0 (in1[2]), .Y
       (gte_15_26_n_3));
  NOR3X1 gte_15_26_g112(.A (in1[7]), .B (in1[5]), .C (in1[4]), .Y
       (gte_15_26_n_2));
  OR2XL gte_15_26_g113(.A (in1[7]), .B (in1[5]), .Y (gte_15_26_n_1));
  NOR2X1 gte_15_26_g114(.A (in1[7]), .B (in1[6]), .Y (gte_15_26_n_0));
endmodule


