`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:46:18 CST (Jun  9 2025 08:46:18 UTC)

module dut_GreaterThanEQ_7Ux8U_1U_1(in2, in1, out1);
  input [6:0] in2;
  input [7:0] in1;
  output out1;
  wire [6:0] in2;
  wire [7:0] in1;
  wire out1;
  wire gte_16_31_n_0, gte_16_31_n_1, gte_16_31_n_2, gte_16_31_n_3,
       gte_16_31_n_4, gte_16_31_n_5, gte_16_31_n_6, gte_16_31_n_7;
  wire gte_16_31_n_8, gte_16_31_n_9, gte_16_31_n_10, gte_16_31_n_11,
       gte_16_31_n_12, gte_16_31_n_13, gte_16_31_n_14, gte_16_31_n_15;
  wire gte_16_31_n_16, gte_16_31_n_17, gte_16_31_n_18, gte_16_31_n_19,
       gte_16_31_n_20, gte_16_31_n_21, gte_16_31_n_22, gte_16_31_n_23;
  wire gte_16_31_n_24, gte_16_31_n_25, gte_16_31_n_26;
  NAND2X1 gte_16_31_g140(.A (gte_16_31_n_24), .B (gte_16_31_n_26), .Y
       (out1));
  NAND2BX1 gte_16_31_g141(.AN (gte_16_31_n_20), .B (gte_16_31_n_25), .Y
       (gte_16_31_n_26));
  OAI21X1 gte_16_31_g142(.A0 (gte_16_31_n_18), .A1 (gte_16_31_n_23),
       .B0 (gte_16_31_n_21), .Y (gte_16_31_n_25));
  AOI21X1 gte_16_31_g143(.A0 (gte_16_31_n_19), .A1 (gte_16_31_n_22),
       .B0 (gte_16_31_n_17), .Y (gte_16_31_n_24));
  AOI21X1 gte_16_31_g144(.A0 (gte_16_31_n_12), .A1 (gte_16_31_n_1), .B0
       (gte_16_31_n_15), .Y (gte_16_31_n_23));
  NAND2X1 gte_16_31_g145(.A (gte_16_31_n_11), .B (gte_16_31_n_16), .Y
       (gte_16_31_n_22));
  AOI21X1 gte_16_31_g146(.A0 (gte_16_31_n_13), .A1 (gte_16_31_n_9), .B0
       (gte_16_31_n_10), .Y (gte_16_31_n_21));
  NAND2X1 gte_16_31_g147(.A (gte_16_31_n_19), .B (gte_16_31_n_4), .Y
       (gte_16_31_n_20));
  AOI21X1 gte_16_31_g148(.A0 (in1[6]), .A1 (gte_16_31_n_6), .B0
       (in1[7]), .Y (gte_16_31_n_19));
  NAND2X1 gte_16_31_g149(.A (gte_16_31_n_13), .B (gte_16_31_n_14), .Y
       (gte_16_31_n_18));
  NOR3X1 gte_16_31_g151(.A (in1[7]), .B (gte_16_31_n_6), .C (in1[6]),
       .Y (gte_16_31_n_17));
  NAND2X1 gte_16_31_g152(.A (gte_16_31_n_2), .B (gte_16_31_n_3), .Y
       (gte_16_31_n_16));
  NOR2X1 gte_16_31_g155(.A (gte_16_31_n_7), .B (in1[1]), .Y
       (gte_16_31_n_15));
  NAND2X1 gte_16_31_g157(.A (in1[2]), .B (gte_16_31_n_8), .Y
       (gte_16_31_n_14));
  NAND2X1 gte_16_31_g159(.A (in1[1]), .B (gte_16_31_n_7), .Y
       (gte_16_31_n_12));
  NAND2BX1 gte_16_31_g161(.AN (in1[5]), .B (in2[5]), .Y
       (gte_16_31_n_11));
  NOR2X1 gte_16_31_g162(.A (gte_16_31_n_5), .B (in1[3]), .Y
       (gte_16_31_n_10));
  NOR2X1 gte_16_31_g163(.A (gte_16_31_n_8), .B (in1[2]), .Y
       (gte_16_31_n_9));
  NAND2X2 gte_16_31_g164(.A (in1[3]), .B (gte_16_31_n_5), .Y
       (gte_16_31_n_13));
  INVX1 gte_16_31_g167(.A (in2[2]), .Y (gte_16_31_n_8));
  INVX1 gte_16_31_g168(.A (in2[1]), .Y (gte_16_31_n_7));
  INVX1 gte_16_31_g169(.A (in2[6]), .Y (gte_16_31_n_6));
  INVX2 gte_16_31_g172(.A (in2[3]), .Y (gte_16_31_n_5));
  NOR2BX1 gte_16_31_g2(.AN (gte_16_31_n_2), .B (gte_16_31_n_0), .Y
       (gte_16_31_n_4));
  NOR2BX1 gte_16_31_g173(.AN (in2[4]), .B (in1[4]), .Y (gte_16_31_n_3));
  NAND2BX1 gte_16_31_g174(.AN (in2[5]), .B (in1[5]), .Y
       (gte_16_31_n_2));
  NAND2BX1 gte_16_31_g175(.AN (in2[0]), .B (in1[0]), .Y
       (gte_16_31_n_1));
  NOR2BX1 gte_16_31_g176(.AN (in1[4]), .B (in2[4]), .Y (gte_16_31_n_0));
endmodule


