`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:44:43 CST (Jun  9 2025 08:44:43 UTC)

module dut_LessThan_1U_41_4(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire lt_15_26_n_0;
  INVX1 lt_15_26_g105(.A (lt_15_26_n_0), .Y (out1));
  OAI32X1 lt_15_26_g106(.A0 (in1[7]), .A1 (in1[5]), .A2 (in1[4]), .B0
       (in1[7]), .B1 (in1[6]), .Y (lt_15_26_n_0));
endmodule


