`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  4 2025 00:39:51 CST (Jun  3 2025 16:39:51 UTC)

module dut_LessThan_8Ux8U_1U_4(in2, in1, out1);
  input [7:0] in2, in1;
  output out1;
  wire [7:0] in2, in1;
  wire out1;
  wire lt_16_23_n_0, lt_16_23_n_1, lt_16_23_n_2, lt_16_23_n_3,
       lt_16_23_n_4, lt_16_23_n_5, lt_16_23_n_6, lt_16_23_n_7;
  wire lt_16_23_n_8, lt_16_23_n_9, lt_16_23_n_10, lt_16_23_n_11,
       lt_16_23_n_12, lt_16_23_n_13, lt_16_23_n_14, lt_16_23_n_15;
  wire lt_16_23_n_16, lt_16_23_n_17, lt_16_23_n_18, lt_16_23_n_19,
       lt_16_23_n_20;
  AOI221X1 lt_16_23_g178(.A0 (lt_16_23_n_14), .A1 (lt_16_23_n_17), .B0
       (lt_16_23_n_16), .B1 (lt_16_23_n_20), .C0 (lt_16_23_n_18), .Y
       (out1));
  OAI211X1 lt_16_23_g179(.A0 (lt_16_23_n_1), .A1 (in1[3]), .B0
       (lt_16_23_n_19), .C0 (lt_16_23_n_13), .Y (lt_16_23_n_20));
  OAI221X1 lt_16_23_g180(.A0 (lt_16_23_n_8), .A1 (lt_16_23_n_12), .B0
       (lt_16_23_n_6), .B1 (in2[2]), .C0 (lt_16_23_n_10), .Y
       (lt_16_23_n_19));
  OAI32X1 lt_16_23_g181(.A0 (lt_16_23_n_11), .A1 (lt_16_23_n_5), .A2
       (in1[6]), .B0 (lt_16_23_n_4), .B1 (in1[7]), .Y (lt_16_23_n_18));
  OAI32X1 lt_16_23_g182(.A0 (lt_16_23_n_9), .A1 (lt_16_23_n_2), .A2
       (in1[4]), .B0 (lt_16_23_n_7), .B1 (in1[5]), .Y (lt_16_23_n_17));
  AOI211XL lt_16_23_g183(.A0 (in1[4]), .A1 (lt_16_23_n_2), .B0
       (lt_16_23_n_15), .C0 (lt_16_23_n_9), .Y (lt_16_23_n_16));
  INVX1 lt_16_23_g184(.A (lt_16_23_n_14), .Y (lt_16_23_n_15));
  AOI21X1 lt_16_23_g185(.A0 (in1[6]), .A1 (lt_16_23_n_5), .B0
       (lt_16_23_n_11), .Y (lt_16_23_n_14));
  NAND3BXL lt_16_23_g186(.AN (in1[2]), .B (lt_16_23_n_10), .C (in2[2]),
       .Y (lt_16_23_n_13));
  AOI22X1 lt_16_23_g187(.A0 (in1[0]), .A1 (lt_16_23_n_3), .B0 (in1[1]),
       .B1 (lt_16_23_n_0), .Y (lt_16_23_n_12));
  NOR2BX1 lt_16_23_g188(.AN (in1[7]), .B (in2[7]), .Y (lt_16_23_n_11));
  NAND2X1 lt_16_23_g189(.A (in1[3]), .B (lt_16_23_n_1), .Y
       (lt_16_23_n_10));
  NOR2BX1 lt_16_23_g190(.AN (in1[5]), .B (in2[5]), .Y (lt_16_23_n_9));
  NOR2X1 lt_16_23_g191(.A (lt_16_23_n_0), .B (in1[1]), .Y
       (lt_16_23_n_8));
  INVX1 lt_16_23_g192(.A (in2[5]), .Y (lt_16_23_n_7));
  INVX1 lt_16_23_g193(.A (in1[2]), .Y (lt_16_23_n_6));
  INVX1 lt_16_23_g194(.A (in2[6]), .Y (lt_16_23_n_5));
  INVX1 lt_16_23_g195(.A (in2[7]), .Y (lt_16_23_n_4));
  INVX1 lt_16_23_g196(.A (in2[0]), .Y (lt_16_23_n_3));
  INVX1 lt_16_23_g197(.A (in2[4]), .Y (lt_16_23_n_2));
  INVX1 lt_16_23_g198(.A (in2[3]), .Y (lt_16_23_n_1));
  INVX1 lt_16_23_g199(.A (in2[1]), .Y (lt_16_23_n_0));
endmodule


