`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:47:04 CST (Jun  9 2025 08:47:04 UTC)

module dut_LessThan_1U_118_1(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire lt_15_26_n_0, lt_15_26_n_1, lt_15_26_n_2, lt_15_26_n_3,
       lt_15_26_n_4, lt_15_26_n_5, lt_15_26_n_6, lt_15_26_n_7;
  wire lt_15_26_n_8, lt_15_26_n_9;
  NAND2X1 lt_15_26_g101(.A (lt_15_26_n_9), .B (lt_15_26_n_8), .Y
       (out1));
  NAND2X1 lt_15_26_g102(.A (in1[3]), .B (lt_15_26_n_0), .Y
       (lt_15_26_n_9));
  NOR2X2 lt_15_26_g104(.A (lt_15_26_n_7), .B (lt_15_26_n_5), .Y
       (lt_15_26_n_8));
  NAND2X2 lt_15_26_g105(.A (lt_15_26_n_1), .B (lt_15_26_n_4), .Y
       (lt_15_26_n_7));
  NAND2X2 lt_15_26_g106(.A (in1[1]), .B (in1[0]), .Y (lt_15_26_n_6));
  NAND2X2 lt_15_26_g107(.A (lt_15_26_n_3), .B (lt_15_26_n_2), .Y
       (lt_15_26_n_5));
  CLKINVX2 lt_15_26_g109(.A (in1[6]), .Y (lt_15_26_n_4));
  CLKINVX2 lt_15_26_g110(.A (in1[5]), .Y (lt_15_26_n_3));
  CLKINVX2 lt_15_26_g111(.A (in1[4]), .Y (lt_15_26_n_2));
  CLKINVX4 lt_15_26_g112(.A (in1[7]), .Y (lt_15_26_n_1));
  NAND2BX1 lt_15_26_g2(.AN (in1[2]), .B (lt_15_26_n_6), .Y
       (lt_15_26_n_0));
endmodule


