`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:44:54 CST (Jun  9 2025 08:44:54 UTC)

module dut_LessThan_1U_67_4(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire lt_15_26_n_0, lt_15_26_n_1;
  AOI2BB1X1 lt_15_26_g116(.A0N (in1[7]), .A1N (in1[6]), .B0
       (lt_15_26_n_1), .Y (out1));
  NOR4X1 lt_15_26_g117(.A (in1[3]), .B (in1[2]), .C (in1[7]), .D
       (lt_15_26_n_0), .Y (lt_15_26_n_1));
  OR2XL lt_15_26_g118(.A (in1[5]), .B (in1[4]), .Y (lt_15_26_n_0));
endmodule


