`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:46:32 CST (Jun  9 2025 08:46:32 UTC)

module dut_GreaterThanEQ_1U_22_1(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  AOI21X4 g2(.A0 (in1[5]), .A1 (in1[6]), .B0 (in1[7]), .Y (out1));
endmodule


