`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  4 2025 00:50:55 CST (Jun  3 2025 16:50:55 UTC)

module dut_Equal_1U_88_4(in1, out1);
  input [6:0] in1;
  output out1;
  wire [6:0] in1;
  wire out1;
  wire n_0;
  NOR4BBX1 g40(.AN (in1[4]), .BN (in1[6]), .C (in1[5]), .D (n_0), .Y
       (out1));
  NAND4BX1 g41(.AN (in1[2]), .B (in1[1]), .C (in1[0]), .D (in1[3]), .Y
       (n_0));
endmodule


