`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:47:11 CST (Jun  9 2025 08:47:11 UTC)

module dut_Add_32S_145_1(in1, out1);
  input [31:0] in1;
  output [31:0] out1;
  wire [31:0] in1;
  wire [31:0] out1;
  wire inc_add_15_23_1_n_6, inc_add_15_23_1_n_7, inc_add_15_23_1_n_8,
       inc_add_15_23_1_n_9, inc_add_15_23_1_n_10, inc_add_15_23_1_n_11,
       inc_add_15_23_1_n_12, inc_add_15_23_1_n_14;
  wire inc_add_15_23_1_n_15, inc_add_15_23_1_n_16,
       inc_add_15_23_1_n_17, inc_add_15_23_1_n_18,
       inc_add_15_23_1_n_20, inc_add_15_23_1_n_21,
       inc_add_15_23_1_n_22, inc_add_15_23_1_n_23;
  wire inc_add_15_23_1_n_24, inc_add_15_23_1_n_25,
       inc_add_15_23_1_n_26, inc_add_15_23_1_n_27,
       inc_add_15_23_1_n_28, inc_add_15_23_1_n_30,
       inc_add_15_23_1_n_31, inc_add_15_23_1_n_32;
  wire inc_add_15_23_1_n_33, inc_add_15_23_1_n_34,
       inc_add_15_23_1_n_35, inc_add_15_23_1_n_36,
       inc_add_15_23_1_n_37, inc_add_15_23_1_n_38,
       inc_add_15_23_1_n_39, inc_add_15_23_1_n_40;
  wire inc_add_15_23_1_n_41, inc_add_15_23_1_n_42,
       inc_add_15_23_1_n_43, inc_add_15_23_1_n_44,
       inc_add_15_23_1_n_45, inc_add_15_23_1_n_46,
       inc_add_15_23_1_n_47, inc_add_15_23_1_n_48;
  wire inc_add_15_23_1_n_49, inc_add_15_23_1_n_50,
       inc_add_15_23_1_n_51, inc_add_15_23_1_n_52,
       inc_add_15_23_1_n_53, inc_add_15_23_1_n_54,
       inc_add_15_23_1_n_55, inc_add_15_23_1_n_56;
  wire inc_add_15_23_1_n_57, inc_add_15_23_1_n_58,
       inc_add_15_23_1_n_59, inc_add_15_23_1_n_60,
       inc_add_15_23_1_n_61, inc_add_15_23_1_n_62,
       inc_add_15_23_1_n_63, inc_add_15_23_1_n_64;
  wire inc_add_15_23_1_n_65, inc_add_15_23_1_n_66,
       inc_add_15_23_1_n_67, inc_add_15_23_1_n_68,
       inc_add_15_23_1_n_69, inc_add_15_23_1_n_70,
       inc_add_15_23_1_n_71, inc_add_15_23_1_n_72;
  wire inc_add_15_23_1_n_73, inc_add_15_23_1_n_74,
       inc_add_15_23_1_n_75, inc_add_15_23_1_n_76,
       inc_add_15_23_1_n_77, inc_add_15_23_1_n_78,
       inc_add_15_23_1_n_79, inc_add_15_23_1_n_80;
  wire inc_add_15_23_1_n_81, inc_add_15_23_1_n_82,
       inc_add_15_23_1_n_84, inc_add_15_23_1_n_86,
       inc_add_15_23_1_n_87, inc_add_15_23_1_n_88,
       inc_add_15_23_1_n_89, inc_add_15_23_1_n_90;
  wire inc_add_15_23_1_n_91, inc_add_15_23_1_n_92,
       inc_add_15_23_1_n_93, inc_add_15_23_1_n_94,
       inc_add_15_23_1_n_95, inc_add_15_23_1_n_96,
       inc_add_15_23_1_n_97, inc_add_15_23_1_n_98;
  wire inc_add_15_23_1_n_99, inc_add_15_23_1_n_100,
       inc_add_15_23_1_n_103, inc_add_15_23_1_n_104,
       inc_add_15_23_1_n_105, inc_add_15_23_1_n_106,
       inc_add_15_23_1_n_107, inc_add_15_23_1_n_108;
  wire inc_add_15_23_1_n_109, inc_add_15_23_1_n_110, n_164, n_165,
       n_167, n_170, n_171, n_172;
  wire n_173, n_174, n_179, n_180, n_181, n_183, n_186, n_187;
  wire n_188, n_190, n_193, n_194, n_195;
  INVX1 g2(.A (in1[0]), .Y (out1[0]));
  MXI2XL inc_add_15_23_1_g362(.A (inc_add_15_23_1_n_36), .B (in1[17]),
       .S0 (inc_add_15_23_1_n_109), .Y (out1[17]));
  MXI2XL inc_add_15_23_1_g363(.A (inc_add_15_23_1_n_38), .B (in1[9]),
       .S0 (inc_add_15_23_1_n_94), .Y (out1[9]));
  MXI2XL inc_add_15_23_1_g365(.A (inc_add_15_23_1_n_21), .B (in1[21]),
       .S0 (inc_add_15_23_1_n_106), .Y (out1[21]));
  MXI2XL inc_add_15_23_1_g366(.A (inc_add_15_23_1_n_20), .B (in1[19]),
       .S0 (inc_add_15_23_1_n_95), .Y (out1[19]));
  MXI2XL inc_add_15_23_1_g367(.A (inc_add_15_23_1_n_23), .B (in1[23]),
       .S0 (inc_add_15_23_1_n_98), .Y (out1[23]));
  MXI2XL inc_add_15_23_1_g368(.A (inc_add_15_23_1_n_33), .B (in1[29]),
       .S0 (inc_add_15_23_1_n_100), .Y (out1[29]));
  MXI2XL inc_add_15_23_1_g369(.A (inc_add_15_23_1_n_35), .B (in1[27]),
       .S0 (inc_add_15_23_1_n_99), .Y (out1[27]));
  MXI2XL inc_add_15_23_1_g370(.A (n_187), .B (n_186), .S0
       (inc_add_15_23_1_n_105), .Y (out1[25]));
  MXI2XL inc_add_15_23_1_g371(.A (inc_add_15_23_1_n_14), .B (in1[26]),
       .S0 (inc_add_15_23_1_n_110), .Y (out1[26]));
  MXI2XL inc_add_15_23_1_g372(.A (n_170), .B (n_171), .S0
       (inc_add_15_23_1_n_11), .Y (out1[24]));
  MXI2XL inc_add_15_23_1_g373(.A (inc_add_15_23_1_n_26), .B (in1[22]),
       .S0 (inc_add_15_23_1_n_96), .Y (out1[22]));
  MXI2XL inc_add_15_23_1_g374(.A (inc_add_15_23_1_n_32), .B (in1[28]),
       .S0 (inc_add_15_23_1_n_104), .Y (out1[28]));
  MXI2XL inc_add_15_23_1_g375(.A (inc_add_15_23_1_n_15), .B (in1[20]),
       .S0 (inc_add_15_23_1_n_108), .Y (out1[20]));
  MXI2XL inc_add_15_23_1_g376(.A (inc_add_15_23_1_n_24), .B (in1[31]),
       .S0 (inc_add_15_23_1_n_107), .Y (out1[31]));
  MXI2XL inc_add_15_23_1_g377(.A (inc_add_15_23_1_n_16), .B (in1[18]),
       .S0 (inc_add_15_23_1_n_103), .Y (out1[18]));
  MXI2XL inc_add_15_23_1_g378(.A (inc_add_15_23_1_n_34), .B (in1[30]),
       .S0 (inc_add_15_23_1_n_97), .Y (out1[30]));
  MXI2XL inc_add_15_23_1_g380(.A (inc_add_15_23_1_n_37), .B (in1[13]),
       .S0 (inc_add_15_23_1_n_90), .Y (out1[13]));
  MXI2XL inc_add_15_23_1_g381(.A (inc_add_15_23_1_n_22), .B (in1[11]),
       .S0 (inc_add_15_23_1_n_89), .Y (out1[11]));
  MXI2XL inc_add_15_23_1_g382(.A (inc_add_15_23_1_n_18), .B (in1[15]),
       .S0 (inc_add_15_23_1_n_88), .Y (out1[15]));
  MXI2XL inc_add_15_23_1_g384(.A (inc_add_15_23_1_n_25), .B (in1[14]),
       .S0 (inc_add_15_23_1_n_92), .Y (out1[14]));
  MXI2XL inc_add_15_23_1_g386(.A (inc_add_15_23_1_n_17), .B (in1[10]),
       .S0 (inc_add_15_23_1_n_93), .Y (out1[10]));
  NOR2XL inc_add_15_23_1_g387(.A (inc_add_15_23_1_n_82), .B
       (inc_add_15_23_1_n_91), .Y (inc_add_15_23_1_n_110));
  NOR2XL inc_add_15_23_1_g388(.A (inc_add_15_23_1_n_31), .B
       (inc_add_15_23_1_n_91), .Y (inc_add_15_23_1_n_109));
  NOR2XL inc_add_15_23_1_g390(.A (inc_add_15_23_1_n_57), .B
       (inc_add_15_23_1_n_91), .Y (inc_add_15_23_1_n_108));
  NOR2XL inc_add_15_23_1_g391(.A (inc_add_15_23_1_n_75), .B
       (inc_add_15_23_1_n_91), .Y (inc_add_15_23_1_n_107));
  NOR2XL inc_add_15_23_1_g392(.A (inc_add_15_23_1_n_72), .B
       (inc_add_15_23_1_n_91), .Y (inc_add_15_23_1_n_106));
  NOR2XL inc_add_15_23_1_g393(.A (inc_add_15_23_1_n_81), .B
       (inc_add_15_23_1_n_91), .Y (inc_add_15_23_1_n_105));
  NOR2XL inc_add_15_23_1_g394(.A (inc_add_15_23_1_n_10), .B
       (inc_add_15_23_1_n_91), .Y (inc_add_15_23_1_n_104));
  NOR2XL inc_add_15_23_1_g395(.A (inc_add_15_23_1_n_44), .B
       (inc_add_15_23_1_n_91), .Y (inc_add_15_23_1_n_103));
  MXI2XL inc_add_15_23_1_g396(.A (inc_add_15_23_1_n_28), .B (in1[6]),
       .S0 (inc_add_15_23_1_n_12), .Y (out1[6]));
  MXI2XL inc_add_15_23_1_g398(.A (inc_add_15_23_1_n_27), .B (in1[8]),
       .S0 (n_167), .Y (out1[8]));
  NOR2XL inc_add_15_23_1_g399(.A (inc_add_15_23_1_n_77), .B
       (inc_add_15_23_1_n_91), .Y (inc_add_15_23_1_n_100));
  NOR2XL inc_add_15_23_1_g400(.A (inc_add_15_23_1_n_76), .B
       (inc_add_15_23_1_n_91), .Y (inc_add_15_23_1_n_99));
  NOR2XL inc_add_15_23_1_g401(.A (inc_add_15_23_1_n_69), .B
       (inc_add_15_23_1_n_91), .Y (inc_add_15_23_1_n_98));
  NOR2X1 inc_add_15_23_1_g402(.A (inc_add_15_23_1_n_79), .B
       (inc_add_15_23_1_n_91), .Y (inc_add_15_23_1_n_97));
  NOR2XL inc_add_15_23_1_g403(.A (inc_add_15_23_1_n_73), .B
       (inc_add_15_23_1_n_91), .Y (inc_add_15_23_1_n_96));
  NOR2XL inc_add_15_23_1_g404(.A (inc_add_15_23_1_n_61), .B
       (inc_add_15_23_1_n_91), .Y (inc_add_15_23_1_n_95));
  NOR2XL inc_add_15_23_1_g405(.A (inc_add_15_23_1_n_27), .B (n_165), .Y
       (inc_add_15_23_1_n_94));
  NOR2XL inc_add_15_23_1_g406(.A (inc_add_15_23_1_n_51), .B (n_165), .Y
       (inc_add_15_23_1_n_93));
  NOR2XL inc_add_15_23_1_g408(.A (inc_add_15_23_1_n_8), .B (n_165), .Y
       (inc_add_15_23_1_n_92));
  NAND2X8 inc_add_15_23_1_g410(.A (inc_add_15_23_1_n_86), .B
       (inc_add_15_23_1_n_68), .Y (inc_add_15_23_1_n_91));
  NOR2XL inc_add_15_23_1_g411(.A (inc_add_15_23_1_n_70), .B (n_165), .Y
       (inc_add_15_23_1_n_90));
  NOR2XL inc_add_15_23_1_g412(.A (inc_add_15_23_1_n_63), .B (n_165), .Y
       (inc_add_15_23_1_n_89));
  NOR2XL inc_add_15_23_1_g414(.A (inc_add_15_23_1_n_67), .B (n_165), .Y
       (inc_add_15_23_1_n_88));
  NAND2X1 inc_add_15_23_1_g416(.A (in1[4]), .B (n_190), .Y
       (inc_add_15_23_1_n_87));
  CLKAND2X6 inc_add_15_23_1_g418(.A (inc_add_15_23_1_n_55), .B
       (inc_add_15_23_1_n_78), .Y (inc_add_15_23_1_n_86));
  NAND2X1 inc_add_15_23_1_g419(.A (inc_add_15_23_1_n_65), .B (n_190),
       .Y (inc_add_15_23_1_n_84));
  MXI2XL inc_add_15_23_1_g420(.A (in1[2]), .B (inc_add_15_23_1_n_30),
       .S0 (inc_add_15_23_1_n_42), .Y (out1[2]));
  NAND2X1 inc_add_15_23_1_g422(.A (inc_add_15_23_1_n_52), .B
       (inc_add_15_23_1_n_71), .Y (inc_add_15_23_1_n_82));
  NAND2X1 inc_add_15_23_1_g423(.A (n_172), .B (inc_add_15_23_1_n_71),
       .Y (inc_add_15_23_1_n_81));
  NOR2X1 inc_add_15_23_1_g424(.A (inc_add_15_23_1_n_30), .B
       (inc_add_15_23_1_n_42), .Y (inc_add_15_23_1_n_80));
  NAND2X1 inc_add_15_23_1_g425(.A (inc_add_15_23_1_n_6), .B
       (inc_add_15_23_1_n_71), .Y (inc_add_15_23_1_n_79));
  NOR2X6 inc_add_15_23_1_g427(.A (inc_add_15_23_1_n_41), .B
       (inc_add_15_23_1_n_42), .Y (inc_add_15_23_1_n_78));
  NAND2X1 inc_add_15_23_1_g428(.A (inc_add_15_23_1_n_74), .B
       (inc_add_15_23_1_n_71), .Y (inc_add_15_23_1_n_77));
  NAND2X1 inc_add_15_23_1_g429(.A (inc_add_15_23_1_n_7), .B
       (inc_add_15_23_1_n_71), .Y (inc_add_15_23_1_n_76));
  NAND2X1 inc_add_15_23_1_g430(.A (inc_add_15_23_1_n_66), .B
       (inc_add_15_23_1_n_71), .Y (inc_add_15_23_1_n_75));
  NOR2X1 inc_add_15_23_1_g432(.A (inc_add_15_23_1_n_32), .B
       (inc_add_15_23_1_n_60), .Y (inc_add_15_23_1_n_74));
  OR2XL inc_add_15_23_1_g434(.A (inc_add_15_23_1_n_45), .B
       (inc_add_15_23_1_n_57), .Y (inc_add_15_23_1_n_73));
  NAND2X1 inc_add_15_23_1_g435(.A (in1[20]), .B (inc_add_15_23_1_n_58),
       .Y (inc_add_15_23_1_n_72));
  NAND2X1 inc_add_15_23_1_g437(.A (in1[12]), .B (n_183), .Y
       (inc_add_15_23_1_n_70));
  NAND3BXL inc_add_15_23_1_g438(.AN (inc_add_15_23_1_n_45), .B
       (inc_add_15_23_1_n_58), .C (in1[22]), .Y (inc_add_15_23_1_n_69));
  CLKAND2X3 inc_add_15_23_1_g439(.A (inc_add_15_23_1_n_56), .B
       (inc_add_15_23_1_n_59), .Y (inc_add_15_23_1_n_68));
  NAND2X1 inc_add_15_23_1_g440(.A (inc_add_15_23_1_n_64), .B (n_183),
       .Y (inc_add_15_23_1_n_67));
  NOR2X1 inc_add_15_23_1_g441(.A (inc_add_15_23_1_n_62), .B
       (inc_add_15_23_1_n_60), .Y (inc_add_15_23_1_n_66));
  CLKAND2X3 inc_add_15_23_1_g442(.A (inc_add_15_23_1_n_54), .B
       (inc_add_15_23_1_n_58), .Y (inc_add_15_23_1_n_71));
  NOR2X1 inc_add_15_23_1_g443(.A (inc_add_15_23_1_n_28), .B (n_194), .Y
       (inc_add_15_23_1_n_65));
  NOR2X1 inc_add_15_23_1_g444(.A (inc_add_15_23_1_n_25), .B (n_180), .Y
       (inc_add_15_23_1_n_64));
  OR2XL inc_add_15_23_1_g445(.A (inc_add_15_23_1_n_17), .B
       (inc_add_15_23_1_n_51), .Y (inc_add_15_23_1_n_63));
  NAND2X1 inc_add_15_23_1_g446(.A (in1[30]), .B (inc_add_15_23_1_n_46),
       .Y (inc_add_15_23_1_n_62));
  OR2XL inc_add_15_23_1_g448(.A (inc_add_15_23_1_n_16), .B
       (inc_add_15_23_1_n_44), .Y (inc_add_15_23_1_n_61));
  INVX1 inc_add_15_23_1_g451(.A (inc_add_15_23_1_n_58), .Y
       (inc_add_15_23_1_n_57));
  NOR2X2 inc_add_15_23_1_g453(.A (inc_add_15_23_1_n_49), .B
       (inc_add_15_23_1_n_53), .Y (inc_add_15_23_1_n_56));
  NOR2X4 inc_add_15_23_1_g454(.A (inc_add_15_23_1_n_50), .B
       (inc_add_15_23_1_n_43), .Y (inc_add_15_23_1_n_55));
  NOR2X1 inc_add_15_23_1_g455(.A (inc_add_15_23_1_n_40), .B
       (inc_add_15_23_1_n_45), .Y (inc_add_15_23_1_n_54));
  NAND2X2 inc_add_15_23_1_g456(.A (inc_add_15_23_1_n_47), .B
       (inc_add_15_23_1_n_52), .Y (inc_add_15_23_1_n_60));
  NOR2X2 inc_add_15_23_1_g457(.A (inc_add_15_23_1_n_39), .B
       (inc_add_15_23_1_n_51), .Y (inc_add_15_23_1_n_59));
  NOR2X2 inc_add_15_23_1_g458(.A (inc_add_15_23_1_n_48), .B
       (inc_add_15_23_1_n_44), .Y (inc_add_15_23_1_n_58));
  NAND2X8 inc_add_15_23_1_g461(.A (in1[7]), .B (in1[6]), .Y
       (inc_add_15_23_1_n_50));
  NAND2X4 inc_add_15_23_1_g462(.A (in1[15]), .B (in1[14]), .Y
       (inc_add_15_23_1_n_49));
  NAND2X4 inc_add_15_23_1_g463(.A (in1[19]), .B (in1[18]), .Y
       (inc_add_15_23_1_n_48));
  NOR2X4 inc_add_15_23_1_g464(.A (inc_add_15_23_1_n_35), .B
       (inc_add_15_23_1_n_14), .Y (inc_add_15_23_1_n_47));
  NAND2X4 inc_add_15_23_1_g465(.A (in1[13]), .B (in1[12]), .Y
       (inc_add_15_23_1_n_53));
  NOR2X4 inc_add_15_23_1_g466(.A (n_188), .B (n_174), .Y
       (inc_add_15_23_1_n_52));
  NAND2X4 inc_add_15_23_1_g467(.A (in1[9]), .B (in1[8]), .Y
       (inc_add_15_23_1_n_51));
  NAND2X8 inc_add_15_23_1_g469(.A (in1[3]), .B (in1[2]), .Y
       (inc_add_15_23_1_n_41));
  NAND2X2 inc_add_15_23_1_g470(.A (in1[23]), .B (in1[22]), .Y
       (inc_add_15_23_1_n_40));
  NAND2X6 inc_add_15_23_1_g471(.A (in1[11]), .B (in1[10]), .Y
       (inc_add_15_23_1_n_39));
  NOR2X2 inc_add_15_23_1_g472(.A (inc_add_15_23_1_n_33), .B
       (inc_add_15_23_1_n_32), .Y (inc_add_15_23_1_n_46));
  NAND2X4 inc_add_15_23_1_g473(.A (in1[21]), .B (in1[20]), .Y
       (inc_add_15_23_1_n_45));
  NAND2X4 inc_add_15_23_1_g474(.A (in1[17]), .B (in1[16]), .Y
       (inc_add_15_23_1_n_44));
  NAND2X4 inc_add_15_23_1_g475(.A (in1[5]), .B (in1[4]), .Y
       (inc_add_15_23_1_n_43));
  NAND2X6 inc_add_15_23_1_g476(.A (in1[1]), .B (in1[0]), .Y
       (inc_add_15_23_1_n_42));
  INVXL inc_add_15_23_1_g478(.A (in1[9]), .Y (inc_add_15_23_1_n_38));
  INVXL inc_add_15_23_1_g479(.A (in1[13]), .Y (inc_add_15_23_1_n_37));
  INVXL inc_add_15_23_1_g480(.A (in1[17]), .Y (inc_add_15_23_1_n_36));
  CLKINVX3 inc_add_15_23_1_g481(.A (in1[27]), .Y
       (inc_add_15_23_1_n_35));
  INVXL inc_add_15_23_1_g482(.A (in1[30]), .Y (inc_add_15_23_1_n_34));
  CLKINVX2 inc_add_15_23_1_g484(.A (in1[29]), .Y
       (inc_add_15_23_1_n_33));
  CLKINVX2 inc_add_15_23_1_g485(.A (in1[28]), .Y
       (inc_add_15_23_1_n_32));
  INVX1 inc_add_15_23_1_g486(.A (in1[16]), .Y (inc_add_15_23_1_n_31));
  INVX1 inc_add_15_23_1_g487(.A (in1[2]), .Y (inc_add_15_23_1_n_30));
  INVX1 inc_add_15_23_1_g489(.A (in1[6]), .Y (inc_add_15_23_1_n_28));
  INVX1 inc_add_15_23_1_g490(.A (in1[8]), .Y (inc_add_15_23_1_n_27));
  INVXL inc_add_15_23_1_g491(.A (in1[22]), .Y (inc_add_15_23_1_n_26));
  INVX1 inc_add_15_23_1_g492(.A (in1[14]), .Y (inc_add_15_23_1_n_25));
  INVXL inc_add_15_23_1_g493(.A (in1[31]), .Y (inc_add_15_23_1_n_24));
  INVXL inc_add_15_23_1_g494(.A (in1[23]), .Y (inc_add_15_23_1_n_23));
  INVXL inc_add_15_23_1_g496(.A (in1[11]), .Y (inc_add_15_23_1_n_22));
  INVXL inc_add_15_23_1_g497(.A (in1[21]), .Y (inc_add_15_23_1_n_21));
  INVXL inc_add_15_23_1_g498(.A (in1[19]), .Y (inc_add_15_23_1_n_20));
  INVXL inc_add_15_23_1_g500(.A (in1[15]), .Y (inc_add_15_23_1_n_18));
  INVX1 inc_add_15_23_1_g502(.A (in1[10]), .Y (inc_add_15_23_1_n_17));
  INVX1 inc_add_15_23_1_g504(.A (in1[18]), .Y (inc_add_15_23_1_n_16));
  INVXL inc_add_15_23_1_g505(.A (in1[20]), .Y (inc_add_15_23_1_n_15));
  CLKINVX3 inc_add_15_23_1_g507(.A (in1[26]), .Y
       (inc_add_15_23_1_n_14));
  MXI2XL inc_add_15_23_1_g2(.A (in1[16]), .B (inc_add_15_23_1_n_31),
       .S0 (inc_add_15_23_1_n_91), .Y (out1[16]));
  NOR2BX1 inc_add_15_23_1_g508(.AN (n_190), .B (n_193), .Y
       (inc_add_15_23_1_n_12));
  NOR2BX1 inc_add_15_23_1_g509(.AN (inc_add_15_23_1_n_71), .B
       (inc_add_15_23_1_n_91), .Y (inc_add_15_23_1_n_11));
  NAND2BX1 inc_add_15_23_1_g510(.AN (inc_add_15_23_1_n_60), .B
       (inc_add_15_23_1_n_71), .Y (inc_add_15_23_1_n_10));
  NOR2BX1 inc_add_15_23_1_g511(.AN (n_183), .B (n_164), .Y
       (inc_add_15_23_1_n_9));
  NAND2BX1 inc_add_15_23_1_g512(.AN (n_179), .B (n_183), .Y
       (inc_add_15_23_1_n_8));
  NOR2BX1 inc_add_15_23_1_g513(.AN (inc_add_15_23_1_n_52), .B
       (inc_add_15_23_1_n_14), .Y (inc_add_15_23_1_n_7));
  NOR2BX1 inc_add_15_23_1_g514(.AN (inc_add_15_23_1_n_46), .B
       (inc_add_15_23_1_n_60), .Y (inc_add_15_23_1_n_6));
  XNOR2X1 inc_add_15_23_1_g515(.A (in1[5]), .B (inc_add_15_23_1_n_87),
       .Y (out1[5]));
  CLKXOR2X1 inc_add_15_23_1_g516(.A (in1[3]), .B
       (inc_add_15_23_1_n_80), .Y (out1[3]));
  XOR2XL inc_add_15_23_1_g517(.A (in1[1]), .B (in1[0]), .Y (out1[1]));
  XNOR2X1 inc_add_15_23_1_g518(.A (in1[7]), .B (inc_add_15_23_1_n_84),
       .Y (out1[7]));
  CLKXOR2X1 inc_add_15_23_1_g519(.A (in1[4]), .B (n_190), .Y (out1[4]));
  XOR2XL inc_add_15_23_1_g520(.A (in1[12]), .B (inc_add_15_23_1_n_9),
       .Y (out1[12]));
  INVXL fopt(.A (inc_add_15_23_1_n_86), .Y (n_164));
  INVXL fopt1(.A (n_165), .Y (n_167));
  CLKINVX1 fopt2(.A (inc_add_15_23_1_n_86), .Y (n_165));
  INVXL fopt521(.A (n_171), .Y (n_170));
  INVXL fopt522(.A (n_173), .Y (n_171));
  INVXL fopt523(.A (n_173), .Y (n_172));
  INVXL fopt524(.A (in1[24]), .Y (n_173));
  CLKINVX3 fopt525(.A (in1[24]), .Y (n_174));
  INVXL fopt528(.A (n_181), .Y (n_179));
  INVXL fopt529(.A (n_181), .Y (n_180));
  INVXL fopt530(.A (inc_add_15_23_1_n_53), .Y (n_181));
  BUFX3 fopt531(.A (inc_add_15_23_1_n_59), .Y (n_183));
  INVXL fopt532(.A (n_187), .Y (n_186));
  INVXL fopt533(.A (in1[25]), .Y (n_187));
  CLKINVX3 fopt534(.A (in1[25]), .Y (n_188));
  BUFX3 fopt535(.A (inc_add_15_23_1_n_78), .Y (n_190));
  INVXL fopt536(.A (n_195), .Y (n_193));
  INVXL fopt537(.A (n_195), .Y (n_194));
  INVXL fopt538(.A (inc_add_15_23_1_n_43), .Y (n_195));
endmodule


