`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  4 2025 00:51:22 CST (Jun  3 2025 16:51:22 UTC)

module dut_Equal_7Ux5U_1U_1(in2, in1, out1);
  input [6:0] in2;
  input [4:0] in1;
  output out1;
  wire [6:0] in2;
  wire [4:0] in1;
  wire out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26;
  NOR2X1 g68(.A (n_23), .B (n_26), .Y (out1));
  NAND2X1 g69(.A (n_25), .B (n_24), .Y (n_26));
  NOR2X2 g71(.A (n_22), .B (n_19), .Y (n_25));
  NOR2X2 g70(.A (n_21), .B (n_20), .Y (n_24));
  NAND2X1 g72(.A (n_10), .B (n_18), .Y (n_23));
  NOR2X2 g74(.A (n_13), .B (n_16), .Y (n_22));
  NOR2X1 g75(.A (n_9), .B (n_15), .Y (n_21));
  NOR2X1 g76(.A (n_12), .B (n_14), .Y (n_20));
  NOR2X1 g73(.A (n_11), .B (n_17), .Y (n_19));
  MXI2XL g77(.A (in2[4]), .B (n_6), .S0 (in1[4]), .Y (n_18));
  NOR2X2 g78(.A (n_0), .B (n_7), .Y (n_17));
  NOR2X6 g82(.A (n_5), .B (n_3), .Y (n_16));
  NOR2X4 g83(.A (n_4), .B (n_8), .Y (n_15));
  NOR2X2 g86(.A (n_2), .B (n_1), .Y (n_14));
  NOR2X2 g79(.A (in2[3]), .B (in1[3]), .Y (n_13));
  NOR2X1 g80(.A (in2[0]), .B (in1[0]), .Y (n_12));
  NOR2X2 g81(.A (in2[2]), .B (in1[2]), .Y (n_11));
  NOR2X1 g84(.A (in2[6]), .B (in2[5]), .Y (n_10));
  NOR2X2 g85(.A (in2[1]), .B (in1[1]), .Y (n_9));
  CLKINVX3 g91(.A (in1[1]), .Y (n_8));
  CLKINVX2 g95(.A (in1[2]), .Y (n_7));
  INVX1 g90(.A (in2[4]), .Y (n_6));
  CLKINVX12 g93(.A (in2[3]), .Y (n_5));
  CLKINVX12 g88(.A (in2[1]), .Y (n_4));
  CLKINVX4 g89(.A (in1[3]), .Y (n_3));
  CLKINVX3 g92(.A (in2[0]), .Y (n_2));
  CLKINVX2 g94(.A (in1[0]), .Y (n_1));
  CLKINVX16 g87(.A (in2[2]), .Y (n_0));
endmodule


