`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:44:20 CST (Jun  9 2025 08:44:20 UTC)

module dut_Add_8Ux8U_9U_4(in2, in1, out1);
  input [7:0] in2, in1;
  output [8:0] out1;
  wire [7:0] in2, in1;
  wire [8:0] out1;
  wire add_16_31_n_0, add_16_31_n_1, add_16_31_n_2, add_16_31_n_3,
       add_16_31_n_4, add_16_31_n_5, add_16_31_n_6, add_16_31_n_7;
  wire add_16_31_n_8, add_16_31_n_9, add_16_31_n_10, add_16_31_n_11,
       add_16_31_n_12, add_16_31_n_13, add_16_31_n_14, add_16_31_n_15;
  wire add_16_31_n_16, add_16_31_n_17, add_16_31_n_18, add_16_31_n_19,
       add_16_31_n_20, add_16_31_n_21, add_16_31_n_24, add_16_31_n_25;
  wire add_16_31_n_27, add_16_31_n_28, add_16_31_n_30, add_16_31_n_32,
       add_16_31_n_33, add_16_31_n_37;
  XNOR2X1 add_16_31_g165(.A (add_16_31_n_15), .B (add_16_31_n_37), .Y
       (out1[7]));
  OAI21X1 add_16_31_g166(.A0 (add_16_31_n_1), .A1 (add_16_31_n_33), .B0
       (add_16_31_n_2), .Y (add_16_31_n_37));
  XNOR2X1 add_16_31_g167(.A (add_16_31_n_13), .B (add_16_31_n_33), .Y
       (out1[6]));
  XNOR2X1 add_16_31_g168(.A (add_16_31_n_12), .B (add_16_31_n_32), .Y
       (out1[5]));
  OAI221X1 add_16_31_g169(.A0 (add_16_31_n_16), .A1 (add_16_31_n_30),
       .B0 (add_16_31_n_16), .B1 (add_16_31_n_19), .C0
       (add_16_31_n_20), .Y (out1[8]));
  AND2XL add_16_31_g170(.A (add_16_31_n_19), .B (add_16_31_n_30), .Y
       (add_16_31_n_33));
  OAI2BB1X1 add_16_31_g171(.A0N (add_16_31_n_7), .A1N (add_16_31_n_28),
       .B0 (add_16_31_n_9), .Y (add_16_31_n_32));
  XNOR2X1 add_16_31_g172(.A (add_16_31_n_18), .B (add_16_31_n_28), .Y
       (out1[4]));
  NAND3BXL add_16_31_g173(.AN (add_16_31_n_3), .B (add_16_31_n_28), .C
       (add_16_31_n_7), .Y (add_16_31_n_30));
  XNOR2X1 add_16_31_g174(.A (add_16_31_n_17), .B (add_16_31_n_27), .Y
       (out1[3]));
  OAI221X1 add_16_31_g175(.A0 (add_16_31_n_8), .A1 (add_16_31_n_25),
       .B0 (add_16_31_n_6), .B1 (add_16_31_n_8), .C0 (add_16_31_n_4),
       .Y (add_16_31_n_28));
  NAND2X1 add_16_31_g176(.A (add_16_31_n_6), .B (add_16_31_n_25), .Y
       (add_16_31_n_27));
  XNOR2X1 add_16_31_g177(.A (add_16_31_n_14), .B (add_16_31_n_24), .Y
       (out1[2]));
  NAND2BX1 add_16_31_g178(.AN (add_16_31_n_11), .B (add_16_31_n_24), .Y
       (add_16_31_n_25));
  ADDFX1 add_16_31_g179(.A (add_16_31_n_21), .B (in1[1]), .CI (in2[1]),
       .CO (add_16_31_n_24), .S (out1[1]));
  ADDHX1 add_16_31_g180(.A (in2[0]), .B (in1[0]), .CO (add_16_31_n_21),
       .S (out1[0]));
  OA21X1 add_16_31_g181(.A0 (add_16_31_n_2), .A1 (add_16_31_n_0), .B0
       (add_16_31_n_5), .Y (add_16_31_n_20));
  OA21X1 add_16_31_g182(.A0 (add_16_31_n_9), .A1 (add_16_31_n_3), .B0
       (add_16_31_n_10), .Y (add_16_31_n_19));
  NAND2X1 add_16_31_g183(.A (add_16_31_n_9), .B (add_16_31_n_7), .Y
       (add_16_31_n_18));
  NAND2BX1 add_16_31_g184(.AN (add_16_31_n_8), .B (add_16_31_n_4), .Y
       (add_16_31_n_17));
  OR2X1 add_16_31_g185(.A (add_16_31_n_0), .B (add_16_31_n_1), .Y
       (add_16_31_n_16));
  NAND2BX1 add_16_31_g186(.AN (add_16_31_n_0), .B (add_16_31_n_5), .Y
       (add_16_31_n_15));
  NAND2BX1 add_16_31_g187(.AN (add_16_31_n_11), .B (add_16_31_n_6), .Y
       (add_16_31_n_14));
  NOR2BX1 add_16_31_g188(.AN (add_16_31_n_2), .B (add_16_31_n_1), .Y
       (add_16_31_n_13));
  NAND2BX1 add_16_31_g189(.AN (add_16_31_n_3), .B (add_16_31_n_10), .Y
       (add_16_31_n_12));
  NOR2X1 add_16_31_g190(.A (in2[2]), .B (in1[2]), .Y (add_16_31_n_11));
  NAND2X1 add_16_31_g191(.A (in2[5]), .B (in1[5]), .Y (add_16_31_n_10));
  NAND2X1 add_16_31_g192(.A (in2[4]), .B (in1[4]), .Y (add_16_31_n_9));
  NOR2X1 add_16_31_g193(.A (in2[3]), .B (in1[3]), .Y (add_16_31_n_8));
  OR2XL add_16_31_g194(.A (in2[4]), .B (in1[4]), .Y (add_16_31_n_7));
  NAND2X1 add_16_31_g195(.A (in2[2]), .B (in1[2]), .Y (add_16_31_n_6));
  NAND2X1 add_16_31_g196(.A (in2[7]), .B (in1[7]), .Y (add_16_31_n_5));
  NAND2X1 add_16_31_g197(.A (in2[3]), .B (in1[3]), .Y (add_16_31_n_4));
  NOR2X1 add_16_31_g198(.A (in2[5]), .B (in1[5]), .Y (add_16_31_n_3));
  NAND2X1 add_16_31_g199(.A (in2[6]), .B (in1[6]), .Y (add_16_31_n_2));
  NOR2X1 add_16_31_g200(.A (in2[6]), .B (in1[6]), .Y (add_16_31_n_1));
  NOR2X1 add_16_31_g201(.A (in2[7]), .B (in1[7]), .Y (add_16_31_n_0));
endmodule


