`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 16:46:36 CST (Jun  9 2025 08:46:36 UTC)

module dut_GreaterThanEQ_1U_34_1(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  wire gte_15_26_n_1, gte_15_26_n_3, n_14, n_15;
  OAI2BB1X1 gte_15_26_g108(.A0N (gte_15_26_n_1), .A1N (gte_15_26_n_3),
       .B0 (n_15), .Y (out1));
  OAI21X2 gte_15_26_g110(.A0 (in1[2]), .A1 (in1[1]), .B0 (in1[3]), .Y
       (gte_15_26_n_3));
  NOR2X1 gte_15_26_g112(.A (in1[7]), .B (in1[5]), .Y (gte_15_26_n_1));
  NAND2BX2 g2(.AN (in1[7]), .B (n_14), .Y (n_15));
  OAI21X4 g3(.A0 (in1[5]), .A1 (in1[4]), .B0 (in1[6]), .Y (n_14));
endmodule


