`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  4 2025 00:51:23 CST (Jun  3 2025 16:51:23 UTC)

module dut_Equal_7Ux7U_1U_1(in2, in1, out1);
  input [6:0] in2, in1;
  output out1;
  wire [6:0] in2, in1;
  wire out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36;
  NOR2X1 g80(.A (n_36), .B (n_35), .Y (out1));
  NAND2X1 g81(.A (n_25), .B (n_34), .Y (n_36));
  NAND2X1 g82(.A (n_33), .B (n_32), .Y (n_35));
  NOR2X2 g83(.A (n_28), .B (n_27), .Y (n_34));
  NOR2X2 g84(.A (n_31), .B (n_26), .Y (n_33));
  NOR2X2 g85(.A (n_30), .B (n_29), .Y (n_32));
  NOR2X2 g91(.A (n_18), .B (n_19), .Y (n_31));
  NOR2X1 g86(.A (n_14), .B (n_23), .Y (n_30));
  NOR2X1 g87(.A (n_13), .B (n_21), .Y (n_29));
  NOR2X2 g88(.A (n_17), .B (n_20), .Y (n_28));
  NOR2X1 g89(.A (n_15), .B (n_24), .Y (n_27));
  NOR2X1 g90(.A (n_16), .B (n_22), .Y (n_26));
  MXI2XL g92(.A (in2[4]), .B (n_4), .S0 (in1[4]), .Y (n_25));
  NOR2X2 g101(.A (n_6), .B (n_7), .Y (n_24));
  NOR2X2 g93(.A (n_9), .B (n_5), .Y (n_23));
  NOR2X2 g95(.A (n_2), .B (n_11), .Y (n_22));
  NOR2X2 g97(.A (n_12), .B (n_3), .Y (n_21));
  NOR2X6 g99(.A (n_1), .B (n_0), .Y (n_20));
  NOR2X4 g100(.A (n_10), .B (n_8), .Y (n_19));
  NOR2X2 g102(.A (in2[3]), .B (in1[3]), .Y (n_18));
  NOR2X2 g103(.A (in2[6]), .B (in1[6]), .Y (n_17));
  NOR2X1 g104(.A (in2[2]), .B (in1[2]), .Y (n_16));
  NOR2X2 g94(.A (in2[5]), .B (in1[5]), .Y (n_15));
  NOR2X2 g96(.A (in2[1]), .B (in1[1]), .Y (n_14));
  NOR2X1 g98(.A (in2[0]), .B (in1[0]), .Y (n_13));
  CLKINVX2 g108(.A (in2[0]), .Y (n_12));
  CLKINVX2 g111(.A (in1[2]), .Y (n_11));
  CLKINVX12 g114(.A (in2[3]), .Y (n_10));
  CLKINVX16 g117(.A (in2[1]), .Y (n_9));
  CLKINVX4 g109(.A (in1[3]), .Y (n_8));
  CLKINVX2 g116(.A (in1[5]), .Y (n_7));
  CLKINVX16 g106(.A (in2[5]), .Y (n_6));
  CLKINVX2 g107(.A (in1[1]), .Y (n_5));
  INVX1 g115(.A (in2[4]), .Y (n_4));
  CLKINVX2 g113(.A (in1[0]), .Y (n_3));
  CLKINVX16 g105(.A (in2[2]), .Y (n_2));
  CLKINVX12 g112(.A (in2[6]), .Y (n_1));
  CLKINVX4 g110(.A (in1[6]), .Y (n_0));
endmodule


