`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  4 2025 00:50:50 CST (Jun  3 2025 16:50:50 UTC)

module dut_Equal_1U_79_4(in1, out1);
  input [6:0] in1;
  output out1;
  wire [6:0] in1;
  wire out1;
  wire n_0, n_1;
  NOR3BXL g45(.AN (in1[5]), .B (n_1), .C (in1[4]), .Y (out1));
  NAND4XL g46(.A (in1[6]), .B (n_0), .C (in1[1]), .D (in1[0]), .Y
       (n_1));
  NOR2X1 g47(.A (in1[3]), .B (in1[2]), .Y (n_0));
endmodule


