`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  4 2025 00:40:06 CST (Jun  3 2025 16:40:06 UTC)

module dut_Sub_4Ux1U_5S_1(in2, in1, out1);
  input [3:0] in2;
  input in1;
  output [4:0] out1;
  wire [3:0] in2;
  wire in1;
  wire [4:0] out1;
  wire dec_sub_16_31_1_n_0, dec_sub_16_31_1_n_1, dec_sub_16_31_1_n_2,
       dec_sub_16_31_1_n_3, dec_sub_16_31_1_n_4, dec_sub_16_31_1_n_6,
       dec_sub_16_31_1_n_7, dec_sub_16_31_1_n_11;
  wire n_29, n_30, n_31;
  MXI2X1 dec_sub_16_31_1_g55(.A (dec_sub_16_31_1_n_0), .B (in2[3]), .S0
       (dec_sub_16_31_1_n_11), .Y (out1[3]));
  MXI2XL dec_sub_16_31_1_g56(.A (dec_sub_16_31_1_n_2), .B (in2[2]), .S0
       (n_30), .Y (out1[2]));
  NOR2X2 dec_sub_16_31_1_g57(.A (in2[2]), .B (n_31), .Y
       (dec_sub_16_31_1_n_11));
  NOR2BX1 dec_sub_16_31_1_g58(.AN (dec_sub_16_31_1_n_4), .B (n_29), .Y
       (out1[4]));
  NAND2BXL dec_sub_16_31_1_g60(.AN (n_30), .B (dec_sub_16_31_1_n_7), .Y
       (out1[1]));
  NAND2XL dec_sub_16_31_1_g61(.A (in2[1]), .B (dec_sub_16_31_1_n_3), .Y
       (dec_sub_16_31_1_n_7));
  NOR2X6 dec_sub_16_31_1_g62(.A (in2[1]), .B (dec_sub_16_31_1_n_3), .Y
       (dec_sub_16_31_1_n_6));
  MXI2XL dec_sub_16_31_1_g63(.A (dec_sub_16_31_1_n_1), .B (in2[0]), .S0
       (in1), .Y (out1[0]));
  NOR2X1 dec_sub_16_31_1_g64(.A (in2[3]), .B (in2[2]), .Y
       (dec_sub_16_31_1_n_4));
  NAND2X8 dec_sub_16_31_1_g65(.A (in1), .B (dec_sub_16_31_1_n_1), .Y
       (dec_sub_16_31_1_n_3));
  INVXL dec_sub_16_31_1_g66(.A (in2[2]), .Y (dec_sub_16_31_1_n_2));
  CLKINVX12 dec_sub_16_31_1_g67(.A (in2[0]), .Y (dec_sub_16_31_1_n_1));
  INVXL dec_sub_16_31_1_g68(.A (in2[3]), .Y (dec_sub_16_31_1_n_0));
  INVXL fopt5(.A (n_30), .Y (n_29));
  CLKINVX1 fopt6(.A (n_31), .Y (n_30));
  CLKINVX4 fopt7(.A (dec_sub_16_31_1_n_6), .Y (n_31));
endmodule


