`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  4 2025 00:39:48 CST (Jun  3 2025 16:39:48 UTC)

module dut_Add_17Sx8U_17S_4(in2, in1, out1);
  input [16:0] in2;
  input [7:0] in1;
  output [16:0] out1;
  wire [16:0] in2;
  wire [7:0] in1;
  wire [16:0] out1;
  wire add_16_23_n_0, add_16_23_n_1, add_16_23_n_2, add_16_23_n_3,
       add_16_23_n_4, add_16_23_n_5, add_16_23_n_6, add_16_23_n_7;
  wire add_16_23_n_8, add_16_23_n_9, add_16_23_n_10, add_16_23_n_11,
       add_16_23_n_12, add_16_23_n_13, add_16_23_n_14, add_16_23_n_15;
  wire add_16_23_n_16, add_16_23_n_17, add_16_23_n_18, add_16_23_n_19,
       add_16_23_n_20, add_16_23_n_21, add_16_23_n_22, add_16_23_n_23;
  wire add_16_23_n_24, add_16_23_n_25, add_16_23_n_26, add_16_23_n_27,
       add_16_23_n_30, add_16_23_n_31, add_16_23_n_33, add_16_23_n_34;
  wire add_16_23_n_36, add_16_23_n_38, add_16_23_n_39, add_16_23_n_40,
       add_16_23_n_43, add_16_23_n_44, add_16_23_n_45, add_16_23_n_46;
  wire add_16_23_n_48, add_16_23_n_49, add_16_23_n_50, add_16_23_n_55;
  XNOR2X1 add_16_23_g332(.A (in2[15]), .B (add_16_23_n_55), .Y
       (out1[15]));
  XNOR2X1 add_16_23_g333(.A (in2[13]), .B (add_16_23_n_49), .Y
       (out1[13]));
  XNOR2X1 add_16_23_g334(.A (in2[11]), .B (add_16_23_n_48), .Y
       (out1[11]));
  XNOR2X1 add_16_23_g335(.A (in2[9]), .B (add_16_23_n_0), .Y (out1[9]));
  XNOR2X1 add_16_23_g336(.A (in2[14]), .B (add_16_23_n_50), .Y
       (out1[14]));
  NAND2BX1 add_16_23_g337(.AN (add_16_23_n_50), .B (in2[14]), .Y
       (add_16_23_n_55));
  XNOR2X1 add_16_23_g338(.A (add_16_23_n_21), .B (add_16_23_n_44), .Y
       (out1[7]));
  XOR2XL add_16_23_g339(.A (in2[16]), .B (add_16_23_n_43), .Y
       (out1[16]));
  XOR2XL add_16_23_g340(.A (in2[12]), .B (add_16_23_n_46), .Y
       (out1[12]));
  XOR2XL add_16_23_g341(.A (in2[10]), .B (add_16_23_n_45), .Y
       (out1[10]));
  NAND2BX1 add_16_23_g342(.AN (add_16_23_n_14), .B (add_16_23_n_46), .Y
       (add_16_23_n_50));
  NAND2X1 add_16_23_g343(.A (in2[12]), .B (add_16_23_n_46), .Y
       (add_16_23_n_49));
  NAND2X1 add_16_23_g344(.A (in2[10]), .B (add_16_23_n_45), .Y
       (add_16_23_n_48));
  XNOR2X1 add_16_23_g345(.A (in2[8]), .B (add_16_23_n_40), .Y
       (out1[8]));
  NOR2X1 add_16_23_g346(.A (add_16_23_n_17), .B (add_16_23_n_40), .Y
       (add_16_23_n_46));
  NOR2X1 add_16_23_g347(.A (add_16_23_n_8), .B (add_16_23_n_40), .Y
       (add_16_23_n_45));
  OAI21X1 add_16_23_g349(.A0 (add_16_23_n_2), .A1 (add_16_23_n_39), .B0
       (add_16_23_n_11), .Y (add_16_23_n_44));
  NOR4X1 add_16_23_g350(.A (add_16_23_n_40), .B (add_16_23_n_17), .C
       (add_16_23_n_1), .D (add_16_23_n_14), .Y (add_16_23_n_43));
  XNOR2X1 add_16_23_g351(.A (add_16_23_n_22), .B (add_16_23_n_39), .Y
       (out1[6]));
  XNOR2X1 add_16_23_g352(.A (add_16_23_n_20), .B (add_16_23_n_38), .Y
       (out1[5]));
  AOI221X1 add_16_23_g354(.A0 (add_16_23_n_23), .A1 (add_16_23_n_25),
       .B0 (add_16_23_n_23), .B1 (add_16_23_n_36), .C0
       (add_16_23_n_26), .Y (add_16_23_n_40));
  NOR2X1 add_16_23_g355(.A (add_16_23_n_25), .B (add_16_23_n_36), .Y
       (add_16_23_n_39));
  OAI2BB1X1 add_16_23_g356(.A0N (add_16_23_n_4), .A1N (add_16_23_n_34),
       .B0 (add_16_23_n_10), .Y (add_16_23_n_38));
  XNOR2X1 add_16_23_g357(.A (add_16_23_n_19), .B (add_16_23_n_34), .Y
       (out1[4]));
  NOR3BX1 add_16_23_g358(.AN (add_16_23_n_34), .B (add_16_23_n_12), .C
       (add_16_23_n_3), .Y (add_16_23_n_36));
  XNOR2X1 add_16_23_g359(.A (add_16_23_n_18), .B (add_16_23_n_33), .Y
       (out1[3]));
  OAI221X1 add_16_23_g360(.A0 (add_16_23_n_5), .A1 (add_16_23_n_31),
       .B0 (add_16_23_n_6), .B1 (add_16_23_n_5), .C0 (add_16_23_n_7),
       .Y (add_16_23_n_34));
  NAND2X1 add_16_23_g361(.A (add_16_23_n_6), .B (add_16_23_n_31), .Y
       (add_16_23_n_33));
  XNOR2X1 add_16_23_g362(.A (add_16_23_n_24), .B (add_16_23_n_30), .Y
       (out1[2]));
  NAND2BX1 add_16_23_g363(.AN (add_16_23_n_15), .B (add_16_23_n_30), .Y
       (add_16_23_n_31));
  ADDFX1 add_16_23_g364(.A (add_16_23_n_27), .B (in1[1]), .CI (in2[1]),
       .CO (add_16_23_n_30), .S (out1[1]));
  ADDHX1 add_16_23_g365(.A (in2[0]), .B (in1[0]), .CO (add_16_23_n_27),
       .S (out1[0]));
  OAI21X1 add_16_23_g366(.A0 (add_16_23_n_11), .A1 (add_16_23_n_13),
       .B0 (add_16_23_n_9), .Y (add_16_23_n_26));
  OAI21X1 add_16_23_g367(.A0 (add_16_23_n_10), .A1 (add_16_23_n_12),
       .B0 (add_16_23_n_16), .Y (add_16_23_n_25));
  NAND2BX1 add_16_23_g368(.AN (add_16_23_n_15), .B (add_16_23_n_6), .Y
       (add_16_23_n_24));
  NOR2X1 add_16_23_g369(.A (add_16_23_n_13), .B (add_16_23_n_2), .Y
       (add_16_23_n_23));
  NOR2BX1 add_16_23_g370(.AN (add_16_23_n_11), .B (add_16_23_n_2), .Y
       (add_16_23_n_22));
  NAND2BX1 add_16_23_g371(.AN (add_16_23_n_13), .B (add_16_23_n_9), .Y
       (add_16_23_n_21));
  NAND2BX1 add_16_23_g372(.AN (add_16_23_n_12), .B (add_16_23_n_16), .Y
       (add_16_23_n_20));
  NAND2X1 add_16_23_g373(.A (add_16_23_n_10), .B (add_16_23_n_4), .Y
       (add_16_23_n_19));
  NAND2BX1 add_16_23_g374(.AN (add_16_23_n_5), .B (add_16_23_n_7), .Y
       (add_16_23_n_18));
  NAND3BXL add_16_23_g375(.AN (add_16_23_n_8), .B (in2[11]), .C
       (in2[10]), .Y (add_16_23_n_17));
  NAND2X1 add_16_23_g376(.A (in2[5]), .B (in1[5]), .Y (add_16_23_n_16));
  NOR2X1 add_16_23_g377(.A (in2[2]), .B (in1[2]), .Y (add_16_23_n_15));
  NAND2X1 add_16_23_g378(.A (in2[13]), .B (in2[12]), .Y
       (add_16_23_n_14));
  NOR2X1 add_16_23_g379(.A (in2[7]), .B (in1[7]), .Y (add_16_23_n_13));
  NOR2X1 add_16_23_g380(.A (in2[5]), .B (in1[5]), .Y (add_16_23_n_12));
  NAND2X1 add_16_23_g381(.A (in2[6]), .B (in1[6]), .Y (add_16_23_n_11));
  NAND2X1 add_16_23_g382(.A (in2[4]), .B (in1[4]), .Y (add_16_23_n_10));
  INVX1 add_16_23_g383(.A (add_16_23_n_3), .Y (add_16_23_n_4));
  NAND2X1 add_16_23_g384(.A (in2[15]), .B (in2[14]), .Y
       (add_16_23_n_1));
  NAND2X1 add_16_23_g385(.A (in2[7]), .B (in1[7]), .Y (add_16_23_n_9));
  NAND2X1 add_16_23_g386(.A (in2[9]), .B (in2[8]), .Y (add_16_23_n_8));
  NAND2X1 add_16_23_g387(.A (in2[3]), .B (in1[3]), .Y (add_16_23_n_7));
  NAND2X1 add_16_23_g388(.A (in2[2]), .B (in1[2]), .Y (add_16_23_n_6));
  NOR2X1 add_16_23_g389(.A (in2[3]), .B (in1[3]), .Y (add_16_23_n_5));
  NOR2X1 add_16_23_g390(.A (in2[4]), .B (in1[4]), .Y (add_16_23_n_3));
  NOR2X1 add_16_23_g391(.A (in2[6]), .B (in1[6]), .Y (add_16_23_n_2));
  NAND2BX1 add_16_23_g2(.AN (add_16_23_n_40), .B (in2[8]), .Y
       (add_16_23_n_0));
endmodule


