`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  4 2025 00:39:42 CST (Jun  3 2025 16:39:42 UTC)

module dut_Sub_4Ux1U_5S_4(in2, in1, out1);
  input [3:0] in2;
  input in1;
  output [4:0] out1;
  wire [3:0] in2;
  wire in1;
  wire [4:0] out1;
  wire dec_sub_16_31_1_n_1, dec_sub_16_31_1_n_3, dec_sub_16_31_1_n_5;
  XNOR2X1 dec_sub_16_31_1_g55(.A (in2[3]), .B (dec_sub_16_31_1_n_5), .Y
       (out1[3]));
  XOR2XL dec_sub_16_31_1_g56(.A (in2[2]), .B (dec_sub_16_31_1_n_3), .Y
       (out1[2]));
  NAND2BX1 dec_sub_16_31_1_g57(.AN (in2[2]), .B (dec_sub_16_31_1_n_3),
       .Y (dec_sub_16_31_1_n_5));
  NOR3BX1 dec_sub_16_31_1_g58(.AN (dec_sub_16_31_1_n_3), .B (in2[3]),
       .C (in2[2]), .Y (out1[4]));
  NOR2X1 dec_sub_16_31_1_g61(.A (in2[1]), .B (dec_sub_16_31_1_n_1), .Y
       (dec_sub_16_31_1_n_3));
  XOR2XL dec_sub_16_31_1_g62(.A (in2[0]), .B (in1), .Y (out1[0]));
  NAND2BX1 dec_sub_16_31_1_g63(.AN (in2[0]), .B (in1), .Y
       (dec_sub_16_31_1_n_1));
  AO21XL dec_sub_16_31_1_g2(.A0 (in2[1]), .A1 (dec_sub_16_31_1_n_1),
       .B0 (dec_sub_16_31_1_n_3), .Y (out1[1]));
endmodule


