`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  4 2025 00:39:49 CST (Jun  3 2025 16:39:49 UTC)

module dut_Add_16Ux8U_16U_4(in2, in1, out1);
  input [15:0] in2;
  input [7:0] in1;
  output [15:0] out1;
  wire [15:0] in2;
  wire [7:0] in1;
  wire [15:0] out1;
  wire add_16_23_n_0, add_16_23_n_1, add_16_23_n_2, add_16_23_n_3,
       add_16_23_n_4, add_16_23_n_5, add_16_23_n_6, add_16_23_n_7;
  wire add_16_23_n_8, add_16_23_n_9, add_16_23_n_10, add_16_23_n_11,
       add_16_23_n_12, add_16_23_n_13, add_16_23_n_14, add_16_23_n_15;
  wire add_16_23_n_16, add_16_23_n_17, add_16_23_n_18, add_16_23_n_19,
       add_16_23_n_20, add_16_23_n_21, add_16_23_n_22, add_16_23_n_23;
  wire add_16_23_n_24, add_16_23_n_27, add_16_23_n_28, add_16_23_n_30,
       add_16_23_n_31, add_16_23_n_33, add_16_23_n_35, add_16_23_n_36;
  wire add_16_23_n_37, add_16_23_n_40, add_16_23_n_41, add_16_23_n_42,
       add_16_23_n_44, add_16_23_n_45, add_16_23_n_46, add_16_23_n_50;
  XNOR2X1 add_16_23_g315(.A (in2[15]), .B (add_16_23_n_50), .Y
       (out1[15]));
  XNOR2X1 add_16_23_g316(.A (in2[13]), .B (add_16_23_n_46), .Y
       (out1[13]));
  XNOR2X1 add_16_23_g317(.A (in2[11]), .B (add_16_23_n_45), .Y
       (out1[11]));
  XNOR2X1 add_16_23_g318(.A (in2[9]), .B (add_16_23_n_41), .Y
       (out1[9]));
  XNOR2X1 add_16_23_g319(.A (in2[14]), .B (add_16_23_n_44), .Y
       (out1[14]));
  NAND2BX1 add_16_23_g320(.AN (add_16_23_n_44), .B (in2[14]), .Y
       (add_16_23_n_50));
  XNOR2X1 add_16_23_g321(.A (in2[12]), .B (add_16_23_n_0), .Y
       (out1[12]));
  XNOR2X1 add_16_23_g322(.A (add_16_23_n_18), .B (add_16_23_n_40), .Y
       (out1[7]));
  XOR2XL add_16_23_g323(.A (in2[10]), .B (add_16_23_n_42), .Y
       (out1[10]));
  NAND2BX1 add_16_23_g324(.AN (add_16_23_n_0), .B (in2[12]), .Y
       (add_16_23_n_46));
  NAND2X1 add_16_23_g325(.A (in2[10]), .B (add_16_23_n_42), .Y
       (add_16_23_n_45));
  NAND3BXL add_16_23_g326(.AN (add_16_23_n_0), .B (in2[13]), .C
       (in2[12]), .Y (add_16_23_n_44));
  XNOR2X1 add_16_23_g327(.A (in2[8]), .B (add_16_23_n_37), .Y
       (out1[8]));
  NOR2X1 add_16_23_g328(.A (add_16_23_n_12), .B (add_16_23_n_37), .Y
       (add_16_23_n_42));
  NAND2BX1 add_16_23_g329(.AN (add_16_23_n_37), .B (in2[8]), .Y
       (add_16_23_n_41));
  OAI21X1 add_16_23_g331(.A0 (add_16_23_n_2), .A1 (add_16_23_n_36), .B0
       (add_16_23_n_3), .Y (add_16_23_n_40));
  XNOR2X1 add_16_23_g332(.A (add_16_23_n_20), .B (add_16_23_n_36), .Y
       (out1[6]));
  XNOR2X1 add_16_23_g333(.A (add_16_23_n_19), .B (add_16_23_n_35), .Y
       (out1[5]));
  AOI221X1 add_16_23_g335(.A0 (add_16_23_n_15), .A1 (add_16_23_n_23),
       .B0 (add_16_23_n_15), .B1 (add_16_23_n_33), .C0
       (add_16_23_n_22), .Y (add_16_23_n_37));
  NOR2X1 add_16_23_g336(.A (add_16_23_n_23), .B (add_16_23_n_33), .Y
       (add_16_23_n_36));
  OAI2BB1X1 add_16_23_g337(.A0N (add_16_23_n_5), .A1N (add_16_23_n_31),
       .B0 (add_16_23_n_9), .Y (add_16_23_n_35));
  XNOR2X1 add_16_23_g338(.A (add_16_23_n_17), .B (add_16_23_n_31), .Y
       (out1[4]));
  NOR3BX1 add_16_23_g339(.AN (add_16_23_n_31), .B (add_16_23_n_11), .C
       (add_16_23_n_4), .Y (add_16_23_n_33));
  XNOR2X1 add_16_23_g340(.A (add_16_23_n_21), .B (add_16_23_n_30), .Y
       (out1[3]));
  OAI221X1 add_16_23_g341(.A0 (add_16_23_n_6), .A1 (add_16_23_n_28),
       .B0 (add_16_23_n_1), .B1 (add_16_23_n_6), .C0 (add_16_23_n_7),
       .Y (add_16_23_n_31));
  NAND2X1 add_16_23_g342(.A (add_16_23_n_1), .B (add_16_23_n_28), .Y
       (add_16_23_n_30));
  XNOR2X1 add_16_23_g343(.A (add_16_23_n_16), .B (add_16_23_n_27), .Y
       (out1[2]));
  NAND2BX1 add_16_23_g344(.AN (add_16_23_n_8), .B (add_16_23_n_27), .Y
       (add_16_23_n_28));
  ADDFX1 add_16_23_g345(.A (add_16_23_n_24), .B (in1[1]), .CI (in2[1]),
       .CO (add_16_23_n_27), .S (out1[1]));
  ADDHX1 add_16_23_g346(.A (in2[0]), .B (in1[0]), .CO (add_16_23_n_24),
       .S (out1[0]));
  OAI21X1 add_16_23_g347(.A0 (add_16_23_n_9), .A1 (add_16_23_n_11), .B0
       (add_16_23_n_13), .Y (add_16_23_n_23));
  OAI21X1 add_16_23_g348(.A0 (add_16_23_n_3), .A1 (add_16_23_n_10), .B0
       (add_16_23_n_14), .Y (add_16_23_n_22));
  NAND2BX1 add_16_23_g349(.AN (add_16_23_n_6), .B (add_16_23_n_7), .Y
       (add_16_23_n_21));
  NOR2BX1 add_16_23_g350(.AN (add_16_23_n_3), .B (add_16_23_n_2), .Y
       (add_16_23_n_20));
  NAND2BX1 add_16_23_g351(.AN (add_16_23_n_11), .B (add_16_23_n_13), .Y
       (add_16_23_n_19));
  NAND2BX1 add_16_23_g352(.AN (add_16_23_n_10), .B (add_16_23_n_14), .Y
       (add_16_23_n_18));
  NAND2X1 add_16_23_g353(.A (add_16_23_n_9), .B (add_16_23_n_5), .Y
       (add_16_23_n_17));
  NAND2BX1 add_16_23_g354(.AN (add_16_23_n_8), .B (add_16_23_n_1), .Y
       (add_16_23_n_16));
  NOR2X1 add_16_23_g355(.A (add_16_23_n_10), .B (add_16_23_n_2), .Y
       (add_16_23_n_15));
  NAND2X1 add_16_23_g356(.A (in2[7]), .B (in1[7]), .Y (add_16_23_n_14));
  NAND2X1 add_16_23_g357(.A (in2[5]), .B (in1[5]), .Y (add_16_23_n_13));
  NAND2X1 add_16_23_g358(.A (in2[9]), .B (in2[8]), .Y (add_16_23_n_12));
  NOR2X1 add_16_23_g359(.A (in2[5]), .B (in1[5]), .Y (add_16_23_n_11));
  NOR2X1 add_16_23_g360(.A (in2[7]), .B (in1[7]), .Y (add_16_23_n_10));
  NAND2X1 add_16_23_g361(.A (in2[4]), .B (in1[4]), .Y (add_16_23_n_9));
  INVX1 add_16_23_g362(.A (add_16_23_n_4), .Y (add_16_23_n_5));
  NOR2X1 add_16_23_g363(.A (in2[2]), .B (in1[2]), .Y (add_16_23_n_8));
  NAND2X1 add_16_23_g364(.A (in2[3]), .B (in1[3]), .Y (add_16_23_n_7));
  NOR2X1 add_16_23_g365(.A (in2[3]), .B (in1[3]), .Y (add_16_23_n_6));
  NOR2X1 add_16_23_g366(.A (in2[4]), .B (in1[4]), .Y (add_16_23_n_4));
  NAND2X1 add_16_23_g367(.A (in2[6]), .B (in1[6]), .Y (add_16_23_n_3));
  NOR2X1 add_16_23_g368(.A (in2[6]), .B (in1[6]), .Y (add_16_23_n_2));
  NAND2X1 add_16_23_g369(.A (in2[2]), .B (in1[2]), .Y (add_16_23_n_1));
  NAND4BBXL add_16_23_g2(.AN (add_16_23_n_12), .BN (add_16_23_n_37), .C
       (in2[11]), .D (in2[10]), .Y (add_16_23_n_0));
endmodule


