`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  4 2025 00:39:45 CST (Jun  3 2025 16:39:45 UTC)

module dut_RightShift_16Ux4U_1U_4(in2, in1, out1);
  input [15:0] in2;
  input [3:0] in1;
  output out1;
  wire [15:0] in2;
  wire [3:0] in1;
  wire out1;
  wire srl_16_23_n_0, srl_16_23_n_1, srl_16_23_n_2, srl_16_23_n_3,
       srl_16_23_n_4, srl_16_23_n_5, srl_16_23_n_6, srl_16_23_n_7;
  wire srl_16_23_n_8, srl_16_23_n_9, srl_16_23_n_10, srl_16_23_n_11,
       srl_16_23_n_12, srl_16_23_n_13, srl_16_23_n_14;
  MX3XL srl_16_23_g192(.A (srl_16_23_n_10), .B (srl_16_23_n_13), .C
       (srl_16_23_n_14), .S0 (in1[2]), .S1 (in1[3]), .Y (out1));
  MX2XL srl_16_23_g193(.A (srl_16_23_n_12), .B (srl_16_23_n_11), .S0
       (in1[2]), .Y (srl_16_23_n_14));
  OAI22X1 srl_16_23_g194(.A0 (in1[1]), .A1 (srl_16_23_n_5), .B0
       (srl_16_23_n_1), .B1 (srl_16_23_n_7), .Y (srl_16_23_n_13));
  OAI22X1 srl_16_23_g195(.A0 (in1[1]), .A1 (srl_16_23_n_2), .B0
       (srl_16_23_n_1), .B1 (srl_16_23_n_4), .Y (srl_16_23_n_12));
  OAI22X1 srl_16_23_g196(.A0 (in1[1]), .A1 (srl_16_23_n_9), .B0
       (srl_16_23_n_1), .B1 (srl_16_23_n_8), .Y (srl_16_23_n_11));
  OAI22X1 srl_16_23_g197(.A0 (in1[1]), .A1 (srl_16_23_n_6), .B0
       (srl_16_23_n_1), .B1 (srl_16_23_n_3), .Y (srl_16_23_n_10));
  AOI22X1 srl_16_23_g198(.A0 (in2[12]), .A1 (srl_16_23_n_0), .B0
       (in2[13]), .B1 (in1[0]), .Y (srl_16_23_n_9));
  AOI22X1 srl_16_23_g199(.A0 (in2[14]), .A1 (srl_16_23_n_0), .B0
       (in2[15]), .B1 (in1[0]), .Y (srl_16_23_n_8));
  AOI22X1 srl_16_23_g200(.A0 (in2[6]), .A1 (srl_16_23_n_0), .B0
       (in2[7]), .B1 (in1[0]), .Y (srl_16_23_n_7));
  AOI22X1 srl_16_23_g201(.A0 (in2[0]), .A1 (srl_16_23_n_0), .B0
       (in2[1]), .B1 (in1[0]), .Y (srl_16_23_n_6));
  AOI22X1 srl_16_23_g202(.A0 (in2[4]), .A1 (srl_16_23_n_0), .B0
       (in2[5]), .B1 (in1[0]), .Y (srl_16_23_n_5));
  AOI22X1 srl_16_23_g203(.A0 (in2[10]), .A1 (srl_16_23_n_0), .B0
       (in2[11]), .B1 (in1[0]), .Y (srl_16_23_n_4));
  AOI22X1 srl_16_23_g204(.A0 (in2[2]), .A1 (srl_16_23_n_0), .B0
       (in2[3]), .B1 (in1[0]), .Y (srl_16_23_n_3));
  AOI22X1 srl_16_23_g205(.A0 (in2[8]), .A1 (srl_16_23_n_0), .B0
       (in2[9]), .B1 (in1[0]), .Y (srl_16_23_n_2));
  INVX1 srl_16_23_g206(.A (in1[1]), .Y (srl_16_23_n_1));
  INVX1 srl_16_23_g207(.A (in1[0]), .Y (srl_16_23_n_0));
endmodule


