`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  4 2025 00:40:06 CST (Jun  3 2025 16:40:06 UTC)

module dut_Sub_15Ux8U_16S_1(in2, in1, out1);
  input [14:0] in2;
  input [7:0] in1;
  output [15:0] out1;
  wire [14:0] in2;
  wire [7:0] in1;
  wire [15:0] out1;
  wire n_117, n_118, n_119, n_120, n_122, n_124, n_126, n_127;
  wire n_128, n_130, n_131, sub_16_31_n_0, sub_16_31_n_1,
       sub_16_31_n_2, sub_16_31_n_3, sub_16_31_n_7;
  wire sub_16_31_n_8, sub_16_31_n_9, sub_16_31_n_10, sub_16_31_n_11,
       sub_16_31_n_12, sub_16_31_n_13, sub_16_31_n_18, sub_16_31_n_21;
  wire sub_16_31_n_22, sub_16_31_n_23, sub_16_31_n_25, sub_16_31_n_26,
       sub_16_31_n_27, sub_16_31_n_28, sub_16_31_n_30, sub_16_31_n_31;
  wire sub_16_31_n_32, sub_16_31_n_33, sub_16_31_n_34, sub_16_31_n_35,
       sub_16_31_n_36, sub_16_31_n_37, sub_16_31_n_38, sub_16_31_n_39;
  wire sub_16_31_n_40, sub_16_31_n_41, sub_16_31_n_42, sub_16_31_n_43,
       sub_16_31_n_44, sub_16_31_n_45, sub_16_31_n_46, sub_16_31_n_47;
  wire sub_16_31_n_48, sub_16_31_n_49, sub_16_31_n_50, sub_16_31_n_51,
       sub_16_31_n_52, sub_16_31_n_53, sub_16_31_n_54, sub_16_31_n_55;
  wire sub_16_31_n_56, sub_16_31_n_57, sub_16_31_n_58, sub_16_31_n_59,
       sub_16_31_n_60, sub_16_31_n_61, sub_16_31_n_62, sub_16_31_n_63;
  wire sub_16_31_n_64, sub_16_31_n_65, sub_16_31_n_66, sub_16_31_n_67,
       sub_16_31_n_68, sub_16_31_n_69, sub_16_31_n_70, sub_16_31_n_71;
  wire sub_16_31_n_72, sub_16_31_n_73, sub_16_31_n_74, sub_16_31_n_75,
       sub_16_31_n_77, sub_16_31_n_78, sub_16_31_n_79, sub_16_31_n_80;
  MXI2X1 sub_16_31_g362(.A (sub_16_31_n_27), .B (in2[9]), .S0
       (sub_16_31_n_78), .Y (out1[9]));
  MXI2XL sub_16_31_g363(.A (in2[12]), .B (sub_16_31_n_26), .S0
       (sub_16_31_n_80), .Y (out1[12]));
  MXI2XL sub_16_31_g364(.A (in2[10]), .B (sub_16_31_n_25), .S0
       (sub_16_31_n_79), .Y (out1[10]));
  MXI2XL sub_16_31_g365(.A (in2[14]), .B (sub_16_31_n_22), .S0
       (sub_16_31_n_77), .Y (out1[14]));
  MXI2X1 sub_16_31_g367(.A (sub_16_31_n_23), .B (in2[11]), .S0
       (sub_16_31_n_74), .Y (out1[11]));
  MXI2XL sub_16_31_g371(.A (sub_16_31_n_52), .B (sub_16_31_n_51), .S0
       (sub_16_31_n_73), .Y (out1[5]));
  NAND2X1 sub_16_31_g372(.A (n_126), .B (sub_16_31_n_72), .Y
       (sub_16_31_n_80));
  NAND2X1 sub_16_31_g373(.A (sub_16_31_n_39), .B (sub_16_31_n_72), .Y
       (sub_16_31_n_79));
  NOR2X1 sub_16_31_g374(.A (in2[8]), .B (sub_16_31_n_71), .Y
       (sub_16_31_n_78));
  NAND2X1 sub_16_31_g375(.A (sub_16_31_n_61), .B (sub_16_31_n_72), .Y
       (sub_16_31_n_77));
  NOR2X1 sub_16_31_g376(.A (sub_16_31_n_56), .B (sub_16_31_n_71), .Y
       (out1[15]));
  NAND2X1 sub_16_31_g377(.A (sub_16_31_n_60), .B (sub_16_31_n_72), .Y
       (sub_16_31_n_75));
  NOR2X1 sub_16_31_g378(.A (sub_16_31_n_49), .B (sub_16_31_n_71), .Y
       (sub_16_31_n_74));
  NOR2X1 sub_16_31_g380(.A (sub_16_31_n_7), .B (sub_16_31_n_69), .Y
       (sub_16_31_n_73));
  INVX1 sub_16_31_g381(.A (sub_16_31_n_72), .Y (sub_16_31_n_71));
  NOR2X4 sub_16_31_g382(.A (sub_16_31_n_63), .B (sub_16_31_n_68), .Y
       (sub_16_31_n_72));
  NOR2X1 sub_16_31_g385(.A (sub_16_31_n_64), .B (sub_16_31_n_67), .Y
       (sub_16_31_n_70));
  NOR2X1 sub_16_31_g387(.A (sub_16_31_n_1), .B (n_122), .Y
       (sub_16_31_n_69));
  NOR2X2 sub_16_31_g388(.A (sub_16_31_n_59), .B (sub_16_31_n_65), .Y
       (sub_16_31_n_68));
  NOR2X1 sub_16_31_g389(.A (sub_16_31_n_58), .B (n_122), .Y
       (sub_16_31_n_67));
  AOI21X1 sub_16_31_g390(.A0 (sub_16_31_n_33), .A1 (sub_16_31_n_62),
       .B0 (sub_16_31_n_32), .Y (sub_16_31_n_66));
  AOI21X2 sub_16_31_g392(.A0 (sub_16_31_n_9), .A1 (sub_16_31_n_62), .B0
       (sub_16_31_n_55), .Y (sub_16_31_n_65));
  OAI21X1 sub_16_31_g394(.A0 (n_117), .A1 (sub_16_31_n_54), .B0
       (sub_16_31_n_38), .Y (sub_16_31_n_64));
  OAI21X2 sub_16_31_g395(.A0 (sub_16_31_n_54), .A1 (sub_16_31_n_48),
       .B0 (sub_16_31_n_57), .Y (sub_16_31_n_63));
  OAI21X4 sub_16_31_g396(.A0 (sub_16_31_n_37), .A1 (sub_16_31_n_34),
       .B0 (sub_16_31_n_43), .Y (sub_16_31_n_62));
  AND2XL sub_16_31_g399(.A (sub_16_31_n_42), .B (sub_16_31_n_45), .Y
       (sub_16_31_n_61));
  AND2XL sub_16_31_g400(.A (sub_16_31_n_26), .B (sub_16_31_n_45), .Y
       (sub_16_31_n_60));
  NAND2X2 sub_16_31_g401(.A (sub_16_31_n_11), .B (sub_16_31_n_12), .Y
       (sub_16_31_n_59));
  NAND2BX1 sub_16_31_g402(.AN (n_120), .B (sub_16_31_n_12), .Y
       (sub_16_31_n_58));
  AOI21X1 sub_16_31_g403(.A0 (sub_16_31_n_40), .A1 (sub_16_31_n_2), .B0
       (sub_16_31_n_44), .Y (sub_16_31_n_57));
  NAND3X1 sub_16_31_g404(.A (n_127), .B (sub_16_31_n_22), .C
       (sub_16_31_n_42), .Y (sub_16_31_n_56));
  OAI2BB1X1 sub_16_31_g405(.A0N (sub_16_31_n_35), .A1N
       (sub_16_31_n_32), .B0 (sub_16_31_n_0), .Y (sub_16_31_n_55));
  AOI21X2 sub_16_31_g407(.A0 (sub_16_31_n_41), .A1 (sub_16_31_n_7), .B0
       (sub_16_31_n_36), .Y (sub_16_31_n_54));
  INVXL sub_16_31_g410(.A (sub_16_31_n_51), .Y (sub_16_31_n_52));
  NAND2X1 sub_16_31_g412(.A (sub_16_31_n_25), .B (sub_16_31_n_39), .Y
       (sub_16_31_n_49));
  NAND2X1 sub_16_31_g413(.A (sub_16_31_n_35), .B (sub_16_31_n_0), .Y
       (sub_16_31_n_53));
  NAND2BX1 sub_16_31_g416(.AN (sub_16_31_n_36), .B (sub_16_31_n_41), .Y
       (sub_16_31_n_51));
  NOR2X1 sub_16_31_g417(.A (n_118), .B (sub_16_31_n_2), .Y
       (sub_16_31_n_50));
  INVX1 sub_16_31_g418(.A (sub_16_31_n_11), .Y (sub_16_31_n_48));
  NOR2X1 sub_16_31_g425(.A (sub_16_31_n_1), .B (sub_16_31_n_7), .Y
       (sub_16_31_n_47));
  NOR2BX1 sub_16_31_g426(.AN (sub_16_31_n_40), .B (sub_16_31_n_44), .Y
       (sub_16_31_n_46));
  NOR3BX1 sub_16_31_g428(.AN (sub_16_31_n_39), .B (in2[11]), .C
       (in2[10]), .Y (sub_16_31_n_45));
  INVX1 sub_16_31_g431(.A (sub_16_31_n_2), .Y (sub_16_31_n_38));
  NOR2BX1 sub_16_31_g432(.AN (in2[7]), .B (in1[7]), .Y
       (sub_16_31_n_44));
  NAND2X4 sub_16_31_g433(.A (in2[1]), .B (sub_16_31_n_28), .Y
       (sub_16_31_n_43));
  NOR2X1 sub_16_31_g434(.A (in2[13]), .B (in2[12]), .Y
       (sub_16_31_n_42));
  NAND2X4 sub_16_31_g435(.A (in1[5]), .B (sub_16_31_n_31), .Y
       (sub_16_31_n_41));
  NAND2X4 sub_16_31_g436(.A (in1[7]), .B (n_124), .Y (sub_16_31_n_40));
  NOR2X1 sub_16_31_g437(.A (in2[9]), .B (in2[8]), .Y (sub_16_31_n_39));
  NOR2X4 sub_16_31_g445(.A (in2[1]), .B (sub_16_31_n_28), .Y
       (sub_16_31_n_37));
  NOR2X1 sub_16_31_g446(.A (sub_16_31_n_31), .B (in1[5]), .Y
       (sub_16_31_n_36));
  NAND2X4 sub_16_31_g448(.A (in1[3]), .B (sub_16_31_n_30), .Y
       (sub_16_31_n_35));
  NOR2X2 sub_16_31_g449(.A (in2[0]), .B (sub_16_31_n_21), .Y
       (sub_16_31_n_34));
  NAND2X4 sub_16_31_g450(.A (in1[2]), .B (n_131), .Y (sub_16_31_n_33));
  NOR2X2 sub_16_31_g451(.A (in1[2]), .B (n_130), .Y (sub_16_31_n_32));
  CLKINVX3 sub_16_31_g453(.A (in2[5]), .Y (sub_16_31_n_31));
  CLKINVX12 sub_16_31_g454(.A (in2[3]), .Y (sub_16_31_n_30));
  CLKINVX20 sub_16_31_g456(.A (in1[1]), .Y (sub_16_31_n_28));
  INVXL sub_16_31_g459(.A (in2[9]), .Y (sub_16_31_n_27));
  INVX1 sub_16_31_g462(.A (in2[12]), .Y (sub_16_31_n_26));
  INVX1 sub_16_31_g463(.A (in2[10]), .Y (sub_16_31_n_25));
  INVXL sub_16_31_g469(.A (in2[11]), .Y (sub_16_31_n_23));
  INVX1 sub_16_31_g470(.A (in2[14]), .Y (sub_16_31_n_22));
  CLKINVX2 sub_16_31_g471(.A (in1[0]), .Y (sub_16_31_n_21));
  XNOR2X1 sub_16_31_g2(.A (sub_16_31_n_8), .B (sub_16_31_n_62), .Y
       (out1[2]));
  CLKXOR2X1 sub_16_31_g472(.A (sub_16_31_n_34), .B (sub_16_31_n_10), .Y
       (out1[1]));
  NOR2BX1 sub_16_31_g473(.AN (sub_16_31_n_54), .B (sub_16_31_n_13), .Y
       (sub_16_31_n_18));
  CLKXOR2X1 sub_16_31_g474(.A (sub_16_31_n_53), .B (sub_16_31_n_66), .Y
       (out1[3]));
  XNOR2X1 sub_16_31_g475(.A (sub_16_31_n_50), .B (sub_16_31_n_18), .Y
       (out1[6]));
  XNOR2X1 sub_16_31_g476(.A (sub_16_31_n_47), .B (n_122), .Y (out1[4]));
  XNOR2X1 sub_16_31_g477(.A (sub_16_31_n_46), .B (sub_16_31_n_70), .Y
       (out1[7]));
  NOR2BX1 sub_16_31_g478(.AN (sub_16_31_n_12), .B (n_122), .Y
       (sub_16_31_n_13));
  NOR2BX2 sub_16_31_g479(.AN (sub_16_31_n_41), .B (sub_16_31_n_1), .Y
       (sub_16_31_n_12));
  NOR2BX1 sub_16_31_g480(.AN (sub_16_31_n_40), .B (sub_16_31_n_3), .Y
       (sub_16_31_n_11));
  NAND2BX1 sub_16_31_g481(.AN (sub_16_31_n_37), .B (sub_16_31_n_43), .Y
       (sub_16_31_n_10));
  CLKAND2X2 sub_16_31_g482(.A (sub_16_31_n_35), .B (sub_16_31_n_33), .Y
       (sub_16_31_n_9));
  NAND2BX1 sub_16_31_g483(.AN (sub_16_31_n_32), .B (sub_16_31_n_33), .Y
       (sub_16_31_n_8));
  NOR2BX2 sub_16_31_g484(.AN (in2[4]), .B (in1[4]), .Y (sub_16_31_n_7));
  XNOR2XL sub_16_31_g485(.A (in2[13]), .B (sub_16_31_n_75), .Y
       (out1[13]));
  CLKXOR2X1 sub_16_31_g486(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  XOR2XL sub_16_31_g487(.A (in2[8]), .B (sub_16_31_n_72), .Y (out1[8]));
  NOR2BX2 sub_16_31_g488(.AN (in1[6]), .B (in2[6]), .Y (sub_16_31_n_3));
  NOR2BX1 sub_16_31_g489(.AN (in2[6]), .B (in1[6]), .Y (sub_16_31_n_2));
  NOR2BX1 sub_16_31_g490(.AN (in1[4]), .B (in2[4]), .Y (sub_16_31_n_1));
  NAND2BX1 sub_16_31_g491(.AN (in1[3]), .B (in2[3]), .Y
       (sub_16_31_n_0));
  INVXL fopt492(.A (n_119), .Y (n_117));
  INVXL fopt493(.A (n_119), .Y (n_118));
  INVXL fopt494(.A (n_120), .Y (n_119));
  BUFX2 fopt495(.A (sub_16_31_n_3), .Y (n_120));
  BUFX3 fopt6(.A (sub_16_31_n_65), .Y (n_122));
  CLKINVX4 fopt(.A (in2[7]), .Y (n_124));
  INVXL fopt496(.A (n_128), .Y (n_126));
  INVXL fopt1(.A (n_128), .Y (n_127));
  INVXL fopt2(.A (sub_16_31_n_45), .Y (n_128));
  CLKINVX3 fopt497(.A (in2[2]), .Y (n_130));
  CLKINVX3 fopt498(.A (in2[2]), .Y (n_131));
endmodule


