`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  4 2025 00:40:26 CST (Jun  3 2025 16:40:26 UTC)

module dut_Add_8U_8_1(in1, out1);
  input [7:0] in1;
  output [7:0] out1;
  wire [7:0] in1;
  wire [7:0] out1;
  wire inc_add_15_23_1_n_0, inc_add_15_23_1_n_1, inc_add_15_23_1_n_2,
       inc_add_15_23_1_n_3, inc_add_15_23_1_n_4, inc_add_15_23_1_n_5,
       inc_add_15_23_1_n_6, inc_add_15_23_1_n_7;
  wire inc_add_15_23_1_n_8, inc_add_15_23_1_n_9, inc_add_15_23_1_n_11,
       inc_add_15_23_1_n_13, inc_add_15_23_1_n_14,
       inc_add_15_23_1_n_16, inc_add_15_23_1_n_17, inc_add_15_23_1_n_18;
  wire n_35, n_36, n_38;
  INVX1 g2(.A (in1[0]), .Y (out1[0]));
  MXI2XL inc_add_15_23_1_g68(.A (inc_add_15_23_1_n_5), .B (in1[5]), .S0
       (inc_add_15_23_1_n_17), .Y (out1[5]));
  MXI2XL inc_add_15_23_1_g69(.A (inc_add_15_23_1_n_0), .B (in1[3]), .S0
       (inc_add_15_23_1_n_14), .Y (out1[3]));
  MXI2X1 inc_add_15_23_1_g70(.A (in1[7]), .B (inc_add_15_23_1_n_4), .S0
       (inc_add_15_23_1_n_16), .Y (out1[7]));
  MXI2XL inc_add_15_23_1_g71(.A (inc_add_15_23_1_n_6), .B (in1[6]), .S0
       (inc_add_15_23_1_n_18), .Y (out1[6]));
  MXI2XL inc_add_15_23_1_g72(.A (inc_add_15_23_1_n_1), .B (in1[4]), .S0
       (n_36), .Y (out1[4]));
  NOR2X1 inc_add_15_23_1_g73(.A (inc_add_15_23_1_n_8), .B (n_35), .Y
       (inc_add_15_23_1_n_18));
  NOR2X1 inc_add_15_23_1_g74(.A (inc_add_15_23_1_n_1), .B (n_38), .Y
       (inc_add_15_23_1_n_17));
  NAND2X1 inc_add_15_23_1_g75(.A (inc_add_15_23_1_n_11), .B
       (inc_add_15_23_1_n_13), .Y (inc_add_15_23_1_n_16));
  MXI2XL inc_add_15_23_1_g76(.A (in1[2]), .B (inc_add_15_23_1_n_3), .S0
       (inc_add_15_23_1_n_7), .Y (out1[2]));
  NOR2X1 inc_add_15_23_1_g77(.A (inc_add_15_23_1_n_3), .B
       (inc_add_15_23_1_n_7), .Y (inc_add_15_23_1_n_14));
  NOR2X4 inc_add_15_23_1_g79(.A (inc_add_15_23_1_n_9), .B
       (inc_add_15_23_1_n_7), .Y (inc_add_15_23_1_n_13));
  NOR2X1 inc_add_15_23_1_g80(.A (inc_add_15_23_1_n_6), .B
       (inc_add_15_23_1_n_8), .Y (inc_add_15_23_1_n_11));
  MXI2XL inc_add_15_23_1_g81(.A (inc_add_15_23_1_n_2), .B (in1[1]), .S0
       (in1[0]), .Y (out1[1]));
  NAND2X8 inc_add_15_23_1_g82(.A (in1[3]), .B (in1[2]), .Y
       (inc_add_15_23_1_n_9));
  NAND2X2 inc_add_15_23_1_g83(.A (in1[5]), .B (in1[4]), .Y
       (inc_add_15_23_1_n_8));
  NAND2X6 inc_add_15_23_1_g84(.A (in1[1]), .B (in1[0]), .Y
       (inc_add_15_23_1_n_7));
  INVX1 inc_add_15_23_1_g85(.A (in1[6]), .Y (inc_add_15_23_1_n_6));
  INVXL inc_add_15_23_1_g86(.A (in1[5]), .Y (inc_add_15_23_1_n_5));
  INVXL inc_add_15_23_1_g87(.A (in1[7]), .Y (inc_add_15_23_1_n_4));
  INVX1 inc_add_15_23_1_g88(.A (in1[2]), .Y (inc_add_15_23_1_n_3));
  INVX1 inc_add_15_23_1_g89(.A (in1[1]), .Y (inc_add_15_23_1_n_2));
  INVX1 inc_add_15_23_1_g90(.A (in1[4]), .Y (inc_add_15_23_1_n_1));
  INVXL inc_add_15_23_1_g91(.A (in1[3]), .Y (inc_add_15_23_1_n_0));
  CLKINVX1 fopt(.A (inc_add_15_23_1_n_13), .Y (n_35));
  BUFX2 fopt1(.A (inc_add_15_23_1_n_13), .Y (n_36));
  CLKINVX1 fopt2(.A (inc_add_15_23_1_n_13), .Y (n_38));
endmodule


