`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  4 2025 00:50:30 CST (Jun  3 2025 16:50:30 UTC)

module dut_Equal_1U_22_4(in1, out1);
  input [6:0] in1;
  output out1;
  wire [6:0] in1;
  wire out1;
  wire n_0;
  NOR4X1 g39(.A (in1[5]), .B (in1[4]), .C (in1[6]), .D (n_0), .Y
       (out1));
  NAND4XL g40(.A (in1[3]), .B (in1[2]), .C (in1[1]), .D (in1[0]), .Y
       (n_0));
endmodule


