`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  4 2025 00:40:15 CST (Jun  3 2025 16:40:15 UTC)

module dut_Add_17Sx8U_17S_1(in2, in1, out1);
  input [16:0] in2;
  input [7:0] in1;
  output [16:0] out1;
  wire [16:0] in2;
  wire [7:0] in1;
  wire [16:0] out1;
  wire add_16_23_n_1, add_16_23_n_2, add_16_23_n_3, add_16_23_n_7,
       add_16_23_n_11, add_16_23_n_13, add_16_23_n_14, add_16_23_n_15;
  wire add_16_23_n_16, add_16_23_n_17, add_16_23_n_18, add_16_23_n_19,
       add_16_23_n_20, add_16_23_n_21, add_16_23_n_22, add_16_23_n_23;
  wire add_16_23_n_24, add_16_23_n_25, add_16_23_n_26, add_16_23_n_27,
       add_16_23_n_28, add_16_23_n_29, add_16_23_n_30, add_16_23_n_31;
  wire add_16_23_n_32, add_16_23_n_33, add_16_23_n_34, add_16_23_n_35,
       add_16_23_n_36, add_16_23_n_37, add_16_23_n_38, add_16_23_n_39;
  wire add_16_23_n_40, add_16_23_n_41, add_16_23_n_42, add_16_23_n_43,
       add_16_23_n_44, add_16_23_n_45, add_16_23_n_46, add_16_23_n_47;
  wire add_16_23_n_48, add_16_23_n_49, add_16_23_n_50, add_16_23_n_51,
       add_16_23_n_52, add_16_23_n_53, add_16_23_n_54, add_16_23_n_55;
  wire add_16_23_n_56, add_16_23_n_57, add_16_23_n_58, add_16_23_n_59,
       add_16_23_n_60, add_16_23_n_61, add_16_23_n_62, add_16_23_n_63;
  wire add_16_23_n_64, add_16_23_n_65, add_16_23_n_66, add_16_23_n_67,
       add_16_23_n_68, add_16_23_n_69, add_16_23_n_70, add_16_23_n_71;
  wire add_16_23_n_72, add_16_23_n_73, add_16_23_n_74, add_16_23_n_75,
       add_16_23_n_76, add_16_23_n_77, add_16_23_n_78, add_16_23_n_79;
  wire add_16_23_n_80, add_16_23_n_81, add_16_23_n_82, add_16_23_n_83,
       add_16_23_n_84, n_119, n_120, n_121;
  wire n_123;
  MXI2XL add_16_23_g363(.A (add_16_23_n_21), .B (in2[9]), .S0
       (add_16_23_n_82), .Y (out1[9]));
  MXI2XL add_16_23_g364(.A (add_16_23_n_17), .B (in2[13]), .S0
       (add_16_23_n_79), .Y (out1[13]));
  MXI2XL add_16_23_g365(.A (add_16_23_n_20), .B (in2[11]), .S0
       (add_16_23_n_78), .Y (out1[11]));
  MXI2XL add_16_23_g366(.A (add_16_23_n_22), .B (in2[15]), .S0
       (add_16_23_n_77), .Y (out1[15]));
  MXI2XL add_16_23_g367(.A (add_16_23_n_13), .B (in2[14]), .S0
       (add_16_23_n_81), .Y (out1[14]));
  MXI2XL add_16_23_g368(.A (add_16_23_n_16), .B (in2[12]), .S0
       (add_16_23_n_84), .Y (out1[12]));
  MXI2XL add_16_23_g369(.A (add_16_23_n_18), .B (in2[16]), .S0
       (add_16_23_n_80), .Y (out1[16]));
  MXI2XL add_16_23_g370(.A (add_16_23_n_14), .B (in2[10]), .S0
       (add_16_23_n_83), .Y (out1[10]));
  MXI2XL add_16_23_g371(.A (in2[8]), .B (add_16_23_n_15), .S0
       (add_16_23_n_76), .Y (out1[8]));
  NOR2X1 add_16_23_g375(.A (add_16_23_n_42), .B (add_16_23_n_76), .Y
       (add_16_23_n_84));
  NOR2X1 add_16_23_g376(.A (add_16_23_n_36), .B (add_16_23_n_76), .Y
       (add_16_23_n_83));
  NOR2X1 add_16_23_g377(.A (add_16_23_n_15), .B (add_16_23_n_76), .Y
       (add_16_23_n_82));
  NOR2BX1 add_16_23_g378(.AN (add_16_23_n_63), .B (add_16_23_n_76), .Y
       (add_16_23_n_81));
  NOR2X1 add_16_23_g379(.A (add_16_23_n_59), .B (add_16_23_n_76), .Y
       (add_16_23_n_80));
  NOR2X1 add_16_23_g380(.A (add_16_23_n_62), .B (add_16_23_n_76), .Y
       (add_16_23_n_79));
  NOR2X1 add_16_23_g381(.A (add_16_23_n_41), .B (add_16_23_n_76), .Y
       (add_16_23_n_78));
  NOR2X1 add_16_23_g382(.A (add_16_23_n_55), .B (add_16_23_n_76), .Y
       (add_16_23_n_77));
  NOR2X2 add_16_23_g383(.A (add_16_23_n_66), .B (add_16_23_n_72), .Y
       (add_16_23_n_76));
  NOR2BX1 add_16_23_g385(.AN (add_16_23_n_37), .B (add_16_23_n_73), .Y
       (add_16_23_n_75));
  NOR2X1 add_16_23_g388(.A (add_16_23_n_67), .B (add_16_23_n_71), .Y
       (add_16_23_n_74));
  NOR2X1 add_16_23_g390(.A (add_16_23_n_28), .B (add_16_23_n_69), .Y
       (add_16_23_n_73));
  NOR2X2 add_16_23_g391(.A (add_16_23_n_61), .B (add_16_23_n_69), .Y
       (add_16_23_n_72));
  NOR2X1 add_16_23_g392(.A (add_16_23_n_60), .B (add_16_23_n_69), .Y
       (add_16_23_n_71));
  NOR2BX1 add_16_23_g393(.AN (add_16_23_n_24), .B (add_16_23_n_2), .Y
       (add_16_23_n_70));
  NOR2X4 add_16_23_g395(.A (add_16_23_n_56), .B (add_16_23_n_68), .Y
       (add_16_23_n_69));
  NOR2X2 add_16_23_g397(.A (add_16_23_n_3), .B (add_16_23_n_65), .Y
       (add_16_23_n_68));
  OAI21X1 add_16_23_g398(.A0 (add_16_23_n_33), .A1 (add_16_23_n_57),
       .B0 (add_16_23_n_39), .Y (add_16_23_n_67));
  OAI21X1 add_16_23_g399(.A0 (add_16_23_n_54), .A1 (add_16_23_n_57),
       .B0 (add_16_23_n_58), .Y (add_16_23_n_66));
  NOR2X4 add_16_23_g400(.A (add_16_23_n_1), .B (add_16_23_n_64), .Y
       (add_16_23_n_65));
  NOR2X2 add_16_23_g402(.A (add_16_23_n_31), .B (add_16_23_n_27), .Y
       (add_16_23_n_64));
  NOR2X1 add_16_23_g404(.A (add_16_23_n_35), .B (add_16_23_n_42), .Y
       (add_16_23_n_63));
  NAND2X1 add_16_23_g405(.A (in2[12]), .B (add_16_23_n_43), .Y
       (add_16_23_n_62));
  NAND2X1 add_16_23_g406(.A (add_16_23_n_53), .B (add_16_23_n_49), .Y
       (add_16_23_n_61));
  NAND2BX1 add_16_23_g407(.AN (add_16_23_n_33), .B (add_16_23_n_49), .Y
       (add_16_23_n_60));
  NAND4BX1 add_16_23_g408(.AN (add_16_23_n_35), .B (in2[14]), .C
       (in2[15]), .D (add_16_23_n_43), .Y (add_16_23_n_59));
  AOI2BB1X1 add_16_23_g409(.A0N (add_16_23_n_39), .A1N
       (add_16_23_n_26), .B0 (add_16_23_n_29), .Y (add_16_23_n_58));
  NOR2X2 add_16_23_g411(.A (add_16_23_n_40), .B (add_16_23_n_48), .Y
       (add_16_23_n_57));
  OAI21X2 add_16_23_g412(.A0 (add_16_23_n_24), .A1 (add_16_23_n_38),
       .B0 (add_16_23_n_30), .Y (add_16_23_n_56));
  NAND3BXL add_16_23_g413(.AN (add_16_23_n_35), .B (add_16_23_n_43), .C
       (in2[14]), .Y (add_16_23_n_55));
  INVX1 add_16_23_g414(.A (add_16_23_n_53), .Y (add_16_23_n_54));
  NOR2X1 add_16_23_g419(.A (add_16_23_n_37), .B (add_16_23_n_34), .Y
       (add_16_23_n_48));
  NOR2X1 add_16_23_g420(.A (add_16_23_n_1), .B (add_16_23_n_31), .Y
       (add_16_23_n_47));
  NOR2X1 add_16_23_g421(.A (add_16_23_n_26), .B (add_16_23_n_33), .Y
       (add_16_23_n_53));
  NOR2BX1 add_16_23_g422(.AN (add_16_23_n_30), .B (n_123), .Y
       (add_16_23_n_52));
  NAND2X1 add_16_23_g423(.A (add_16_23_n_24), .B (add_16_23_n_25), .Y
       (add_16_23_n_51));
  NAND2BX1 add_16_23_g424(.AN (add_16_23_n_28), .B (add_16_23_n_37), .Y
       (add_16_23_n_50));
  NOR2X1 add_16_23_g425(.A (add_16_23_n_34), .B (add_16_23_n_28), .Y
       (add_16_23_n_49));
  INVX1 add_16_23_g429(.A (add_16_23_n_43), .Y (add_16_23_n_42));
  OR2XL add_16_23_g431(.A (add_16_23_n_14), .B (add_16_23_n_36), .Y
       (add_16_23_n_41));
  NOR2X1 add_16_23_g433(.A (add_16_23_n_29), .B (add_16_23_n_26), .Y
       (add_16_23_n_46));
  NAND2BX1 add_16_23_g434(.AN (add_16_23_n_33), .B (add_16_23_n_39), .Y
       (add_16_23_n_45));
  NOR2X1 add_16_23_g435(.A (add_16_23_n_40), .B (add_16_23_n_34), .Y
       (add_16_23_n_44));
  NOR2X1 add_16_23_g436(.A (add_16_23_n_32), .B (add_16_23_n_36), .Y
       (add_16_23_n_43));
  NAND2X1 add_16_23_g438(.A (in2[11]), .B (in2[10]), .Y
       (add_16_23_n_32));
  AND2X1 add_16_23_g439(.A (in2[5]), .B (in1[5]), .Y (add_16_23_n_40));
  NAND2X1 add_16_23_g440(.A (in2[6]), .B (in1[6]), .Y (add_16_23_n_39));
  NOR2X8 add_16_23_g441(.A (in2[3]), .B (in1[3]), .Y (add_16_23_n_38));
  NAND2X1 add_16_23_g442(.A (in2[4]), .B (in1[4]), .Y (add_16_23_n_37));
  NAND2X1 add_16_23_g443(.A (in2[9]), .B (in2[8]), .Y (add_16_23_n_36));
  NAND2X1 add_16_23_g444(.A (in2[13]), .B (in2[12]), .Y
       (add_16_23_n_35));
  NOR2X2 add_16_23_g445(.A (in2[5]), .B (in1[5]), .Y (add_16_23_n_34));
  NOR2X2 add_16_23_g446(.A (in2[6]), .B (in1[6]), .Y (add_16_23_n_33));
  NOR2X6 add_16_23_g448(.A (in2[1]), .B (in1[1]), .Y (add_16_23_n_31));
  NAND2X1 add_16_23_g449(.A (in2[3]), .B (in1[3]), .Y (add_16_23_n_30));
  AND2X1 add_16_23_g451(.A (in2[7]), .B (in1[7]), .Y (add_16_23_n_29));
  NOR2X1 add_16_23_g452(.A (in2[4]), .B (in1[4]), .Y (add_16_23_n_28));
  NAND2X6 add_16_23_g453(.A (in2[0]), .B (in1[0]), .Y (add_16_23_n_27));
  NOR2X2 add_16_23_g454(.A (in2[7]), .B (in1[7]), .Y (add_16_23_n_26));
  NAND2X4 add_16_23_g455(.A (add_16_23_n_19), .B (add_16_23_n_23), .Y
       (add_16_23_n_25));
  NAND2X1 add_16_23_g456(.A (in2[2]), .B (in1[2]), .Y (add_16_23_n_24));
  CLKINVX2 add_16_23_g458(.A (in1[2]), .Y (add_16_23_n_23));
  INVXL add_16_23_g459(.A (in2[15]), .Y (add_16_23_n_22));
  INVXL add_16_23_g461(.A (in2[9]), .Y (add_16_23_n_21));
  INVXL add_16_23_g462(.A (in2[11]), .Y (add_16_23_n_20));
  CLKINVX2 add_16_23_g464(.A (in2[2]), .Y (add_16_23_n_19));
  INVXL add_16_23_g465(.A (in2[16]), .Y (add_16_23_n_18));
  INVXL add_16_23_g466(.A (in2[13]), .Y (add_16_23_n_17));
  INVXL add_16_23_g467(.A (in2[12]), .Y (add_16_23_n_16));
  INVX1 add_16_23_g468(.A (in2[8]), .Y (add_16_23_n_15));
  INVX1 add_16_23_g469(.A (in2[10]), .Y (add_16_23_n_14));
  INVXL add_16_23_g470(.A (in2[14]), .Y (add_16_23_n_13));
  XNOR2X1 add_16_23_g2(.A (add_16_23_n_27), .B (add_16_23_n_47), .Y
       (out1[1]));
  NOR2BX1 add_16_23_g471(.AN (add_16_23_n_57), .B (add_16_23_n_7), .Y
       (add_16_23_n_11));
  XNOR2X1 add_16_23_g472(.A (add_16_23_n_52), .B (add_16_23_n_70), .Y
       (out1[3]));
  CLKXOR2X1 add_16_23_g473(.A (add_16_23_n_51), .B (n_119), .Y
       (out1[2]));
  CLKXOR2X1 add_16_23_g474(.A (add_16_23_n_50), .B (add_16_23_n_69), .Y
       (out1[4]));
  NOR2BX1 add_16_23_g475(.AN (add_16_23_n_49), .B (add_16_23_n_69), .Y
       (add_16_23_n_7));
  XNOR2XL add_16_23_g476(.A (add_16_23_n_46), .B (add_16_23_n_74), .Y
       (out1[7]));
  CLKXOR2X1 add_16_23_g477(.A (add_16_23_n_45), .B (add_16_23_n_11), .Y
       (out1[6]));
  XNOR2XL add_16_23_g478(.A (add_16_23_n_44), .B (add_16_23_n_75), .Y
       (out1[5]));
  NAND2BX1 add_16_23_g479(.AN (add_16_23_n_38), .B (add_16_23_n_25), .Y
       (add_16_23_n_3));
  NOR2BX1 add_16_23_g480(.AN (add_16_23_n_25), .B (n_120), .Y
       (add_16_23_n_2));
  CLKAND2X6 add_16_23_g481(.A (in2[1]), .B (in1[1]), .Y
       (add_16_23_n_1));
  CLKXOR2X1 add_16_23_g482(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  INVXL fopt(.A (n_121), .Y (n_119));
  INVXL fopt1(.A (n_121), .Y (n_120));
  INVXL fopt2(.A (add_16_23_n_65), .Y (n_121));
  BUFX2 fopt483(.A (add_16_23_n_38), .Y (n_123));
endmodule


