`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  4 2025 00:40:13 CST (Jun  3 2025 16:40:13 UTC)

module dut_Add_8Ux1U_8U_1(in2, in1, out1);
  input [7:0] in2;
  input in1;
  output [7:0] out1;
  wire [7:0] in2;
  wire in1;
  wire [7:0] out1;
  wire inc_add_16_23_1_n_0, inc_add_16_23_1_n_2, inc_add_16_23_1_n_3,
       inc_add_16_23_1_n_4, inc_add_16_23_1_n_5, inc_add_16_23_1_n_6,
       inc_add_16_23_1_n_7, inc_add_16_23_1_n_8;
  wire inc_add_16_23_1_n_9, inc_add_16_23_1_n_10, inc_add_16_23_1_n_11,
       inc_add_16_23_1_n_12, inc_add_16_23_1_n_14,
       inc_add_16_23_1_n_15, inc_add_16_23_1_n_17, inc_add_16_23_1_n_19;
  wire inc_add_16_23_1_n_20, inc_add_16_23_1_n_21, n_38, n_40, n_42;
  MXI2XL inc_add_16_23_1_g71(.A (inc_add_16_23_1_n_2), .B (in2[5]), .S0
       (inc_add_16_23_1_n_20), .Y (out1[5]));
  MXI2XL inc_add_16_23_1_g72(.A (inc_add_16_23_1_n_9), .B (in2[3]), .S0
       (inc_add_16_23_1_n_0), .Y (out1[3]));
  MXI2XL inc_add_16_23_1_g73(.A (inc_add_16_23_1_n_5), .B (in2[7]), .S0
       (inc_add_16_23_1_n_19), .Y (out1[7]));
  MXI2XL inc_add_16_23_1_g74(.A (inc_add_16_23_1_n_8), .B (in2[6]), .S0
       (inc_add_16_23_1_n_21), .Y (out1[6]));
  NOR2X1 inc_add_16_23_1_g76(.A (n_42), .B (inc_add_16_23_1_n_17), .Y
       (inc_add_16_23_1_n_21));
  NOR2X1 inc_add_16_23_1_g77(.A (inc_add_16_23_1_n_4), .B
       (inc_add_16_23_1_n_17), .Y (inc_add_16_23_1_n_20));
  NOR2X1 inc_add_16_23_1_g78(.A (inc_add_16_23_1_n_14), .B
       (inc_add_16_23_1_n_17), .Y (inc_add_16_23_1_n_19));
  MXI2XL inc_add_16_23_1_g79(.A (inc_add_16_23_1_n_3), .B (in2[2]), .S0
       (n_40), .Y (out1[2]));
  NAND2X4 inc_add_16_23_1_g82(.A (inc_add_16_23_1_n_12), .B
       (inc_add_16_23_1_n_15), .Y (inc_add_16_23_1_n_17));
  MXI2XL inc_add_16_23_1_g84(.A (in2[1]), .B (inc_add_16_23_1_n_7), .S0
       (n_38), .Y (out1[1]));
  NOR2X6 inc_add_16_23_1_g85(.A (inc_add_16_23_1_n_7), .B
       (inc_add_16_23_1_n_10), .Y (inc_add_16_23_1_n_15));
  OR2XL inc_add_16_23_1_g86(.A (inc_add_16_23_1_n_8), .B
       (inc_add_16_23_1_n_11), .Y (inc_add_16_23_1_n_14));
  MXI2XL inc_add_16_23_1_g87(.A (inc_add_16_23_1_n_6), .B (in2[0]), .S0
       (in1), .Y (out1[0]));
  NOR2X4 inc_add_16_23_1_g88(.A (inc_add_16_23_1_n_9), .B
       (inc_add_16_23_1_n_3), .Y (inc_add_16_23_1_n_12));
  NAND2X1 inc_add_16_23_1_g89(.A (in2[5]), .B (in2[4]), .Y
       (inc_add_16_23_1_n_11));
  NAND2X8 inc_add_16_23_1_g90(.A (in2[0]), .B (in1), .Y
       (inc_add_16_23_1_n_10));
  CLKINVX2 inc_add_16_23_1_g91(.A (in2[3]), .Y (inc_add_16_23_1_n_9));
  INVX1 inc_add_16_23_1_g92(.A (in2[6]), .Y (inc_add_16_23_1_n_8));
  CLKINVX2 inc_add_16_23_1_g93(.A (in2[1]), .Y (inc_add_16_23_1_n_7));
  INVX1 inc_add_16_23_1_g94(.A (in2[0]), .Y (inc_add_16_23_1_n_6));
  INVXL inc_add_16_23_1_g95(.A (in2[7]), .Y (inc_add_16_23_1_n_5));
  INVX1 inc_add_16_23_1_g96(.A (in2[4]), .Y (inc_add_16_23_1_n_4));
  CLKINVX2 inc_add_16_23_1_g97(.A (in2[2]), .Y (inc_add_16_23_1_n_3));
  INVXL inc_add_16_23_1_g98(.A (in2[5]), .Y (inc_add_16_23_1_n_2));
  MXI2XL inc_add_16_23_1_g2(.A (in2[4]), .B (inc_add_16_23_1_n_4), .S0
       (inc_add_16_23_1_n_17), .Y (out1[4]));
  NOR2BX1 inc_add_16_23_1_g99(.AN (inc_add_16_23_1_n_15), .B
       (inc_add_16_23_1_n_3), .Y (inc_add_16_23_1_n_0));
  BUFX2 fopt(.A (inc_add_16_23_1_n_10), .Y (n_38));
  BUFX2 fopt101(.A (inc_add_16_23_1_n_15), .Y (n_40));
  BUFX2 fopt102(.A (inc_add_16_23_1_n_11), .Y (n_42));
endmodule


