`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  4 2025 00:50:37 CST (Jun  3 2025 16:50:37 UTC)

module dut_Equal_1U_48_4(in1, out1);
  input [6:0] in1;
  output out1;
  wire [6:0] in1;
  wire out1;
  wire n_0;
  NOR4BBX1 g26(.AN (in1[5]), .BN (n_0), .C (in1[4]), .D (in1[3]), .Y
       (out1));
  NOR4BX1 g27(.AN (in1[0]), .B (in1[6]), .C (in1[2]), .D (in1[1]), .Y
       (n_0));
endmodule


