`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  4 2025 00:50:43 CST (Jun  3 2025 16:50:43 UTC)

module dut_Equal_1U_62_4(in1, out1);
  input [6:0] in1;
  output out1;
  wire [6:0] in1;
  wire out1;
  wire n_0, n_1;
  NOR3XL g50(.A (n_1), .B (in1[5]), .C (in1[4]), .Y (out1));
  NAND4XL g51(.A (in1[6]), .B (n_0), .C (in1[3]), .D (in1[2]), .Y
       (n_1));
  NOR2X1 g52(.A (in1[1]), .B (in1[0]), .Y (n_0));
endmodule


