`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  4 2025 00:51:59 CST (Jun  3 2025 16:51:59 UTC)

module dut_Equal_1U_100_1(in1, out1);
  input [6:0] in1;
  output out1;
  wire [6:0] in1;
  wire out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5;
  NOR2X1 g49(.A (n_4), .B (n_5), .Y (out1));
  NAND2BX1 g50(.AN (in1[4]), .B (n_3), .Y (n_5));
  NAND2X1 g51(.A (n_2), .B (n_1), .Y (n_4));
  NOR2X2 g52(.A (in1[5]), .B (n_0), .Y (n_3));
  NOR2X6 g53(.A (in1[3]), .B (in1[2]), .Y (n_2));
  NOR2X2 g54(.A (in1[1]), .B (in1[0]), .Y (n_1));
  CLKINVX12 g55(.A (in1[6]), .Y (n_0));
endmodule


