`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  4 2025 00:40:17 CST (Jun  3 2025 16:40:17 UTC)

module dut_Sub_16Ux8U_16S_1(in2, in1, out1);
  input [15:0] in2;
  input [7:0] in1;
  output [15:0] out1;
  wire [15:0] in2;
  wire [7:0] in1;
  wire [15:0] out1;
  wire sub_16_23_n_1, sub_16_23_n_2, sub_16_23_n_3, sub_16_23_n_4,
       sub_16_23_n_5, sub_16_23_n_6, sub_16_23_n_7, sub_16_23_n_8;
  wire sub_16_23_n_9, sub_16_23_n_10, sub_16_23_n_14, sub_16_23_n_17,
       sub_16_23_n_20, sub_16_23_n_21, sub_16_23_n_22, sub_16_23_n_23;
  wire sub_16_23_n_24, sub_16_23_n_25, sub_16_23_n_26, sub_16_23_n_27,
       sub_16_23_n_28, sub_16_23_n_29, sub_16_23_n_30, sub_16_23_n_31;
  wire sub_16_23_n_32, sub_16_23_n_33, sub_16_23_n_34, sub_16_23_n_35,
       sub_16_23_n_36, sub_16_23_n_37, sub_16_23_n_38, sub_16_23_n_39;
  wire sub_16_23_n_40, sub_16_23_n_41, sub_16_23_n_42, sub_16_23_n_43,
       sub_16_23_n_44, sub_16_23_n_45, sub_16_23_n_46, sub_16_23_n_47;
  wire sub_16_23_n_48, sub_16_23_n_49, sub_16_23_n_50, sub_16_23_n_51,
       sub_16_23_n_52, sub_16_23_n_53, sub_16_23_n_54, sub_16_23_n_55;
  wire sub_16_23_n_56, sub_16_23_n_57, sub_16_23_n_58, sub_16_23_n_59,
       sub_16_23_n_60, sub_16_23_n_61, sub_16_23_n_62, sub_16_23_n_63;
  wire sub_16_23_n_64, sub_16_23_n_65, sub_16_23_n_66, sub_16_23_n_67,
       sub_16_23_n_68, sub_16_23_n_69, sub_16_23_n_70, sub_16_23_n_71;
  wire sub_16_23_n_72, sub_16_23_n_73, sub_16_23_n_74, sub_16_23_n_75,
       sub_16_23_n_76, sub_16_23_n_77, sub_16_23_n_78, sub_16_23_n_79;
  wire sub_16_23_n_80, sub_16_23_n_81, sub_16_23_n_82;
  MXI2XL sub_16_23_g381(.A (sub_16_23_n_28), .B (in2[9]), .S0
       (sub_16_23_n_80), .Y (out1[9]));
  MXI2XL sub_16_23_g382(.A (in2[12]), .B (sub_16_23_n_26), .S0
       (sub_16_23_n_82), .Y (out1[12]));
  MXI2XL sub_16_23_g383(.A (in2[14]), .B (sub_16_23_n_22), .S0
       (sub_16_23_n_79), .Y (out1[14]));
  MXI2XL sub_16_23_g384(.A (in2[13]), .B (sub_16_23_n_23), .S0
       (sub_16_23_n_77), .Y (out1[13]));
  MXI2XL sub_16_23_g385(.A (in2[10]), .B (sub_16_23_n_25), .S0
       (sub_16_23_n_81), .Y (out1[10]));
  MXI2XL sub_16_23_g386(.A (sub_16_23_n_32), .B (in2[15]), .S0
       (sub_16_23_n_78), .Y (out1[15]));
  MXI2XL sub_16_23_g387(.A (sub_16_23_n_27), .B (in2[11]), .S0
       (sub_16_23_n_76), .Y (out1[11]));
  MXI2XL sub_16_23_g388(.A (sub_16_23_n_20), .B (in2[8]), .S0
       (sub_16_23_n_74), .Y (out1[8]));
  NAND2X1 sub_16_23_g392(.A (sub_16_23_n_47), .B (sub_16_23_n_74), .Y
       (sub_16_23_n_82));
  NAND2X1 sub_16_23_g393(.A (sub_16_23_n_34), .B (sub_16_23_n_74), .Y
       (sub_16_23_n_81));
  NOR2X1 sub_16_23_g394(.A (in2[8]), .B (sub_16_23_n_73), .Y
       (sub_16_23_n_80));
  NAND2X1 sub_16_23_g395(.A (sub_16_23_n_63), .B (sub_16_23_n_74), .Y
       (sub_16_23_n_79));
  NOR2X1 sub_16_23_g396(.A (sub_16_23_n_57), .B (sub_16_23_n_73), .Y
       (sub_16_23_n_78));
  NAND2X1 sub_16_23_g397(.A (sub_16_23_n_62), .B (sub_16_23_n_74), .Y
       (sub_16_23_n_77));
  NOR2X1 sub_16_23_g398(.A (sub_16_23_n_52), .B (sub_16_23_n_73), .Y
       (sub_16_23_n_76));
  NOR2X1 sub_16_23_g400(.A (sub_16_23_n_6), .B (sub_16_23_n_71), .Y
       (sub_16_23_n_75));
  CLKINVX4 sub_16_23_g401(.A (sub_16_23_n_74), .Y (sub_16_23_n_73));
  NOR2X6 sub_16_23_g402(.A (sub_16_23_n_65), .B (sub_16_23_n_70), .Y
       (sub_16_23_n_74));
  NOR2X1 sub_16_23_g405(.A (sub_16_23_n_66), .B (sub_16_23_n_69), .Y
       (sub_16_23_n_72));
  NOR2X1 sub_16_23_g407(.A (sub_16_23_n_3), .B (sub_16_23_n_67), .Y
       (sub_16_23_n_71));
  NOR2X2 sub_16_23_g408(.A (sub_16_23_n_61), .B (sub_16_23_n_67), .Y
       (sub_16_23_n_70));
  NOR2X1 sub_16_23_g409(.A (sub_16_23_n_60), .B (sub_16_23_n_67), .Y
       (sub_16_23_n_69));
  AOI21X1 sub_16_23_g410(.A0 (sub_16_23_n_42), .A1 (sub_16_23_n_64),
       .B0 (sub_16_23_n_41), .Y (sub_16_23_n_68));
  AOI21X2 sub_16_23_g412(.A0 (sub_16_23_n_64), .A1 (sub_16_23_n_10),
       .B0 (sub_16_23_n_56), .Y (sub_16_23_n_67));
  OAI21X1 sub_16_23_g414(.A0 (sub_16_23_n_2), .A1 (sub_16_23_n_59), .B0
       (sub_16_23_n_33), .Y (sub_16_23_n_66));
  OAI21X2 sub_16_23_g415(.A0 (sub_16_23_n_59), .A1 (sub_16_23_n_49),
       .B0 (sub_16_23_n_58), .Y (sub_16_23_n_65));
  OAI21X2 sub_16_23_g416(.A0 (sub_16_23_n_37), .A1 (sub_16_23_n_43),
       .B0 (sub_16_23_n_35), .Y (sub_16_23_n_64));
  AND2XL sub_16_23_g419(.A (sub_16_23_n_45), .B (sub_16_23_n_47), .Y
       (sub_16_23_n_63));
  AND2XL sub_16_23_g420(.A (sub_16_23_n_26), .B (sub_16_23_n_47), .Y
       (sub_16_23_n_62));
  NAND2X1 sub_16_23_g421(.A (sub_16_23_n_53), .B (sub_16_23_n_7), .Y
       (sub_16_23_n_61));
  NAND2BX1 sub_16_23_g422(.AN (sub_16_23_n_2), .B (sub_16_23_n_53), .Y
       (sub_16_23_n_60));
  AOI21X2 sub_16_23_g424(.A0 (sub_16_23_n_39), .A1 (sub_16_23_n_6), .B0
       (sub_16_23_n_36), .Y (sub_16_23_n_59));
  AOI21X1 sub_16_23_g425(.A0 (sub_16_23_n_4), .A1 (sub_16_23_n_1), .B0
       (sub_16_23_n_46), .Y (sub_16_23_n_58));
  NAND3X1 sub_16_23_g426(.A (sub_16_23_n_47), .B (sub_16_23_n_22), .C
       (sub_16_23_n_45), .Y (sub_16_23_n_57));
  OAI2BB1X1 sub_16_23_g427(.A0N (sub_16_23_n_44), .A1N
       (sub_16_23_n_41), .B0 (sub_16_23_n_5), .Y (sub_16_23_n_56));
  NAND2X1 sub_16_23_g432(.A (sub_16_23_n_25), .B (sub_16_23_n_34), .Y
       (sub_16_23_n_52));
  NOR2BX1 sub_16_23_g433(.AN (sub_16_23_n_4), .B (sub_16_23_n_46), .Y
       (sub_16_23_n_55));
  NAND2X1 sub_16_23_g435(.A (sub_16_23_n_44), .B (sub_16_23_n_5), .Y
       (sub_16_23_n_54));
  NOR2X2 sub_16_23_g437(.A (sub_16_23_n_3), .B (sub_16_23_n_40), .Y
       (sub_16_23_n_53));
  INVX1 sub_16_23_g440(.A (sub_16_23_n_7), .Y (sub_16_23_n_49));
  NOR2X1 sub_16_23_g444(.A (sub_16_23_n_2), .B (sub_16_23_n_1), .Y
       (sub_16_23_n_51));
  NOR2X1 sub_16_23_g445(.A (sub_16_23_n_3), .B (sub_16_23_n_6), .Y
       (sub_16_23_n_50));
  NOR2X1 sub_16_23_g447(.A (sub_16_23_n_40), .B (sub_16_23_n_36), .Y
       (sub_16_23_n_48));
  AND2XL sub_16_23_g448(.A (sub_16_23_n_38), .B (sub_16_23_n_34), .Y
       (sub_16_23_n_47));
  INVX1 sub_16_23_g452(.A (sub_16_23_n_39), .Y (sub_16_23_n_40));
  NOR2X1 sub_16_23_g453(.A (in2[11]), .B (in2[10]), .Y
       (sub_16_23_n_38));
  NOR2BX1 sub_16_23_g454(.AN (in2[7]), .B (in1[7]), .Y
       (sub_16_23_n_46));
  NOR2X1 sub_16_23_g456(.A (in2[13]), .B (in2[12]), .Y
       (sub_16_23_n_45));
  NAND2X4 sub_16_23_g457(.A (in1[3]), .B (sub_16_23_n_24), .Y
       (sub_16_23_n_44));
  NOR2X2 sub_16_23_g458(.A (in2[0]), .B (sub_16_23_n_21), .Y
       (sub_16_23_n_43));
  NAND2X2 sub_16_23_g459(.A (in1[2]), .B (sub_16_23_n_31), .Y
       (sub_16_23_n_42));
  NOR2X2 sub_16_23_g460(.A (in1[2]), .B (sub_16_23_n_31), .Y
       (sub_16_23_n_41));
  NAND2X2 sub_16_23_g461(.A (in1[5]), .B (sub_16_23_n_29), .Y
       (sub_16_23_n_39));
  INVX1 sub_16_23_g464(.A (sub_16_23_n_1), .Y (sub_16_23_n_33));
  NOR2X4 sub_16_23_g465(.A (in2[1]), .B (sub_16_23_n_30), .Y
       (sub_16_23_n_37));
  NOR2X1 sub_16_23_g466(.A (sub_16_23_n_29), .B (in1[5]), .Y
       (sub_16_23_n_36));
  NAND2X2 sub_16_23_g467(.A (in2[1]), .B (sub_16_23_n_30), .Y
       (sub_16_23_n_35));
  NOR2X1 sub_16_23_g468(.A (in2[9]), .B (in2[8]), .Y (sub_16_23_n_34));
  INVXL sub_16_23_g476(.A (in2[15]), .Y (sub_16_23_n_32));
  INVX3 sub_16_23_g478(.A (in2[2]), .Y (sub_16_23_n_31));
  CLKINVX12 sub_16_23_g479(.A (in1[1]), .Y (sub_16_23_n_30));
  INVX1 sub_16_23_g480(.A (in2[5]), .Y (sub_16_23_n_29));
  INVXL sub_16_23_g481(.A (in2[9]), .Y (sub_16_23_n_28));
  INVXL sub_16_23_g482(.A (in2[11]), .Y (sub_16_23_n_27));
  INVX1 sub_16_23_g483(.A (in2[12]), .Y (sub_16_23_n_26));
  INVX1 sub_16_23_g484(.A (in2[10]), .Y (sub_16_23_n_25));
  CLKINVX4 sub_16_23_g486(.A (in2[3]), .Y (sub_16_23_n_24));
  INVXL sub_16_23_g489(.A (in2[13]), .Y (sub_16_23_n_23));
  INVX1 sub_16_23_g490(.A (in2[14]), .Y (sub_16_23_n_22));
  CLKINVX2 sub_16_23_g492(.A (in1[0]), .Y (sub_16_23_n_21));
  INVXL sub_16_23_g493(.A (in2[8]), .Y (sub_16_23_n_20));
  XNOR2X1 sub_16_23_g2(.A (sub_16_23_n_9), .B (sub_16_23_n_64), .Y
       (out1[2]));
  CLKXOR2X1 sub_16_23_g494(.A (sub_16_23_n_43), .B (sub_16_23_n_8), .Y
       (out1[1]));
  NOR2BX1 sub_16_23_g495(.AN (sub_16_23_n_59), .B (sub_16_23_n_14), .Y
       (sub_16_23_n_17));
  XNOR2X1 sub_16_23_g496(.A (sub_16_23_n_55), .B (sub_16_23_n_72), .Y
       (out1[7]));
  CLKXOR2X1 sub_16_23_g497(.A (sub_16_23_n_54), .B (sub_16_23_n_68), .Y
       (out1[3]));
  NOR2BX1 sub_16_23_g498(.AN (sub_16_23_n_53), .B (sub_16_23_n_67), .Y
       (sub_16_23_n_14));
  XNOR2X1 sub_16_23_g499(.A (sub_16_23_n_51), .B (sub_16_23_n_17), .Y
       (out1[6]));
  XNOR2X1 sub_16_23_g500(.A (sub_16_23_n_50), .B (sub_16_23_n_67), .Y
       (out1[4]));
  XNOR2X1 sub_16_23_g501(.A (sub_16_23_n_48), .B (sub_16_23_n_75), .Y
       (out1[5]));
  CLKAND2X2 sub_16_23_g502(.A (sub_16_23_n_44), .B (sub_16_23_n_42), .Y
       (sub_16_23_n_10));
  NAND2BX1 sub_16_23_g503(.AN (sub_16_23_n_41), .B (sub_16_23_n_42), .Y
       (sub_16_23_n_9));
  NAND2BX1 sub_16_23_g504(.AN (sub_16_23_n_37), .B (sub_16_23_n_35), .Y
       (sub_16_23_n_8));
  NOR2BX1 sub_16_23_g505(.AN (sub_16_23_n_4), .B (sub_16_23_n_2), .Y
       (sub_16_23_n_7));
  NOR2BX2 sub_16_23_g506(.AN (in2[4]), .B (in1[4]), .Y (sub_16_23_n_6));
  NAND2BX1 sub_16_23_g507(.AN (in1[3]), .B (in2[3]), .Y
       (sub_16_23_n_5));
  NAND2BX1 sub_16_23_g508(.AN (in2[7]), .B (in1[7]), .Y
       (sub_16_23_n_4));
  NOR2BX1 sub_16_23_g509(.AN (in1[4]), .B (in2[4]), .Y (sub_16_23_n_3));
  NOR2BX1 sub_16_23_g510(.AN (in1[6]), .B (in2[6]), .Y (sub_16_23_n_2));
  NOR2BX1 sub_16_23_g511(.AN (in2[6]), .B (in1[6]), .Y (sub_16_23_n_1));
  CLKXOR2X1 sub_16_23_g512(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
endmodule


