// Generated by stratus_hls 23.02-s004  (100793.100415)
// Wed Jun  4 00:39:36 2025
// from dut.cc

`timescale 1ps / 1ps


module dut_Sub_15Ux8U_15U_4( in2, in1, out1 );

    input [14:0] in2;
    input [7:0] in1;
    output [14:0] out1;

    
    // rtl_process:dut_Sub_15Ux8U_15U_4/dut_Sub_15Ux8U_15U_4_thread_1
    assign out1 = in2 - {7'b0000000, in1};

endmodule



