// Generated by stratus_hls 23.02-s004  (100793.100415)
// Wed Jun  4 00:39:36 2025
// from dut.cc

`timescale 1ps / 1ps


module dut_Not_1U_1U_4( in1, out1 );

    input in1;
    output out1;

    
    // rtl_process:dut_Not_1U_1U_4/dut_Not_1U_1U_4_thread_1
    assign out1 = !in1;

endmodule



