// Generated by stratus_hls 23.02-s004  (100793.100415)
// Wed Jun  4 00:42:28 2025
// from dut.cc

`timescale 1ps / 1ps


module dut_N_Mux_16_2_22_4( in2, ctrl1, out1 );

    input [15:0] in2;
    input ctrl1;
    output [15:0] out1;
    reg [15:0] out1;

    
    // rtl_process:dut_N_Mux_16_2_22_4/dut_N_Mux_16_2_22_4_thread_1
    always @*
      begin : dut_N_Mux_16_2_22_4_thread_1
        case (ctrl1) 
          1'b1: 
            begin
              out1 = in2;
            end
          default: 
            begin
              out1 = 16'd00000;
            end
        endcase
      end

endmodule


