// Generated by stratus_hls 23.02-s004  (100793.100415)
// Wed Jun  4 01:36:10 2025
// from dut.cc

`timescale 1ps / 1ps


module dut_N_Mux_56_2_105_1( in3, in2, ctrl1, out1 );

    input [55:0] in3;
    input [55:0] in2;
    input ctrl1;
    output [55:0] out1;
    reg [55:0] out1;

    
    // rtl_process:dut_N_Mux_56_2_105_1/dut_N_Mux_56_2_105_1_thread_1
    always @*
      begin : dut_N_Mux_56_2_105_1_thread_1
        case (ctrl1) 
          1'b1: 
            begin
              out1 = in2;
            end
          default: 
            begin
              out1 = in3;
            end
        endcase
      end

endmodule


