// Generated by stratus_hls 23.02-s004  (100793.100415)
// Mon Jun  9 10:34:47 2025
// from dut.cc

`timescale 1ps / 1ps


module dut_N_Mux_8_2_14_1( in2, ctrl1, out1 );

    input [7:0] in2;
    input ctrl1;
    output [7:0] out1;
    reg [7:0] out1;

    
    // rtl_process:dut_N_Mux_8_2_14_1/dut_N_Mux_8_2_14_1_thread_1
    always @*
      begin : dut_N_Mux_8_2_14_1_thread_1
        case (ctrl1) 
          1'b1: 
            begin
              out1 = 8'd000;
            end
          default: 
            begin
              out1 = in2;
            end
        endcase
      end

endmodule


