// Generated by stratus_hls 23.02-s004  (100793.100415)
// Wed Jun  4 00:39:36 2025
// from dut.cc

`timescale 1ps / 1ps


module dut_LeftShift_16U_0_4( in1, out1 );

    input [3:0] in1;
    output [15:0] out1;

    
    // rtl_process:dut_LeftShift_16U_0_4/dut_LeftShift_16U_0_4_thread_1
    assign out1 = 16'd00001 << in1;

endmodule


