// Generated by stratus_hls 23.02-s004  (100793.100415)
// Wed Jun  4 00:39:36 2025
// from dut.cc

`timescale 1ps / 1ps


module dut_LessThan_1U_4_4( in1, out1 );

    input [8:0] in1;
    output out1;

    
    // rtl_process:dut_LessThan_1U_4_4/dut_LessThan_1U_4_4_thread_1
    assign out1 = (in1 > 9'd000 & !in1[8]);

endmodule


