// Generated by stratus_hls 23.02-s004  (100793.100415)
// Wed Jun  4 00:40:00 2025
// from dut.cc

`timescale 1ps / 1ps


module dut_Sub_4Ux1U_5S_1( in2, in1, out1 );

    input [3:0] in2;
    input in1;
    output [4:0] out1;

    
    // rtl_process:dut_Sub_4Ux1U_5S_1/dut_Sub_4Ux1U_5S_1_thread_1
    assign out1 = {1'b0, in2} - {4'b0000, in1};

endmodule


