// Generated by stratus_hls 23.02-s004  (100793.100415)
// Mon Jun  9 16:43:58 2025
// from dut.cc

`timescale 1ps / 1ps


module dut_OrReduction_3U_1U_4( in1, out1 );

    input [2:0] in1;
    output out1;

    
    // rtl_process:dut_OrReduction_3U_1U_4/dut_OrReduction_3U_1U_4_thread_1
    assign out1 = (|in1);

endmodule


