// Generated by stratus_hls 23.02-s004  (100793.100415)
// Mon Jun  9 16:43:59 2025
// from dut.cc

`timescale 1ps / 1ps


module dut_N_Mux_1_2_155_4( in2, ctrl1, out1 );

    input in2;
    input ctrl1;
    output out1;
    reg out1;

    
    // rtl_process:dut_N_Mux_1_2_155_4/dut_N_Mux_1_2_155_4_thread_1
    always @*
      begin : dut_N_Mux_1_2_155_4_thread_1
        case (ctrl1) 
          1'b1: 
            begin
              out1 = 1'b0;
            end
          default: 
            begin
              out1 = in2;
            end
        endcase
      end

endmodule


