// Generated by stratus_hls 23.02-s004  (100793.100415)
// Mon Jun  9 16:43:58 2025
// from dut.cc

`timescale 1ps / 1ps


module dut_GreaterThanEQ_6Ux8U_1U_4( in2, in1, out1 );

    input [5:0] in2;
    input [7:0] in1;
    output out1;

    
    // rtl_process:dut_GreaterThanEQ_6Ux8U_1U_4/dut_GreaterThanEQ_6Ux8U_1U_4_thread_1
    assign out1 = {2'b00, in2} >= in1;

endmodule


