// Generated by stratus_hls 23.02-s004  (100793.100415)
// Wed Jun  4 01:15:07 2025
// from dut.cc

`timescale 1ps / 1ps


module dut_Muxu8i0u1_4( in2, ctrl1, out1 );

    input [7:0] in2;
    input ctrl1;
    output [7:0] out1;
    reg [7:0] out1;

    
    // rtl_process:dut_Muxu8i0u1_4/dut_Muxu8i0u1_4_thread_1
    always @*
      begin : dut_Muxu8i0u1_4_thread_1
        case (ctrl1) 
          1'b1: 
            begin
              out1 = in2;
            end
          default: 
            begin
              out1 = 8'd000;
            end
        endcase
      end

endmodule



