// Generated by stratus_hls 23.02-s004  (100793.100415)
// Wed Jun  4 00:39:36 2025
// from dut.cc

`timescale 1ps / 1ps


module dut_Add_17Sx16U_17S_4( in2, in1, out1 );

    input [16:0] in2;
    input [15:0] in1;
    output [16:0] out1;

    
    // rtl_process:dut_Add_17Sx16U_17S_4/dut_Add_17Sx16U_17S_4_thread_1
    assign out1 = in2 + {1'b0, in1};

endmodule



