// Generated by stratus_hls 23.02-s004  (100793.100415)
// Wed Jun  4 00:40:00 2025
// from dut.cc

`timescale 1ps / 1ps


module dut_Add_8U_8_1( in1, out1 );

    input [7:0] in1;
    output [7:0] out1;

    
    // rtl_process:dut_Add_8U_8_1/dut_Add_8U_8_1_thread_1
    assign out1 = in1 + 8'd001;

endmodule



