// Generated by stratus_hls 23.02-s004  (100793.100415)
// Mon Jun  9 15:57:40 2025
// from dut.cc

`timescale 1ps / 1ps


module dut_Sub_4Ux1U_5S_4( in2, in1, out1 );

    input [3:0] in2;
    input in1;
    output [4:0] out1;

    
    // rtl_process:dut_Sub_4Ux1U_5S_4/dut_Sub_4Ux1U_5S_4_thread_1
    assign out1 = {1'b0, in2} - {4'b0000, in1};

endmodule


