// Generated by stratus_hls 23.02-s004  (100793.100415)
// Mon Jun  9 17:04:39 2025
// from dut.cc

`timescale 1ps / 1ps


module dut_Add_9Ux9U_10U_4( in2, in1, out1 );

    input [8:0] in2;
    input [8:0] in1;
    output [9:0] out1;

    
    // rtl_process:dut_Add_9Ux9U_10U_4/dut_Add_9Ux9U_10U_4_thread_1
    assign out1 = {1'b0, in2} + {1'b0, in1};

endmodule


