// Generated by stratus_hls 23.02-s004  (100793.100415)
// Mon Jun  9 17:04:40 2025
// from dut.cc

`timescale 1ps / 1ps


module dut_Add_32S_145_4( in1, out1 );

    input [31:0] in1;
    output [31:0] out1;

    
    // rtl_process:dut_Add_32S_145_4/dut_Add_32S_145_4_thread_1
    assign out1 = in1 + 32'd0000000001;

endmodule


