// Generated by stratus_hls 23.02-s004  (100793.100415)
// Mon Jun  9 17:04:40 2025
// from dut.cc

`timescale 1ps / 1ps


module dut_GreaterThanEQ_1U_165_4( in1, out1 );

    input [7:0] in1;
    output out1;

    
    // rtl_process:dut_GreaterThanEQ_1U_165_4/dut_GreaterThanEQ_1U_165_4_thread_1
    assign out1 = 8'd012 >= in1;

endmodule


