// Generated by stratus_hls 23.02-s004  (100793.100415)
// Mon Jun  9 15:40:15 2025
// from dut.cc

`timescale 1ps / 1ps


module dut_Add_4U_33_4( in1, out1 );

    input [3:0] in1;
    output [3:0] out1;

    
    // rtl_process:dut_Add_4U_33_4/dut_Add_4U_33_4_thread_1
    assign out1 = in1 + 4'd01;

endmodule


