// Generated by stratus_hls 23.02-s004  (100793.100415)
// Mon Jun  9 15:46:22 2025
// from dut.cc

`timescale 1ps / 1ps


module dut_Equal_7Ux5U_1U_1( in2, in1, out1 );

    input [6:0] in2;
    input [4:0] in1;
    output out1;

    
    // rtl_process:dut_Equal_7Ux5U_1U_1/dut_Equal_7Ux5U_1U_1_thread_1
    assign out1 = in2 == {2'b00, in1};

endmodule


