`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  4 2025 00:42:43 CST (Jun  3 2025 16:42:43 UTC)

module dut_GreaterThanEQ_2Ux8U_1U_1(in2, in1, out1);
  input [1:0] in2;
  input [7:0] in1;
  output out1;
  wire [1:0] in2;
  wire [7:0] in1;
  wire out1;
  wire gte_16_36_n_0, gte_16_36_n_1, gte_16_36_n_2, gte_16_36_n_3,
       gte_16_36_n_4, gte_16_36_n_5, gte_16_36_n_6, gte_16_36_n_7;
  wire gte_16_36_n_8;
  NOR3BX1 gte_16_36_g123(.AN (gte_16_36_n_5), .B (gte_16_36_n_6), .C
       (gte_16_36_n_8), .Y (out1));
  NOR2X1 gte_16_36_g124(.A (gte_16_36_n_1), .B (gte_16_36_n_7), .Y
       (gte_16_36_n_8));
  NOR2X1 gte_16_36_g125(.A (gte_16_36_n_0), .B (gte_16_36_n_2), .Y
       (gte_16_36_n_7));
  NAND2X1 gte_16_36_g126(.A (gte_16_36_n_4), .B (gte_16_36_n_3), .Y
       (gte_16_36_n_6));
  NOR2X1 gte_16_36_g129(.A (in1[3]), .B (in1[2]), .Y (gte_16_36_n_5));
  NOR2X1 gte_16_36_g130(.A (in1[7]), .B (in1[6]), .Y (gte_16_36_n_4));
  NOR2X1 gte_16_36_g131(.A (in1[5]), .B (in1[4]), .Y (gte_16_36_n_3));
  NOR2BX1 gte_16_36_g2(.AN (in1[0]), .B (in2[0]), .Y (gte_16_36_n_2));
  NOR2BX1 gte_16_36_g136(.AN (in2[1]), .B (in1[1]), .Y (gte_16_36_n_1));
  NOR2BX1 gte_16_36_g137(.AN (in1[1]), .B (in2[1]), .Y (gte_16_36_n_0));
endmodule


