`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  4 2025 00:40:02 CST (Jun  3 2025 16:40:02 UTC)

module dut_gen_busy_r_1(in1, in2, in3, out1);
  input in1, in2, in3;
  output [2:0] out1;
  wire in1, in2, in3;
  wire [2:0] out1;
  wire n_1, n_2, n_11;
  CLKINVX3 g17(.A (out1[1]), .Y (out1[0]));
  NOR2X6 g18(.A (n_11), .B (out1[2]), .Y (out1[1]));
  NOR2X6 g19(.A (n_1), .B (n_2), .Y (out1[2]));
  NOR2X8 g20(.A (in1), .B (in3), .Y (n_2));
  CLKINVX4 g21(.A (in2), .Y (n_1));
  CLKINVX2 fopt(.A (in1), .Y (n_11));
endmodule


