`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  4 2025 00:50:35 CST (Jun  3 2025 16:50:35 UTC)

module dut_Equal_1U_38_4(in1, out1);
  input [6:0] in1;
  output out1;
  wire [6:0] in1;
  wire out1;
  wire n_0, n_1;
  NOR3BXL g39(.AN (in1[1]), .B (n_1), .C (in1[2]), .Y (out1));
  NAND4XL g40(.A (in1[0]), .B (in1[3]), .C (in1[4]), .D (n_0), .Y
       (n_1));
  NOR2X1 g41(.A (in1[6]), .B (in1[5]), .Y (n_0));
endmodule


