`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  4 2025 00:39:41 CST (Jun  3 2025 16:39:41 UTC)

module dut_Sub_15Ux8U_16S_4(in2, in1, out1);
  input [14:0] in2;
  input [7:0] in1;
  output [15:0] out1;
  wire [14:0] in2;
  wire [7:0] in1;
  wire [15:0] out1;
  wire sub_16_31_n_0, sub_16_31_n_1, sub_16_31_n_2, sub_16_31_n_3,
       sub_16_31_n_4, sub_16_31_n_5, sub_16_31_n_6, sub_16_31_n_7;
  wire sub_16_31_n_8, sub_16_31_n_9, sub_16_31_n_10, sub_16_31_n_11,
       sub_16_31_n_12, sub_16_31_n_13, sub_16_31_n_14, sub_16_31_n_16;
  wire sub_16_31_n_17, sub_16_31_n_18, sub_16_31_n_19, sub_16_31_n_20,
       sub_16_31_n_21, sub_16_31_n_22, sub_16_31_n_23, sub_16_31_n_24;
  wire sub_16_31_n_26, sub_16_31_n_27, sub_16_31_n_29, sub_16_31_n_30,
       sub_16_31_n_32, sub_16_31_n_34, sub_16_31_n_35, sub_16_31_n_36;
  wire sub_16_31_n_38, sub_16_31_n_40, sub_16_31_n_41, sub_16_31_n_42,
       sub_16_31_n_44, sub_16_31_n_45, sub_16_31_n_48, sub_16_31_n_49;
  XNOR2X1 sub_16_31_g350(.A (in2[13]), .B (sub_16_31_n_49), .Y
       (out1[13]));
  XNOR2X1 sub_16_31_g351(.A (in2[11]), .B (sub_16_31_n_45), .Y
       (out1[11]));
  XOR2XL sub_16_31_g352(.A (in2[14]), .B (sub_16_31_n_48), .Y
       (out1[14]));
  XOR2XL sub_16_31_g353(.A (in2[9]), .B (sub_16_31_n_42), .Y (out1[9]));
  NOR2BX1 sub_16_31_g354(.AN (sub_16_31_n_48), .B (in2[14]), .Y
       (out1[15]));
  OAI2BB1X1 sub_16_31_g355(.A0N (in2[12]), .A1N (sub_16_31_n_44), .B0
       (sub_16_31_n_49), .Y (out1[12]));
  OR2XL sub_16_31_g356(.A (in2[12]), .B (sub_16_31_n_44), .Y
       (sub_16_31_n_49));
  NOR3X1 sub_16_31_g357(.A (sub_16_31_n_44), .B (in2[13]), .C
       (in2[12]), .Y (sub_16_31_n_48));
  OAI2BB1X1 sub_16_31_g358(.A0N (in2[10]), .A1N (sub_16_31_n_41), .B0
       (sub_16_31_n_45), .Y (out1[10]));
  XNOR2X1 sub_16_31_g359(.A (sub_16_31_n_20), .B (sub_16_31_n_40), .Y
       (out1[7]));
  OR2XL sub_16_31_g360(.A (in2[10]), .B (sub_16_31_n_41), .Y
       (sub_16_31_n_45));
  OR3XL sub_16_31_g361(.A (sub_16_31_n_41), .B (in2[11]), .C (in2[10]),
       .Y (sub_16_31_n_44));
  AO21XL sub_16_31_g362(.A0 (in2[8]), .A1 (sub_16_31_n_38), .B0
       (sub_16_31_n_42), .Y (out1[8]));
  NOR2X1 sub_16_31_g363(.A (in2[8]), .B (sub_16_31_n_38), .Y
       (sub_16_31_n_42));
  OR3XL sub_16_31_g364(.A (sub_16_31_n_38), .B (in2[9]), .C (in2[8]),
       .Y (sub_16_31_n_41));
  OAI21X1 sub_16_31_g365(.A0 (sub_16_31_n_11), .A1 (sub_16_31_n_36),
       .B0 (sub_16_31_n_6), .Y (sub_16_31_n_40));
  XNOR2X1 sub_16_31_g366(.A (sub_16_31_n_19), .B (sub_16_31_n_36), .Y
       (out1[6]));
  OAI2BB1X1 sub_16_31_g367(.A0N (sub_16_31_n_16), .A1N
       (sub_16_31_n_35), .B0 (sub_16_31_n_24), .Y (sub_16_31_n_38));
  XNOR2X1 sub_16_31_g368(.A (sub_16_31_n_17), .B (sub_16_31_n_34), .Y
       (out1[5]));
  NOR2X1 sub_16_31_g369(.A (sub_16_31_n_23), .B (sub_16_31_n_35), .Y
       (sub_16_31_n_36));
  NOR2X1 sub_16_31_g370(.A (sub_16_31_n_10), .B (sub_16_31_n_32), .Y
       (sub_16_31_n_35));
  NAND2X1 sub_16_31_g371(.A (sub_16_31_n_9), .B (sub_16_31_n_32), .Y
       (sub_16_31_n_34));
  XNOR2X1 sub_16_31_g372(.A (sub_16_31_n_22), .B (sub_16_31_n_30), .Y
       (out1[4]));
  NAND2X1 sub_16_31_g373(.A (sub_16_31_n_7), .B (sub_16_31_n_30), .Y
       (sub_16_31_n_32));
  XNOR2X1 sub_16_31_g374(.A (sub_16_31_n_21), .B (sub_16_31_n_29), .Y
       (out1[3]));
  OAI221X1 sub_16_31_g375(.A0 (sub_16_31_n_4), .A1 (sub_16_31_n_27),
       .B0 (sub_16_31_n_4), .B1 (sub_16_31_n_2), .C0 (sub_16_31_n_12),
       .Y (sub_16_31_n_30));
  NAND2X1 sub_16_31_g376(.A (sub_16_31_n_2), .B (sub_16_31_n_27), .Y
       (sub_16_31_n_29));
  XNOR2X1 sub_16_31_g377(.A (sub_16_31_n_18), .B (sub_16_31_n_26), .Y
       (out1[2]));
  NAND2X1 sub_16_31_g378(.A (sub_16_31_n_14), .B (sub_16_31_n_26), .Y
       (sub_16_31_n_27));
  ADDFX1 sub_16_31_g379(.A (sub_16_31_n_1), .B (in2[1]), .CI
       (sub_16_31_n_0), .CO (sub_16_31_n_26), .S (out1[1]));
  AOI221X1 sub_16_31_g380(.A0 (sub_16_31_n_3), .A1 (sub_16_31_n_5), .B0
       (sub_16_31_n_16), .B1 (sub_16_31_n_23), .C0 (sub_16_31_n_13), .Y
       (sub_16_31_n_24));
  OAI21X1 sub_16_31_g381(.A0 (sub_16_31_n_10), .A1 (sub_16_31_n_9), .B0
       (sub_16_31_n_8), .Y (sub_16_31_n_23));
  NAND2X1 sub_16_31_g382(.A (sub_16_31_n_7), .B (sub_16_31_n_9), .Y
       (sub_16_31_n_22));
  NAND2BX1 sub_16_31_g383(.AN (sub_16_31_n_4), .B (sub_16_31_n_12), .Y
       (sub_16_31_n_21));
  NAND2BX1 sub_16_31_g384(.AN (sub_16_31_n_13), .B (sub_16_31_n_3), .Y
       (sub_16_31_n_20));
  NOR2X1 sub_16_31_g385(.A (sub_16_31_n_11), .B (sub_16_31_n_5), .Y
       (sub_16_31_n_19));
  NAND2X1 sub_16_31_g386(.A (sub_16_31_n_14), .B (sub_16_31_n_2), .Y
       (sub_16_31_n_18));
  NAND2BX1 sub_16_31_g387(.AN (sub_16_31_n_10), .B (sub_16_31_n_8), .Y
       (sub_16_31_n_17));
  NOR2BX1 sub_16_31_g388(.AN (sub_16_31_n_3), .B (sub_16_31_n_11), .Y
       (sub_16_31_n_16));
  XOR2XL sub_16_31_g389(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  NAND2BX1 sub_16_31_g390(.AN (in2[2]), .B (in1[2]), .Y
       (sub_16_31_n_14));
  NOR2BX1 sub_16_31_g391(.AN (in2[7]), .B (in1[7]), .Y
       (sub_16_31_n_13));
  NAND2BX1 sub_16_31_g392(.AN (in1[3]), .B (in2[3]), .Y
       (sub_16_31_n_12));
  NOR2BX1 sub_16_31_g393(.AN (in1[6]), .B (in2[6]), .Y
       (sub_16_31_n_11));
  NOR2BX1 sub_16_31_g394(.AN (in1[5]), .B (in2[5]), .Y
       (sub_16_31_n_10));
  NAND2BX1 sub_16_31_g395(.AN (in1[4]), .B (in2[4]), .Y
       (sub_16_31_n_9));
  INVX1 sub_16_31_g396(.A (sub_16_31_n_5), .Y (sub_16_31_n_6));
  NAND2BX1 sub_16_31_g397(.AN (in1[5]), .B (in2[5]), .Y
       (sub_16_31_n_8));
  NAND2BX1 sub_16_31_g398(.AN (in2[4]), .B (in1[4]), .Y
       (sub_16_31_n_7));
  NAND2BX1 sub_16_31_g399(.AN (in2[0]), .B (in1[0]), .Y
       (sub_16_31_n_1));
  NOR2BX1 sub_16_31_g400(.AN (in2[6]), .B (in1[6]), .Y (sub_16_31_n_5));
  NOR2BX1 sub_16_31_g401(.AN (in1[3]), .B (in2[3]), .Y (sub_16_31_n_4));
  NAND2BX1 sub_16_31_g402(.AN (in2[7]), .B (in1[7]), .Y
       (sub_16_31_n_3));
  NAND2BX1 sub_16_31_g403(.AN (in1[2]), .B (in2[2]), .Y
       (sub_16_31_n_2));
  INVX1 sub_16_31_g404(.A (in1[1]), .Y (sub_16_31_n_0));
endmodule


