`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  4 2025 00:51:20 CST (Jun  3 2025 16:51:20 UTC)

module dut_OrReduction_7U_1U_1(in1, out1);
  input [6:0] in1;
  output out1;
  wire [6:0] in1;
  wire out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  NAND2X1 g21(.A (n_5), .B (n_7), .Y (out1));
  NOR2X2 g23(.A (n_6), .B (n_4), .Y (n_7));
  NAND2X2 g24(.A (n_3), .B (n_2), .Y (n_6));
  NOR3X1 g22(.A (in1[0]), .B (in1[2]), .C (in1[1]), .Y (n_5));
  NAND2X2 g25(.A (n_1), .B (n_0), .Y (n_4));
  CLKINVX4 g26(.A (in1[6]), .Y (n_3));
  INVX2 g29(.A (in1[5]), .Y (n_2));
  INVX2 g28(.A (in1[4]), .Y (n_1));
  INVX2 g27(.A (in1[3]), .Y (n_0));
endmodule


