`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  4 2025 00:42:36 CST (Jun  3 2025 16:42:36 UTC)

module dut_Equal_15Ux7U_1U_4(in2, in1, out1);
  input [14:0] in2;
  input [6:0] in1;
  output out1;
  wire [14:0] in2;
  wire [6:0] in1;
  wire out1;
  wire eq_16_23_n_0, eq_16_23_n_1, eq_16_23_n_2, eq_16_23_n_3,
       eq_16_23_n_4, eq_16_23_n_5, eq_16_23_n_6, eq_16_23_n_7;
  wire eq_16_23_n_8, eq_16_23_n_9, eq_16_23_n_10;
  NOR3BX1 eq_16_23_g85(.AN (eq_16_23_n_8), .B (eq_16_23_n_10), .C
       (eq_16_23_n_9), .Y (out1));
  NAND4BX1 eq_16_23_g86(.AN (in2[7]), .B (eq_16_23_n_4), .C
       (eq_16_23_n_1), .D (eq_16_23_n_7), .Y (eq_16_23_n_10));
  NAND4XL eq_16_23_g87(.A (eq_16_23_n_6), .B (eq_16_23_n_5), .C
       (eq_16_23_n_3), .D (eq_16_23_n_2), .Y (eq_16_23_n_9));
  NOR4X1 eq_16_23_g88(.A (eq_16_23_n_0), .B (in2[12]), .C (in2[14]), .D
       (in2[13]), .Y (eq_16_23_n_8));
  XNOR2X1 eq_16_23_g89(.A (in2[6]), .B (in1[6]), .Y (eq_16_23_n_7));
  XNOR2X1 eq_16_23_g90(.A (in2[3]), .B (in1[3]), .Y (eq_16_23_n_6));
  XNOR2X1 eq_16_23_g91(.A (in2[2]), .B (in1[2]), .Y (eq_16_23_n_5));
  XNOR2X1 eq_16_23_g92(.A (in2[5]), .B (in1[5]), .Y (eq_16_23_n_4));
  XNOR2X1 eq_16_23_g93(.A (in2[1]), .B (in1[1]), .Y (eq_16_23_n_3));
  XNOR2X1 eq_16_23_g94(.A (in2[0]), .B (in1[0]), .Y (eq_16_23_n_2));
  XNOR2X1 eq_16_23_g95(.A (in2[4]), .B (in1[4]), .Y (eq_16_23_n_1));
  OR4X1 eq_16_23_g96(.A (in2[11]), .B (in2[10]), .C (in2[9]), .D
       (in2[8]), .Y (eq_16_23_n_0));
endmodule


