`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  4 2025 00:52:02 CST (Jun  3 2025 16:52:02 UTC)

module dut_Equal_1U_107_1(in1, out1);
  input [6:0] in1;
  output out1;
  wire [6:0] in1;
  wire out1;
  wire n_0, n_1, n_2, n_3, n_4;
  NOR2X2 g40(.A (n_2), .B (n_4), .Y (out1));
  NAND2X2 g42(.A (n_1), .B (n_3), .Y (n_4));
  NOR2X6 g43(.A (in1[0]), .B (n_0), .Y (n_3));
  NAND3X8 g41(.A (in1[5]), .B (in1[4]), .C (in1[3]), .Y (n_2));
  NOR2X4 g44(.A (in1[6]), .B (in1[2]), .Y (n_1));
  CLKINVX12 g45(.A (in1[1]), .Y (n_0));
endmodule


