`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Jun  9 2025 10:34:45 CST (Jun  9 2025 02:34:45 UTC)

module dut_Sub_16Ux8U_16U_4(in2, in1, out1);
  input [15:0] in2;
  input [7:0] in1;
  output [15:0] out1;
  wire [15:0] in2;
  wire [7:0] in1;
  wire [15:0] out1;
  wire sub_16_23_n_0, sub_16_23_n_1, sub_16_23_n_2, sub_16_23_n_3,
       sub_16_23_n_4, sub_16_23_n_5, sub_16_23_n_6, sub_16_23_n_7;
  wire sub_16_23_n_8, sub_16_23_n_9, sub_16_23_n_10, sub_16_23_n_11,
       sub_16_23_n_12, sub_16_23_n_13, sub_16_23_n_14, sub_16_23_n_16;
  wire sub_16_23_n_17, sub_16_23_n_18, sub_16_23_n_19, sub_16_23_n_20,
       sub_16_23_n_21, sub_16_23_n_22, sub_16_23_n_23, sub_16_23_n_24;
  wire sub_16_23_n_26, sub_16_23_n_27, sub_16_23_n_29, sub_16_23_n_30,
       sub_16_23_n_32, sub_16_23_n_34, sub_16_23_n_35, sub_16_23_n_36;
  wire sub_16_23_n_38, sub_16_23_n_40, sub_16_23_n_41, sub_16_23_n_42,
       sub_16_23_n_44, sub_16_23_n_45, sub_16_23_n_48, sub_16_23_n_49;
  wire sub_16_23_n_51;
  XNOR2X1 sub_16_23_g363(.A (in2[15]), .B (sub_16_23_n_51), .Y
       (out1[15]));
  XNOR2X1 sub_16_23_g364(.A (in2[13]), .B (sub_16_23_n_49), .Y
       (out1[13]));
  XNOR2X1 sub_16_23_g365(.A (in2[11]), .B (sub_16_23_n_45), .Y
       (out1[11]));
  OAI2BB1X1 sub_16_23_g366(.A0N (in2[14]), .A1N (sub_16_23_n_48), .B0
       (sub_16_23_n_51), .Y (out1[14]));
  XOR2XL sub_16_23_g367(.A (in2[9]), .B (sub_16_23_n_42), .Y (out1[9]));
  OR2XL sub_16_23_g368(.A (in2[14]), .B (sub_16_23_n_48), .Y
       (sub_16_23_n_51));
  OAI2BB1X1 sub_16_23_g369(.A0N (in2[12]), .A1N (sub_16_23_n_44), .B0
       (sub_16_23_n_49), .Y (out1[12]));
  OR2XL sub_16_23_g370(.A (in2[12]), .B (sub_16_23_n_44), .Y
       (sub_16_23_n_49));
  OR3XL sub_16_23_g371(.A (sub_16_23_n_44), .B (in2[13]), .C (in2[12]),
       .Y (sub_16_23_n_48));
  OAI2BB1X1 sub_16_23_g372(.A0N (in2[10]), .A1N (sub_16_23_n_40), .B0
       (sub_16_23_n_45), .Y (out1[10]));
  XNOR2X1 sub_16_23_g373(.A (sub_16_23_n_20), .B (sub_16_23_n_41), .Y
       (out1[7]));
  OR2XL sub_16_23_g374(.A (in2[10]), .B (sub_16_23_n_40), .Y
       (sub_16_23_n_45));
  OR3XL sub_16_23_g375(.A (sub_16_23_n_40), .B (in2[11]), .C (in2[10]),
       .Y (sub_16_23_n_44));
  AO21XL sub_16_23_g376(.A0 (in2[8]), .A1 (sub_16_23_n_38), .B0
       (sub_16_23_n_42), .Y (out1[8]));
  NOR2X1 sub_16_23_g377(.A (in2[8]), .B (sub_16_23_n_38), .Y
       (sub_16_23_n_42));
  OAI21X1 sub_16_23_g378(.A0 (sub_16_23_n_4), .A1 (sub_16_23_n_36), .B0
       (sub_16_23_n_10), .Y (sub_16_23_n_41));
  OR3XL sub_16_23_g379(.A (sub_16_23_n_38), .B (in2[9]), .C (in2[8]),
       .Y (sub_16_23_n_40));
  XNOR2X1 sub_16_23_g380(.A (sub_16_23_n_19), .B (sub_16_23_n_36), .Y
       (out1[6]));
  OAI2BB1X1 sub_16_23_g381(.A0N (sub_16_23_n_16), .A1N
       (sub_16_23_n_35), .B0 (sub_16_23_n_24), .Y (sub_16_23_n_38));
  XNOR2X1 sub_16_23_g382(.A (sub_16_23_n_18), .B (sub_16_23_n_34), .Y
       (out1[5]));
  NOR2X1 sub_16_23_g383(.A (sub_16_23_n_23), .B (sub_16_23_n_35), .Y
       (sub_16_23_n_36));
  NOR2X1 sub_16_23_g384(.A (sub_16_23_n_2), .B (sub_16_23_n_32), .Y
       (sub_16_23_n_35));
  NAND2X1 sub_16_23_g385(.A (sub_16_23_n_12), .B (sub_16_23_n_32), .Y
       (sub_16_23_n_34));
  XNOR2X1 sub_16_23_g386(.A (sub_16_23_n_17), .B (sub_16_23_n_30), .Y
       (out1[4]));
  NAND2X1 sub_16_23_g387(.A (sub_16_23_n_7), .B (sub_16_23_n_30), .Y
       (sub_16_23_n_32));
  XNOR2X1 sub_16_23_g388(.A (sub_16_23_n_21), .B (sub_16_23_n_29), .Y
       (out1[3]));
  OAI221X1 sub_16_23_g389(.A0 (sub_16_23_n_3), .A1 (sub_16_23_n_27),
       .B0 (sub_16_23_n_3), .B1 (sub_16_23_n_11), .C0 (sub_16_23_n_6),
       .Y (sub_16_23_n_30));
  NAND2X1 sub_16_23_g390(.A (sub_16_23_n_11), .B (sub_16_23_n_27), .Y
       (sub_16_23_n_29));
  XNOR2X1 sub_16_23_g391(.A (sub_16_23_n_22), .B (sub_16_23_n_26), .Y
       (out1[2]));
  NAND2X1 sub_16_23_g392(.A (sub_16_23_n_14), .B (sub_16_23_n_26), .Y
       (sub_16_23_n_27));
  ADDFX1 sub_16_23_g393(.A (sub_16_23_n_8), .B (in2[1]), .CI
       (sub_16_23_n_0), .CO (sub_16_23_n_26), .S (out1[1]));
  AOI221X1 sub_16_23_g394(.A0 (sub_16_23_n_1), .A1 (sub_16_23_n_9), .B0
       (sub_16_23_n_16), .B1 (sub_16_23_n_23), .C0 (sub_16_23_n_5), .Y
       (sub_16_23_n_24));
  OAI21X1 sub_16_23_g395(.A0 (sub_16_23_n_2), .A1 (sub_16_23_n_12), .B0
       (sub_16_23_n_13), .Y (sub_16_23_n_23));
  NAND2X1 sub_16_23_g396(.A (sub_16_23_n_14), .B (sub_16_23_n_11), .Y
       (sub_16_23_n_22));
  NAND2BX1 sub_16_23_g397(.AN (sub_16_23_n_3), .B (sub_16_23_n_6), .Y
       (sub_16_23_n_21));
  NAND2BX1 sub_16_23_g398(.AN (sub_16_23_n_5), .B (sub_16_23_n_1), .Y
       (sub_16_23_n_20));
  NOR2X1 sub_16_23_g399(.A (sub_16_23_n_4), .B (sub_16_23_n_9), .Y
       (sub_16_23_n_19));
  NAND2BX1 sub_16_23_g400(.AN (sub_16_23_n_2), .B (sub_16_23_n_13), .Y
       (sub_16_23_n_18));
  NAND2X1 sub_16_23_g401(.A (sub_16_23_n_7), .B (sub_16_23_n_12), .Y
       (sub_16_23_n_17));
  NOR2BX1 sub_16_23_g402(.AN (sub_16_23_n_1), .B (sub_16_23_n_4), .Y
       (sub_16_23_n_16));
  XOR2XL sub_16_23_g403(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  INVX1 sub_16_23_g404(.A (sub_16_23_n_9), .Y (sub_16_23_n_10));
  NAND2BX1 sub_16_23_g405(.AN (in2[2]), .B (in1[2]), .Y
       (sub_16_23_n_14));
  NAND2BX1 sub_16_23_g406(.AN (in1[5]), .B (in2[5]), .Y
       (sub_16_23_n_13));
  NAND2BX1 sub_16_23_g407(.AN (in1[4]), .B (in2[4]), .Y
       (sub_16_23_n_12));
  NAND2BX1 sub_16_23_g408(.AN (in1[2]), .B (in2[2]), .Y
       (sub_16_23_n_11));
  NOR2BX1 sub_16_23_g409(.AN (in2[6]), .B (in1[6]), .Y (sub_16_23_n_9));
  NAND2BX1 sub_16_23_g410(.AN (in2[0]), .B (in1[0]), .Y
       (sub_16_23_n_8));
  NAND2BX1 sub_16_23_g411(.AN (in2[4]), .B (in1[4]), .Y
       (sub_16_23_n_7));
  NAND2BX1 sub_16_23_g412(.AN (in1[3]), .B (in2[3]), .Y
       (sub_16_23_n_6));
  NOR2BX1 sub_16_23_g413(.AN (in2[7]), .B (in1[7]), .Y (sub_16_23_n_5));
  NOR2BX1 sub_16_23_g414(.AN (in1[6]), .B (in2[6]), .Y (sub_16_23_n_4));
  NOR2BX1 sub_16_23_g415(.AN (in1[3]), .B (in2[3]), .Y (sub_16_23_n_3));
  NOR2BX1 sub_16_23_g416(.AN (in1[5]), .B (in2[5]), .Y (sub_16_23_n_2));
  NAND2BX1 sub_16_23_g417(.AN (in2[7]), .B (in1[7]), .Y
       (sub_16_23_n_1));
  INVX1 sub_16_23_g418(.A (in1[1]), .Y (sub_16_23_n_0));
endmodule


