// Generated by stratus_hls 23.02-s004  (100793.100415)
// Wed Jun  4 01:19:01 2025
// from dut.cc

`timescale 1ps / 1ps


module dut_N_Mux_8_100_131_1( in101, in100, in99, in98, in97, in96, in95, in94, in93, in92, in91, in90, in89, in88, in87, in86, in85, in84, in83, in82, in81, in80, in79, in78, in77, in76, in75, in74, in73, in72, in71, in70, in69, in68, in67, in66, in65, in64, in63, in62, in61, in60, in59, in58, in57, in56, in55, in54, in53, in52, in51, in50, in49, in48, in47, in46, in45, in44, in43, in42, in41, in40, in39, in38, in37, in36, in35, in34, in33, in32, in31, in30, in29, in28, in27, in26, in25, in24
      , in23, in22, in21, in20, in19, in18, in17, in16, in15, in14, in13, in12, in11, in10, in9, in8, in7, in6, in5, in4, in3, in2, ctrl1, out1 );

    input [7:0] in101;
    input [7:0] in100;
    input [7:0] in99;
    input [7:0] in98;
    input [7:0] in97;
    input [7:0] in96;
    input [7:0] in95;
    input [7:0] in94;
    input [7:0] in93;
    input [7:0] in92;
    input [7:0] in91;
    input [7:0] in90;
    input [7:0] in89;
    input [7:0] in88;
    input [7:0] in87;
    input [7:0] in86;
    input [7:0] in85;
    input [7:0] in84;
    input [7:0] in83;
    input [7:0] in82;
    input [7:0] in81;
    input [7:0] in80;
    input [7:0] in79;
    input [7:0] in78;
    input [7:0] in77;
    input [7:0] in76;
    input [7:0] in75;
    input [7:0] in74;
    input [7:0] in73;
    input [7:0] in72;
    input [7:0] in71;
    input [7:0] in70;
    input [7:0] in69;
    input [7:0] in68;
    input [7:0] in67;
    input [7:0] in66;
    input [7:0] in65;
    input [7:0] in64;
    input [7:0] in63;
    input [7:0] in62;
    input [7:0] in61;
    input [7:0] in60;
    input [7:0] in59;
    input [7:0] in58;
    input [7:0] in57;
    input [7:0] in56;
    input [7:0] in55;
    input [7:0] in54;
    input [7:0] in53;
    input [7:0] in52;
    input [7:0] in51;
    input [7:0] in50;
    input [7:0] in49;
    input [7:0] in48;
    input [7:0] in47;
    input [7:0] in46;
    input [7:0] in45;
    input [7:0] in44;
    input [7:0] in43;
    input [7:0] in42;
    input [7:0] in41;
    input [7:0] in40;
    input [7:0] in39;
    input [7:0] in38;
    input [7:0] in37;
    input [7:0] in36;
    input [7:0] in35;
    input [7:0] in34;
    input [7:0] in33;
    input [7:0] in32;
    input [7:0] in31;
    input [7:0] in30;
    input [7:0] in29;
    input [7:0] in28;
    input [7:0] in27;
    input [7:0] in26;
    input [7:0] in25;
    input [7:0] in24;
    input [7:0] in23;
    input [7:0] in22;
    input [7:0] in21;
    input [7:0] in20;
    input [7:0] in19;
    input [7:0] in18;
    input [7:0] in17;
    input [7:0] in16;
    input [7:0] in15;
    input [7:0] in14;
    input [7:0] in13;
    input [7:0] in12;
    input [7:0] in11;
    input [7:0] in10;
    input [7:0] in9;
    input [7:0] in8;
    input [7:0] in7;
    input [7:0] in6;
    input [7:0] in5;
    input [7:0] in4;
    input [7:0] in3;
    input [7:0] in2;
    input [6:0] ctrl1;
    output [7:0] out1;
    reg [7:0] out1;

    
    // rtl_process:dut_N_Mux_8_100_131_1/dut_N_Mux_8_100_131_1_thread_1
    always @*
      begin : dut_N_Mux_8_100_131_1_thread_1
        case (ctrl1) 
          7'd098: 
            begin
              out1 = in100;
            end
          7'd097: 
            begin
              out1 = in99;
            end
          7'd096: 
            begin
              out1 = in98;
            end
          7'd095: 
            begin
              out1 = in97;
            end
          7'd094: 
            begin
              out1 = in96;
            end
          7'd093: 
            begin
              out1 = in95;
            end
          7'd092: 
            begin
              out1 = in94;
            end
          7'd091: 
            begin
              out1 = in93;
            end
          7'd090: 
            begin
              out1 = in92;
            end
          7'd089: 
            begin
              out1 = in91;
            end
          7'd088: 
            begin
              out1 = in90;
            end
          7'd087: 
            begin
              out1 = in89;
            end
          7'd086: 
            begin
              out1 = in88;
            end
          7'd085: 
            begin
              out1 = in87;
            end
          7'd084: 
            begin
              out1 = in86;
            end
          7'd083: 
            begin
              out1 = in85;
            end
          7'd082: 
            begin
              out1 = in84;
            end
          7'd081: 
            begin
              out1 = in83;
            end
          7'd080: 
            begin
              out1 = in82;
            end
          7'd079: 
            begin
              out1 = in81;
            end
          7'd078: 
            begin
              out1 = in80;
            end
          7'd077: 
            begin
              out1 = in79;
            end
          7'd076: 
            begin
              out1 = in78;
            end
          7'd075: 
            begin
              out1 = in77;
            end
          7'd074: 
            begin
              out1 = in76;
            end
          7'd073: 
            begin
              out1 = in75;
            end
          7'd072: 
            begin
              out1 = in74;
            end
          7'd071: 
            begin
              out1 = in73;
            end
          7'd070: 
            begin
              out1 = in72;
            end
          7'd069: 
            begin
              out1 = in71;
            end
          7'd068: 
            begin
              out1 = in70;
            end
          7'd067: 
            begin
              out1 = in69;
            end
          7'd066: 
            begin
              out1 = in68;
            end
          7'd065: 
            begin
              out1 = in67;
            end
          7'd064: 
            begin
              out1 = in66;
            end
          7'd063: 
            begin
              out1 = in65;
            end
          7'd062: 
            begin
              out1 = in64;
            end
          7'd061: 
            begin
              out1 = in63;
            end
          7'd060: 
            begin
              out1 = in62;
            end
          7'd059: 
            begin
              out1 = in61;
            end
          7'd058: 
            begin
              out1 = in60;
            end
          7'd057: 
            begin
              out1 = in59;
            end
          7'd056: 
            begin
              out1 = in58;
            end
          7'd055: 
            begin
              out1 = in57;
            end
          7'd054: 
            begin
              out1 = in56;
            end
          7'd053: 
            begin
              out1 = in55;
            end
          7'd052: 
            begin
              out1 = in54;
            end
          7'd051: 
            begin
              out1 = in53;
            end
          7'd050: 
            begin
              out1 = in52;
            end
          7'd049: 
            begin
              out1 = in51;
            end
          7'd048: 
            begin
              out1 = in50;
            end
          7'd047: 
            begin
              out1 = in49;
            end
          7'd046: 
            begin
              out1 = in48;
            end
          7'd045: 
            begin
              out1 = in47;
            end
          7'd044: 
            begin
              out1 = in46;
            end
          7'd043: 
            begin
              out1 = in45;
            end
          7'd042: 
            begin
              out1 = in44;
            end
          7'd041: 
            begin
              out1 = in43;
            end
          7'd040: 
            begin
              out1 = in42;
            end
          7'd039: 
            begin
              out1 = in41;
            end
          7'd038: 
            begin
              out1 = in40;
            end
          7'd037: 
            begin
              out1 = in39;
            end
          7'd036: 
            begin
              out1 = in38;
            end
          7'd035: 
            begin
              out1 = in37;
            end
          7'd034: 
            begin
              out1 = in36;
            end
          7'd033: 
            begin
              out1 = in35;
            end
          7'd032: 
            begin
              out1 = in34;
            end
          7'd031: 
            begin
              out1 = in33;
            end
          7'd030: 
            begin
              out1 = in32;
            end
          7'd029: 
            begin
              out1 = in31;
            end
          7'd028: 
            begin
              out1 = in30;
            end
          7'd027: 
            begin
              out1 = in29;
            end
          7'd026: 
            begin
              out1 = in28;
            end
          7'd025: 
            begin
              out1 = in27;
            end
          7'd024: 
            begin
              out1 = in26;
            end
          7'd023: 
            begin
              out1 = in25;
            end
          7'd022: 
            begin
              out1 = in24;
            end
          7'd021: 
            begin
              out1 = in23;
            end
          7'd020: 
            begin
              out1 = in22;
            end
          7'd019: 
            begin
              out1 = in21;
            end
          7'd018: 
            begin
              out1 = in20;
            end
          7'd017: 
            begin
              out1 = in19;
            end
          7'd016: 
            begin
              out1 = in18;
            end
          7'd015: 
            begin
              out1 = in17;
            end
          7'd014: 
            begin
              out1 = in16;
            end
          7'd013: 
            begin
              out1 = in15;
            end
          7'd012: 
            begin
              out1 = in14;
            end
          7'd011: 
            begin
              out1 = in13;
            end
          7'd010: 
            begin
              out1 = in12;
            end
          7'd009: 
            begin
              out1 = in11;
            end
          7'd008: 
            begin
              out1 = in10;
            end
          7'd007: 
            begin
              out1 = in9;
            end
          7'd006: 
            begin
              out1 = in8;
            end
          7'd005: 
            begin
              out1 = in7;
            end
          7'd004: 
            begin
              out1 = in6;
            end
          7'd003: 
            begin
              out1 = in5;
            end
          7'd002: 
            begin
              out1 = in4;
            end
          7'd001: 
            begin
              out1 = in3;
            end
          7'd000: 
            begin
              out1 = in2;
            end
          default: 
            begin
              out1 = in101;
            end
        endcase
      end

endmodule


