// Generated by stratus_hls 23.02-s004  (100793.100415)
// Wed Jun  4 01:36:23 2025
// from dut.cc

`timescale 1ps / 1ps


module dut_Equal_1U_38_1( in1, out1 );

    input [6:0] in1;
    output out1;

    
    // rtl_process:dut_Equal_1U_35_1/dut_Equal_1U_35_1_thread_1
    assign out1 = in1 == 7'd027;

endmodule


