// Generated by stratus_hls 23.02-s004  (100793.100415)
// Mon Jun  9 13:25:00 2025
// from dut.cc

`timescale 1ps / 1ps


module dut_LessThan_2Sx9S_1U_4( in2, in1, out1 );

    input [1:0] in2;
    input [8:0] in1;
    output out1;

    
    // rtl_process:dut_LessThan_2Sx9S_1U_4/dut_LessThan_2Sx9S_1U_4_thread_1
    assign out1 = ({{ 7 {in2[1]}}, in2} < in1 ^ (in1[8] ^ in2[1]));

endmodule


